# Tutorial 53: Creation of Longitudinal Section - and Edge Dataframe

This Example demonstrates the capabilities of the class Dataframes_SIR3S_Model that extends SIR3S_Model be abilities to work directley with pandas dataframes. It is shown how to create dataframes containing information that does not concern individual elements types such as Nodes, Pipes, etc. but instead concerning more abstract SIR 3S data such as longitudinal sections or concatenations of multiple element types like hydraulic edges.

# Toolkit Release

In [1]:
#pip install

# Imports

## SIR 3S Toolkit

### Regular Import/Init

In [2]:
SIR3S_SIRGRAF_DIR = r"C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2" #change to local path

In [3]:
from sir3stoolkit.core import wrapper

In [4]:
wrapper

In [5]:
wrapper.Initialize_Toolkit(SIR3S_SIRGRAF_DIR)

[2026-06-08 14:23:36,336] INFO in sir3stoolkit.core.wrapper: [Initialization] Using provided SirGraf path: C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2
[2026-06-08 14:23:36,336] INFO in sir3stoolkit.core.wrapper: [Initialization] Using provided SirGraf path: C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2
[2026-06-08 14:23:36,359] INFO in sir3stoolkit.core.wrapper: [Initialization] Initializing toolkit with SirGraf path: C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2

### Additional Import/Init for Dataframes class

In [6]:
from sir3stoolkit.mantle.dataframes import SIR3S_Model_Dataframes

In [7]:
s3s = SIR3S_Model_Dataframes()

[2026-06-08 14:23:43,282] INFO in sir3stoolkit.core.wrapper: [Model Class Initialization] Initialization complete

## Additional

In [8]:
import pandas as pd
from shapely.geometry import Point
import re
import folium
from folium.plugins import HeatMap
import numpy as np
import geopandas as gpd
from shapely import wkt
import matplotlib.pyplot as plt
import contextily as cx

# Open Model

In [9]:
s3s.OpenModel(dbName=r"Toolkit_Tutorial53_Model.db3",
              providerType=s3s.ProviderTypes.SQLite,
              Mid="M-1-0-1",
              saveCurrentlyOpenModel=False,
              namedInstance="",
              userID="",
              password="")

[2026-06-08 14:23:50,849] INFO in sir3stoolkit.core.wrapper: Model is open for further operation

# Generate Non-Element Dataframes

## Edge dataframe

We can use the function [generate_edge_dataframe()](https://3sconsult.github.io/sir3stoolkit/references/sir3stoolkit.mantle.html#sir3stoolkit.mantle.dataframes.SIR3S_Model_Dataframes.generate_edge_dataframe) to obtain a dataframe containing all edge objects in the model (each row representing one edge element). Below is a list of all element types, whose representatives that will be included in the dataframe, if present in the model.

In [10]:
edge_types = [
    'Pipe', 'Valve', 'SafetyValve', 'PressureRegulator', 'DifferentialRegulator',
    'FlapValve', 'PhaseSeparation', 'FlowControlUnit', 'ControlValve', 'Pump',
    'DistrictHeatingConsumer', 'DistrictHeatingFeeder', 'Compressor', 'HeaterCooler', 'HeatFeederConsumerStation'
]

HeatExchanger is not supported.

### Parametrization 1: Default

If we don't request any properties, we will only get [tk, Fkcont, geometry, fkKI, fkKK, element_type, L] as df columns.

In [11]:
df, timestamp_to_tuple_index = s3s.generate_edge_dataframe()
df.head(5)

[2026-06-08 14:23:50,877] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating edge dataframe ...
[2026-06-08 14:23:50,955] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Pipe ...
[2026-06-08 14:23:50,966] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-06-08 14:23:50,968] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 14:23:50,969] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-06-08 14:23:50,970] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-06-08 14:23:51,179] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:23:51,220] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:23:51,220] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (524, 6)
[2026-06-08 14:23:51,225] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-06-08 14:23:51,310] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-06-08 14:23:51,313] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 14:23:51,314] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-06-08 14:23:51,323] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:23:51,326] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 14:23:51,329] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-06-08 14:23:51,329] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:23:51,332] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Input dataframe is empty. Returning empty dataframe.
[2026-06-08 14:23:51,334] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Pipe.
[2026-06-08 14:23:51,337] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Valve ...
[2026-06-08 14:23:51,337] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Valve
[2026-06-08 14:23:51,337] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 12 element(s) of element type ObjectTypes.Valve.
[2026-06-08 14:23:51,342] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-06-08 14:23:51,342] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-06-08 14:23:51,796] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:23:51,813] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:23:51,813] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (12, 6)
[2026-06-08 14:23:51,817] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Valve
[2026-06-08 14:23:51,902] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-06-08 14:23:51,912] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 12 element(s) of element type ObjectTypes.Valve.
[2026-06-08 14:23:51,916] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-06-08 14:23:51,934] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:23:51,940] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 14:23:51,943] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-06-08 14:23:51,946] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:23:51,946] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Input dataframe is empty. Returning empty dataframe.
[2026-06-08 14:23:51,949] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Valve.
[2026-06-08 14:23:51,953] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.FlapValve ...
[2026-06-08 14:23:51,956] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.FlapValve
[2026-06-08 14:23:51,959] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 3 element(s) of element type ObjectTypes.FlapValve.
[2026-06-08 14:23:51,960] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-06-08 14:23:51,963] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-06-08 14:23:51,979] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:23:51,996] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:23:51,996] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (3, 6)
[2026-06-08 14:23:52,008] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.FlapValve
[2026-06-08 14:23:52,096] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-06-08 14:23:52,113] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 3 element(s) of element type ObjectTypes.FlapValve.
[2026-06-08 14:23:52,113] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-06-08 14:23:52,133] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:23:52,134] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 14:23:52,137] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-06-08 14:23:52,137] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:23:52,139] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Input dataframe is empty. Returning empty dataframe.
[2026-06-08 14:23:52,142] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.FlapValve.
[2026-06-08 14:23:52,144] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Pump ...
[2026-06-08 14:23:52,148] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pump
[2026-06-08 14:23:52,148] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 2 element(s) of element type ObjectTypes.Pump.
[2026-06-08 14:23:52,151] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-06-08 14:23:52,151] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-06-08 14:23:52,314] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:23:52,330] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:23:52,333] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (2, 6)
[2026-06-08 14:23:52,333] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pump
[2026-06-08 14:23:52,430] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-06-08 14:23:52,433] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 2 element(s) of element type ObjectTypes.Pump.
[2026-06-08 14:23:52,434] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-06-08 14:23:52,485] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:23:52,492] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 14:23:52,496] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-06-08 14:23:52,498] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:23:52,499] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Input dataframe is empty. Returning empty dataframe.
[2026-06-08 14:23:52,501] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Pump.
[2026-06-08 14:23:52,503] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.DistrictHeatingConsumer ...
[2026-06-08 14:23:52,507] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.DistrictHeatingConsumer
[2026-06-08 14:23:52,510] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 337 element(s) of element type ObjectTypes.DistrictHeatingConsumer.
[2026-06-08 14:23:52,512] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-06-08 14:23:52,514] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-06-08 14:23:52,613] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:23:52,646] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:23:52,646] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (337, 6)
[2026-06-08 14:23:52,648] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.DistrictHeatingConsumer
[2026-06-08 14:23:52,744] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-06-08 14:23:52,747] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 337 element(s) of element type ObjectTypes.DistrictHeatingConsumer.
[2026-06-08 14:23:52,747] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-06-08 14:23:52,774] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:23:52,777] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 14:23:52,779] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-06-08 14:23:52,779] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:23:52,782] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Input dataframe is empty. Returning empty dataframe.
[2026-06-08 14:23:52,787] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.DistrictHeatingConsumer.
[2026-06-08 14:23:52,788] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.DistrictHeatingFeeder ...
[2026-06-08 14:23:52,790] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.DistrictHeatingFeeder
[2026-06-08 14:23:52,792] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 1 element(s) of element type ObjectTypes.DistrictHeatingFeeder.
[2026-06-08 14:23:52,796] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-06-08 14:23:52,796] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-06-08 14:23:52,813] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:23:52,839] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:23:52,841] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (1, 6)
[2026-06-08 14:23:52,841] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.DistrictHeatingFeeder
[2026-06-08 14:23:52,960] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-06-08 14:23:52,962] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 1 element(s) of element type ObjectTypes.DistrictHeatingFeeder.
[2026-06-08 14:23:52,962] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-06-08 14:23:52,979] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:23:52,983] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 14:23:52,986] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-06-08 14:23:52,987] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:23:52,987] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Input dataframe is empty. Returning empty dataframe.
[2026-06-08 14:23:52,990] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.DistrictHeatingFeeder.
[2026-06-08 14:23:53,007] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Retrieved 879 edges from 6 element types.

,Fkcont,L,element type,fkKI,fkKK,geometry,tk
0,5029128874972463118,0,Pipe,5669301360686511351,5397948523091900401,"LINESTRING (713620.268 5578828.419, 713602.295...",5442010239090746007
1,5029128874972463118,0,Pipe,5397948523091900401,5239335112004772156,"LINESTRING (713602.295 5578860.106, 713574.062...",4917786378639043296
2,5029128874972463118,0,Pipe,5239335112004772156,5298886695042021307,"LINESTRING (713574.062 5578909.873, 713553.84 ...",4762482310382009633
3,5029128874972463118,0,Pipe,5298886695042021307,4993257270457791438,"LINESTRING (713553.84 5578945.533, 713553.394 ...",4987229536643024523
4,5029128874972463118,0,Pipe,4993257270457791438,5317865645994989592,"LINESTRING (713553.394 5578952.352, 713556.294...",5722206630503885118

### Parametrization 2: Properties + tk filter

We can request additional properties. Here we can mix model data and result properties in the same param.

If a property is not defined for all edge element types, a column for that property will be created, but only populated, where values exists.

We can also filter for certain tks to exclusivly include in the dataframe. This is especially useful for large networks with known tks of interest.

In [12]:
tks_of_interest = df["tk"][520:550].tolist() # now we just choose some randomly

In [13]:
df, timestamp_to_tuple_index = s3s.generate_edge_dataframe(properties=["Hal", "Kvr", "JV", "PVEC", "MVEC"],
                                                           tks=tks_of_interest)
df.head(5)

[2026-06-08 14:23:53,063] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating edge dataframe ...
[2026-06-08 14:23:53,196] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] TK filtering active. Requested tks: ['4957957828740199285', '5499776682108862751', '5285235772707481262', '5373158549695106826', '5078909058477631059', '5120684848284658605', '5652541284139882253', '5240450756436834634', '5257205059759497594', '4702663206643375451', '5217273986390542544', '5514879539114546017', '5586353371153335311', '5397401198360947165', '5684594766069449552', '4817917631249014225', '5110715607374589471', '5760916286273932524', '4656308032396859575', '5374020919990423089', '5661833458038115239', '4743997951091160959', '5014209100699808035', '4627580049017248376', '5018070164989726059', '5668240250035163192', '4681770111719926437', '5048206626643560289', '4874631416147311583', '4891291656447821692']
[2026-06-08 14:23:53,200] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Pipe ...
[2026-06-08 14:23:53,205] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-06-08 14:23:53,209] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 14:23:53,211] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 4 tks remain after filtering for given tks.
[2026-06-08 14:23:53,214] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 3 model_data properties.
[2026-06-08 14:23:53,215] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Hal', 'Kvr', 'Fkcont'], geometry, end nodes...
[2026-06-08 14:23:53,246] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:23:53,271] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:23:53,271] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (4, 8)
[2026-06-08 14:23:53,277] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-06-08 14:23:53,392] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-06-08 14:23:53,396] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 14:23:53,396] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 4 tks remain after filtering for given tks.
[2026-06-08 14:23:53,399] INFO in sir3stoolkit.mantle.dataframes: [results] Using 3 result properties.
[2026-06-08 14:23:53,426] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:23:53,451] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 14:23:53,458] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 12)
[2026-06-08 14:23:53,516] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:23:53,524] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Done. Shape: (1, 28)
[2026-06-08 14:23:53,533] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Pipe.
[2026-06-08 14:23:53,540] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Valve ...
[2026-06-08 14:23:53,541] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Valve
[2026-06-08 14:23:53,546] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 12 element(s) of element type ObjectTypes.Valve.
[2026-06-08 14:23:53,547] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 12 tks remain after filtering for given tks.
[2026-06-08 14:23:53,549] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-06-08 14:23:53,552] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-06-08 14:23:53,566] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:23:53,590] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:23:53,591] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (12, 6)
[2026-06-08 14:23:53,595] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Valve
[2026-06-08 14:23:53,723] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-06-08 14:23:53,723] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 12 element(s) of element type ObjectTypes.Valve.
[2026-06-08 14:23:53,723] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 12 tks remain after filtering for given tks.
[2026-06-08 14:23:53,729] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-06-08 14:23:53,749] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:23:53,750] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 14:23:53,755] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-06-08 14:23:53,755] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:23:53,758] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Input dataframe is empty. Returning empty dataframe.
[2026-06-08 14:23:53,762] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Valve.
[2026-06-08 14:23:53,766] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.FlapValve ...
[2026-06-08 14:23:53,768] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.FlapValve
[2026-06-08 14:23:53,770] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 3 element(s) of element type ObjectTypes.FlapValve.
[2026-06-08 14:23:53,772] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 3 tks remain after filtering for given tks.
[2026-06-08 14:23:53,777] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-06-08 14:23:53,777] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-06-08 14:23:53,790] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:23:53,812] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:23:53,812] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (3, 6)
[2026-06-08 14:23:53,812] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.FlapValve
[2026-06-08 14:23:53,999] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-06-08 14:23:53,999] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 3 element(s) of element type ObjectTypes.FlapValve.
[2026-06-08 14:23:53,999] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 3 tks remain after filtering for given tks.
[2026-06-08 14:23:54,007] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-06-08 14:23:54,057] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:23:54,058] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 14:23:54,065] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-06-08 14:23:54,066] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:23:54,068] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Input dataframe is empty. Returning empty dataframe.
[2026-06-08 14:23:54,071] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.FlapValve.
[2026-06-08 14:23:54,075] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Pump ...
[2026-06-08 14:23:54,078] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pump
[2026-06-08 14:23:54,080] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 2 element(s) of element type ObjectTypes.Pump.
[2026-06-08 14:23:54,083] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 2 tks remain after filtering for given tks.
[2026-06-08 14:23:54,086] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-06-08 14:23:54,086] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-06-08 14:23:54,141] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:23:54,162] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:23:54,162] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (2, 6)
[2026-06-08 14:23:54,162] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pump
[2026-06-08 14:23:54,285] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-06-08 14:23:54,291] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 2 element(s) of element type ObjectTypes.Pump.
[2026-06-08 14:23:54,291] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 2 tks remain after filtering for given tks.
[2026-06-08 14:23:54,298] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-06-08 14:23:54,363] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:23:54,363] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 14:23:54,363] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-06-08 14:23:54,374] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:23:54,377] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Input dataframe is empty. Returning empty dataframe.
[2026-06-08 14:23:54,380] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Pump.
[2026-06-08 14:23:54,383] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.DistrictHeatingConsumer ...
[2026-06-08 14:23:54,388] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.DistrictHeatingConsumer
[2026-06-08 14:23:54,391] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 337 element(s) of element type ObjectTypes.DistrictHeatingConsumer.
[2026-06-08 14:23:54,393] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 9 tks remain after filtering for given tks.
[2026-06-08 14:23:54,397] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-06-08 14:23:54,398] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-06-08 14:23:54,411] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:23:54,438] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:23:54,439] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (9, 6)
[2026-06-08 14:23:54,441] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.DistrictHeatingConsumer
[2026-06-08 14:23:54,580] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-06-08 14:23:54,583] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 337 element(s) of element type ObjectTypes.DistrictHeatingConsumer.
[2026-06-08 14:23:54,585] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 9 tks remain after filtering for given tks.
[2026-06-08 14:23:54,589] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-06-08 14:23:54,610] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:23:54,613] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 14:23:54,616] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-06-08 14:23:54,618] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:23:54,621] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Input dataframe is empty. Returning empty dataframe.
[2026-06-08 14:23:54,623] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.DistrictHeatingConsumer.
[2026-06-08 14:23:54,634] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Retrieved 30 edges from 5 element types.

,Fkcont,Hal,JV,Kvr,L,MVEC_end,MVEC_sequence,MVEC_start,PVEC_end,PVEC_sequence,PVEC_start,element type,fkKI,fkKK,geometry,tk
0,5029128874972463118,0.0,"(0.0,)",2.0,0,"(0.0,)","((0.0, 0.0, 0.0),)","(0.0,)","(1.38355,)","((1.638605, 1.51108, 1.38355),)","(1.638605,)",Pipe,4863932769493405228,5295548655235318963,"LINESTRING (714408.376 5578937.983, 714404.59 ...",4957957828740199285
1,5029128874972463118,0.0,"(0.7570621,)",1.0,0,"(8.407589,)","((8.407589, 8.407589),)","(8.407589,)","(4.845395,)","((4.839625, 4.845395),)","(4.839625,)",Pipe,5172212715463480789,5392476601138952594,"LINESTRING (713580.476 5578511.084, 713584.785...",5285235772707481262
2,5029128874972463118,0.0,"(0.7657993,)",2.0,0,"(-8.407588,)","((-8.407588, -8.407588),)","(-8.407588,)","(3.997365,)","((3.981985, 3.997365),)","(3.981985,)",Pipe,5093129494518007690,5337935179219974656,"LINESTRING (713582.476 5578511.084, 713586.785...",5373158549695106826
3,5029128874972463118,0.0,"(0.0,)",2.0,0,"(0.0,)","((0.0, 0.0, 0.0, 0.0),)","(0.0,)","(1.06867,)","((1.38355, 1.27859, 1.17363, 1.06867),)","(1.38355,)",Pipe,5295548655235318963,5475286394948521111,"LINESTRING (714404.59 5578954.91, 714397.405 5...",5499776682108862751
4,5027846505677995694,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,Valve,5160850648779674898,4945502875946918021,POINT (190 208),5078909058477631059

The resulting df now includes model data properties such as "Hal" or "Kvr", but also result properties such as "JV" or result vector properties along pipe interior points like "PVEC" or "MVEC", which are split into the columns PVEC_start, PVEC_end, and PVEC_sequence = (PVEC_start, PVEC_2, PVEC_3, ..., PVEC_end).

As we didn't specify a timestamp, the result values are obtained for the stationary timestamp (s3s.GetTimeStamps()[1]).

Note that typical int cols like "Kvr" are float here. This happens due to the merge of many dataframes, some with NaN values.

In [14]:
len(df)

30

We only get the rows for the requested tks.

### Parametrization 3: Properties + Timestamps

In [15]:
simulation_timestamps = s3s.GetTimeStamps()[0]

In [16]:
simulation_timestamps

['2023-02-13 00:00:00.000 +01:00',
 '2023-02-13 01:00:00.000 +01:00',
 '2023-02-13 02:00:00.000 +01:00',
 '2023-02-13 03:00:00.000 +01:00',
 '2023-02-13 04:00:00.000 +01:00',
 '2023-02-13 05:00:00.000 +01:00',
 '2023-02-13 06:00:00.000 +01:00',
 '2023-02-13 07:00:00.000 +01:00',
 '2023-02-13 08:00:00.000 +01:00',
 '2023-02-13 09:00:00.000 +01:00',
 '2023-02-13 10:00:00.000 +01:00',
 '2023-02-13 11:00:00.000 +01:00',
 '2023-02-13 12:00:00.000 +01:00',
 '2023-02-13 13:00:00.000 +01:00',
 '2023-02-13 14:00:00.000 +01:00',
 '2023-02-13 15:00:00.000 +01:00',
 '2023-02-13 16:00:00.000 +01:00',
 '2023-02-13 17:00:00.000 +01:00',
 '2023-02-13 18:00:00.000 +01:00',
 '2023-02-13 19:00:00.000 +01:00',
 '2023-02-13 20:00:00.000 +01:00',
 '2023-02-13 21:00:00.000 +01:00',
 '2023-02-13 22:00:00.000 +01:00',
 '2023-02-13 23:00:00.000 +01:00',
 '2023-02-14 00:00:00.000 +01:00']

We can request a list of timestamps for retrival of results properties. Therefore we take a slice from the available simulation timestamps.

In [17]:
df_edge, timestamp_to_tuple_index = s3s.generate_edge_dataframe(properties=["Hal", "Kvr", "JV", "PVEC", "MVEC"]
                                                                ,timestamps=[0, 5, -1])
df_edge.head(5)

[2026-06-08 14:23:54,931] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating edge dataframe ...
[2026-06-08 14:23:54,938] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Pipe ...
[2026-06-08 14:23:54,945] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-06-08 14:23:54,951] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 14:23:54,954] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 3 model_data properties.
[2026-06-08 14:23:54,958] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Hal', 'Kvr', 'Fkcont'], geometry, end nodes...
[2026-06-08 14:23:55,343] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:23:55,400] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:23:55,400] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (524, 8)
[2026-06-08 14:23:55,408] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-06-08 14:23:55,529] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 3 timestamps: ['2023-02-13 00:00:00.000 +01:00', '2023-02-13 05:00:00.000 +01:00', '2023-02-14 00:00:00.000 +01:00']
[2026-06-08 14:23:55,532] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 14:23:55,535] INFO in sir3stoolkit.mantle.dataframes: [results] Using 3 result properties.
[2026-06-08 14:23:55,563] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:23:56,460] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 14:23:56,725] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (3, 1572)
[2026-06-08 14:24:02,909] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:24:03,602] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Done. Shape: (1, 3668)
[2026-06-08 14:24:03,620] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Pipe.
[2026-06-08 14:24:03,620] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Valve ...
[2026-06-08 14:24:03,627] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Valve
[2026-06-08 14:24:03,629] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 12 element(s) of element type ObjectTypes.Valve.
[2026-06-08 14:24:03,632] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-06-08 14:24:03,634] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-06-08 14:24:03,647] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:24:03,667] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:24:03,667] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (12, 6)
[2026-06-08 14:24:03,667] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Valve
[2026-06-08 14:24:03,767] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 3 timestamps: ['2023-02-13 00:00:00.000 +01:00', '2023-02-13 05:00:00.000 +01:00', '2023-02-14 00:00:00.000 +01:00']
[2026-06-08 14:24:03,767] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 12 element(s) of element type ObjectTypes.Valve.
[2026-06-08 14:24:03,771] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-06-08 14:24:03,796] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:24:03,796] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 14:24:03,796] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-06-08 14:24:03,796] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:24:03,806] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Input dataframe is empty. Returning empty dataframe.
[2026-06-08 14:24:03,808] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Valve.
[2026-06-08 14:24:03,815] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.FlapValve ...
[2026-06-08 14:24:03,816] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.FlapValve
[2026-06-08 14:24:03,816] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 3 element(s) of element type ObjectTypes.FlapValve.
[2026-06-08 14:24:03,820] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-06-08 14:24:03,825] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-06-08 14:24:03,833] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:24:03,856] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:24:03,857] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (3, 6)
[2026-06-08 14:24:03,860] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.FlapValve
[2026-06-08 14:24:03,984] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 3 timestamps: ['2023-02-13 00:00:00.000 +01:00', '2023-02-13 05:00:00.000 +01:00', '2023-02-14 00:00:00.000 +01:00']
[2026-06-08 14:24:03,985] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 3 element(s) of element type ObjectTypes.FlapValve.
[2026-06-08 14:24:03,988] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-06-08 14:24:04,001] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:24:04,005] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 14:24:04,010] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-06-08 14:24:04,012] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:24:04,015] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Input dataframe is empty. Returning empty dataframe.
[2026-06-08 14:24:04,016] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.FlapValve.
[2026-06-08 14:24:04,020] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Pump ...
[2026-06-08 14:24:04,023] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pump
[2026-06-08 14:24:04,026] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 2 element(s) of element type ObjectTypes.Pump.
[2026-06-08 14:24:04,030] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-06-08 14:24:04,032] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-06-08 14:24:04,079] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:24:04,107] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:24:04,109] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (2, 6)
[2026-06-08 14:24:04,109] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pump
[2026-06-08 14:24:04,217] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 3 timestamps: ['2023-02-13 00:00:00.000 +01:00', '2023-02-13 05:00:00.000 +01:00', '2023-02-14 00:00:00.000 +01:00']
[2026-06-08 14:24:04,225] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 2 element(s) of element type ObjectTypes.Pump.
[2026-06-08 14:24:04,227] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-06-08 14:24:04,289] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:24:04,291] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 14:24:04,296] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-06-08 14:24:04,296] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:24:04,299] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Input dataframe is empty. Returning empty dataframe.
[2026-06-08 14:24:04,300] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Pump.
[2026-06-08 14:24:04,304] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.DistrictHeatingConsumer ...
[2026-06-08 14:24:04,309] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.DistrictHeatingConsumer
[2026-06-08 14:24:04,313] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 337 element(s) of element type ObjectTypes.DistrictHeatingConsumer.
[2026-06-08 14:24:04,313] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-06-08 14:24:04,313] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-06-08 14:24:04,468] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:24:04,529] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:24:04,529] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (337, 6)
[2026-06-08 14:24:04,532] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.DistrictHeatingConsumer
[2026-06-08 14:24:04,651] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 3 timestamps: ['2023-02-13 00:00:00.000 +01:00', '2023-02-13 05:00:00.000 +01:00', '2023-02-14 00:00:00.000 +01:00']
[2026-06-08 14:24:04,658] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 337 element(s) of element type ObjectTypes.DistrictHeatingConsumer.
[2026-06-08 14:24:04,663] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-06-08 14:24:04,691] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:24:04,696] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 14:24:04,700] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-06-08 14:24:04,702] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:24:04,704] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Input dataframe is empty. Returning empty dataframe.
[2026-06-08 14:24:04,708] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.DistrictHeatingConsumer.
[2026-06-08 14:24:04,711] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.DistrictHeatingFeeder ...
[2026-06-08 14:24:04,715] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.DistrictHeatingFeeder
[2026-06-08 14:24:04,717] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 1 element(s) of element type ObjectTypes.DistrictHeatingFeeder.
[2026-06-08 14:24:04,719] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-06-08 14:24:04,720] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-06-08 14:24:04,728] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:24:04,759] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:24:04,761] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (1, 6)
[2026-06-08 14:24:04,765] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.DistrictHeatingFeeder
[2026-06-08 14:24:04,907] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 3 timestamps: ['2023-02-13 00:00:00.000 +01:00', '2023-02-13 05:00:00.000 +01:00', '2023-02-14 00:00:00.000 +01:00']
[2026-06-08 14:24:04,909] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 1 element(s) of element type ObjectTypes.DistrictHeatingFeeder.
[2026-06-08 14:24:04,913] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-06-08 14:24:04,934] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:24:04,938] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 14:24:04,943] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-06-08 14:24:04,945] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:24:04,947] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Input dataframe is empty. Returning empty dataframe.
[2026-06-08 14:24:04,950] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.DistrictHeatingFeeder.
[2026-06-08 14:24:04,968] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Retrieved 879 edges from 6 element types.

,Fkcont,Hal,JV,Kvr,L,MVEC_end,MVEC_sequence,MVEC_start,PVEC_end,PVEC_sequence,PVEC_start,element type,fkKI,fkKK,geometry,tk
0,5029128874972463118,0.0,"(4.303457e-23, 6.974091e-22, 0.0)",2.0,0,"(2.837623e-10, 1.142325e-09, 0.0)","((2.837623e-10, 2.837623e-10), (1.142325e-09, ...","(2.837623e-10, 1.142325e-09, 0.0)","(1.68863, 1.68863, 1.68864)","((1.615055, 1.68863), (1.615055, 1.68863), (1....","(1.615055, 1.615055, 1.61507)",Pipe,4730066059089961857,4917189080965035120,"LINESTRING (714262.483 5578857.42, 714269.543 ...",4614463970292122863
1,5029128874972463118,0.0,"(4.756155e-23, 0.0, 4.756155e-23)",1.0,0,"(-2.983143e-10, 0.0, -2.983143e-10)","((-2.983143e-10, -2.983143e-10, -2.983143e-10,...","(-2.983143e-10, 0.0, -2.983143e-10)","(3.59, 3.74699, 3.604835)","((3.304535, 3.345315, 3.386095, 3.426875, 3.46...","(3.304535, 3.461525, 3.31937)",Pipe,5129584372458662150,5332825919690090061,"LINESTRING (713738.297 5579219.902, 713793.23 ...",4615723899944629797
2,5029128874972463118,0.0,"(0.2111366, 0.4887606, 0.2371578)",2.0,0,"(-4.251046, -6.639488, -4.5234)","((-4.251046, -4.251046), (-6.639488, -6.639488...","(-4.251046, -6.639488, -4.5234)","(2.19852, 2.56674, 2.2329)","((2.210225, 2.19852), (2.577345, 2.56674), (2....","(2.210225, 2.577345, 2.244505)",Pipe,5070795580168283912,5725848577942138606,"LINESTRING (713650.613 5578990.488, 713649.498...",4621030304810285220
3,5029128874972463118,0.0,"(0.1849831, 0.4417774, 0.208755)",1.0,0,"(-24.13726, -37.92842, -25.70856)","((-24.13726, -24.13726, -24.13726, -24.13726),...","(-24.13726, -37.92842, -25.70856)","(4.21452, 4.61464, 4.251935)","((4.1376, 4.16324, 4.18888, 4.21452), (4.53218...","(4.1376, 4.532185, 4.174505)",Pipe,5106194195554624313,5416743601805578486,"LINESTRING (713283.932 5578718.123, 713299.538...",4621904482639719098
4,5029128874972463118,0.0,"(1.64011e-23, 7.243163e-24, 1.769575e-24)",2.0,0,"(1.737135e-10, -1.164153e-10, 5.729817e-11)","((1.737135e-10, 1.737135e-10, 1.737135e-10, 1....","(1.737135e-10, -1.164153e-10, 5.729817e-11)","(2.328365, 2.56135, 2.350165)","((2.304045, 2.30891, 2.313775, 2.318635, 2.323...","(2.304045, 2.53683, 2.325845)",Pipe,5395214589547810761,5186627743244018598,"LINESTRING (713231.461 5579074.621, 713266.467...",4623301797443553869

In the resulting dataframe every result value becomes a tuple, each element corresponding to one timestamp.

In [18]:
df_edge["JV"].iloc[0]

(4.303457e-23, 6.974091e-22, 0.0)

We also get a dict returned, that maps timestamp to tuple index.

In [19]:
timestamp_to_tuple_index

{'2023-02-13 00:00:00.000 +01:00': 0,
 '2023-02-13 05:00:00.000 +01:00': 1,
 '2023-02-14 00:00:00.000 +01:00': 2}

In [20]:
df_edge["JV"].iloc[0][timestamp_to_tuple_index[simulation_timestamps[0]]]

4.303457e-23

We can also get series of the "JV" values for one timestamp in the different pipes.

In [28]:
df_edge["JV"].str[timestamp_to_tuple_index[simulation_timestamps[0]]]

0      4.303457e-23
1      4.756155e-23
2      2.111366e-01
3      1.849831e-01
4      1.640110e-23
5      4.420876e-24
6      8.080109e-02
7      7.522397e-23
8      6.953945e-20
9      4.121174e-01
10     4.974777e-01
11     9.559039e-23
12     3.172845e-01
13     1.986323e-23
14     5.729455e-25
15     0.000000e+00
16     1.619071e-22
17     4.238189e-23
18     4.253159e-01
19     1.903912e-24
20     1.195405e-22
21     1.472177e-02
22     1.839792e-23
23     2.993693e-01
24     4.505997e-01
25     0.000000e+00
26     1.527271e-01
27     2.120296e-23
28     1.021399e-23
29     1.308296e-22
30     0.000000e+00
31     2.925582e-01
32     4.394961e-01
33     7.883015e-01
34     7.355869e-20
35     6.155628e-24
36     2.288080e-25
37     1.548829e-01
38     1.925734e-24
39     0.000000e+00
40     1.548817e-01
41     2.858229e-01
42     1.912648e-23
43     1.562514e-23
44     3.565702e-23
45     1.158490e-01
46     1.110624e-23
47     1.742017e-01
48     7.028960e-02
49     0.000000e+00
50     0.000000e+00
51     7.947674e-23
52     2.669777e-01
53     1.527272e-01
54     1.980363e-01
55     2.985731e-01
56     2.652031e-01
57     0.000000e+00
58     1.207613e-22
59     3.570947e-01
60     1.080041e-24
61     3.741830e-24
62     0.000000e+00
63     2.606477e-01
64     4.701927e-01
65     2.100977e-23
66     1.018570e-24
67     0.000000e+00
68     2.747048e-01
69     4.241799e-01
70     0.000000e+00
71     4.950556e-01
72     4.640312e-01
73     2.754110e-01
74     2.508921e-01
75     0.000000e+00
76     2.069825e-01
77     1.200835e-01
78     2.913226e-01
79     2.296366e-01
80     0.000000e+00
81     2.482058e-01
82     1.247748e-23
83     3.846532e-01
84     1.712854e-01
85     3.124212e-01
86     6.052179e-25
87     3.088085e-01
88     0.000000e+00
89     0.000000e+00
90     0.000000e+00
91     8.174199e-25
92     4.289367e-01
93     0.000000e+00
94     2.181537e-01
95     1.527282e-01
96     5.066090e-01
97     4.058762e-23
98     0.000000e+00
99     1.810791e-24
100    2.993662e-01
101    3.677806e-01
102    2.343103e-01
103    2.120296e-23
104    1.104298e-01
105    0.000000e+00
106    1.107319e-01
107    1.257429e-01
108    2.988512e-25
109    2.710529e-01
110    1.214838e-01
111    1.426281e-22
112    3.655859e-01
113    3.770334e-01
114    9.683487e-24
115    0.000000e+00
116    3.117812e-01
117    0.000000e+00
118    1.940978e-01
119    0.000000e+00
120    2.776836e-01
121    1.661062e-01
122    4.524863e-01
123    0.000000e+00
124    2.710598e-01
125    1.548807e-01
126    0.000000e+00
127    0.000000e+00
128    7.773713e-01
129    2.216026e-22
130    2.111379e-01
131    0.000000e+00
132    1.608204e-01
133    2.555952e-01
134    1.548811e-01
135    1.548840e-01
136    3.119370e-24
137    4.151931e-01
138    1.767306e-01
139    7.243163e-24
140    2.448825e-01
141    4.463838e-01
142    4.354812e-24
143    7.289717e-02
144    2.975431e-01
145    3.939885e-20
146    3.350547e-01
147    0.000000e+00
148    0.000000e+00
149    0.000000e+00
150    0.000000e+00
151    1.948761e-01
152    1.655813e-22
153    2.952875e-02
154    1.266267e-01
155    1.527273e-01
156    2.062604e-23
157    5.061461e-24
158    0.000000e+00
159    2.914878e-22
160    2.903744e-01
161    4.463846e-01
162    5.864754e-02
163    2.338643e-25
164    3.367092e-01
165    0.000000e+00
166    6.383745e-23
167    1.515435e-11
168    4.234985e-24
169    1.171455e-01
170    2.652053e-01
171    1.515429e-11
172    4.061712e-01
173    4.527077e-01
174    1.504877e-23
175    1.247748e-23
176    8.470953e-03
177    5.539653e-02
178    1.214829e-01
179    4.579187e-02
180    5.174996e-01
181    4.289363e-01
182    2.139704e-23
183    2.024584e-23
184    2.402802e-01
185    1.512934e-22
186    0.000000e+00
187    4.241795e-01
188    2.355885e-24
189    4.586048e-23
190    1.548843e-01
191    3.277889e-01
192    2.384703e-01
193    2.425734e-01
194    2.646096e-24
195    9.999411e-01
196    4.470567e-23
197    1.527280e-01
198    0.000000e+00
199    1.012029e+00
200    2.181513e-01
201    6.260403e-24
202    2.111331e-01
203    4.301477e-21
204    7.047192e-01
205    8.558816e-23
206    1.527269e-01
207    1.179526e-01
208    0.000000e+00
209    2.291782e-24
210    6.928089e-01
211    4.524885e-01
212    1.799285e-01
213    6.654043e-02
214    2.116998e-22
215    3.989840e-24
216    1.768350e-25
217    1.035048e-23
218    6.366061e-24
219    4.554363e-01
220    9.471385e-13
221    4.362459e-02
222    1.767291e-01
223    2.652068e-01
224    3.685119e-02
225    2.369509e-01
226    2.078105e-01
227    0.000000e+00
228    8.793223e-02
229    0.000000e+00
230    1.772591e-01
231    1.371614e-01
232    1.573929e-01
233    3.249280e-01
234    2.901416e-01
235    4.328763e-21
236    5.152456e-01
237    1.527278e-01
238    2.619251e-01
239    1.527270e-01
240    0.000000e+00
241    1.905865e-01
242    0.000000e+00
243    9.342699e-02
244    1.629712e-23
245    9.517969e-23
246    2.265090e-01
247    0.000000e+00
248    1.052805e-22
249    4.526977e-23
250    3.906286e-24
251    2.504161e-23
252    2.553498e-24
253    9.471354e-13
254    0.000000e+00
255    1.527282e-01
256    7.215577e-23
257    1.496732e-23
258    0.000000e+00
259    3.175208e-01
260    3.941613e-01
261    2.053055e-01
262    4.527002e-01
263    2.285671e-22
264    1.548836e-01
265    1.425111e-01
266    1.105219e-22
267    3.347352e-01
268    4.253644e-01
269    1.813176e-01
270    3.740127e-01
271    1.076507e-01
272    4.151549e-01
273    0.000000e+00
274    9.471461e-13
275    1.595936e-23
276    2.719015e-23
277    1.018570e-24
278    3.439105e-22
279    2.141543e-22
280    1.548838e-01
281    5.249823e-01
282    1.515438e-11
283    2.181489e-01
284    3.284129e-01
285    2.695813e-01
286    0.000000e+00
287    0.000000e+00
288    0.000000e+00
289    2.612634e-24
290    3.201388e-01
291    1.767275e-01
292    7.595785e-02
293    4.187142e-24
294    1.548841e-01
295    0.000000e+00
296    4.074279e-24
297    0.000000e+00
298    2.089901e-01
299    3.117134e-01
300    3.790634e-01
301    1.840568e-01
302    4.420876e-24
303    1.527281e-01
304    1.984244e-01
305    1.601867e-23
306    3.916663e-02
307    4.406782e-01
308    4.166431e-01
309    1.515431e-11
310    3.977182e-01
311    2.900268e-01
312    8.080196e-02
313    3.019033e-23
314    2.191390e-01
315    0.000000e+00
316    0.000000e+00
317    4.647416e-01
318    1.070411e-23
319    0.000000e+00
320    1.318391e-01
321    1.386387e-24
322    2.478295e-01
323    2.570325e-24
324    9.846123e-02
325    3.269680e-24
326    1.642338e-01
327    5.063423e-01
328    1.619071e-22
329    4.272147e-01
330    4.074279e-24
331    7.570621e-01
332    2.471572e-01
333    3.989840e-24
334    1.978243e-01
335    0.000000e+00
336    1.116299e-22
337    1.908822e-01
338    1.825619e-01
339    3.007076e-01
340    2.281491e-22
341    3.725578e-22
342    1.548839e-01
343    1.832338e-01
344    4.112450e-21
345    1.912648e-23
346    1.515435e-11
347    2.298148e-23
348    5.035654e-25
349    7.696611e-02
350    3.011048e-01
351    1.714870e-01
352    8.558816e-25
353    1.496732e-23
354    3.156616e-24
355    0.000000e+00
356    0.000000e+00
357    4.554389e-01
358    0.000000e+00
359    2.884523e-01
360    3.213035e-02
361    2.062604e-23
362    7.730345e-02
363    2.817275e-01
364    4.363441e-01
365    4.850768e-01
366    2.218219e-23
367    0.000000e+00
368    4.203661e-01
369    3.205252e-01
370    7.657993e-01
371    1.842995e-01
372    1.548808e-01
373    1.908742e-01
374    0.000000e+00
375    3.360286e-01
376    7.047325e-01
377    3.593367e-01
378    2.287928e-01
379    1.876043e-23
380    2.897265e-23
381    4.051316e-21
382    1.480507e-23
383    5.066961e-01
384    4.241788e-01
385    1.920340e-01
386    4.061442e-21
387    4.133108e-21
388    1.527270e-01
389    1.195405e-22
390    2.810753e-02
391    3.717957e-25
392    1.754646e-22
393    0.000000e+00
394    3.075350e-01
395    0.000000e+00
396    4.245809e-24
397    1.642594e-01
398    7.073401e-25
399    2.860698e-01
400    1.527275e-01
401    1.185769e-01
402    2.673994e-01
403    1.483630e-01
404    2.252419e-01
405    0.000000e+00
406    2.909392e-01
407    8.631269e-25
408    2.269066e-01
409    9.471552e-13
410    1.980477e-01
411    1.867239e-01
412    4.849612e-01
413    2.010624e-01
414    2.897265e-23
415    2.024584e-23
416    8.046433e-02
417    9.749625e-02
418    6.250057e-23
419    4.764677e-01
420    2.832771e-01
421    1.623863e-01
422    0.000000e+00
423    0.000000e+00
424    2.053085e-01
425    2.988512e-25
426    5.215554e-01
427    1.825923e-01
428    2.686214e-22
429    2.900247e-01
430    4.627620e-01
431    6.383745e-25
432    2.534064e-01
433    0.000000e+00
434    1.204268e-23
435    2.234374e-01
436    5.545547e-24
437    5.170833e-23
438    9.471456e-13
439    0.000000e+00
440    4.289365e-01
441    3.941567e-01
442    9.471522e-13
443    8.080516e-02
444    6.928181e-01
445    0.000000e+00
446    4.892633e-01
447    2.548272e-01
448    1.940334e-23
449    1.164582e-01
450    3.810379e-24
451    3.392094e-23
452    1.715212e-01
453    2.486743e-24
454    2.323470e-01
455    4.321852e-01
456    3.682109e-01
457    1.515435e-11
458    0.000000e+00
459    3.246669e-01
460    2.687042e-23
461    1.658386e-01
462    5.110533e-23
463    3.465967e-25
464    1.418758e-22
465    1.189039e-23
466    1.548824e-01
467    2.559007e-01
468    9.471506e-13
469    2.710555e-01
470    4.261577e-01
471    2.621137e-24
472    3.083724e-01
473    1.239811e-01
474    7.073401e-25
475    1.668275e-01
476    3.339565e-01
477    3.438914e-01
478    1.515436e-11
479    7.243163e-24
480    1.657954e-01
481    2.053063e-01
482    1.018570e-22
483    2.520010e-22
484    5.040621e-01
485    2.945801e-01
486    1.548804e-01
487    2.553498e-24
488    4.406827e-01
489    9.471390e-13
490    1.764308e-01
491    0.000000e+00
492    3.235976e-01
493    1.214550e-23
494    1.018570e-24
495    2.710543e-01
496    2.591581e-01
497    0.000000e+00
498    1.515431e-11
499    7.696372e-02
500    1.652632e-20
501    2.586954e-01
502    5.039342e-01
503    1.527268e-01
504    3.184624e-01
505    1.727137e-20
506    0.000000e+00
507    0.000000e+00
508    1.036103e-01
509    1.527269e-01
510    2.652060e-01
511    2.138750e-01
512    1.019758e-01
513    3.689702e-20
514    1.349420e-24
515    0.000000e+00
516    1.548833e-01
517    0.000000e+00
518    2.438451e-01
519    1.371981e-01
520    1.713358e-01
521    7.696675e-02
522    6.207240e-02
523    5.545547e-24
524             NaN
525             NaN
526             NaN
527             NaN
528             NaN
529             NaN
530             NaN
531             NaN
532             NaN
533             NaN
534             NaN
535             NaN
536             NaN
537             NaN
538             NaN
539             NaN
540             NaN
541             NaN
542             NaN
543             NaN
544             NaN
545             NaN
546             NaN
547             NaN
548             NaN
549             NaN
550             NaN
551             NaN
552             NaN
553             NaN
554             NaN
555             NaN
556             NaN
557             NaN
558             NaN
559             NaN
560             NaN
561             NaN
562             NaN
563             NaN
564             NaN
565             NaN
566             NaN
567             NaN
568             NaN
569             NaN
570             NaN
571             NaN
572             NaN
573             NaN
574             NaN
575             NaN
576             NaN
577             NaN
578             NaN
579             NaN
580             NaN
581             NaN
582             NaN
583             NaN
584             NaN
585             NaN
586             NaN
587             NaN
588             NaN
589             NaN
590             NaN
591             NaN
592             NaN
593             NaN
594             NaN
595             NaN
596             NaN
597             NaN
598             NaN
599             NaN
600             NaN
601             NaN
602             NaN
603             NaN
604             NaN
605             NaN
606             NaN
607             NaN
608             NaN
609             NaN
610             NaN
611             NaN
612             NaN
613             NaN
614             NaN
615             NaN
616             NaN
617             NaN
618             NaN
619             NaN
620             NaN
621             NaN
622             NaN
623             NaN
624             NaN
625             NaN
626             NaN
627             NaN
628             NaN
629             NaN
630             NaN
631             NaN
632             NaN
633             NaN
634             NaN
635             NaN
636             NaN
637             NaN
638             NaN
639             NaN
640             NaN
641             NaN
642             NaN
643             NaN
644             NaN
645             NaN
646             NaN
647             NaN
648             NaN
649             NaN
650             NaN
651             NaN
652             NaN
653             NaN
654             NaN
655             NaN
656             NaN
657             NaN
658             NaN
659             NaN
660             NaN
661             NaN
662             NaN
663             NaN
664             NaN
665             NaN
666             NaN
667             NaN
668             NaN
669             NaN
670             NaN
671             NaN
672             NaN
673             NaN
674             NaN
675             NaN
676             NaN
677             NaN
678             NaN
679             NaN
680             NaN
681             NaN
682             NaN
683             NaN
684             NaN
685             NaN
686             NaN
687             NaN
688             NaN
689             NaN
690             NaN
691             NaN
692             NaN
693             NaN
694             NaN
695             NaN
696             NaN
697             NaN
698             NaN
699             NaN
700             NaN
701             NaN
702             NaN
703             NaN
704             NaN
705             NaN
706             NaN
707             NaN
708             NaN
709             NaN
710             NaN
711             NaN
712             NaN
713             NaN
714             NaN
715             NaN
716             NaN
717             NaN
718             NaN
719             NaN
720             NaN
721             NaN
722             NaN
723             NaN
724             NaN
725             NaN
726             NaN
727             NaN
728             NaN
729             NaN
730             NaN
731             NaN
732             NaN
733             NaN
734             NaN
735             NaN
736             NaN
737             NaN
738             NaN
739             NaN
740             NaN
741             NaN
742             NaN
743             NaN
744             NaN
745             NaN
746             NaN
747             NaN
748             NaN
749             NaN
750             NaN
751             NaN
752             NaN
753             NaN
754             NaN
755             NaN
756             NaN
757             NaN
758             NaN
759             NaN
760             NaN
761             NaN
762             NaN
763             NaN
764             NaN
765             NaN
766             NaN
767             NaN
768             NaN
769             NaN
770             NaN
771             NaN
772             NaN
773             NaN
774             NaN
775             NaN
776             NaN
777             NaN
778             NaN
779             NaN
780             NaN
781             NaN
782             NaN
783             NaN
784             NaN
785             NaN
786             NaN
787             NaN
788             NaN
789             NaN
790             NaN
791             NaN
792             NaN
793             NaN
794             NaN
795             NaN
796             NaN
797             NaN
798             NaN
799             NaN
800             NaN
801             NaN
802             NaN
803             NaN
804             NaN
805             NaN
806             NaN
807             NaN
808             NaN
809             NaN
810             NaN
811             NaN
812             NaN
813             NaN
814             NaN
815             NaN
816             NaN
817             NaN
818             NaN
819             NaN
820             NaN
821             NaN
822             NaN
823             NaN
824             NaN
825             NaN
826             NaN
827             NaN
828             NaN
829             NaN
830             NaN
831             NaN
832             NaN
833             NaN
834             NaN
835             NaN
836             NaN
837             NaN
838             NaN
839             NaN
840             NaN
841             NaN
842             NaN
843             NaN
844             NaN
845             NaN
846             NaN
847             NaN
848             NaN
849             NaN
850             NaN
851             NaN
852             NaN
853             NaN
854             NaN
855             NaN
856             NaN
857             NaN
858             NaN
859             NaN
860             NaN
861             NaN
862             NaN
863             NaN
864             NaN
865             NaN
866             NaN
867             NaN
868             NaN
869             NaN
870             NaN
871             NaN
872             NaN
873             NaN
874             NaN
875             NaN
876             NaN
877             NaN
878             NaN
Name: JV, dtype: float64

For already vectorized results (pipe interior points) we get tuple of tuples with the time tuple being the higher level one.

In [22]:
df_edge["MVEC_sequence"].iloc[0]

((2.837623e-10, 2.837623e-10), (1.142325e-09, 1.142325e-09), (0.0, 0.0))

In [23]:
df_edge["MVEC_sequence"].iloc[0][timestamp_to_tuple_index[simulation_timestamps[0]]]

(2.837623e-10, 2.837623e-10)

## AGSN (Longitudinal Sections)

We can use the method [generate_longitudinal_section_dataframes()](https://3sconsult.github.io/sir3stoolkit/references/sir3stoolkit.mantle.html#sir3stoolkit.mantle.dataframes.SIR3S_Model_Dataframes.generate_longitudinal_section_dataframes) to obtain a list indexed by (lfdnr-1) filled with size-2-tuples with 0 - Supply and 1 - Return..

In [24]:
dfs = s3s.generate_longitudinal_section_dataframes()

[2026-06-08 14:24:05,208] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.AGSN_HydraulicProfile
[2026-06-08 14:24:05,213] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 3 element(s) of element type ObjectTypes.AGSN_HydraulicProfile.
[2026-06-08 14:24:05,217] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.AGSN_HydraulicProfile.
[2026-06-08 14:24:05,218] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 9 model_data properties.
[2026-06-08 14:24:05,220] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'Lfdnr', 'Aktiv', 'AllNodesAndLinks', 'ObjsString', 'MainWay', 'Tk', 'Pk', 'InVariant']...
[2026-06-08 14:24:05,259] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (3, 10)
[2026-06-08 14:24:05,263] INFO in sir3stoolkit.mantle.dataframes: Retrieving Hydraulic Profile with Lfdnr: 1.
[2026-06-08 14:24:05,284] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:05,286] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:05,298] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-06-08 14:24:05,304] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 14:24:05,306] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-06-08 14:24:05,310] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-06-08 14:24:05,312] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-06-08 14:24:05,313] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH'], geometry, end nodes...
[2026-06-08 14:24:05,732] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:24:06,147] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:24:06,149] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (44, 67)
[2026-06-08 14:24:06,279] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:06,281] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-06-08 14:24:06,400] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-06-08 14:24:06,407] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 14:24:06,411] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-06-08 14:24:06,415] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-06-08 14:24:06,444] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:24:07,174] INFO in sir3stoolkit.mantle.dataframes: [results] 2244 fully NaN columns dropped.
[2026-06-08 14:24:07,407] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1364)
[2026-06-08 14:24:12,150] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:24:12,483] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Done. Shape: (1, 2156)
[2026-06-08 14:24:12,489] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:12,501] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:12,505] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:12,515] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-06-08 14:24:12,515] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 14:24:12,515] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-06-08 14:24:12,523] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-06-08 14:24:12,524] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-06-08 14:24:12,526] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH'], geometry, end nodes...
[2026-06-08 14:24:12,709] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:24:12,889] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:24:12,896] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (44, 67)
[2026-06-08 14:24:12,989] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:12,989] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-06-08 14:24:13,079] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-06-08 14:24:13,082] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 14:24:13,084] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-06-08 14:24:13,086] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-06-08 14:24:13,116] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:24:13,739] INFO in sir3stoolkit.mantle.dataframes: [results] 2244 fully NaN columns dropped.
[2026-06-08 14:24:13,948] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1364)
[2026-06-08 14:24:18,441] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:24:18,768] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Done. Shape: (1, 2156)
[2026-06-08 14:24:18,771] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:18,786] INFO in sir3stoolkit.mantle.dataframes: Retrieving Hydraulic Profile with Lfdnr: 2.
[2026-06-08 14:24:18,789] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:18,790] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:18,799] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-06-08 14:24:18,799] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 14:24:18,805] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-06-08 14:24:18,809] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-06-08 14:24:18,810] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-06-08 14:24:18,812] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH'], geometry, end nodes...
[2026-06-08 14:24:19,016] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:24:19,216] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:24:19,224] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (44, 67)
[2026-06-08 14:24:19,316] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:19,316] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-06-08 14:24:19,539] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-06-08 14:24:19,542] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 14:24:19,544] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-06-08 14:24:19,547] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-06-08 14:24:19,582] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:24:20,275] INFO in sir3stoolkit.mantle.dataframes: [results] 2244 fully NaN columns dropped.
[2026-06-08 14:24:20,526] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1364)
[2026-06-08 14:24:24,965] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:24:25,291] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Done. Shape: (1, 2156)
[2026-06-08 14:24:25,296] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:25,313] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:25,313] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:25,321] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-06-08 14:24:25,326] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 14:24:25,328] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-06-08 14:24:25,329] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-06-08 14:24:25,331] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-06-08 14:24:25,331] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH'], geometry, end nodes...
[2026-06-08 14:24:25,506] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:24:25,683] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:24:25,683] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (44, 67)
[2026-06-08 14:24:25,775] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:25,778] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-06-08 14:24:25,864] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-06-08 14:24:25,869] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 14:24:25,871] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-06-08 14:24:25,875] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-06-08 14:24:25,937] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:24:26,663] INFO in sir3stoolkit.mantle.dataframes: [results] 2244 fully NaN columns dropped.
[2026-06-08 14:24:26,891] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1364)
[2026-06-08 14:24:31,149] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:24:31,488] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Done. Shape: (1, 2156)
[2026-06-08 14:24:31,488] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:31,510] INFO in sir3stoolkit.mantle.dataframes: Retrieving Hydraulic Profile with Lfdnr: 3.
[2026-06-08 14:24:31,512] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:31,513] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:31,524] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-06-08 14:24:31,528] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 14:24:31,530] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-06-08 14:24:31,532] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-06-08 14:24:31,534] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-06-08 14:24:31,535] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH'], geometry, end nodes...
[2026-06-08 14:24:31,746] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-06-08 14:24:31,973] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 14:24:31,974] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (44, 67)
[2026-06-08 14:24:32,196] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:32,196] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-06-08 14:24:32,305] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-06-08 14:24:32,307] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 14:24:32,309] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-06-08 14:24:32,314] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-06-08 14:24:32,360] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 14:24:33,026] INFO in sir3stoolkit.mantle.dataframes: [results] 2244 fully NaN columns dropped.
[2026-06-08 14:24:33,243] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1364)
[2026-06-08 14:24:37,334] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 14:24:37,686] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Done. Shape: (1, 2156)
[2026-06-08 14:24:37,691] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:37,708] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:37,710] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-06-08 14:24:37,718] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-06-08 14:24:37,723] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.

In [25]:
dfs[0][1].head() # Lfdnr 1 RL

,tk,Name,FkdtroRowd,Fkltgr,Fkstrasse,L,Lzu,Rau,Jlambs,Lambda0,Zein,Zaus,Zuml,Asoll,Indschall,Baujahr,Hal,Fkcont,Fk2lrohr,Beschreibung,Idreferenz,Iplanung,Kvr,LineWidthMM,DottedLine,DN,Di,KvrKlartext,HasClosedNSCHs,Tk,Pk,InVariant,Xkor,Ykor,GeometriesDiffer,bz.Fk,bz.Qsvb,bz.Irtrenn,bz.Leckstatus,bz.Leckstart,bz.Leckend,bz.Leckort,bz.Leckmenge,bz.Imptnz,bz.Zvlimptnz,bz.Kantenzv,bz.ITrennWithNSCH,geometry,fkKI,fkKK,PipeTable: Table Name,PipeTable: Name,PipeTable: Fk,PipeTable: Dn,PipeTable: Di,PipeTable: Da,PipeTable: S,PipeTable: Wsteig,PipeTable: Wtiefe,PipeTable: Kt,PipeTable: Pn,PipeTable: Ausfallzeit,PipeTable: Reparatur,PipeTable: Rehabilitation,PipeTable: Tk,PipeTable: Pk,PipeTable: InVariant,A,DTTR,DWVERL,DWVERLABS,IAKTIV,IRTRENN,JV,MVEC_end,MVEC_sequence,MVEC_start,PDAMPF,PHR,PMIN,PVECMAX_INST_end,PVECMAX_INST_sequence,PVECMAX_INST_start,PVECMIN_INST_end,PVECMIN_INST_sequence,PVECMIN_INST_start,PVEC_end,PVEC_sequence,PVEC_start,QMAV,QMI,QMK,RHOI,RHOK,RHOVEC_end,RHOVEC_sequence,RHOVEC_start,SVEC_end,SVEC_sequence,SVEC_start,TI,TK,TTRVEC_end,TTRVEC_sequence,TTRVEC_start,TVEC_end,TVEC_sequence,TVEC_start,VAV,VI,VK,VOLDA,WVL,ZVEC_end,ZVEC_sequence,ZVEC_start,l_sum,AGSN_Lfdnr,AGSN_Name
0,5025945677694931826,Rohr R-E0 R-K4163S,4816511167455310973,4779752876656844188,5204829332281547346,15.351700,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5691533564979419761,OSM: Knoten 476971238 -> Knoten 299394923; Län...,39785520,0,2,0.005,0,350,345.6,Rücklauf,,5025945677694931826,5025945677694931826,False,713621.921383,5.578219e+06,False,5025945677694931826,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713621.921 5578218.954, 713616.649...",5160850648779674898,4851678476955084637,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,"(0.0,)","(0.004934843,)","(26.63305,)","(0.4088626,)","(0.0,)","(0.0,)","(0.1548843,)","(-79.74764,)","((-79.74764, -79.74764, -79.74764),)","(-79.74764,)","(0.1976851,)","(0.002377737,)","(3.953543,)","(3.95354,)","((4.025455, 3.9895, 3.95354),)","(4.025455,)","(3.95354,)","((4.025455, 3.9895, 3.95354),)","(4.025455,)","(3.95354,)","((4.025455, 3.9895, 3.95354),)","(4.025455,)","(-287.0915,)","(-287.0915,)","(-287.0915,)","(983.7845,)","(983.7839,)","(983.7839,)","((983.7845, 983.7842, 983.7839),)","(983.7845,)","(15.3517,)","((0.0, 7.67585, 15.3517),)","(0.0,)","(59.83105,)","(59.83229,)","(0.311801,)","((0.3167359, 0.3142685, 0.311801),)","(0.3167359,)","(59.83231,)","((59.83105, 59.83167, 59.83231),)","(59.83105,)","(-0.8641331,)","(-0.8641329,)","(-0.8641334,)","(0.0,)","(0.0,)","(542.2,)","((541.43, 541.815, 542.2),)","(541.43,)",15.351701,1,Längsschnitt
1,5216742060270992761,Rohr R-K4163S R-K4173S,4816511167455310973,4779752876656844188,5204829332281547346,12.508950,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5048873293262650113,OSM: Knoten 299394923 -> Knoten 4105649557; Lä...,39785520,0,2,0.005,0,350,345.6,Rücklauf,,5216742060270992761,5216742060270992761,False,713616.648712,5.578233e+06,False,5216742060270992761,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.649 5578233.372, 713616.465...",4851678476955084637,5469753985021987570,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,"(0.0,)","(0.004021031,)","(27.238,)","(0.3407188,)","(0.0,)","(0.0,)","(0.1548841,)","(-79.74764,)","((-79.74764, -79.74764, -79.74764),)","(-79.74764,)","(0.1976953,)","(0.001937438,)","(3.885054,)","(3.885055,)","((3.95354, 3.9193, 3.885055),)","(3.95354,)","(3.885055,)","((3.95354, 3.9193, 3.885055),)","(3.95354,)","(3.885055,)","((3.95354, 3.9193, 3.885055),)","(3.95354,)","(-287.0915,)","(-287.0915,)","(-287.0915,)","(983.7839,)","(983.7833,)","(983.7833,)","((983.7839, 983.7836, 983.7833),)","(983.7839,)","(12.50895,)","((0.0, 6.254475, 12.50895),)","(0.0,)","(59.83229,)","(59.8333,)","(0.30778,)","((0.311801, 0.3097906, 0.30778),)","(0.311801,)","(59.83331,)","((59.83231, 59.83279, 59.83331),)","(59.83231,)","(-0.8641337,)","(-0.8641334,)","(-0.8641339,)","(0.0,)","(0.0,)","(542.93,)","((542.2, 542.565, 542.93),)","(542.2,)",27.860648,1,Längsschnitt
2,4919359344392474301,Rohr R-K4643S R-K4173S,4816511167455310973,4779752876656844188,5204829332281547346,6.265505,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5715081934973525403,OSM: Knoten 299394922 -> Knoten 4105649557; Lä...,595926249,0,2,0.005,0,350,345.6,Rücklauf,,4919359344392474301,4919359344392474301,False,713616.369043,5.578252e+06,False,4919359344392474301,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.369 5578252.145, 713616.465...",5207603338578264169,5469753985021987570,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,"(0.0,)","(0.00201406,)","(26.41319,)","(0.165492,)","(0.0,)","(0.0,)","(0.154884,)","(79.74764,)","((79.74764, 79.74764),)","(79.74764,)","(0.197702,)","(0.0009704267,)","(3.851295,)","(3.885055,)","((3.851295, 3.885055),)","(3.851295,)","(3.885055,)","((3.851295, 3.885055),)","(3.851295,)","(3.885055,)","((3.851295, 3.885055),)","(3.851295,)","(287.0915,)","(287.0915,)","(287.0915,)","(983.7831,)","(983.7833,)","(983.7833,)","((983.7831, 983.7833),)","(983.7831,)","(6.265505,)","((0.0, 6.265505),)","(0.0,)","(59.83381,)","(59.8333,)","(0.30778,)","((0.305766, 0.30778),)","(0.305766,)","(59.83331,)","((59.8338, 59.83331),)","(59.8338,)","(0.864134,)","(0.8641341,)","(0.8641339,)","(0.0,)","(0.0,)","(542.93,)","((543.29, 542.93),)","(543.29,)",34.126153,1,Längsschnitt
3,5299861566239260044,Rohr R-K4523S R-K4643S,4816511167455310973,4779752876656844188,5204829332281547346,14.407540,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5413647981880727734,OSM: Knoten 299394921 -> Knoten 299394922; Län...,595926249,0,2,0.005,0,350,345.6,Rücklauf,,5299861566239260044,5299861566239260044,False,713618.883649,5.578266e+06,False,5299861566239260044,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713618.884 5578266.331, 713616.369...",5191457421068378074,5207603338578264169,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,"(0.0,)","(0.004631334,)","(27.02703,)","(0.3893929,)","(0.0,)","(0.0,)","(0.1548839,)","(79.74764,)","((79.74764, 79.74764, 79.74764),)","(79.74764,)","(0.1977094,)","(0.002231496,)","(3.773449,)","(3.851295,)","((3.77345, 3.81237, 3.851295),)","(3.77345,)","(3.851295,)","((3.77345, 3.81237, 3.851295),)","(3.77345,)","(3.851295,)","((3.77345, 3.81237, 3.851295),)","(3.77345,)","(287.0915,)","(287.0915,)","(287.0915,)","(983.7825,)","(983.7831,)","(983.7831,)","((983.7825, 983.7828, 983.7831),)","(983.7825,)","(14.40754,)","((0.0, 7.20377, 14.40754),)","(0.0,)","(59.83496,)","(59.83381,)","(0.305766,)","((0.3011346, 0.3034503, 0.305766),)","(0.3011346,)","(59.8338,)","((59.83496, 59.83438, 59.8338),)","(59.83496,)","(0.8641343,)","(0.8641346,)","(0.8641341,)","(0.0,)","(0.0,)","(543.29,)","((544.12, 543.705, 543.29),)","(544.12,)",48.533695,1,Längsschnitt
4,5204837016964086891,Rohr R-K4513S R-K4523S,4816511167455310973,4779752876656844188,5204829332281547346,13.515840,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5134010500800575790,OSM: Knoten 4105649561 -> Knoten 299394921; Lä...,408665320,0,2,0.005,0,350,345.6,Rücklauf,,5204837016964086891,5204837016964086891,False,713616.238695,5.578280e+06,False,5204837016964086891,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.239 5578279.586, 713618.884...",4875054825941361274,5191457421068378074,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,"(0.0,)","(0.004344692,)","(27.36961,)","(0.3699233,)","(0.0,)","(0.0,)","(0.1548838,)","(79.74764,)","((79.74764, 79.74764, 79.74764),)","(79.74764,)","(0.1977196,)","(0.002093384,)","(3.729236,)","(3.77345,)","((3.729235, 3.751345, 3.77345),)","(3.729235,)","(3.77345,)","((3.729235, 3.751345, 3.77345),)","(3.729235,)","(3.77345,)","((3.729235, 3.751345, 3.77345),)","(3.729235,)","(287.0915,)","(287.0915,)","(287.0915,)","(983.782,)","(983.7825,)","(983.7825,)","((983.782, 983.7822, 983.7825),)","(983.782,)","(13.51584,)","((0.0, 6.75792, 13.51584),)","(0.0,)","(59.83606,)","(59.83496,)","(0.3011346,)","((0.2967899, 0.2989623, 0.3011346),)","(0.2967899,)","(59.83496,)","((59.83606, 59.83551, 59.83496),)","(59.83606,)","(0.8641348,)","(0.8641351,)","(0.8641346,)","(0.0,)","(0.0,)","(544.12,)","((544.6, 544.36, 544.12),)","(544.6,)",62.049538,1,Längsschnitt

In [26]:
dfs[1][0].head() # Lfdnr 2 VL

,tk,Name,FkdtroRowd,Fkltgr,Fkstrasse,L,Lzu,Rau,Jlambs,Lambda0,Zein,Zaus,Zuml,Asoll,Indschall,Baujahr,Hal,Fkcont,Fk2lrohr,Beschreibung,Idreferenz,Iplanung,Kvr,LineWidthMM,DottedLine,DN,Di,KvrKlartext,HasClosedNSCHs,Tk,Pk,InVariant,Xkor,Ykor,GeometriesDiffer,bz.Fk,bz.Qsvb,bz.Irtrenn,bz.Leckstatus,bz.Leckstart,bz.Leckend,bz.Leckort,bz.Leckmenge,bz.Imptnz,bz.Zvlimptnz,bz.Kantenzv,bz.ITrennWithNSCH,geometry,fkKI,fkKK,PipeTable: Table Name,PipeTable: Name,PipeTable: Fk,PipeTable: Dn,PipeTable: Di,PipeTable: Da,PipeTable: S,PipeTable: Wsteig,PipeTable: Wtiefe,PipeTable: Kt,PipeTable: Pn,PipeTable: Ausfallzeit,PipeTable: Reparatur,PipeTable: Rehabilitation,PipeTable: Tk,PipeTable: Pk,PipeTable: InVariant,A,DTTR,DWVERL,DWVERLABS,IAKTIV,IRTRENN,JV,MVEC_end,MVEC_sequence,MVEC_start,PDAMPF,PHR,PMIN,PVECMAX_INST_end,PVECMAX_INST_sequence,PVECMAX_INST_start,PVECMIN_INST_end,PVECMIN_INST_sequence,PVECMIN_INST_start,PVEC_end,PVEC_sequence,PVEC_start,QMAV,QMI,QMK,RHOI,RHOK,RHOVEC_end,RHOVEC_sequence,RHOVEC_start,SVEC_end,SVEC_sequence,SVEC_start,TI,TK,TTRVEC_end,TTRVEC_sequence,TTRVEC_start,TVEC_end,TVEC_sequence,TVEC_start,VAV,VI,VK,VOLDA,WVL,ZVEC_end,ZVEC_sequence,ZVEC_start,l_sum,AGSN_Lfdnr,AGSN_Name
0,5691533564979419761,Rohr V-E0 V-K1683S,4816511167455310973,4779752876656844188,5204829332281547346,15.351700,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5025945677694931826,OSM: Knoten 476971238 -> Knoten 299394923; Län...,39785520,0,1,0.005,0,350,345.6,Vorlauf,,5691533564979419761,5691533564979419761,False,713619.921383,5.578219e+06,False,5691533564979419761,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713619.921 5578218.954, 713614.649...",5398100694284104779,4825391580467484032,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,"(0.0,)","(0.004844132,)","(43.12018,)","(0.661968,)","(0.0,)","(0.0,)","(0.1527268,)","(79.74764,)","((79.74764, 79.74764, 79.74764),)","(79.74764,)","(0.701074,)","(0.002344616,)","(5.800529,)","(5.80053,)","((5.878635, 5.83958, 5.80053),)","(5.878635,)","(5.80053,)","((5.878635, 5.83958, 5.80053),)","(5.878635,)","(5.80053,)","((5.878635, 5.83958, 5.80053),)","(5.878635,)","(287.0915,)","(287.0915,)","(287.0915,)","(965.7,)","(965.7012,)","(965.7012,)","((965.7, 965.7006, 965.7012),)","(965.7,)","(15.3517,)","((0.0, 7.67585, 15.3517),)","(0.0,)","(89.99999,)","(89.99802,)","(0.004844132,)","((0.0, 0.002422066, 0.004844132),)","(0.0,)","(89.99802,)","((90.0, 89.99902, 89.99802),)","(90.0,)","(0.8803148,)","(0.8803153,)","(0.8803143,)","(0.0,)","(10082.88,)","(542.29,)","((541.49, 541.89, 542.29),)","(541.49,)",15.351701,2,Längsschnitt in mlc
1,5048873293262650113,Rohr V-K1683S V-K1693S,4816511167455310973,4779752876656844188,5204829332281547346,12.508950,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5216742060270992761,OSM: Knoten 299394923 -> Knoten 4105649557; Lä...,39785520,0,1,0.005,0,350,345.6,Vorlauf,,5048873293262650113,5048873293262650113,False,713614.648712,5.578233e+06,False,5048873293262650113,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713614.649 5578233.372, 713614.465...",4825391580467484032,5180617780362861593,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,"(0.0,)","(0.003947125,)","(43.58081,)","(0.5451502,)","(0.0,)","(0.0,)","(0.1527269,)","(79.74764,)","((79.74764, 79.74764, 79.74764),)","(79.74764,)","(0.7010268,)","(0.001910453,)","(5.732326,)","(5.732325,)","((5.80053, 5.76643, 5.732325),)","(5.80053,)","(5.732325,)","((5.80053, 5.76643, 5.732325),)","(5.80053,)","(5.732325,)","((5.80053, 5.76643, 5.732325),)","(5.80053,)","(287.0915,)","(287.0915,)","(287.0915,)","(965.7012,)","(965.7021,)","(965.7021,)","((965.7012, 965.7017, 965.7021),)","(965.7012,)","(12.50895,)","((0.0, 6.254475, 12.50895),)","(0.0,)","(89.99802,)","(89.9964,)","(0.008791257,)","((0.004844132, 0.006817694, 0.008791257),)","(0.004844132,)","(89.9964,)","((89.99802, 89.99722, 89.9964),)","(89.99802,)","(0.8803138,)","(0.8803143,)","(0.8803134,)","(0.0,)","(10081.81,)","(542.99,)","((542.29, 542.64, 542.99),)","(542.29,)",27.860648,2,Längsschnitt in mlc
2,5715081934973525403,Rohr V-K2163S V-K1693S,4816511167455310973,4779752876656844188,5204829332281547346,6.265505,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,4919359344392474301,OSM: Knoten 299394922 -> Knoten 4105649557; Lä...,595926249,0,1,0.005,0,350,345.6,Vorlauf,,5715081934973525403,5715081934973525403,False,713614.369043,5.578252e+06,False,5715081934973525403,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713614.369 5578252.145, 713614.465...",4964920487041183545,5180617780362861593,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,"(0.0,)","(0.001977044,)","(43.50409,)","(0.2725751,)","(0.0,)","(0.0,)","(0.1527269,)","(-79.74764,)","((-79.74764, -79.74764),)","(-79.74764,)","(0.7009952,)","(0.0009569113,)","(5.699167,)","(5.732325,)","((5.699165, 5.732325),)","(5.699165,)","(5.732325,)","((5.699165, 5.732325),)","(5.699165,)","(5.732325,)","((5.699165, 5.732325),)","(5.699165,)","(-287.0915,)","(-287.0915,)","(-287.0915,)","(965.7026,)","(965.7021,)","(965.7021,)","((965.7026, 965.7021),)","(965.7026,)","(6.265505,)","((0.0, 6.265505),)","(0.0,)","(89.9956,)","(89.9964,)","(0.008791257,)","((0.0107683, 0.008791257),)","(0.0107683,)","(89.9964,)","((89.99561, 89.9964),)","(89.99561,)","(-0.8803132,)","(-0.8803129,)","(-0.8803134,)","(0.0,)","(-10080.93,)","(542.99,)","((543.33, 542.99),)","(543.33,)",34.126153,2,Längsschnitt in mlc
3,5413647981880727734,Rohr V-K2043S V-K2163S,4816511167455310973,4779752876656844188,5204829332281547346,14.407540,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5299861566239260044,OSM: Knoten 299394921 -> Knoten 299394922; Län...,595926249,0,1,0.005,0,350,345.6,Vorlauf,,5413647981880727734,5413647981880727734,False,713616.883649,5.578266e+06,False,5413647981880727734,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.884 5578266.331, 713614.369...",4794016231137548967,4964920487041183545,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,"(0.0,)","(0.004546221,)","(43.24324,)","(0.6230287,)","(0.0,)","(0.0,)","(0.152727,)","(-79.74764,)","((-79.74764, -79.74764, -79.74764),)","(-79.74764,)","(0.7009605,)","(0.00220042,)","(5.630673,)","(5.699165,)","((5.630675, 5.66492, 5.699165),)","(5.630675,)","(5.699165,)","((5.630675, 5.66492, 5.699165),)","(5.630675,)","(5.699165,)","((5.630675, 5.66492, 5.699165),)","(5.630675,)","(-287.0915,)","(-287.0915,)","(-287.0915,)","(965.7037,)","(965.7026,)","(965.7026,)","((965.7037, 965.7032, 965.7026),)","(965.7037,)","(14.40754,)","((0.0, 7.20377, 14.40754),)","(0.0,)","(89.99374,)","(89.9956,)","(0.0107683,)","((0.01531452, 0.01304141, 0.0107683),)","(0.01531452,)","(89.99561,)","((89.99374, 89.99466, 89.99561),)","(89.99374,)","(-0.8803124,)","(-0.8803119,)","(-0.8803129,)","(0.0,)","(-10080.49,)","(543.33,)","((544.03, 543.6801, 543.33),)","(544.03,)",48.533695,2,Längsschnitt in mlc
4,5134010500800575790,Rohr V-K2033S V-K2043S,4816511167455310973,4779752876656844188,5204829332281547346,13.515840,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5204837016964086891,OSM: Knoten 4105649561 -> Knoten 299394921; Lä...,408665320,0,1,0.005,0,350,345.6,Vorlauf,,5134010500800575790,5134010500800575790,False,713614.238695,5.578280e+06,False,5134010500800575790,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713614.239 5578279.586, 713616.884...",5473123125979010325,4794016231137548967,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,"(0.0,)","(0.004264854,)","(42.49493,)","(0.5743546,)","(0.0,)","(0.0,)","(0.152727,)","(-79.74764,)","((-79.74764, -79.74764, -79.74764),)","(-79.74764,)","(0.7009133,)","(0.002064234,)","(5.580316,)","(5.630675,)","((5.580315, 5.605495, 5.630675),)","(5.580315,)","(5.630675,)","((5.580315, 5.605495, 5.630675),)","(5.580315,)","(5.630675,)","((5.580315, 5.605495, 5.630675),)","(5.580315,)","(-287.0915,)","(-287.0915,)","(-287.0915,)","(965.7048,)","(965.7037,)","(965.7037,)","((965.7048, 965.7043, 965.7037),)","(965.7048,)","(13.51584,)","((0.0, 6.75792, 13.51584),)","(0.0,)","(89.992,)","(89.99374,)","(0.01531453,)","((0.01957938, 0.01744695, 0.01531453),)","(0.01957938,)","(89.99374,)","((89.992, 89.99286, 89.99374),)","(89.992,)","(-0.8803114,)","(-0.880311,)","(-0.8803119,)","(0.0,)","(-10079.48,)","(544.03,)","((544.54, 544.285, 544.03),)","(544.54,)",62.049538,2,Längsschnitt in mlc

In [27]:
dfs[1][1].head() # Lfdnr 2 RL

,tk,Name,FkdtroRowd,Fkltgr,Fkstrasse,L,Lzu,Rau,Jlambs,Lambda0,Zein,Zaus,Zuml,Asoll,Indschall,Baujahr,Hal,Fkcont,Fk2lrohr,Beschreibung,Idreferenz,Iplanung,Kvr,LineWidthMM,DottedLine,DN,Di,KvrKlartext,HasClosedNSCHs,Tk,Pk,InVariant,Xkor,Ykor,GeometriesDiffer,bz.Fk,bz.Qsvb,bz.Irtrenn,bz.Leckstatus,bz.Leckstart,bz.Leckend,bz.Leckort,bz.Leckmenge,bz.Imptnz,bz.Zvlimptnz,bz.Kantenzv,bz.ITrennWithNSCH,geometry,fkKI,fkKK,PipeTable: Table Name,PipeTable: Name,PipeTable: Fk,PipeTable: Dn,PipeTable: Di,PipeTable: Da,PipeTable: S,PipeTable: Wsteig,PipeTable: Wtiefe,PipeTable: Kt,PipeTable: Pn,PipeTable: Ausfallzeit,PipeTable: Reparatur,PipeTable: Rehabilitation,PipeTable: Tk,PipeTable: Pk,PipeTable: InVariant,A,DTTR,DWVERL,DWVERLABS,IAKTIV,IRTRENN,JV,MVEC_end,MVEC_sequence,MVEC_start,PDAMPF,PHR,PMIN,PVECMAX_INST_end,PVECMAX_INST_sequence,PVECMAX_INST_start,PVECMIN_INST_end,PVECMIN_INST_sequence,PVECMIN_INST_start,PVEC_end,PVEC_sequence,PVEC_start,QMAV,QMI,QMK,RHOI,RHOK,RHOVEC_end,RHOVEC_sequence,RHOVEC_start,SVEC_end,SVEC_sequence,SVEC_start,TI,TK,TTRVEC_end,TTRVEC_sequence,TTRVEC_start,TVEC_end,TVEC_sequence,TVEC_start,VAV,VI,VK,VOLDA,WVL,ZVEC_end,ZVEC_sequence,ZVEC_start,l_sum,AGSN_Lfdnr,AGSN_Name
0,5025945677694931826,Rohr R-E0 R-K4163S,4816511167455310973,4779752876656844188,5204829332281547346,15.351700,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5691533564979419761,OSM: Knoten 476971238 -> Knoten 299394923; Län...,39785520,0,2,0.005,0,350,345.6,Rücklauf,,5025945677694931826,5025945677694931826,False,713621.921383,5.578219e+06,False,5025945677694931826,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713621.921 5578218.954, 713616.649...",5160850648779674898,4851678476955084637,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,"(0.0,)","(0.004934843,)","(26.63305,)","(0.4088626,)","(0.0,)","(0.0,)","(0.1548843,)","(-79.74764,)","((-79.74764, -79.74764, -79.74764),)","(-79.74764,)","(0.1976851,)","(0.002377737,)","(3.953543,)","(3.95354,)","((4.025455, 3.9895, 3.95354),)","(4.025455,)","(3.95354,)","((4.025455, 3.9895, 3.95354),)","(4.025455,)","(3.95354,)","((4.025455, 3.9895, 3.95354),)","(4.025455,)","(-287.0915,)","(-287.0915,)","(-287.0915,)","(983.7845,)","(983.7839,)","(983.7839,)","((983.7845, 983.7842, 983.7839),)","(983.7845,)","(15.3517,)","((0.0, 7.67585, 15.3517),)","(0.0,)","(59.83105,)","(59.83229,)","(0.311801,)","((0.3167359, 0.3142685, 0.311801),)","(0.3167359,)","(59.83231,)","((59.83105, 59.83167, 59.83231),)","(59.83105,)","(-0.8641331,)","(-0.8641329,)","(-0.8641334,)","(0.0,)","(0.0,)","(542.2,)","((541.43, 541.815, 542.2),)","(541.43,)",15.351701,2,Längsschnitt in mlc
1,5216742060270992761,Rohr R-K4163S R-K4173S,4816511167455310973,4779752876656844188,5204829332281547346,12.508950,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5048873293262650113,OSM: Knoten 299394923 -> Knoten 4105649557; Lä...,39785520,0,2,0.005,0,350,345.6,Rücklauf,,5216742060270992761,5216742060270992761,False,713616.648712,5.578233e+06,False,5216742060270992761,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.649 5578233.372, 713616.465...",4851678476955084637,5469753985021987570,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,"(0.0,)","(0.004021031,)","(27.238,)","(0.3407188,)","(0.0,)","(0.0,)","(0.1548841,)","(-79.74764,)","((-79.74764, -79.74764, -79.74764),)","(-79.74764,)","(0.1976953,)","(0.001937438,)","(3.885054,)","(3.885055,)","((3.95354, 3.9193, 3.885055),)","(3.95354,)","(3.885055,)","((3.95354, 3.9193, 3.885055),)","(3.95354,)","(3.885055,)","((3.95354, 3.9193, 3.885055),)","(3.95354,)","(-287.0915,)","(-287.0915,)","(-287.0915,)","(983.7839,)","(983.7833,)","(983.7833,)","((983.7839, 983.7836, 983.7833),)","(983.7839,)","(12.50895,)","((0.0, 6.254475, 12.50895),)","(0.0,)","(59.83229,)","(59.8333,)","(0.30778,)","((0.311801, 0.3097906, 0.30778),)","(0.311801,)","(59.83331,)","((59.83231, 59.83279, 59.83331),)","(59.83231,)","(-0.8641337,)","(-0.8641334,)","(-0.8641339,)","(0.0,)","(0.0,)","(542.93,)","((542.2, 542.565, 542.93),)","(542.2,)",27.860648,2,Längsschnitt in mlc
2,4919359344392474301,Rohr R-K4643S R-K4173S,4816511167455310973,4779752876656844188,5204829332281547346,6.265505,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5715081934973525403,OSM: Knoten 299394922 -> Knoten 4105649557; Lä...,595926249,0,2,0.005,0,350,345.6,Rücklauf,,4919359344392474301,4919359344392474301,False,713616.369043,5.578252e+06,False,4919359344392474301,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.369 5578252.145, 713616.465...",5207603338578264169,5469753985021987570,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,"(0.0,)","(0.00201406,)","(26.41319,)","(0.165492,)","(0.0,)","(0.0,)","(0.154884,)","(79.74764,)","((79.74764, 79.74764),)","(79.74764,)","(0.197702,)","(0.0009704267,)","(3.851295,)","(3.885055,)","((3.851295, 3.885055),)","(3.851295,)","(3.885055,)","((3.851295, 3.885055),)","(3.851295,)","(3.885055,)","((3.851295, 3.885055),)","(3.851295,)","(287.0915,)","(287.0915,)","(287.0915,)","(983.7831,)","(983.7833,)","(983.7833,)","((983.7831, 983.7833),)","(983.7831,)","(6.265505,)","((0.0, 6.265505),)","(0.0,)","(59.83381,)","(59.8333,)","(0.30778,)","((0.305766, 0.30778),)","(0.305766,)","(59.83331,)","((59.8338, 59.83331),)","(59.8338,)","(0.864134,)","(0.8641341,)","(0.8641339,)","(0.0,)","(0.0,)","(542.93,)","((543.29, 542.93),)","(543.29,)",34.126153,2,Längsschnitt in mlc
3,5299861566239260044,Rohr R-K4523S R-K4643S,4816511167455310973,4779752876656844188,5204829332281547346,14.407540,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5413647981880727734,OSM: Knoten 299394921 -> Knoten 299394922; Län...,595926249,0,2,0.005,0,350,345.6,Rücklauf,,5299861566239260044,5299861566239260044,False,713618.883649,5.578266e+06,False,5299861566239260044,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713618.884 5578266.331, 713616.369...",5191457421068378074,5207603338578264169,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,"(0.0,)","(0.004631334,)","(27.02703,)","(0.3893929,)","(0.0,)","(0.0,)","(0.1548839,)","(79.74764,)","((79.74764, 79.74764, 79.74764),)","(79.74764,)","(0.1977094,)","(0.002231496,)","(3.773449,)","(3.851295,)","((3.77345, 3.81237, 3.851295),)","(3.77345,)","(3.851295,)","((3.77345, 3.81237, 3.851295),)","(3.77345,)","(3.851295,)","((3.77345, 3.81237, 3.851295),)","(3.77345,)","(287.0915,)","(287.0915,)","(287.0915,)","(983.7825,)","(983.7831,)","(983.7831,)","((983.7825, 983.7828, 983.7831),)","(983.7825,)","(14.40754,)","((0.0, 7.20377, 14.40754),)","(0.0,)","(59.83496,)","(59.83381,)","(0.305766,)","((0.3011346, 0.3034503, 0.305766),)","(0.3011346,)","(59.8338,)","((59.83496, 59.83438, 59.8338),)","(59.83496,)","(0.8641343,)","(0.8641346,)","(0.8641341,)","(0.0,)","(0.0,)","(543.29,)","((544.12, 543.705, 543.29),)","(544.12,)",48.533695,2,Längsschnitt in mlc
4,5204837016964086891,Rohr R-K4513S R-K4523S,4816511167455310973,4779752876656844188,5204829332281547346,13.515840,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5134010500800575790,OSM: Knoten 4105649561 -> Knoten 299394921; Lä...,408665320,0,2,0.005,0,350,345.6,Rücklauf,,5204837016964086891,5204837016964086891,False,713616.238695,5.578280e+06,False,5204837016964086891,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.239 5578279.586, 713618.884...",4875054825941361274,5191457421068378074,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,"(0.0,)","(0.004344692,)","(27.36961,)","(0.3699233,)","(0.0,)","(0.0,)","(0.1548838,)","(79.74764,)","((79.74764, 79.74764, 79.74764),)","(79.74764,)","(0.1977196,)","(0.002093384,)","(3.729236,)","(3.77345,)","((3.729235, 3.751345, 3.77345),)","(3.729235,)","(3.77345,)","((3.729235, 3.751345, 3.77345),)","(3.729235,)","(3.77345,)","((3.729235, 3.751345, 3.77345),)","(3.729235,)","(287.0915,)","(287.0915,)","(287.0915,)","(983.782,)","(983.7825,)","(983.7825,)","((983.782, 983.7822, 983.7825),)","(983.782,)","(13.51584,)","((0.0, 6.75792, 13.51584),)","(0.0,)","(59.83606,)","(59.83496,)","(0.3011346,)","((0.2967899, 0.2989623, 0.3011346),)","(0.2967899,)","(59.83496,)","((59.83606, 59.83551, 59.83496),)","(59.83606,)","(0.8641348,)","(0.8641351,)","(0.8641346,)","(0.0,)","(0.0,)","(544.12,)","((544.6, 544.36, 544.12),)","(544.6,)",62.049538,2,Längsschnitt in mlc