# Tutorial 53: Creation of  Longitudinal Section - and Edge Dataframe

This Example demonstrates the capabilities of the class Dataframes_SIR3S_Model that extends SIR3S_Model be abilities to work directley with pandas dataframes. It is shown how to create dataframes containing information that does not concern individual elements types such as Nodes, Pipes, etc. but instead concerning more abstract SIR 3S data such as longitudinal sections or concatenations of multiple element types like hydraulic edges.

# Toolkit Release

In [1]:
#pip install

# Imports

## SIR 3S Toolkit

### Regular Import/Init

In [2]:
SIR3S_SIRGRAF_DIR = r"C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2" #change to local path

In [3]:
from sir3stoolkit.core import wrapper

In [4]:
wrapper

In [5]:
wrapper.Initialize_Toolkit(SIR3S_SIRGRAF_DIR)

### Additional Import/Init for Dataframes class

In [6]:
from sir3stoolkit.mantle.dataframes import SIR3S_Model_Dataframes

In [7]:
s3s = SIR3S_Model_Dataframes()

Initialization complete

## Additional

In [8]:
import pandas as pd
from shapely.geometry import Point
import re
import folium
from folium.plugins import HeatMap
import numpy as np
import geopandas as gpd
from shapely import wkt
import matplotlib.pyplot as plt
import contextily as cx

# Open Model

In [9]:
s3s.OpenModel(dbName=r"Toolkit_Tutorial53_Model.db3",
              providerType=s3s.ProviderTypes.SQLite,
              Mid="M-1-0-1",
              saveCurrentlyOpenModel=False,
              namedInstance="",
              userID="",
              password="")

Model is open for further operation

# Calculate Model

In [10]:
s3s.ExecCalculation(True) # To ensure result data

Model Calculation is complete

# Generate Non-Element Dataframes

## AGSN (Longitudinal Sections)

We can use the method [generate_longitudinal_section_dataframes()](https://3sconsult.github.io/sir3stoolkit/references/sir3stoolkit.mantle.html#sir3stoolkit.mantle.dataframes.SIR3S_Model_Dataframes.generate_longitudinal_section_dataframes) to obtain a list indexed by (lfdnr-1) filled with size-2-tuples with 0 - Supply and 1 - Return..

In [11]:
dfs = s3s.generate_longitudinal_section_dataframes()

[2026-03-27 18:25:53,491] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.AGSN_HydraulicProfile
[2026-03-27 18:25:53,500] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 3 element(s) of element type ObjectTypes.AGSN_HydraulicProfile.
[2026-03-27 18:25:53,517] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.AGSN_HydraulicProfile.
[2026-03-27 18:25:53,517] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 9 model_data properties.
[2026-03-27 18:25:53,524] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'Lfdnr', 'Aktiv', 'AllNodesAndLinks', 'ObjsString', 'MainWay', 'Tk', 'Pk', 'InVariant']...
[2026-03-27 18:25:53,559] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (3, 10)
[2026-03-27 18:25:53,567] INFO in sir3stoolkit.mantle.dataframes: Retrieving Hydraulic Profile with Lfdnr: 1.
[2026-03-27 18:25:53,580] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-03-27 18:25:53,584] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-03-27 18:25:53,709] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-03-27 18:25:53,717] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-03-27 18:25:53,717] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-03-27 18:25:53,721] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-03-27 18:25:53,722] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-03-27 18:25:53,722] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH'], geometry, end nodes...
[2026-03-27 18:25:54,154] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-03-27 18:25:54,329] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-03-27 18:25:54,329] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (44, 67)
[2026-03-27 18:25:54,411] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.Pipe; at timestamp: 2023-02-13 00:00:00.000 +01:00 ...
[2026-03-27 18:25:54,413] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-03-27 18:25:54,498] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-03-27 18:25:54,500] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] 1 valid timestamp(s) will be used.
[2026-03-27 18:25:54,502] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-03-27 18:25:54,503] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-03-27 18:25:54,507] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-03-27 18:25:54,519] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-03-27 18:25:55,163] INFO in sir3stoolkit.mantle.dataframes: [results] 2244 fully NaN columns dropped.
[2026-03-27 18:25:55,343] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1364)
[2026-03-27 18:25:55,344] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.Pipe ...
[2026-03-27 18:25:55,384] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-03-27 18:25:55,384] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-03-27 18:25:55,389] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-03-27 18:25:55,395] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-03-27 18:25:55,397] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-03-27 18:25:55,399] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-03-27 18:25:55,399] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-03-27 18:25:55,401] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH'], geometry, end nodes...
[2026-03-27 18:25:55,536] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-03-27 18:25:55,683] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-03-27 18:25:55,683] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (44, 67)
[2026-03-27 18:25:55,762] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.Pipe; at timestamp: 2023-02-13 00:00:00.000 +01:00 ...
[2026-03-27 18:25:55,763] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-03-27 18:25:55,844] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-03-27 18:25:55,844] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] 1 valid timestamp(s) will be used.
[2026-03-27 18:25:55,847] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-03-27 18:25:55,848] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-03-27 18:25:55,849] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-03-27 18:25:55,859] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-03-27 18:25:56,367] INFO in sir3stoolkit.mantle.dataframes: [results] 2244 fully NaN columns dropped.
[2026-03-27 18:25:56,550] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1364)
[2026-03-27 18:25:56,550] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.Pipe ...
[2026-03-27 18:25:56,600] INFO in sir3stoolkit.mantle.dataframes: Retrieving Hydraulic Profile with Lfdnr: 2.
[2026-03-27 18:25:56,600] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-03-27 18:25:56,605] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-03-27 18:25:56,609] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-03-27 18:25:56,614] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-03-27 18:25:56,614] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-03-27 18:25:56,617] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-03-27 18:25:56,617] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-03-27 18:25:56,617] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH'], geometry, end nodes...
[2026-03-27 18:25:56,784] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-03-27 18:25:56,950] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-03-27 18:25:56,955] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (44, 67)
[2026-03-27 18:25:57,051] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.Pipe; at timestamp: 2023-02-13 00:00:00.000 +01:00 ...
[2026-03-27 18:25:57,052] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-03-27 18:25:57,151] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-03-27 18:25:57,151] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] 1 valid timestamp(s) will be used.
[2026-03-27 18:25:57,161] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-03-27 18:25:57,162] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-03-27 18:25:57,165] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-03-27 18:25:57,204] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-03-27 18:25:58,248] INFO in sir3stoolkit.mantle.dataframes: [results] 2244 fully NaN columns dropped.
[2026-03-27 18:25:58,767] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1364)
[2026-03-27 18:25:58,769] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.Pipe ...
[2026-03-27 18:25:58,860] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-03-27 18:25:58,861] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-03-27 18:25:58,872] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-03-27 18:25:58,877] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-03-27 18:25:58,879] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-03-27 18:25:58,883] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-03-27 18:25:58,884] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-03-27 18:25:58,885] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH'], geometry, end nodes...
[2026-03-27 18:25:59,180] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-03-27 18:25:59,484] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-03-27 18:25:59,484] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (44, 67)
[2026-03-27 18:25:59,592] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.Pipe; at timestamp: 2023-02-13 00:00:00.000 +01:00 ...
[2026-03-27 18:25:59,594] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-03-27 18:25:59,767] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-03-27 18:25:59,767] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] 1 valid timestamp(s) will be used.
[2026-03-27 18:25:59,767] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-03-27 18:25:59,776] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-03-27 18:25:59,778] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-03-27 18:25:59,817] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-03-27 18:26:00,426] INFO in sir3stoolkit.mantle.dataframes: [results] 2244 fully NaN columns dropped.
[2026-03-27 18:26:00,611] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1364)
[2026-03-27 18:26:00,611] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.Pipe ...
[2026-03-27 18:26:00,654] INFO in sir3stoolkit.mantle.dataframes: Retrieving Hydraulic Profile with Lfdnr: 3.
[2026-03-27 18:26:00,655] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-03-27 18:26:00,657] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-03-27 18:26:00,661] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-03-27 18:26:00,665] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-03-27 18:26:00,667] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-03-27 18:26:00,668] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-03-27 18:26:00,670] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-03-27 18:26:00,671] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH'], geometry, end nodes...
[2026-03-27 18:26:00,811] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-03-27 18:26:00,975] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-03-27 18:26:00,976] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (44, 67)
[2026-03-27 18:26:01,045] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.Pipe; at timestamp: 2023-02-13 00:00:00.000 +01:00 ...
[2026-03-27 18:26:01,050] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-03-27 18:26:01,117] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-03-27 18:26:01,117] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] 1 valid timestamp(s) will be used.
[2026-03-27 18:26:01,121] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-03-27 18:26:01,123] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-03-27 18:26:01,125] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-03-27 18:26:01,150] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-03-27 18:26:01,633] INFO in sir3stoolkit.mantle.dataframes: [results] 2244 fully NaN columns dropped.
[2026-03-27 18:26:01,796] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1364)
[2026-03-27 18:26:01,796] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.Pipe ...
[2026-03-27 18:26:01,837] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-03-27 18:26:01,838] DEBUG in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-03-27 18:26:01,841] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-03-27 18:26:01,841] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-03-27 18:26:01,850] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-03-27 18:26:01,851] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.

In [12]:
dfs[0][0].head() # Lfdnr 1, Vl

,tk,Name,FkdtroRowd,Fkltgr,Fkstrasse,L,Lzu,Rau,Jlambs,Lambda0,Zein,Zaus,Zuml,Asoll,Indschall,Baujahr,Hal,Fkcont,Fk2lrohr,Beschreibung,Idreferenz,Iplanung,Kvr,LineWidthMM,DottedLine,DN,Di,KvrKlartext,HasClosedNSCHs,Tk,Pk,InVariant,Xkor,Ykor,GeometriesDiffer,bz.Fk,bz.Qsvb,bz.Irtrenn,bz.Leckstatus,bz.Leckstart,bz.Leckend,bz.Leckort,bz.Leckmenge,bz.Imptnz,bz.Zvlimptnz,bz.Kantenzv,bz.ITrennWithNSCH,geometry,fkKI,fkKK,PipeTable: Table Name,PipeTable: Name,PipeTable: Fk,PipeTable: Dn,PipeTable: Di,PipeTable: Da,PipeTable: S,PipeTable: Wsteig,PipeTable: Wtiefe,PipeTable: Kt,PipeTable: Pn,PipeTable: Ausfallzeit,PipeTable: Reparatur,PipeTable: Rehabilitation,PipeTable: Tk,PipeTable: Pk,PipeTable: InVariant,A,DTTR,DWVERL,DWVERLABS,IAKTIV,IRTRENN,JV,MVEC_start,MVEC_end,MVEC_sequence,PDAMPF,PHR,PMIN,PVEC_start,PVEC_end,PVEC_sequence,PVECMAX_INST_start,PVECMAX_INST_end,PVECMAX_INST_sequence,PVECMIN_INST_start,PVECMIN_INST_end,PVECMIN_INST_sequence,QMAV,QMI,QMK,RHOI,RHOK,RHOVEC_start,RHOVEC_end,RHOVEC_sequence,SVEC_start,SVEC_end,SVEC_sequence,TI,TK,TTRVEC_start,TTRVEC_end,TTRVEC_sequence,TVEC_start,TVEC_end,TVEC_sequence,VAV,VI,VK,VOLDA,WVL,ZVEC_start,ZVEC_end,ZVEC_sequence,l_sum,AGSN_Lfdnr,AGSN_Name
0,5691533564979419761,Rohr V-E0 V-K1683S,4816511167455310973,4779752876656844188,5204829332281547346,15.351700,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5025945677694931826,OSM: Knoten 476971238 -> Knoten 299394923; Län...,39785520,0,1,0.005,0,350,345.6,Vorlauf,,5691533564979419761,5691533564979419761,False,713619.921383,5.578219e+06,False,5691533564979419761,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713619.921 5578218.954, 713614.649...",5398100694284104779,4825391580467484032,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004844,43.12017,0.661968,0.0,0.0,0.152727,79.74766,79.74766,"(79.74766, 79.74766, 79.74766)",0.701074,0.002345,5.800681,5.878785,5.800680,"(5.878785, 5.839735, 5.80068)",5.878785,5.800680,"(5.878785, 5.839735, 5.80068)",5.878785,5.800680,"(5.878785, 5.839735, 5.80068)",287.0916,287.0916,287.0916,965.7,965.7012,965.7000,965.7012,"(965.7, 965.7006, 965.7012)",0.0,15.351700,"(0.0, 7.67585, 15.3517)",89.99999,89.99802,0.000000,0.004844,"(0.0, 0.002422066, 0.004844131)",90.00000,89.99802,"(90.0, 89.99902, 89.99802)",0.880315,0.880316,0.880314,0.0,10082.88,541.49,542.29,"(541.49, 541.89, 542.29)",15.351701,1,Längsschnitt
1,5048873293262650113,Rohr V-K1683S V-K1693S,4816511167455310973,4779752876656844188,5204829332281547346,12.508950,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5216742060270992761,OSM: Knoten 299394923 -> Knoten 4105649557; Lä...,39785520,0,1,0.005,0,350,345.6,Vorlauf,,5048873293262650113,5048873293262650113,False,713614.648712,5.578233e+06,False,5048873293262650113,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713614.649 5578233.372, 713614.465...",4825391580467484032,5180617780362861593,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.003947,43.5808,0.54515,0.0,0.0,0.152727,79.74766,79.74766,"(79.74766, 79.74766, 79.74766)",0.701027,0.00191,5.732477,5.800680,5.732475,"(5.80068, 5.76658, 5.732475)",5.800680,5.732475,"(5.80068, 5.76658, 5.732475)",5.800680,5.732475,"(5.80068, 5.76658, 5.732475)",287.0916,287.0916,287.0916,965.7012,965.7021,965.7012,965.7021,"(965.7012, 965.7017, 965.7021)",0.0,12.508950,"(0.0, 6.254475, 12.50895)",89.99802,89.9964,0.004844,0.008791,"(0.004844131, 0.006817694, 0.008791256)",89.99802,89.99640,"(89.99802, 89.99722, 89.9964)",0.880314,0.880314,0.880313,0.0,10081.81,542.29,542.99,"(542.29, 542.64, 542.99)",27.860648,1,Längsschnitt
2,5715081934973525403,Rohr V-K2163S V-K1693S,4816511167455310973,4779752876656844188,5204829332281547346,6.265505,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,4919359344392474301,OSM: Knoten 299394922 -> Knoten 4105649557; Lä...,595926249,0,1,0.005,0,350,345.6,Vorlauf,,5715081934973525403,5715081934973525403,False,713614.369043,5.578252e+06,False,5715081934973525403,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713614.369 5578252.145, 713614.465...",4964920487041183545,5180617780362861593,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.001977,43.50408,0.272575,0.0,0.0,0.152727,-79.74766,-79.74766,"(-79.74766, -79.74766)",0.700995,0.000957,5.699318,5.699320,5.732475,"(5.69932, 5.732475)",5.699320,5.732475,"(5.69932, 5.732475)",5.699320,5.732475,"(5.69932, 5.732475)",-287.0916,-287.0916,-287.0916,965.7026,965.7021,965.7026,965.7021,"(965.7026, 965.7021)",0.0,6.265505,"(0.0, 6.265505)",89.9956,89.9964,0.010768,0.008791,"(0.0107683, 0.008791256)",89.99561,89.99640,"(89.99561, 89.9964)",-0.880313,-0.880313,-0.880313,0.0,-10080.92,543.33,542.99,"(543.33, 542.99)",34.126153,1,Längsschnitt
3,5413647981880727734,Rohr V-K2043S V-K2163S,4816511167455310973,4779752876656844188,5204829332281547346,14.407540,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5299861566239260044,OSM: Knoten 299394921 -> Knoten 299394922; Län...,595926249,0,1,0.005,0,350,345.6,Vorlauf,,5413647981880727734,5413647981880727734,False,713616.883649,5.578266e+06,False,5413647981880727734,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.884 5578266.331, 713614.369...",4794016231137548967,4964920487041183545,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004546,43.24324,0.623029,0.0,0.0,0.152727,-79.74766,-79.74766,"(-79.74766, -79.74766, -79.74766)",0.70096,0.0022,5.630825,5.630825,5.699320,"(5.630825, 5.66507, 5.69932)",5.630825,5.699320,"(5.630825, 5.66507, 5.69932)",5.630825,5.699320,"(5.630825, 5.66507, 5.69932)",-287.0916,-287.0916,-287.0916,965.7037,965.7026,965.7037,965.7026,"(965.7037, 965.7032, 965.7026)",0.0,14.407540,"(0.0, 7.20377, 14.40754)",89.99374,89.9956,0.015315,0.010768,"(0.01531452, 0.01304141, 0.0107683)",89.99374,89.99561,"(89.99374, 89.99466, 89.99561)",-0.880313,-0.880312,-0.880313,0.0,-10080.49,544.03,543.33,"(544.03, 543.6801, 543.33)",48.533695,1,Längsschnitt
4,5134010500800575790,Rohr V-K2033S V-K2043S,4816511167455310973,4779752876656844188,5204829332281547346,13.515840,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5204837016964086891,OSM: Knoten 4105649561 -> Knoten 299394921; Lä...,408665320,0,1,0.005,0,350,345.6,Vorlauf,,5134010500800575790,5134010500800575790,False,713614.238695,5.578280e+06,False,5134010500800575790,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713614.239 5578279.586, 713616.884...",5473123125979010325,4794016231137548967,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004265,42.49492,0.574354,0.0,0.0,0.152727,-79.74766,-79.74766,"(-79.74766, -79.74766, -79.74766)",0.700913,0.002064,5.580467,5.580465,5.630825,"(5.580465, 5.605645, 5.630825)",5.580465,5.630825,"(5.580465, 5.605645, 5.630825)",5.580465,5.630825,"(5.580465, 5.605645, 5.630825)",-287.0916,-287.0916,-287.0916,965.7048,965.7037,965.7048,965.7037,"(965.7048, 965.7043, 965.7037)",0.0,13.515840,"(0.0, 6.75792, 13.51584)",89.992,89.99374,0.019579,0.015315,"(0.01957937, 0.01744694, 0.01531452)",89.99200,89.99374,"(89.992, 89.99286, 89.99374)",-0.880312,-0.880311,-0.880312,0.0,-10079.47,544.54,544.03,"(544.54, 544.285, 544.03)",62.049538,1,Längsschnitt

In [13]:
dfs[0][1].head() # Lfdnr 1 RL

,tk,Name,FkdtroRowd,Fkltgr,Fkstrasse,L,Lzu,Rau,Jlambs,Lambda0,Zein,Zaus,Zuml,Asoll,Indschall,Baujahr,Hal,Fkcont,Fk2lrohr,Beschreibung,Idreferenz,Iplanung,Kvr,LineWidthMM,DottedLine,DN,Di,KvrKlartext,HasClosedNSCHs,Tk,Pk,InVariant,Xkor,Ykor,GeometriesDiffer,bz.Fk,bz.Qsvb,bz.Irtrenn,bz.Leckstatus,bz.Leckstart,bz.Leckend,bz.Leckort,bz.Leckmenge,bz.Imptnz,bz.Zvlimptnz,bz.Kantenzv,bz.ITrennWithNSCH,geometry,fkKI,fkKK,PipeTable: Table Name,PipeTable: Name,PipeTable: Fk,PipeTable: Dn,PipeTable: Di,PipeTable: Da,PipeTable: S,PipeTable: Wsteig,PipeTable: Wtiefe,PipeTable: Kt,PipeTable: Pn,PipeTable: Ausfallzeit,PipeTable: Reparatur,PipeTable: Rehabilitation,PipeTable: Tk,PipeTable: Pk,PipeTable: InVariant,A,DTTR,DWVERL,DWVERLABS,IAKTIV,IRTRENN,JV,MVEC_start,MVEC_end,MVEC_sequence,PDAMPF,PHR,PMIN,PVEC_start,PVEC_end,PVEC_sequence,PVECMAX_INST_start,PVECMAX_INST_end,PVECMAX_INST_sequence,PVECMIN_INST_start,PVECMIN_INST_end,PVECMIN_INST_sequence,QMAV,QMI,QMK,RHOI,RHOK,RHOVEC_start,RHOVEC_end,RHOVEC_sequence,SVEC_start,SVEC_end,SVEC_sequence,TI,TK,TTRVEC_start,TTRVEC_end,TTRVEC_sequence,TVEC_start,TVEC_end,TVEC_sequence,VAV,VI,VK,VOLDA,WVL,ZVEC_start,ZVEC_end,ZVEC_sequence,l_sum,AGSN_Lfdnr,AGSN_Name
0,5025945677694931826,Rohr R-E0 R-K4163S,4816511167455310973,4779752876656844188,5204829332281547346,15.351700,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5691533564979419761,OSM: Knoten 476971238 -> Knoten 299394923; Län...,39785520,0,2,0.005,0,350,345.6,Rücklauf,,5025945677694931826,5025945677694931826,False,713621.921383,5.578219e+06,False,5025945677694931826,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713621.921 5578218.954, 713616.649...",5160850648779674898,4851678476955084637,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004935,26.63305,0.408863,0.0,0.0,0.154884,-79.74766,-79.74766,"(-79.74766, -79.74766, -79.74766)",0.197685,0.002378,3.953687,4.025600,3.953685,"(4.0256, 3.98964, 3.953685)",4.025600,3.953685,"(4.0256, 3.98964, 3.953685)",4.025600,3.953685,"(4.0256, 3.98964, 3.953685)",-287.0916,-287.0916,-287.0916,983.7845,983.7839,983.7845,983.7839,"(983.7845, 983.7842, 983.7839)",0.0,15.351700,"(0.0, 7.67585, 15.3517)",59.83105,59.83229,0.316736,0.311801,"(0.3167358, 0.3142684, 0.311801)",59.83105,59.83231,"(59.83105, 59.83167, 59.83231)",-0.864133,-0.864133,-0.864133,0.0,0.0,541.43,542.20,"(541.43, 541.815, 542.2)",15.351701,1,Längsschnitt
1,5216742060270992761,Rohr R-K4163S R-K4173S,4816511167455310973,4779752876656844188,5204829332281547346,12.508950,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5048873293262650113,OSM: Knoten 299394923 -> Knoten 4105649557; Lä...,39785520,0,2,0.005,0,350,345.6,Rücklauf,,5216742060270992761,5216742060270992761,False,713616.648712,5.578233e+06,False,5216742060270992761,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.649 5578233.372, 713616.465...",4851678476955084637,5469753985021987570,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004021,27.238,0.340719,0.0,0.0,0.154884,-79.74766,-79.74766,"(-79.74766, -79.74766, -79.74766)",0.197695,0.001937,3.885199,3.953685,3.885200,"(3.953685, 3.919445, 3.8852)",3.953685,3.885200,"(3.953685, 3.919445, 3.8852)",3.953685,3.885200,"(3.953685, 3.919445, 3.8852)",-287.0916,-287.0916,-287.0916,983.7839,983.7833,983.7839,983.7833,"(983.7839, 983.7836, 983.7833)",0.0,12.508950,"(0.0, 6.254475, 12.50895)",59.83229,59.8333,0.311801,0.307780,"(0.311801, 0.3097905, 0.3077799)",59.83231,59.83331,"(59.83231, 59.83279, 59.83331)",-0.864134,-0.864133,-0.864134,0.0,0.0,542.20,542.93,"(542.2, 542.565, 542.93)",27.860648,1,Längsschnitt
2,4919359344392474301,Rohr R-K4643S R-K4173S,4816511167455310973,4779752876656844188,5204829332281547346,6.265505,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5715081934973525403,OSM: Knoten 299394922 -> Knoten 4105649557; Lä...,595926249,0,2,0.005,0,350,345.6,Rücklauf,,4919359344392474301,4919359344392474301,False,713616.369043,5.578252e+06,False,4919359344392474301,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.369 5578252.145, 713616.465...",5207603338578264169,5469753985021987570,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.002014,26.41319,0.165492,0.0,0.0,0.154884,79.74766,79.74766,"(79.74766, 79.74766)",0.197702,0.00097,3.851439,3.851440,3.885200,"(3.85144, 3.8852)",3.851440,3.885200,"(3.85144, 3.8852)",3.851440,3.885200,"(3.85144, 3.8852)",287.0916,287.0916,287.0916,983.7831,983.7833,983.7831,983.7833,"(983.7831, 983.7833)",0.0,6.265505,"(0.0, 6.265505)",59.83381,59.8333,0.305766,0.307780,"(0.3057659, 0.3077799)",59.83380,59.83331,"(59.8338, 59.83331)",0.864134,0.864134,0.864134,0.0,0.0,543.29,542.93,"(543.29, 542.93)",34.126153,1,Längsschnitt
3,5299861566239260044,Rohr R-K4523S R-K4643S,4816511167455310973,4779752876656844188,5204829332281547346,14.407540,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5413647981880727734,OSM: Knoten 299394921 -> Knoten 299394922; Län...,595926249,0,2,0.005,0,350,345.6,Rücklauf,,5299861566239260044,5299861566239260044,False,713618.883649,5.578266e+06,False,5299861566239260044,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713618.884 5578266.331, 713616.369...",5191457421068378074,5207603338578264169,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004631,27.02702,0.389393,0.0,0.0,0.154884,79.74766,79.74766,"(79.74766, 79.74766, 79.74766)",0.197709,0.002231,3.773594,3.773595,3.851440,"(3.773595, 3.812515, 3.85144)",3.773595,3.851440,"(3.773595, 3.812515, 3.85144)",3.773595,3.851440,"(3.773595, 3.812515, 3.85144)",287.0916,287.0916,287.0916,983.7825,983.7831,983.7825,983.7831,"(983.7825, 983.7828, 983.7831)",0.0,14.407540,"(0.0, 7.20377, 14.40754)",59.83496,59.83381,0.301135,0.305766,"(0.3011346, 0.3034503, 0.3057659)",59.83496,59.83380,"(59.83496, 59.83438, 59.8338)",0.864135,0.864135,0.864134,0.0,0.0,544.12,543.29,"(544.12, 543.705, 543.29)",48.533695,1,Längsschnitt
4,5204837016964086891,Rohr R-K4513S R-K4523S,4816511167455310973,4779752876656844188,5204829332281547346,13.515840,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5134010500800575790,OSM: Knoten 4105649561 -> Knoten 299394921; Lä...,408665320,0,2,0.005,0,350,345.6,Rücklauf,,5204837016964086891,5204837016964086891,False,713616.238695,5.578280e+06,False,5204837016964086891,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.239 5578279.586, 713618.884...",4875054825941361274,5191457421068378074,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004345,27.36961,0.369923,0.0,0.0,0.154884,79.74766,79.74766,"(79.74766, 79.74766, 79.74766)",0.19772,0.002093,3.72938,3.729380,3.773595,"(3.72938, 3.751485, 3.773595)",3.729380,3.773595,"(3.72938, 3.751485, 3.773595)",3.729380,3.773595,"(3.72938, 3.751485, 3.773595)",287.0916,287.0916,287.0916,983.782,983.7825,983.7820,983.7825,"(983.782, 983.7822, 983.7825)",0.0,13.515840,"(0.0, 6.75792, 13.51584)",59.83606,59.83496,0.296790,0.301135,"(0.2967899, 0.2989622, 0.3011346)",59.83606,59.83496,"(59.83606, 59.83551, 59.83496)",0.864135,0.864135,0.864135,0.0,0.0,544.60,544.12,"(544.6, 544.36, 544.12)",62.049538,1,Längsschnitt

In [14]:
dfs[1][0].head() # Lfdnr 2 VL

,tk,Name,FkdtroRowd,Fkltgr,Fkstrasse,L,Lzu,Rau,Jlambs,Lambda0,Zein,Zaus,Zuml,Asoll,Indschall,Baujahr,Hal,Fkcont,Fk2lrohr,Beschreibung,Idreferenz,Iplanung,Kvr,LineWidthMM,DottedLine,DN,Di,KvrKlartext,HasClosedNSCHs,Tk,Pk,InVariant,Xkor,Ykor,GeometriesDiffer,bz.Fk,bz.Qsvb,bz.Irtrenn,bz.Leckstatus,bz.Leckstart,bz.Leckend,bz.Leckort,bz.Leckmenge,bz.Imptnz,bz.Zvlimptnz,bz.Kantenzv,bz.ITrennWithNSCH,geometry,fkKI,fkKK,PipeTable: Table Name,PipeTable: Name,PipeTable: Fk,PipeTable: Dn,PipeTable: Di,PipeTable: Da,PipeTable: S,PipeTable: Wsteig,PipeTable: Wtiefe,PipeTable: Kt,PipeTable: Pn,PipeTable: Ausfallzeit,PipeTable: Reparatur,PipeTable: Rehabilitation,PipeTable: Tk,PipeTable: Pk,PipeTable: InVariant,A,DTTR,DWVERL,DWVERLABS,IAKTIV,IRTRENN,JV,MVEC_start,MVEC_end,MVEC_sequence,PDAMPF,PHR,PMIN,PVEC_start,PVEC_end,PVEC_sequence,PVECMAX_INST_start,PVECMAX_INST_end,PVECMAX_INST_sequence,PVECMIN_INST_start,PVECMIN_INST_end,PVECMIN_INST_sequence,QMAV,QMI,QMK,RHOI,RHOK,RHOVEC_start,RHOVEC_end,RHOVEC_sequence,SVEC_start,SVEC_end,SVEC_sequence,TI,TK,TTRVEC_start,TTRVEC_end,TTRVEC_sequence,TVEC_start,TVEC_end,TVEC_sequence,VAV,VI,VK,VOLDA,WVL,ZVEC_start,ZVEC_end,ZVEC_sequence,l_sum,AGSN_Lfdnr,AGSN_Name
0,5691533564979419761,Rohr V-E0 V-K1683S,4816511167455310973,4779752876656844188,5204829332281547346,15.351700,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5025945677694931826,OSM: Knoten 476971238 -> Knoten 299394923; Län...,39785520,0,1,0.005,0,350,345.6,Vorlauf,,5691533564979419761,5691533564979419761,False,713619.921383,5.578219e+06,False,5691533564979419761,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713619.921 5578218.954, 713614.649...",5398100694284104779,4825391580467484032,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004844,43.12017,0.661968,0.0,0.0,0.152727,79.74766,79.74766,"(79.74766, 79.74766, 79.74766)",0.701074,0.002345,5.800681,5.878785,5.800680,"(5.878785, 5.839735, 5.80068)",5.878785,5.800680,"(5.878785, 5.839735, 5.80068)",5.878785,5.800680,"(5.878785, 5.839735, 5.80068)",287.0916,287.0916,287.0916,965.7,965.7012,965.7000,965.7012,"(965.7, 965.7006, 965.7012)",0.0,15.351700,"(0.0, 7.67585, 15.3517)",89.99999,89.99802,0.000000,0.004844,"(0.0, 0.002422066, 0.004844131)",90.00000,89.99802,"(90.0, 89.99902, 89.99802)",0.880315,0.880316,0.880314,0.0,10082.88,541.49,542.29,"(541.49, 541.89, 542.29)",15.351701,2,Längsschnitt in mlc
1,5048873293262650113,Rohr V-K1683S V-K1693S,4816511167455310973,4779752876656844188,5204829332281547346,12.508950,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5216742060270992761,OSM: Knoten 299394923 -> Knoten 4105649557; Lä...,39785520,0,1,0.005,0,350,345.6,Vorlauf,,5048873293262650113,5048873293262650113,False,713614.648712,5.578233e+06,False,5048873293262650113,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713614.649 5578233.372, 713614.465...",4825391580467484032,5180617780362861593,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.003947,43.5808,0.54515,0.0,0.0,0.152727,79.74766,79.74766,"(79.74766, 79.74766, 79.74766)",0.701027,0.00191,5.732477,5.800680,5.732475,"(5.80068, 5.76658, 5.732475)",5.800680,5.732475,"(5.80068, 5.76658, 5.732475)",5.800680,5.732475,"(5.80068, 5.76658, 5.732475)",287.0916,287.0916,287.0916,965.7012,965.7021,965.7012,965.7021,"(965.7012, 965.7017, 965.7021)",0.0,12.508950,"(0.0, 6.254475, 12.50895)",89.99802,89.9964,0.004844,0.008791,"(0.004844131, 0.006817694, 0.008791256)",89.99802,89.99640,"(89.99802, 89.99722, 89.9964)",0.880314,0.880314,0.880313,0.0,10081.81,542.29,542.99,"(542.29, 542.64, 542.99)",27.860648,2,Längsschnitt in mlc
2,5715081934973525403,Rohr V-K2163S V-K1693S,4816511167455310973,4779752876656844188,5204829332281547346,6.265505,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,4919359344392474301,OSM: Knoten 299394922 -> Knoten 4105649557; Lä...,595926249,0,1,0.005,0,350,345.6,Vorlauf,,5715081934973525403,5715081934973525403,False,713614.369043,5.578252e+06,False,5715081934973525403,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713614.369 5578252.145, 713614.465...",4964920487041183545,5180617780362861593,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.001977,43.50408,0.272575,0.0,0.0,0.152727,-79.74766,-79.74766,"(-79.74766, -79.74766)",0.700995,0.000957,5.699318,5.699320,5.732475,"(5.69932, 5.732475)",5.699320,5.732475,"(5.69932, 5.732475)",5.699320,5.732475,"(5.69932, 5.732475)",-287.0916,-287.0916,-287.0916,965.7026,965.7021,965.7026,965.7021,"(965.7026, 965.7021)",0.0,6.265505,"(0.0, 6.265505)",89.9956,89.9964,0.010768,0.008791,"(0.0107683, 0.008791256)",89.99561,89.99640,"(89.99561, 89.9964)",-0.880313,-0.880313,-0.880313,0.0,-10080.92,543.33,542.99,"(543.33, 542.99)",34.126153,2,Längsschnitt in mlc
3,5413647981880727734,Rohr V-K2043S V-K2163S,4816511167455310973,4779752876656844188,5204829332281547346,14.407540,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5299861566239260044,OSM: Knoten 299394921 -> Knoten 299394922; Län...,595926249,0,1,0.005,0,350,345.6,Vorlauf,,5413647981880727734,5413647981880727734,False,713616.883649,5.578266e+06,False,5413647981880727734,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.884 5578266.331, 713614.369...",4794016231137548967,4964920487041183545,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004546,43.24324,0.623029,0.0,0.0,0.152727,-79.74766,-79.74766,"(-79.74766, -79.74766, -79.74766)",0.70096,0.0022,5.630825,5.630825,5.699320,"(5.630825, 5.66507, 5.69932)",5.630825,5.699320,"(5.630825, 5.66507, 5.69932)",5.630825,5.699320,"(5.630825, 5.66507, 5.69932)",-287.0916,-287.0916,-287.0916,965.7037,965.7026,965.7037,965.7026,"(965.7037, 965.7032, 965.7026)",0.0,14.407540,"(0.0, 7.20377, 14.40754)",89.99374,89.9956,0.015315,0.010768,"(0.01531452, 0.01304141, 0.0107683)",89.99374,89.99561,"(89.99374, 89.99466, 89.99561)",-0.880313,-0.880312,-0.880313,0.0,-10080.49,544.03,543.33,"(544.03, 543.6801, 543.33)",48.533695,2,Längsschnitt in mlc
4,5134010500800575790,Rohr V-K2033S V-K2043S,4816511167455310973,4779752876656844188,5204829332281547346,13.515840,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5204837016964086891,OSM: Knoten 4105649561 -> Knoten 299394921; Lä...,408665320,0,1,0.005,0,350,345.6,Vorlauf,,5134010500800575790,5134010500800575790,False,713614.238695,5.578280e+06,False,5134010500800575790,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713614.239 5578279.586, 713616.884...",5473123125979010325,4794016231137548967,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004265,42.49492,0.574354,0.0,0.0,0.152727,-79.74766,-79.74766,"(-79.74766, -79.74766, -79.74766)",0.700913,0.002064,5.580467,5.580465,5.630825,"(5.580465, 5.605645, 5.630825)",5.580465,5.630825,"(5.580465, 5.605645, 5.630825)",5.580465,5.630825,"(5.580465, 5.605645, 5.630825)",-287.0916,-287.0916,-287.0916,965.7048,965.7037,965.7048,965.7037,"(965.7048, 965.7043, 965.7037)",0.0,13.515840,"(0.0, 6.75792, 13.51584)",89.992,89.99374,0.019579,0.015315,"(0.01957937, 0.01744694, 0.01531452)",89.99200,89.99374,"(89.992, 89.99286, 89.99374)",-0.880312,-0.880311,-0.880312,0.0,-10079.47,544.54,544.03,"(544.54, 544.285, 544.03)",62.049538,2,Längsschnitt in mlc

In [15]:
dfs[1][1].head() # Lfdnr 2 RL

,tk,Name,FkdtroRowd,Fkltgr,Fkstrasse,L,Lzu,Rau,Jlambs,Lambda0,Zein,Zaus,Zuml,Asoll,Indschall,Baujahr,Hal,Fkcont,Fk2lrohr,Beschreibung,Idreferenz,Iplanung,Kvr,LineWidthMM,DottedLine,DN,Di,KvrKlartext,HasClosedNSCHs,Tk,Pk,InVariant,Xkor,Ykor,GeometriesDiffer,bz.Fk,bz.Qsvb,bz.Irtrenn,bz.Leckstatus,bz.Leckstart,bz.Leckend,bz.Leckort,bz.Leckmenge,bz.Imptnz,bz.Zvlimptnz,bz.Kantenzv,bz.ITrennWithNSCH,geometry,fkKI,fkKK,PipeTable: Table Name,PipeTable: Name,PipeTable: Fk,PipeTable: Dn,PipeTable: Di,PipeTable: Da,PipeTable: S,PipeTable: Wsteig,PipeTable: Wtiefe,PipeTable: Kt,PipeTable: Pn,PipeTable: Ausfallzeit,PipeTable: Reparatur,PipeTable: Rehabilitation,PipeTable: Tk,PipeTable: Pk,PipeTable: InVariant,A,DTTR,DWVERL,DWVERLABS,IAKTIV,IRTRENN,JV,MVEC_start,MVEC_end,MVEC_sequence,PDAMPF,PHR,PMIN,PVEC_start,PVEC_end,PVEC_sequence,PVECMAX_INST_start,PVECMAX_INST_end,PVECMAX_INST_sequence,PVECMIN_INST_start,PVECMIN_INST_end,PVECMIN_INST_sequence,QMAV,QMI,QMK,RHOI,RHOK,RHOVEC_start,RHOVEC_end,RHOVEC_sequence,SVEC_start,SVEC_end,SVEC_sequence,TI,TK,TTRVEC_start,TTRVEC_end,TTRVEC_sequence,TVEC_start,TVEC_end,TVEC_sequence,VAV,VI,VK,VOLDA,WVL,ZVEC_start,ZVEC_end,ZVEC_sequence,l_sum,AGSN_Lfdnr,AGSN_Name
0,5025945677694931826,Rohr R-E0 R-K4163S,4816511167455310973,4779752876656844188,5204829332281547346,15.351700,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5691533564979419761,OSM: Knoten 476971238 -> Knoten 299394923; Län...,39785520,0,2,0.005,0,350,345.6,Rücklauf,,5025945677694931826,5025945677694931826,False,713621.921383,5.578219e+06,False,5025945677694931826,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713621.921 5578218.954, 713616.649...",5160850648779674898,4851678476955084637,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004935,26.63305,0.408863,0.0,0.0,0.154884,-79.74766,-79.74766,"(-79.74766, -79.74766, -79.74766)",0.197685,0.002378,3.953687,4.025600,3.953685,"(4.0256, 3.98964, 3.953685)",4.025600,3.953685,"(4.0256, 3.98964, 3.953685)",4.025600,3.953685,"(4.0256, 3.98964, 3.953685)",-287.0916,-287.0916,-287.0916,983.7845,983.7839,983.7845,983.7839,"(983.7845, 983.7842, 983.7839)",0.0,15.351700,"(0.0, 7.67585, 15.3517)",59.83105,59.83229,0.316736,0.311801,"(0.3167358, 0.3142684, 0.311801)",59.83105,59.83231,"(59.83105, 59.83167, 59.83231)",-0.864133,-0.864133,-0.864133,0.0,0.0,541.43,542.20,"(541.43, 541.815, 542.2)",15.351701,2,Längsschnitt in mlc
1,5216742060270992761,Rohr R-K4163S R-K4173S,4816511167455310973,4779752876656844188,5204829332281547346,12.508950,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5048873293262650113,OSM: Knoten 299394923 -> Knoten 4105649557; Lä...,39785520,0,2,0.005,0,350,345.6,Rücklauf,,5216742060270992761,5216742060270992761,False,713616.648712,5.578233e+06,False,5216742060270992761,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.649 5578233.372, 713616.465...",4851678476955084637,5469753985021987570,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004021,27.238,0.340719,0.0,0.0,0.154884,-79.74766,-79.74766,"(-79.74766, -79.74766, -79.74766)",0.197695,0.001937,3.885199,3.953685,3.885200,"(3.953685, 3.919445, 3.8852)",3.953685,3.885200,"(3.953685, 3.919445, 3.8852)",3.953685,3.885200,"(3.953685, 3.919445, 3.8852)",-287.0916,-287.0916,-287.0916,983.7839,983.7833,983.7839,983.7833,"(983.7839, 983.7836, 983.7833)",0.0,12.508950,"(0.0, 6.254475, 12.50895)",59.83229,59.8333,0.311801,0.307780,"(0.311801, 0.3097905, 0.3077799)",59.83231,59.83331,"(59.83231, 59.83279, 59.83331)",-0.864134,-0.864133,-0.864134,0.0,0.0,542.20,542.93,"(542.2, 542.565, 542.93)",27.860648,2,Längsschnitt in mlc
2,4919359344392474301,Rohr R-K4643S R-K4173S,4816511167455310973,4779752876656844188,5204829332281547346,6.265505,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5715081934973525403,OSM: Knoten 299394922 -> Knoten 4105649557; Lä...,595926249,0,2,0.005,0,350,345.6,Rücklauf,,4919359344392474301,4919359344392474301,False,713616.369043,5.578252e+06,False,4919359344392474301,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.369 5578252.145, 713616.465...",5207603338578264169,5469753985021987570,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.002014,26.41319,0.165492,0.0,0.0,0.154884,79.74766,79.74766,"(79.74766, 79.74766)",0.197702,0.00097,3.851439,3.851440,3.885200,"(3.85144, 3.8852)",3.851440,3.885200,"(3.85144, 3.8852)",3.851440,3.885200,"(3.85144, 3.8852)",287.0916,287.0916,287.0916,983.7831,983.7833,983.7831,983.7833,"(983.7831, 983.7833)",0.0,6.265505,"(0.0, 6.265505)",59.83381,59.8333,0.305766,0.307780,"(0.3057659, 0.3077799)",59.83380,59.83331,"(59.8338, 59.83331)",0.864134,0.864134,0.864134,0.0,0.0,543.29,542.93,"(543.29, 542.93)",34.126153,2,Längsschnitt in mlc
3,5299861566239260044,Rohr R-K4523S R-K4643S,4816511167455310973,4779752876656844188,5204829332281547346,14.407540,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5413647981880727734,OSM: Knoten 299394921 -> Knoten 299394922; Län...,595926249,0,2,0.005,0,350,345.6,Rücklauf,,5299861566239260044,5299861566239260044,False,713618.883649,5.578266e+06,False,5299861566239260044,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713618.884 5578266.331, 713616.369...",5191457421068378074,5207603338578264169,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004631,27.02702,0.389393,0.0,0.0,0.154884,79.74766,79.74766,"(79.74766, 79.74766, 79.74766)",0.197709,0.002231,3.773594,3.773595,3.851440,"(3.773595, 3.812515, 3.85144)",3.773595,3.851440,"(3.773595, 3.812515, 3.85144)",3.773595,3.851440,"(3.773595, 3.812515, 3.85144)",287.0916,287.0916,287.0916,983.7825,983.7831,983.7825,983.7831,"(983.7825, 983.7828, 983.7831)",0.0,14.407540,"(0.0, 7.20377, 14.40754)",59.83496,59.83381,0.301135,0.305766,"(0.3011346, 0.3034503, 0.3057659)",59.83496,59.83380,"(59.83496, 59.83438, 59.8338)",0.864135,0.864135,0.864134,0.0,0.0,544.12,543.29,"(544.12, 543.705, 543.29)",48.533695,2,Längsschnitt in mlc
4,5204837016964086891,Rohr R-K4513S R-K4523S,4816511167455310973,4779752876656844188,5204829332281547346,13.515840,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5134010500800575790,OSM: Knoten 4105649561 -> Knoten 299394921; Lä...,408665320,0,2,0.005,0,350,345.6,Rücklauf,,5204837016964086891,5204837016964086891,False,713616.238695,5.578280e+06,False,5204837016964086891,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.239 5578279.586, 713618.884...",4875054825941361274,5191457421068378074,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004345,27.36961,0.369923,0.0,0.0,0.154884,79.74766,79.74766,"(79.74766, 79.74766, 79.74766)",0.19772,0.002093,3.72938,3.729380,3.773595,"(3.72938, 3.751485, 3.773595)",3.729380,3.773595,"(3.72938, 3.751485, 3.773595)",3.729380,3.773595,"(3.72938, 3.751485, 3.773595)",287.0916,287.0916,287.0916,983.782,983.7825,983.7820,983.7825,"(983.782, 983.7822, 983.7825)",0.0,13.515840,"(0.0, 6.75792, 13.51584)",59.83606,59.83496,0.296790,0.301135,"(0.2967899, 0.2989622, 0.3011346)",59.83606,59.83496,"(59.83606, 59.83551, 59.83496)",0.864135,0.864135,0.864135,0.0,0.0,544.60,544.12,"(544.6, 544.36, 544.12)",62.049538,2,Längsschnitt in mlc

## Edge dataframe

Can be used to create user-defined graphs.

[generate_edge_dataframe()](https://3sconsult.github.io/sir3stoolkit/references/sir3stoolkit.mantle.html#sir3stoolkit.mantle.dataframes.SIR3S_Model_Dataframes.generate_edge_dataframe)

In [16]:
(s3s.generate_edge_dataframe()).head(5)

[2026-03-27 18:26:03,537] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-03-27 18:26:03,540] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-03-27 18:26:03,542] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-03-27 18:26:03,543] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-03-27 18:26:03,675] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-03-27 18:26:03,708] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-03-27 18:26:03,708] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (524, 6)
[2026-03-27 18:26:03,714] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Valve
[2026-03-27 18:26:03,714] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 12 element(s) of element type ObjectTypes.Valve.
[2026-03-27 18:26:03,718] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-03-27 18:26:03,718] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-03-27 18:26:03,891] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-03-27 18:26:03,908] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-03-27 18:26:03,908] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (12, 6)
[2026-03-27 18:26:03,915] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.FlapValve
[2026-03-27 18:26:03,917] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 3 element(s) of element type ObjectTypes.FlapValve.
[2026-03-27 18:26:03,918] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-03-27 18:26:03,918] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-03-27 18:26:03,933] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-03-27 18:26:03,944] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-03-27 18:26:03,944] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (3, 6)
[2026-03-27 18:26:03,951] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pump
[2026-03-27 18:26:03,952] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 2 element(s) of element type ObjectTypes.Pump.
[2026-03-27 18:26:03,953] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-03-27 18:26:03,955] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-03-27 18:26:04,067] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-03-27 18:26:04,079] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-03-27 18:26:04,083] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (2, 6)
[2026-03-27 18:26:04,083] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.DistrictHeatingConsumer
[2026-03-27 18:26:04,083] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 337 element(s) of element type ObjectTypes.DistrictHeatingConsumer.
[2026-03-27 18:26:04,089] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-03-27 18:26:04,089] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-03-27 18:26:04,158] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-03-27 18:26:04,184] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-03-27 18:26:04,184] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (337, 6)
[2026-03-27 18:26:04,186] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.DistrictHeatingFeeder
[2026-03-27 18:26:04,186] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 1 element(s) of element type ObjectTypes.DistrictHeatingFeeder.
[2026-03-27 18:26:04,189] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-03-27 18:26:04,191] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-03-27 18:26:04,206] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-03-27 18:26:04,219] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-03-27 18:26:04,222] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (1, 6)
[2026-03-27 18:26:04,223] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.HeatExchanger
[2026-03-27 18:26:04,225] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 1 element(s) of element type ObjectTypes.HeatExchanger.
[2026-03-27 18:26:04,225] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-03-27 18:26:04,229] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-03-27 18:26:04,261] INFO in sir3stoolkit.mantle.dataframes: [model_data] 4 non-empty end node columns were created.
[2026-03-27 18:26:04,274] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-03-27 18:26:04,274] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (1, 8)
[2026-03-27 18:26:04,285] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Retrieved 880 edges from 17 element types.

,tk,Fkcont,geometry,fkKI,fkKK,element type,fkKI2,fkKK2
0,5442010239090746007,5029128874972463118,"LINESTRING (713620.268 5578828.419, 713602.295...",5669301360686511351,5397948523091900401,Pipe,NaN,NaN
1,4917786378639043296,5029128874972463118,"LINESTRING (713602.295 5578860.106, 713574.062...",5397948523091900401,5239335112004772156,Pipe,NaN,NaN
2,4762482310382009633,5029128874972463118,"LINESTRING (713574.062 5578909.873, 713553.84 ...",5239335112004772156,5298886695042021307,Pipe,NaN,NaN
3,4987229536643024523,5029128874972463118,"LINESTRING (713553.84 5578945.533, 713553.394 ...",5298886695042021307,4993257270457791438,Pipe,NaN,NaN
4,5722206630503885118,5029128874972463118,"LINESTRING (713553.394 5578952.352, 713556.294...",4993257270457791438,5317865645994989592,Pipe,NaN,NaN