# Tutorial 53: Creation of Longitudinal Section - and Edge Dataframe

This Example demonstrates the capabilities of the class Dataframes_SIR3S_Model that extends SIR3S_Model be abilities to work directley with pandas dataframes. It is shown how to create dataframes containing information that does not concern individual elements types such as Nodes, Pipes, etc. but instead concerning more abstract SIR 3S data such as longitudinal sections or concatenations of multiple element types like hydraulic edges.

# Toolkit Release

In [27]:
#pip install

# Imports

## SIR 3S Toolkit

### Regular Import/Init

In [28]:
SIR3S_SIRGRAF_DIR = r"C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2" #change to local path

In [29]:
from sir3stoolkit.core import wrapper

In [30]:
wrapper

In [31]:
wrapper.Initialize_Toolkit(SIR3S_SIRGRAF_DIR)

[2026-05-25 14:18:21,782] INFO in sir3stoolkit.core.wrapper: [Initialization] Using provided SirGraf path: C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2
[2026-05-25 14:18:21,785] INFO in sir3stoolkit.core.wrapper: [Initialization] Initializing toolkit with SirGraf path: C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2

### Additional Import/Init for Dataframes class

In [32]:
from sir3stoolkit.mantle.dataframes import SIR3S_Model_Dataframes

In [33]:
s3s = SIR3S_Model_Dataframes()

[2026-05-25 14:18:22,052] INFO in sir3stoolkit.core.wrapper: [Model Class Initialization] Initialization complete

## Additional

In [34]:
import pandas as pd
from shapely.geometry import Point
import re
import folium
from folium.plugins import HeatMap
import numpy as np
import geopandas as gpd
from shapely import wkt
import matplotlib.pyplot as plt
import contextily as cx

# Open Model

In [35]:
s3s.OpenModel(dbName=r"Toolkit_Tutorial53_Model.db3",
              providerType=s3s.ProviderTypes.SQLite,
              Mid="M-1-0-1",
              saveCurrentlyOpenModel=False,
              namedInstance="",
              userID="",
              password="")

[2026-05-25 14:18:48,025] INFO in sir3stoolkit.core.wrapper: Model is open for further operation

# Generate Non-Element Dataframes

## Edge dataframe

We can use the function [generate_edge_dataframe()](https://3sconsult.github.io/sir3stoolkit/references/sir3stoolkit.mantle.html#sir3stoolkit.mantle.dataframes.SIR3S_Model_Dataframes.generate_edge_dataframe) to obtain a dataframe containing all edge objects in the model. Below is a list of all element types, whose representatives that will be included in the dataframe, if present in the model.

In [36]:
edge_types = [
    'Pipe', 'Valve', 'SafetyValve', 'PressureRegulator', 'DifferentialRegulator',
    'FlapValve', 'PhaseSeparation', 'FlowControlUnit', 'ControlValve', 'Pump',
    'DistrictHeatingConsumer', 'DistrictHeatingFeeder', 'Compressor', 'HeaterCooler', 'HeatFeederConsumerStation'
]

HeatExchanger is not supported.

### Parametrization 1: Default

If we don't request any properties, we will only get [tk, Fkcont, geometry, fkKI, fkKK, element_type, L] as df columns.

In [37]:
(s3s.generate_edge_dataframe()).head(5)

[2026-05-25 14:18:48,582] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Pipe ...
[2026-05-25 14:18:48,608] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:18:48,615] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:18:48,623] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:18:48,628] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:18:49,226] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:18:49,340] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:18:49,340] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (524, 6)
[2026-05-25 14:18:49,340] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:18:49,601] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-05-25 14:18:49,602] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:18:49,611] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:18:49,661] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:18:49,668] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:18:49,672] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:18:49,703] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Pipe.
[2026-05-25 14:18:49,706] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Valve ...
[2026-05-25 14:18:49,712] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Valve
[2026-05-25 14:18:49,712] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 12 element(s) of element type ObjectTypes.Valve.
[2026-05-25 14:18:49,721] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:18:49,721] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:18:49,739] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:18:49,790] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:18:49,790] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (12, 6)
[2026-05-25 14:18:49,795] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Valve
[2026-05-25 14:18:50,102] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-05-25 14:18:50,106] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 12 element(s) of element type ObjectTypes.Valve.
[2026-05-25 14:18:50,111] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:18:50,162] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:18:50,167] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:18:50,173] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:18:50,204] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Valve.
[2026-05-25 14:18:50,211] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.FlapValve ...
[2026-05-25 14:18:50,216] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.FlapValve
[2026-05-25 14:18:50,220] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 3 element(s) of element type ObjectTypes.FlapValve.
[2026-05-25 14:18:50,226] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:18:50,229] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:18:50,245] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:18:50,302] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:18:50,305] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (3, 6)
[2026-05-25 14:18:50,311] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.FlapValve
[2026-05-25 14:18:50,570] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-05-25 14:18:50,570] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 3 element(s) of element type ObjectTypes.FlapValve.
[2026-05-25 14:18:50,585] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:18:50,609] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:18:50,609] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:18:50,620] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:18:50,643] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.FlapValve.
[2026-05-25 14:18:50,660] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Pump ...
[2026-05-25 14:18:50,666] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pump
[2026-05-25 14:18:50,668] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 2 element(s) of element type ObjectTypes.Pump.
[2026-05-25 14:18:50,670] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:18:50,675] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:18:50,770] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:18:50,814] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:18:50,814] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (2, 6)
[2026-05-25 14:18:50,820] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pump
[2026-05-25 14:18:51,036] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-05-25 14:18:51,038] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 2 element(s) of element type ObjectTypes.Pump.
[2026-05-25 14:18:51,048] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:18:51,175] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:18:51,177] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:18:51,186] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:18:51,211] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Pump.
[2026-05-25 14:18:51,215] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.DistrictHeatingConsumer ...
[2026-05-25 14:18:51,220] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.DistrictHeatingConsumer
[2026-05-25 14:18:51,223] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 337 element(s) of element type ObjectTypes.DistrictHeatingConsumer.
[2026-05-25 14:18:51,228] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:18:51,230] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:18:51,336] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:18:51,412] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:18:51,420] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (337, 6)
[2026-05-25 14:18:51,420] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.DistrictHeatingConsumer
[2026-05-25 14:18:51,612] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-05-25 14:18:51,615] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 337 element(s) of element type ObjectTypes.DistrictHeatingConsumer.
[2026-05-25 14:18:51,620] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:18:51,659] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:18:51,662] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:18:51,665] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:18:51,686] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.DistrictHeatingConsumer.
[2026-05-25 14:18:51,686] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.DistrictHeatingFeeder ...
[2026-05-25 14:18:51,695] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.DistrictHeatingFeeder
[2026-05-25 14:18:51,695] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 1 element(s) of element type ObjectTypes.DistrictHeatingFeeder.
[2026-05-25 14:18:51,704] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:18:51,704] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:18:51,714] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:18:51,753] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:18:51,756] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (1, 6)
[2026-05-25 14:18:51,756] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.DistrictHeatingFeeder
[2026-05-25 14:18:51,958] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-05-25 14:18:51,963] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 1 element(s) of element type ObjectTypes.DistrictHeatingFeeder.
[2026-05-25 14:18:51,970] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:18:52,037] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:18:52,043] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:18:52,051] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:18:52,082] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.DistrictHeatingFeeder.
[2026-05-25 14:18:52,103] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Retrieved 879 edges from 6 element types.

,Fkcont,L,element type,fkKI,fkKK,geometry,tk
0,5029128874972463118,0,Pipe,4730066059089961857,4917189080965035120,"LINESTRING (714262.483 5578857.42, 714269.543 ...",4614463970292122863
1,5029128874972463118,0,Pipe,5129584372458662150,5332825919690090061,"LINESTRING (713738.297 5579219.902, 713793.23 ...",4615723899944629797
2,5029128874972463118,0,Pipe,5070795580168283912,5725848577942138606,"LINESTRING (713650.613 5578990.488, 713649.498...",4621030304810285220
3,5029128874972463118,0,Pipe,5106194195554624313,5416743601805578486,"LINESTRING (713283.932 5578718.123, 713299.538...",4621904482639719098
4,5029128874972463118,0,Pipe,5395214589547810761,5186627743244018598,"LINESTRING (713231.461 5579074.621, 713266.467...",4623301797443553869

### Parametrization 2: Properties

We can request additional properties. Here we can mix model data and result properties in the same param.

If a property is not defined for all edge element types, a column for that property will be created, but only populated, where values exists.

In [38]:
(s3s.generate_edge_dataframe(properties=["Hal", "Kvr", "JV", "PVEC", "MVEC"])).head(5) # use last simulation timestamp

[2026-05-25 14:18:52,611] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Pipe ...
[2026-05-25 14:18:52,616] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:18:52,622] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:18:52,627] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 3 model_data properties.
[2026-05-25 14:18:52,630] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Hal', 'Kvr', 'Fkcont'], geometry, end nodes...
[2026-05-25 14:18:53,318] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:18:53,419] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:18:53,422] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (524, 8)
[2026-05-25 14:18:53,425] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:18:53,585] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-05-25 14:18:53,590] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:18:53,593] INFO in sir3stoolkit.mantle.dataframes: [results] Using 3 result properties.
[2026-05-25 14:18:53,640] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:18:54,411] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:18:55,018] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1572)
[2026-05-25 14:18:55,085] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Pipe.
[2026-05-25 14:18:55,094] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Valve ...
[2026-05-25 14:18:55,099] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Valve
[2026-05-25 14:18:55,101] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 12 element(s) of element type ObjectTypes.Valve.
[2026-05-25 14:18:55,106] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:18:55,110] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:18:55,128] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:18:55,166] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:18:55,168] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (12, 6)
[2026-05-25 14:18:55,168] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Valve
[2026-05-25 14:18:55,340] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-05-25 14:18:55,340] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 12 element(s) of element type ObjectTypes.Valve.
[2026-05-25 14:18:55,351] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:18:55,386] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:18:55,390] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:18:55,396] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:18:55,411] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Valve.
[2026-05-25 14:18:55,417] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.FlapValve ...
[2026-05-25 14:18:55,421] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.FlapValve
[2026-05-25 14:18:55,424] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 3 element(s) of element type ObjectTypes.FlapValve.
[2026-05-25 14:18:55,427] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:18:55,427] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:18:55,439] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:18:55,468] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:18:55,471] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (3, 6)
[2026-05-25 14:18:55,473] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.FlapValve
[2026-05-25 14:18:55,654] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-05-25 14:18:55,654] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 3 element(s) of element type ObjectTypes.FlapValve.
[2026-05-25 14:18:55,664] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:18:55,690] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:18:55,695] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:18:55,701] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:18:55,725] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.FlapValve.
[2026-05-25 14:18:55,742] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Pump ...
[2026-05-25 14:18:55,746] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pump
[2026-05-25 14:18:55,752] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 2 element(s) of element type ObjectTypes.Pump.
[2026-05-25 14:18:55,757] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:18:55,761] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:18:55,885] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:18:55,933] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:18:55,939] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (2, 6)
[2026-05-25 14:18:55,943] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pump
[2026-05-25 14:18:56,174] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-05-25 14:18:56,174] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 2 element(s) of element type ObjectTypes.Pump.
[2026-05-25 14:18:56,183] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:18:56,298] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:18:56,301] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:18:56,310] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:18:56,331] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Pump.
[2026-05-25 14:18:56,336] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.DistrictHeatingConsumer ...
[2026-05-25 14:18:56,341] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.DistrictHeatingConsumer
[2026-05-25 14:18:56,341] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 337 element(s) of element type ObjectTypes.DistrictHeatingConsumer.
[2026-05-25 14:18:56,351] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:18:56,351] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:18:56,485] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:18:56,552] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:18:56,553] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (337, 6)
[2026-05-25 14:18:56,559] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.DistrictHeatingConsumer
[2026-05-25 14:18:56,785] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-05-25 14:18:56,791] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 337 element(s) of element type ObjectTypes.DistrictHeatingConsumer.
[2026-05-25 14:18:56,794] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:18:56,826] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:18:56,838] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:18:56,841] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:18:56,869] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.DistrictHeatingConsumer.
[2026-05-25 14:18:56,872] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.DistrictHeatingFeeder ...
[2026-05-25 14:18:56,877] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.DistrictHeatingFeeder
[2026-05-25 14:18:56,880] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 1 element(s) of element type ObjectTypes.DistrictHeatingFeeder.
[2026-05-25 14:18:56,885] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:18:56,888] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:18:56,901] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:18:56,942] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:18:56,942] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (1, 6)
[2026-05-25 14:18:56,952] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.DistrictHeatingFeeder
[2026-05-25 14:18:57,175] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-05-25 14:18:57,175] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 1 element(s) of element type ObjectTypes.DistrictHeatingFeeder.
[2026-05-25 14:18:57,185] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:18:57,235] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:18:57,235] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:18:57,246] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:18:57,270] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.DistrictHeatingFeeder.
[2026-05-25 14:18:57,291] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Retrieved 879 edges from 6 element types.

,Fkcont,Hal,JV,Kvr,L,MVEC_end,MVEC_sequence,MVEC_start,PVEC_end,PVEC_sequence,PVEC_start,element type,fkKI,fkKK,geometry,tk
0,5029128874972463118,0.0,0.0,2.0,0,2.837623e-10,"(2.837623e-10, 2.837623e-10)",2.837623e-10,1.688630,"(1.615055, 1.68863)",1.615055,Pipe,4730066059089961857,4917189080965035120,"LINESTRING (714262.483 5578857.42, 714269.543 ...",4614463970292122863
1,5029128874972463118,0.0,0.0,1.0,0,-2.983143e-10,"(-2.983143e-10, -2.983143e-10, -2.983143e-10, ...",-2.983143e-10,3.590000,"(3.304535, 3.345315, 3.386095, 3.426875, 3.467...",3.304535,Pipe,5129584372458662150,5332825919690090061,"LINESTRING (713738.297 5579219.902, 713793.23 ...",4615723899944629797
2,5029128874972463118,0.0,0.211137,2.0,0,-4.251046e+00,"(-4.251046, -4.251046)",-4.251046e+00,2.198520,"(2.210225, 2.19852)",2.210225,Pipe,5070795580168283912,5725848577942138606,"LINESTRING (713650.613 5578990.488, 713649.498...",4621030304810285220
3,5029128874972463118,0.0,0.184983,1.0,0,-2.413726e+01,"(-24.13726, -24.13726, -24.13726, -24.13726)",-2.413726e+01,4.214520,"(4.1376, 4.16324, 4.18888, 4.21452)",4.137600,Pipe,5106194195554624313,5416743601805578486,"LINESTRING (713283.932 5578718.123, 713299.538...",4621904482639719098
4,5029128874972463118,0.0,0.0,2.0,0,1.737135e-10,"(1.737135e-10, 1.737135e-10, 1.737135e-10, 1.7...",1.737135e-10,2.328365,"(2.304045, 2.30891, 2.313775, 2.318635, 2.3235...",2.304045,Pipe,5395214589547810761,5186627743244018598,"LINESTRING (713231.461 5579074.621, 713266.467...",4623301797443553869

The resulting df now includes model data properties such as "Hal" or "Kvr", but also result properties such as "JV" or result vector properties along pipe interior points like "PVEC" or "MVEC", which are split into the columns PVEC_start, PVEC_end, and PVEC_sequence = (PVEC_start, PVEC_2, PVEC_3, ..., PVEC_end).

As we didn't specify a timestamp, the result values are obtained for the stationary timestamp (s3s.GetTimeStamps()[1]).

Note that typical int cols like "Kvr" are float here. This happens due to the merge of many dataframes, some with NaN values.

### Parametrization 3: Properties + Timestamps

In [39]:
simulation_timestamps = s3s.GetTimeStamps()[0]

In [40]:
simulation_timestamps

['2023-02-13 00:00:00.000 +01:00',
 '2023-02-13 01:00:00.000 +01:00',
 '2023-02-13 02:00:00.000 +01:00',
 '2023-02-13 03:00:00.000 +01:00',
 '2023-02-13 04:00:00.000 +01:00',
 '2023-02-13 05:00:00.000 +01:00',
 '2023-02-13 06:00:00.000 +01:00',
 '2023-02-13 07:00:00.000 +01:00',
 '2023-02-13 08:00:00.000 +01:00',
 '2023-02-13 09:00:00.000 +01:00',
 '2023-02-13 10:00:00.000 +01:00',
 '2023-02-13 11:00:00.000 +01:00',
 '2023-02-13 12:00:00.000 +01:00',
 '2023-02-13 13:00:00.000 +01:00',
 '2023-02-13 14:00:00.000 +01:00',
 '2023-02-13 15:00:00.000 +01:00',
 '2023-02-13 16:00:00.000 +01:00',
 '2023-02-13 17:00:00.000 +01:00',
 '2023-02-13 18:00:00.000 +01:00',
 '2023-02-13 19:00:00.000 +01:00',
 '2023-02-13 20:00:00.000 +01:00',
 '2023-02-13 21:00:00.000 +01:00',
 '2023-02-13 22:00:00.000 +01:00',
 '2023-02-13 23:00:00.000 +01:00',
 '2023-02-14 00:00:00.000 +01:00']

In [41]:
timestamp_idx = 8

In [42]:
timestamp_str = simulation_timestamps[timestamp_idx]

In [43]:
timestamp_str

'2023-02-13 08:00:00.000 +01:00'

In [44]:
(s3s.generate_edge_dataframe(properties=["Hal", "Kvr", "JV", "PVEC", "MVEC"]
                             ,timestamp=timestamp_idx)).head(5)

[2026-05-25 14:18:58,162] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Pipe ...
[2026-05-25 14:18:58,168] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:18:58,175] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:18:58,180] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 3 model_data properties.
[2026-05-25 14:18:58,182] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Hal', 'Kvr', 'Fkcont'], geometry, end nodes...
[2026-05-25 14:18:59,502] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:18:59,896] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:18:59,896] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (524, 8)
[2026-05-25 14:18:59,907] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:19:00,247] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 1 timestamps: ['2023-02-13 08:00:00.000 +01:00']
[2026-05-25 14:19:00,253] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:19:00,258] INFO in sir3stoolkit.mantle.dataframes: [results] Using 3 result properties.
[2026-05-25 14:19:00,301] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:19:01,637] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:19:02,537] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1572)
[2026-05-25 14:19:02,621] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Pipe.
[2026-05-25 14:19:02,629] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Valve ...
[2026-05-25 14:19:02,640] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Valve
[2026-05-25 14:19:02,643] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 12 element(s) of element type ObjectTypes.Valve.
[2026-05-25 14:19:02,651] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:19:02,655] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:19:02,687] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:19:02,760] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:19:02,765] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (12, 6)
[2026-05-25 14:19:02,769] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Valve
[2026-05-25 14:19:03,168] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 1 timestamps: ['2023-02-13 08:00:00.000 +01:00']
[2026-05-25 14:19:03,173] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 12 element(s) of element type ObjectTypes.Valve.
[2026-05-25 14:19:03,178] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:19:03,230] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:19:03,237] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:19:03,246] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:19:03,295] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Valve.
[2026-05-25 14:19:03,307] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.FlapValve ...
[2026-05-25 14:19:03,313] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.FlapValve
[2026-05-25 14:19:03,317] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 3 element(s) of element type ObjectTypes.FlapValve.
[2026-05-25 14:19:03,327] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:19:03,332] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:19:03,355] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:19:03,426] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:19:03,430] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (3, 6)
[2026-05-25 14:19:03,437] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.FlapValve
[2026-05-25 14:19:03,788] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 1 timestamps: ['2023-02-13 08:00:00.000 +01:00']
[2026-05-25 14:19:03,790] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 3 element(s) of element type ObjectTypes.FlapValve.
[2026-05-25 14:19:03,797] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:19:03,856] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:19:03,861] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:19:03,869] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:19:03,925] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.FlapValve.
[2026-05-25 14:19:03,930] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Pump ...
[2026-05-25 14:19:03,940] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pump
[2026-05-25 14:19:03,945] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 2 element(s) of element type ObjectTypes.Pump.
[2026-05-25 14:19:03,950] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:19:03,954] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:19:04,169] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:19:04,236] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:19:04,240] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (2, 6)
[2026-05-25 14:19:04,245] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pump
[2026-05-25 14:19:04,683] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 1 timestamps: ['2023-02-13 08:00:00.000 +01:00']
[2026-05-25 14:19:04,683] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 2 element(s) of element type ObjectTypes.Pump.
[2026-05-25 14:19:04,692] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:19:04,918] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:19:04,926] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:19:04,930] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:19:04,975] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Pump.
[2026-05-25 14:19:04,977] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.DistrictHeatingConsumer ...
[2026-05-25 14:19:04,989] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.DistrictHeatingConsumer
[2026-05-25 14:19:04,994] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 337 element(s) of element type ObjectTypes.DistrictHeatingConsumer.
[2026-05-25 14:19:05,005] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:19:05,007] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:19:05,248] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:19:05,351] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:19:05,363] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (337, 6)
[2026-05-25 14:19:05,368] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.DistrictHeatingConsumer
[2026-05-25 14:19:05,635] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 1 timestamps: ['2023-02-13 08:00:00.000 +01:00']
[2026-05-25 14:19:05,644] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 337 element(s) of element type ObjectTypes.DistrictHeatingConsumer.
[2026-05-25 14:19:05,649] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:19:05,708] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:19:05,717] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:19:05,722] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:19:05,752] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.DistrictHeatingConsumer.
[2026-05-25 14:19:05,754] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.DistrictHeatingFeeder ...
[2026-05-25 14:19:05,761] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.DistrictHeatingFeeder
[2026-05-25 14:19:05,761] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 1 element(s) of element type ObjectTypes.DistrictHeatingFeeder.
[2026-05-25 14:19:05,769] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:19:05,772] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:19:05,786] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:19:05,832] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:19:05,835] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (1, 6)
[2026-05-25 14:19:05,835] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.DistrictHeatingFeeder
[2026-05-25 14:19:06,109] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 1 timestamps: ['2023-02-13 08:00:00.000 +01:00']
[2026-05-25 14:19:06,112] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 1 element(s) of element type ObjectTypes.DistrictHeatingFeeder.
[2026-05-25 14:19:06,118] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:19:06,177] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:19:06,180] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:19:06,192] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:19:06,218] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.DistrictHeatingFeeder.
[2026-05-25 14:19:06,246] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Retrieved 879 edges from 6 element types.

,Fkcont,Hal,JV,Kvr,L,MVEC_end,MVEC_sequence,MVEC_start,PVEC_end,PVEC_sequence,PVEC_start,element type,fkKI,fkKK,geometry,tk
0,5029128874972463118,0.0,0.0,2.0,0,1.382432e-10,"(1.382432e-10, 1.382432e-10)",1.382432e-10,1.688630,"(1.615055, 1.68863)",1.615055,Pipe,4730066059089961857,4917189080965035120,"LINESTRING (714262.483 5578857.42, 714269.543 ...",4614463970292122863
1,5029128874972463118,0.0,0.0,1.0,0,-2.983143e-10,"(-2.983143e-10, -2.983143e-10, -2.983143e-10, ...",-2.983143e-10,3.847980,"(3.562515, 3.603295, 3.644075, 3.684855, 3.725...",3.562515,Pipe,5129584372458662150,5332825919690090061,"LINESTRING (713738.297 5579219.902, 713793.23 ...",4615723899944629797
2,5029128874972463118,0.0,0.667982,2.0,0,-7.826131e+00,"(-7.826131, -7.826131)",-7.826131e+00,2.805950,"(2.81585, 2.80595)",2.815850,Pipe,5070795580168283912,5725848577942138606,"LINESTRING (713650.613 5578990.488, 713649.498...",4621030304810285220
3,5029128874972463118,0.0,0.609716,1.0,0,-4.478037e+01,"(-44.78037, -44.78037, -44.78037, -44.78037)",-4.478037e+01,4.874130,"(4.788045, 4.81674, 4.845435, 4.87413)",4.788045,Pipe,5106194195554624313,5416743601805578486,"LINESTRING (713283.932 5578718.123, 713299.538...",4621904482639719098
4,5029128874972463118,0.0,0.0,2.0,0,-1.737135e-10,"(-1.737135e-10, -1.737135e-10, -1.737135e-10, ...",-1.737135e-10,2.712575,"(2.68805, 2.692955, 2.69786, 2.702765, 2.70767...",2.688050,Pipe,5395214589547810761,5186627743244018598,"LINESTRING (713231.461 5579074.621, 713266.467...",4623301797443553869

In [45]:
(s3s.generate_edge_dataframe(properties=["Hal", "Kvr", "JV", "PVEC", "MVEC"]
                             ,timestamp=timestamp_str)).head(5)

[2026-05-25 14:19:06,357] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Pipe ...
[2026-05-25 14:19:06,365] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:19:06,371] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:19:06,376] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 3 model_data properties.
[2026-05-25 14:19:06,378] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Hal', 'Kvr', 'Fkcont'], geometry, end nodes...
[2026-05-25 14:19:07,435] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:19:07,607] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:19:07,618] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (524, 8)
[2026-05-25 14:19:07,627] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:19:08,025] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 1 timestamps: ['2023-02-13 08:00:00.000 +01:00']
[2026-05-25 14:19:08,029] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:19:08,038] INFO in sir3stoolkit.mantle.dataframes: [results] Using 3 result properties.
[2026-05-25 14:19:08,075] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:19:09,150] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:19:10,072] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1572)
[2026-05-25 14:19:10,161] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Pipe.
[2026-05-25 14:19:10,170] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Valve ...
[2026-05-25 14:19:10,177] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Valve
[2026-05-25 14:19:10,181] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 12 element(s) of element type ObjectTypes.Valve.
[2026-05-25 14:19:10,189] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:19:10,191] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:19:10,235] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:19:10,333] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:19:10,335] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (12, 6)
[2026-05-25 14:19:10,341] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Valve
[2026-05-25 14:19:10,640] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 1 timestamps: ['2023-02-13 08:00:00.000 +01:00']
[2026-05-25 14:19:10,643] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 12 element(s) of element type ObjectTypes.Valve.
[2026-05-25 14:19:10,643] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:19:10,738] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:19:10,738] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:19:10,754] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:19:10,780] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Valve.
[2026-05-25 14:19:10,785] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.FlapValve ...
[2026-05-25 14:19:10,792] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.FlapValve
[2026-05-25 14:19:10,798] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 3 element(s) of element type ObjectTypes.FlapValve.
[2026-05-25 14:19:10,803] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:19:10,805] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:19:10,821] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:19:10,858] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:19:10,858] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (3, 6)
[2026-05-25 14:19:10,863] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.FlapValve
[2026-05-25 14:19:11,178] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 1 timestamps: ['2023-02-13 08:00:00.000 +01:00']
[2026-05-25 14:19:11,178] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 3 element(s) of element type ObjectTypes.FlapValve.
[2026-05-25 14:19:11,189] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:19:11,239] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:19:11,239] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:19:11,261] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:19:11,315] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.FlapValve.
[2026-05-25 14:19:11,324] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.Pump ...
[2026-05-25 14:19:11,332] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pump
[2026-05-25 14:19:11,338] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 2 element(s) of element type ObjectTypes.Pump.
[2026-05-25 14:19:11,347] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:19:11,351] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:19:11,508] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:19:11,561] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:19:11,566] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (2, 6)
[2026-05-25 14:19:11,570] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pump
[2026-05-25 14:19:11,879] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 1 timestamps: ['2023-02-13 08:00:00.000 +01:00']
[2026-05-25 14:19:11,884] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 2 element(s) of element type ObjectTypes.Pump.
[2026-05-25 14:19:11,890] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:19:12,106] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:19:12,113] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:19:12,122] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:19:12,154] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.Pump.
[2026-05-25 14:19:12,161] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.DistrictHeatingConsumer ...
[2026-05-25 14:19:12,168] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.DistrictHeatingConsumer
[2026-05-25 14:19:12,174] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 337 element(s) of element type ObjectTypes.DistrictHeatingConsumer.
[2026-05-25 14:19:12,180] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:19:12,182] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:19:12,422] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:19:12,516] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:19:12,519] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (337, 6)
[2026-05-25 14:19:12,522] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.DistrictHeatingConsumer
[2026-05-25 14:19:12,766] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 1 timestamps: ['2023-02-13 08:00:00.000 +01:00']
[2026-05-25 14:19:12,771] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 337 element(s) of element type ObjectTypes.DistrictHeatingConsumer.
[2026-05-25 14:19:12,776] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:19:12,827] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:19:12,836] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:19:12,841] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:19:12,870] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.DistrictHeatingConsumer.
[2026-05-25 14:19:12,874] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generating dataframe for ObjectTypes.DistrictHeatingFeeder ...
[2026-05-25 14:19:12,883] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.DistrictHeatingFeeder
[2026-05-25 14:19:12,888] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 1 element(s) of element type ObjectTypes.DistrictHeatingFeeder.
[2026-05-25 14:19:12,905] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-05-25 14:19:12,907] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Fkcont'], geometry, end nodes...
[2026-05-25 14:19:12,927] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:19:12,996] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:19:13,000] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (1, 6)
[2026-05-25 14:19:13,004] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.DistrictHeatingFeeder
[2026-05-25 14:19:14,291] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 1 timestamps: ['2023-02-13 08:00:00.000 +01:00']
[2026-05-25 14:19:14,306] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 1 element(s) of element type ObjectTypes.DistrictHeatingFeeder.
[2026-05-25 14:19:14,314] INFO in sir3stoolkit.mantle.dataframes: [results] Using 0 result properties.
[2026-05-25 14:19:14,425] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:19:14,444] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-05-25 14:19:14,455] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (0, 0)
[2026-05-25 14:19:14,547] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Generated dataframe for ObjectTypes.DistrictHeatingFeeder.
[2026-05-25 14:19:14,629] INFO in sir3stoolkit.mantle.dataframes: [edge dataframe] Retrieved 879 edges from 6 element types.

,Fkcont,Hal,JV,Kvr,L,MVEC_end,MVEC_sequence,MVEC_start,PVEC_end,PVEC_sequence,PVEC_start,element type,fkKI,fkKK,geometry,tk
0,5029128874972463118,0.0,0.0,2.0,0,1.382432e-10,"(1.382432e-10, 1.382432e-10)",1.382432e-10,1.688630,"(1.615055, 1.68863)",1.615055,Pipe,4730066059089961857,4917189080965035120,"LINESTRING (714262.483 5578857.42, 714269.543 ...",4614463970292122863
1,5029128874972463118,0.0,0.0,1.0,0,-2.983143e-10,"(-2.983143e-10, -2.983143e-10, -2.983143e-10, ...",-2.983143e-10,3.847980,"(3.562515, 3.603295, 3.644075, 3.684855, 3.725...",3.562515,Pipe,5129584372458662150,5332825919690090061,"LINESTRING (713738.297 5579219.902, 713793.23 ...",4615723899944629797
2,5029128874972463118,0.0,0.667982,2.0,0,-7.826131e+00,"(-7.826131, -7.826131)",-7.826131e+00,2.805950,"(2.81585, 2.80595)",2.815850,Pipe,5070795580168283912,5725848577942138606,"LINESTRING (713650.613 5578990.488, 713649.498...",4621030304810285220
3,5029128874972463118,0.0,0.609716,1.0,0,-4.478037e+01,"(-44.78037, -44.78037, -44.78037, -44.78037)",-4.478037e+01,4.874130,"(4.788045, 4.81674, 4.845435, 4.87413)",4.788045,Pipe,5106194195554624313,5416743601805578486,"LINESTRING (713283.932 5578718.123, 713299.538...",4621904482639719098
4,5029128874972463118,0.0,0.0,2.0,0,-1.737135e-10,"(-1.737135e-10, -1.737135e-10, -1.737135e-10, ...",-1.737135e-10,2.712575,"(2.68805, 2.692955, 2.69786, 2.702765, 2.70767...",2.688050,Pipe,5395214589547810761,5186627743244018598,"LINESTRING (713231.461 5579074.621, 713266.467...",4623301797443553869

The above two dataframes were requested for the same timestamp, therefore they are identical

In [46]:
df = s3s.generate_element_model_data_dataframe(s3s.ObjectTypes.Pipe)

[2026-05-25 14:19:14,887] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:19:14,899] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:19:14,908] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-05-25 14:19:14,911] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-05-25 14:19:14,919] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH']...
[2026-05-25 14:19:24,911] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (524, 47)

## AGSN (Longitudinal Sections)

We can use the method [generate_longitudinal_section_dataframes()](https://3sconsult.github.io/sir3stoolkit/references/sir3stoolkit.mantle.html#sir3stoolkit.mantle.dataframes.SIR3S_Model_Dataframes.generate_longitudinal_section_dataframes) to obtain a list indexed by (lfdnr-1) filled with size-2-tuples with 0 - Supply and 1 - Return..

In [47]:
dfs = s3s.generate_longitudinal_section_dataframes()

[2026-05-25 14:19:24,942] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.AGSN_HydraulicProfile
[2026-05-25 14:19:24,946] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 3 element(s) of element type ObjectTypes.AGSN_HydraulicProfile.
[2026-05-25 14:19:24,950] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.AGSN_HydraulicProfile.
[2026-05-25 14:19:24,953] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 9 model_data properties.
[2026-05-25 14:19:24,955] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'Lfdnr', 'Aktiv', 'AllNodesAndLinks', 'ObjsString', 'MainWay', 'Tk', 'Pk', 'InVariant']...
[2026-05-25 14:19:25,004] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (3, 10)
[2026-05-25 14:19:25,010] INFO in sir3stoolkit.mantle.dataframes: Retrieving Hydraulic Profile with Lfdnr: 1.
[2026-05-25 14:19:25,014] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-05-25 14:19:25,017] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-05-25 14:19:25,035] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:19:25,041] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:19:25,043] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-05-25 14:19:25,050] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-05-25 14:19:25,053] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-05-25 14:19:25,057] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH'], geometry, end nodes...
[2026-05-25 14:19:25,608] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:19:26,081] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:19:26,084] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (44, 67)
[2026-05-25 14:19:26,470] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.Pipe; at timestamp: 2023-02-13 00:00:00.000 +01:00 ...
[2026-05-25 14:19:26,472] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:19:26,729] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-05-25 14:19:26,733] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:19:26,735] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-05-25 14:19:26,741] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-05-25 14:19:26,838] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:19:28,518] INFO in sir3stoolkit.mantle.dataframes: [results] 2244 fully NaN columns dropped.
[2026-05-25 14:19:28,983] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1364)
[2026-05-25 14:19:28,987] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.Pipe ...
[2026-05-25 14:19:29,083] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-05-25 14:19:29,085] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-05-25 14:19:29,105] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:19:29,110] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:19:29,114] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-05-25 14:19:29,118] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-05-25 14:19:29,119] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-05-25 14:19:29,120] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH'], geometry, end nodes...
[2026-05-25 14:19:29,431] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:19:29,756] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:19:29,756] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (44, 67)
[2026-05-25 14:19:29,935] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.Pipe; at timestamp: 2023-02-13 00:00:00.000 +01:00 ...
[2026-05-25 14:19:29,935] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:19:30,132] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-05-25 14:19:30,136] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:19:30,140] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-05-25 14:19:30,144] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-05-25 14:19:30,202] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:19:31,379] INFO in sir3stoolkit.mantle.dataframes: [results] 2244 fully NaN columns dropped.
[2026-05-25 14:19:31,688] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1364)
[2026-05-25 14:19:31,688] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.Pipe ...
[2026-05-25 14:19:31,763] INFO in sir3stoolkit.mantle.dataframes: Retrieving Hydraulic Profile with Lfdnr: 2.
[2026-05-25 14:19:31,764] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-05-25 14:19:31,767] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-05-25 14:19:31,772] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:19:31,780] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:19:31,784] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-05-25 14:19:31,788] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-05-25 14:19:31,790] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-05-25 14:19:31,792] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH'], geometry, end nodes...
[2026-05-25 14:19:32,056] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:19:32,415] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:19:32,417] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (44, 67)
[2026-05-25 14:19:32,592] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.Pipe; at timestamp: 2023-02-13 00:00:00.000 +01:00 ...
[2026-05-25 14:19:32,597] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:19:32,742] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-05-25 14:19:32,745] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:19:32,746] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-05-25 14:19:32,751] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-05-25 14:19:32,801] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:19:33,747] INFO in sir3stoolkit.mantle.dataframes: [results] 2244 fully NaN columns dropped.
[2026-05-25 14:19:34,068] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1364)
[2026-05-25 14:19:34,068] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.Pipe ...
[2026-05-25 14:19:34,135] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-05-25 14:19:34,135] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-05-25 14:19:34,151] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:19:34,156] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:19:34,159] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-05-25 14:19:34,163] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-05-25 14:19:34,164] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-05-25 14:19:34,166] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH'], geometry, end nodes...
[2026-05-25 14:19:34,470] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:19:34,787] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:19:34,787] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (44, 67)
[2026-05-25 14:19:34,920] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.Pipe; at timestamp: 2023-02-13 00:00:00.000 +01:00 ...
[2026-05-25 14:19:34,920] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:19:35,038] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-05-25 14:19:35,046] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:19:35,049] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-05-25 14:19:35,052] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-05-25 14:19:35,152] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:19:36,589] INFO in sir3stoolkit.mantle.dataframes: [results] 2244 fully NaN columns dropped.
[2026-05-25 14:19:36,903] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1364)
[2026-05-25 14:19:36,903] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.Pipe ...
[2026-05-25 14:19:36,975] INFO in sir3stoolkit.mantle.dataframes: Retrieving Hydraulic Profile with Lfdnr: 3.
[2026-05-25 14:19:36,977] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-05-25 14:19:36,979] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-05-25 14:19:36,989] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:19:36,993] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:19:36,995] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-05-25 14:19:36,999] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-05-25 14:19:37,001] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.
[2026-05-25 14:19:37,004] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'FkdtroRowd', 'Fkltgr', 'Fkstrasse', 'L', 'Lzu', 'Rau', 'Jlambs', 'Lambda0', 'Zein', 'Zaus', 'Zuml', 'Asoll', 'Indschall', 'Baujahr', 'Hal', 'Fkcont', 'Fk2lrohr', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'LineWidthMM', 'DottedLine', 'DN', 'Di', 'KvrKlartext', 'HasClosedNSCHs', 'Tk', 'Pk', 'InVariant', 'Xkor', 'Ykor', 'GeometriesDiffer', 'bz.Fk', 'bz.Qsvb', 'bz.Irtrenn', 'bz.Leckstatus', 'bz.Leckstart', 'bz.Leckend', 'bz.Leckort', 'bz.Leckmenge', 'bz.Imptnz', 'bz.Zvlimptnz', 'bz.Kantenzv', 'bz.ITrennWithNSCH'], geometry, end nodes...
[2026-05-25 14:19:37,259] INFO in sir3stoolkit.mantle.dataframes: [model_data] 2 non-empty end node columns were created.
[2026-05-25 14:19:37,771] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-05-25 14:19:37,773] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (44, 67)
[2026-05-25 14:19:37,941] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_results for element type: ObjectTypes.Pipe; at timestamp: 2023-02-13 00:00:00.000 +01:00 ...
[2026-05-25 14:19:37,941] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:19:38,089] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-05-25 14:19:38,096] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:19:38,099] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-05-25 14:19:38,104] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-05-25 14:19:38,154] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-05-25 14:19:39,324] INFO in sir3stoolkit.mantle.dataframes: [results] 2244 fully NaN columns dropped.
[2026-05-25 14:19:39,763] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 1364)
[2026-05-25 14:19:39,765] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Merging df_model_data with df_results for element type: ObjectTypes.Pipe ...
[2026-05-25 14:19:39,861] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df for element type: ObjectTypes.Pipe ...
[2026-05-25 14:19:39,863] INFO in sir3stoolkit.mantle.dataframes: [generate_element_dataframe] Generating df_model_data for element type: ObjectTypes.Pipe ...
[2026-05-25 14:19:39,873] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-05-25 14:19:39,880] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-05-25 14:19:39,884] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 44 tks remain after filtering for given tks.
[2026-05-25 14:19:39,889] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Pipe.
[2026-05-25 14:19:39,890] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 46 model_data properties.

In [48]:
dfs[0][0].head() # Lfdnr 1, Vl

,tk,Name,FkdtroRowd,Fkltgr,Fkstrasse,L,Lzu,Rau,Jlambs,Lambda0,Zein,Zaus,Zuml,Asoll,Indschall,Baujahr,Hal,Fkcont,Fk2lrohr,Beschreibung,Idreferenz,Iplanung,Kvr,LineWidthMM,DottedLine,DN,Di,KvrKlartext,HasClosedNSCHs,Tk,Pk,InVariant,Xkor,Ykor,GeometriesDiffer,bz.Fk,bz.Qsvb,bz.Irtrenn,bz.Leckstatus,bz.Leckstart,bz.Leckend,bz.Leckort,bz.Leckmenge,bz.Imptnz,bz.Zvlimptnz,bz.Kantenzv,bz.ITrennWithNSCH,geometry,fkKI,fkKK,PipeTable: Table Name,PipeTable: Name,PipeTable: Fk,PipeTable: Dn,PipeTable: Di,PipeTable: Da,PipeTable: S,PipeTable: Wsteig,PipeTable: Wtiefe,PipeTable: Kt,PipeTable: Pn,PipeTable: Ausfallzeit,PipeTable: Reparatur,PipeTable: Rehabilitation,PipeTable: Tk,PipeTable: Pk,PipeTable: InVariant,A,DTTR,DWVERL,DWVERLABS,IAKTIV,IRTRENN,JV,MVEC_start,MVEC_end,MVEC_sequence,PDAMPF,PHR,PMIN,PVEC_start,PVEC_end,PVEC_sequence,PVECMAX_INST_start,PVECMAX_INST_end,PVECMAX_INST_sequence,PVECMIN_INST_start,PVECMIN_INST_end,PVECMIN_INST_sequence,QMAV,QMI,QMK,RHOI,RHOK,RHOVEC_start,RHOVEC_end,RHOVEC_sequence,SVEC_start,SVEC_end,SVEC_sequence,TI,TK,TTRVEC_start,TTRVEC_end,TTRVEC_sequence,TVEC_start,TVEC_end,TVEC_sequence,VAV,VI,VK,VOLDA,WVL,ZVEC_start,ZVEC_end,ZVEC_sequence,l_sum,AGSN_Lfdnr,AGSN_Name
0,5691533564979419761,Rohr V-E0 V-K1683S,4816511167455310973,4779752876656844188,5204829332281547346,15.351700,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5025945677694931826,OSM: Knoten 476971238 -> Knoten 299394923; Län...,39785520,0,1,0.005,0,350,345.6,Vorlauf,,5691533564979419761,5691533564979419761,False,713619.921383,5.578219e+06,False,5691533564979419761,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713619.921 5578218.954, 713614.649...",5398100694284104779,4825391580467484032,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004844,43.12018,0.661968,0.0,0.0,0.152727,79.74764,79.74764,"(79.74764, 79.74764, 79.74764)",0.701074,0.002345,5.800529,5.878635,5.800530,"(5.878635, 5.83958, 5.80053)",5.878635,5.800530,"(5.878635, 5.83958, 5.80053)",5.878635,5.800530,"(5.878635, 5.83958, 5.80053)",287.0915,287.0915,287.0915,965.7,965.7012,965.7000,965.7012,"(965.7, 965.7006, 965.7012)",0.0,15.351700,"(0.0, 7.67585, 15.3517)",89.99999,89.99802,0.000000,0.004844,"(0.0, 0.002422066, 0.004844132)",90.00000,89.99802,"(90.0, 89.99902, 89.99802)",0.880315,0.880315,0.880314,0.0,10082.88,541.49,542.29,"(541.49, 541.89, 542.29)",15.351701,1,Längsschnitt
1,5048873293262650113,Rohr V-K1683S V-K1693S,4816511167455310973,4779752876656844188,5204829332281547346,12.508950,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5216742060270992761,OSM: Knoten 299394923 -> Knoten 4105649557; Lä...,39785520,0,1,0.005,0,350,345.6,Vorlauf,,5048873293262650113,5048873293262650113,False,713614.648712,5.578233e+06,False,5048873293262650113,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713614.649 5578233.372, 713614.465...",4825391580467484032,5180617780362861593,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.003947,43.58081,0.54515,0.0,0.0,0.152727,79.74764,79.74764,"(79.74764, 79.74764, 79.74764)",0.701027,0.00191,5.732326,5.800530,5.732325,"(5.80053, 5.76643, 5.732325)",5.800530,5.732325,"(5.80053, 5.76643, 5.732325)",5.800530,5.732325,"(5.80053, 5.76643, 5.732325)",287.0915,287.0915,287.0915,965.7012,965.7021,965.7012,965.7021,"(965.7012, 965.7017, 965.7021)",0.0,12.508950,"(0.0, 6.254475, 12.50895)",89.99802,89.9964,0.004844,0.008791,"(0.004844132, 0.006817694, 0.008791257)",89.99802,89.99640,"(89.99802, 89.99722, 89.9964)",0.880314,0.880314,0.880313,0.0,10081.81,542.29,542.99,"(542.29, 542.64, 542.99)",27.860648,1,Längsschnitt
2,5715081934973525403,Rohr V-K2163S V-K1693S,4816511167455310973,4779752876656844188,5204829332281547346,6.265505,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,4919359344392474301,OSM: Knoten 299394922 -> Knoten 4105649557; Lä...,595926249,0,1,0.005,0,350,345.6,Vorlauf,,5715081934973525403,5715081934973525403,False,713614.369043,5.578252e+06,False,5715081934973525403,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713614.369 5578252.145, 713614.465...",4964920487041183545,5180617780362861593,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.001977,43.50409,0.272575,0.0,0.0,0.152727,-79.74764,-79.74764,"(-79.74764, -79.74764)",0.700995,0.000957,5.699167,5.699165,5.732325,"(5.699165, 5.732325)",5.699165,5.732325,"(5.699165, 5.732325)",5.699165,5.732325,"(5.699165, 5.732325)",-287.0915,-287.0915,-287.0915,965.7026,965.7021,965.7026,965.7021,"(965.7026, 965.7021)",0.0,6.265505,"(0.0, 6.265505)",89.9956,89.9964,0.010768,0.008791,"(0.0107683, 0.008791257)",89.99561,89.99640,"(89.99561, 89.9964)",-0.880313,-0.880313,-0.880313,0.0,-10080.93,543.33,542.99,"(543.33, 542.99)",34.126153,1,Längsschnitt
3,5413647981880727734,Rohr V-K2043S V-K2163S,4816511167455310973,4779752876656844188,5204829332281547346,14.407540,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5299861566239260044,OSM: Knoten 299394921 -> Knoten 299394922; Län...,595926249,0,1,0.005,0,350,345.6,Vorlauf,,5413647981880727734,5413647981880727734,False,713616.883649,5.578266e+06,False,5413647981880727734,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.884 5578266.331, 713614.369...",4794016231137548967,4964920487041183545,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004546,43.24324,0.623029,0.0,0.0,0.152727,-79.74764,-79.74764,"(-79.74764, -79.74764, -79.74764)",0.70096,0.0022,5.630673,5.630675,5.699165,"(5.630675, 5.66492, 5.699165)",5.630675,5.699165,"(5.630675, 5.66492, 5.699165)",5.630675,5.699165,"(5.630675, 5.66492, 5.699165)",-287.0915,-287.0915,-287.0915,965.7037,965.7026,965.7037,965.7026,"(965.7037, 965.7032, 965.7026)",0.0,14.407540,"(0.0, 7.20377, 14.40754)",89.99374,89.9956,0.015315,0.010768,"(0.01531452, 0.01304141, 0.0107683)",89.99374,89.99561,"(89.99374, 89.99466, 89.99561)",-0.880312,-0.880312,-0.880313,0.0,-10080.49,544.03,543.33,"(544.03, 543.6801, 543.33)",48.533695,1,Längsschnitt
4,5134010500800575790,Rohr V-K2033S V-K2043S,4816511167455310973,4779752876656844188,5204829332281547346,13.515840,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5204837016964086891,OSM: Knoten 4105649561 -> Knoten 299394921; Lä...,408665320,0,1,0.005,0,350,345.6,Vorlauf,,5134010500800575790,5134010500800575790,False,713614.238695,5.578280e+06,False,5134010500800575790,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713614.239 5578279.586, 713616.884...",5473123125979010325,4794016231137548967,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004265,42.49493,0.574355,0.0,0.0,0.152727,-79.74764,-79.74764,"(-79.74764, -79.74764, -79.74764)",0.700913,0.002064,5.580316,5.580315,5.630675,"(5.580315, 5.605495, 5.630675)",5.580315,5.630675,"(5.580315, 5.605495, 5.630675)",5.580315,5.630675,"(5.580315, 5.605495, 5.630675)",-287.0915,-287.0915,-287.0915,965.7048,965.7037,965.7048,965.7037,"(965.7048, 965.7043, 965.7037)",0.0,13.515840,"(0.0, 6.75792, 13.51584)",89.992,89.99374,0.019579,0.015315,"(0.01957938, 0.01744695, 0.01531453)",89.99200,89.99374,"(89.992, 89.99286, 89.99374)",-0.880311,-0.880311,-0.880312,0.0,-10079.48,544.54,544.03,"(544.54, 544.285, 544.03)",62.049538,1,Längsschnitt

In [49]:
dfs[0][1].head() # Lfdnr 1 RL

,tk,Name,FkdtroRowd,Fkltgr,Fkstrasse,L,Lzu,Rau,Jlambs,Lambda0,Zein,Zaus,Zuml,Asoll,Indschall,Baujahr,Hal,Fkcont,Fk2lrohr,Beschreibung,Idreferenz,Iplanung,Kvr,LineWidthMM,DottedLine,DN,Di,KvrKlartext,HasClosedNSCHs,Tk,Pk,InVariant,Xkor,Ykor,GeometriesDiffer,bz.Fk,bz.Qsvb,bz.Irtrenn,bz.Leckstatus,bz.Leckstart,bz.Leckend,bz.Leckort,bz.Leckmenge,bz.Imptnz,bz.Zvlimptnz,bz.Kantenzv,bz.ITrennWithNSCH,geometry,fkKI,fkKK,PipeTable: Table Name,PipeTable: Name,PipeTable: Fk,PipeTable: Dn,PipeTable: Di,PipeTable: Da,PipeTable: S,PipeTable: Wsteig,PipeTable: Wtiefe,PipeTable: Kt,PipeTable: Pn,PipeTable: Ausfallzeit,PipeTable: Reparatur,PipeTable: Rehabilitation,PipeTable: Tk,PipeTable: Pk,PipeTable: InVariant,A,DTTR,DWVERL,DWVERLABS,IAKTIV,IRTRENN,JV,MVEC_start,MVEC_end,MVEC_sequence,PDAMPF,PHR,PMIN,PVEC_start,PVEC_end,PVEC_sequence,PVECMAX_INST_start,PVECMAX_INST_end,PVECMAX_INST_sequence,PVECMIN_INST_start,PVECMIN_INST_end,PVECMIN_INST_sequence,QMAV,QMI,QMK,RHOI,RHOK,RHOVEC_start,RHOVEC_end,RHOVEC_sequence,SVEC_start,SVEC_end,SVEC_sequence,TI,TK,TTRVEC_start,TTRVEC_end,TTRVEC_sequence,TVEC_start,TVEC_end,TVEC_sequence,VAV,VI,VK,VOLDA,WVL,ZVEC_start,ZVEC_end,ZVEC_sequence,l_sum,AGSN_Lfdnr,AGSN_Name
0,5025945677694931826,Rohr R-E0 R-K4163S,4816511167455310973,4779752876656844188,5204829332281547346,15.351700,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5691533564979419761,OSM: Knoten 476971238 -> Knoten 299394923; Län...,39785520,0,2,0.005,0,350,345.6,Rücklauf,,5025945677694931826,5025945677694931826,False,713621.921383,5.578219e+06,False,5025945677694931826,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713621.921 5578218.954, 713616.649...",5160850648779674898,4851678476955084637,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004935,26.63305,0.408863,0.0,0.0,0.154884,-79.74764,-79.74764,"(-79.74764, -79.74764, -79.74764)",0.197685,0.002378,3.953543,4.025455,3.953540,"(4.025455, 3.9895, 3.95354)",4.025455,3.953540,"(4.025455, 3.9895, 3.95354)",4.025455,3.953540,"(4.025455, 3.9895, 3.95354)",-287.0915,-287.0915,-287.0915,983.7845,983.7839,983.7845,983.7839,"(983.7845, 983.7842, 983.7839)",0.0,15.351700,"(0.0, 7.67585, 15.3517)",59.83105,59.83229,0.316736,0.311801,"(0.3167359, 0.3142685, 0.311801)",59.83105,59.83231,"(59.83105, 59.83167, 59.83231)",-0.864133,-0.864133,-0.864133,0.0,0.0,541.43,542.20,"(541.43, 541.815, 542.2)",15.351701,1,Längsschnitt
1,5216742060270992761,Rohr R-K4163S R-K4173S,4816511167455310973,4779752876656844188,5204829332281547346,12.508950,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5048873293262650113,OSM: Knoten 299394923 -> Knoten 4105649557; Lä...,39785520,0,2,0.005,0,350,345.6,Rücklauf,,5216742060270992761,5216742060270992761,False,713616.648712,5.578233e+06,False,5216742060270992761,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.649 5578233.372, 713616.465...",4851678476955084637,5469753985021987570,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004021,27.238,0.340719,0.0,0.0,0.154884,-79.74764,-79.74764,"(-79.74764, -79.74764, -79.74764)",0.197695,0.001937,3.885054,3.953540,3.885055,"(3.95354, 3.9193, 3.885055)",3.953540,3.885055,"(3.95354, 3.9193, 3.885055)",3.953540,3.885055,"(3.95354, 3.9193, 3.885055)",-287.0915,-287.0915,-287.0915,983.7839,983.7833,983.7839,983.7833,"(983.7839, 983.7836, 983.7833)",0.0,12.508950,"(0.0, 6.254475, 12.50895)",59.83229,59.8333,0.311801,0.307780,"(0.311801, 0.3097906, 0.30778)",59.83231,59.83331,"(59.83231, 59.83279, 59.83331)",-0.864134,-0.864133,-0.864134,0.0,0.0,542.20,542.93,"(542.2, 542.565, 542.93)",27.860648,1,Längsschnitt
2,4919359344392474301,Rohr R-K4643S R-K4173S,4816511167455310973,4779752876656844188,5204829332281547346,6.265505,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5715081934973525403,OSM: Knoten 299394922 -> Knoten 4105649557; Lä...,595926249,0,2,0.005,0,350,345.6,Rücklauf,,4919359344392474301,4919359344392474301,False,713616.369043,5.578252e+06,False,4919359344392474301,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.369 5578252.145, 713616.465...",5207603338578264169,5469753985021987570,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.002014,26.41319,0.165492,0.0,0.0,0.154884,79.74764,79.74764,"(79.74764, 79.74764)",0.197702,0.00097,3.851295,3.851295,3.885055,"(3.851295, 3.885055)",3.851295,3.885055,"(3.851295, 3.885055)",3.851295,3.885055,"(3.851295, 3.885055)",287.0915,287.0915,287.0915,983.7831,983.7833,983.7831,983.7833,"(983.7831, 983.7833)",0.0,6.265505,"(0.0, 6.265505)",59.83381,59.8333,0.305766,0.307780,"(0.305766, 0.30778)",59.83380,59.83331,"(59.8338, 59.83331)",0.864134,0.864134,0.864134,0.0,0.0,543.29,542.93,"(543.29, 542.93)",34.126153,1,Längsschnitt
3,5299861566239260044,Rohr R-K4523S R-K4643S,4816511167455310973,4779752876656844188,5204829332281547346,14.407540,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5413647981880727734,OSM: Knoten 299394921 -> Knoten 299394922; Län...,595926249,0,2,0.005,0,350,345.6,Rücklauf,,5299861566239260044,5299861566239260044,False,713618.883649,5.578266e+06,False,5299861566239260044,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713618.884 5578266.331, 713616.369...",5191457421068378074,5207603338578264169,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004631,27.02703,0.389393,0.0,0.0,0.154884,79.74764,79.74764,"(79.74764, 79.74764, 79.74764)",0.197709,0.002231,3.773449,3.773450,3.851295,"(3.77345, 3.81237, 3.851295)",3.773450,3.851295,"(3.77345, 3.81237, 3.851295)",3.773450,3.851295,"(3.77345, 3.81237, 3.851295)",287.0915,287.0915,287.0915,983.7825,983.7831,983.7825,983.7831,"(983.7825, 983.7828, 983.7831)",0.0,14.407540,"(0.0, 7.20377, 14.40754)",59.83496,59.83381,0.301135,0.305766,"(0.3011346, 0.3034503, 0.305766)",59.83496,59.83380,"(59.83496, 59.83438, 59.8338)",0.864134,0.864135,0.864134,0.0,0.0,544.12,543.29,"(544.12, 543.705, 543.29)",48.533695,1,Längsschnitt
4,5204837016964086891,Rohr R-K4513S R-K4523S,4816511167455310973,4779752876656844188,5204829332281547346,13.515840,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5134010500800575790,OSM: Knoten 4105649561 -> Knoten 299394921; Lä...,408665320,0,2,0.005,0,350,345.6,Rücklauf,,5204837016964086891,5204837016964086891,False,713616.238695,5.578280e+06,False,5204837016964086891,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.239 5578279.586, 713618.884...",4875054825941361274,5191457421068378074,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004345,27.36961,0.369923,0.0,0.0,0.154884,79.74764,79.74764,"(79.74764, 79.74764, 79.74764)",0.19772,0.002093,3.729236,3.729235,3.773450,"(3.729235, 3.751345, 3.77345)",3.729235,3.773450,"(3.729235, 3.751345, 3.77345)",3.729235,3.773450,"(3.729235, 3.751345, 3.77345)",287.0915,287.0915,287.0915,983.782,983.7825,983.7820,983.7825,"(983.782, 983.7822, 983.7825)",0.0,13.515840,"(0.0, 6.75792, 13.51584)",59.83606,59.83496,0.296790,0.301135,"(0.2967899, 0.2989623, 0.3011346)",59.83606,59.83496,"(59.83606, 59.83551, 59.83496)",0.864135,0.864135,0.864135,0.0,0.0,544.60,544.12,"(544.6, 544.36, 544.12)",62.049538,1,Längsschnitt

In [50]:
dfs[1][0].head() # Lfdnr 2 VL

,tk,Name,FkdtroRowd,Fkltgr,Fkstrasse,L,Lzu,Rau,Jlambs,Lambda0,Zein,Zaus,Zuml,Asoll,Indschall,Baujahr,Hal,Fkcont,Fk2lrohr,Beschreibung,Idreferenz,Iplanung,Kvr,LineWidthMM,DottedLine,DN,Di,KvrKlartext,HasClosedNSCHs,Tk,Pk,InVariant,Xkor,Ykor,GeometriesDiffer,bz.Fk,bz.Qsvb,bz.Irtrenn,bz.Leckstatus,bz.Leckstart,bz.Leckend,bz.Leckort,bz.Leckmenge,bz.Imptnz,bz.Zvlimptnz,bz.Kantenzv,bz.ITrennWithNSCH,geometry,fkKI,fkKK,PipeTable: Table Name,PipeTable: Name,PipeTable: Fk,PipeTable: Dn,PipeTable: Di,PipeTable: Da,PipeTable: S,PipeTable: Wsteig,PipeTable: Wtiefe,PipeTable: Kt,PipeTable: Pn,PipeTable: Ausfallzeit,PipeTable: Reparatur,PipeTable: Rehabilitation,PipeTable: Tk,PipeTable: Pk,PipeTable: InVariant,A,DTTR,DWVERL,DWVERLABS,IAKTIV,IRTRENN,JV,MVEC_start,MVEC_end,MVEC_sequence,PDAMPF,PHR,PMIN,PVEC_start,PVEC_end,PVEC_sequence,PVECMAX_INST_start,PVECMAX_INST_end,PVECMAX_INST_sequence,PVECMIN_INST_start,PVECMIN_INST_end,PVECMIN_INST_sequence,QMAV,QMI,QMK,RHOI,RHOK,RHOVEC_start,RHOVEC_end,RHOVEC_sequence,SVEC_start,SVEC_end,SVEC_sequence,TI,TK,TTRVEC_start,TTRVEC_end,TTRVEC_sequence,TVEC_start,TVEC_end,TVEC_sequence,VAV,VI,VK,VOLDA,WVL,ZVEC_start,ZVEC_end,ZVEC_sequence,l_sum,AGSN_Lfdnr,AGSN_Name
0,5691533564979419761,Rohr V-E0 V-K1683S,4816511167455310973,4779752876656844188,5204829332281547346,15.351700,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5025945677694931826,OSM: Knoten 476971238 -> Knoten 299394923; Län...,39785520,0,1,0.005,0,350,345.6,Vorlauf,,5691533564979419761,5691533564979419761,False,713619.921383,5.578219e+06,False,5691533564979419761,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713619.921 5578218.954, 713614.649...",5398100694284104779,4825391580467484032,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004844,43.12018,0.661968,0.0,0.0,0.152727,79.74764,79.74764,"(79.74764, 79.74764, 79.74764)",0.701074,0.002345,5.800529,5.878635,5.800530,"(5.878635, 5.83958, 5.80053)",5.878635,5.800530,"(5.878635, 5.83958, 5.80053)",5.878635,5.800530,"(5.878635, 5.83958, 5.80053)",287.0915,287.0915,287.0915,965.7,965.7012,965.7000,965.7012,"(965.7, 965.7006, 965.7012)",0.0,15.351700,"(0.0, 7.67585, 15.3517)",89.99999,89.99802,0.000000,0.004844,"(0.0, 0.002422066, 0.004844132)",90.00000,89.99802,"(90.0, 89.99902, 89.99802)",0.880315,0.880315,0.880314,0.0,10082.88,541.49,542.29,"(541.49, 541.89, 542.29)",15.351701,2,Längsschnitt in mlc
1,5048873293262650113,Rohr V-K1683S V-K1693S,4816511167455310973,4779752876656844188,5204829332281547346,12.508950,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5216742060270992761,OSM: Knoten 299394923 -> Knoten 4105649557; Lä...,39785520,0,1,0.005,0,350,345.6,Vorlauf,,5048873293262650113,5048873293262650113,False,713614.648712,5.578233e+06,False,5048873293262650113,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713614.649 5578233.372, 713614.465...",4825391580467484032,5180617780362861593,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.003947,43.58081,0.54515,0.0,0.0,0.152727,79.74764,79.74764,"(79.74764, 79.74764, 79.74764)",0.701027,0.00191,5.732326,5.800530,5.732325,"(5.80053, 5.76643, 5.732325)",5.800530,5.732325,"(5.80053, 5.76643, 5.732325)",5.800530,5.732325,"(5.80053, 5.76643, 5.732325)",287.0915,287.0915,287.0915,965.7012,965.7021,965.7012,965.7021,"(965.7012, 965.7017, 965.7021)",0.0,12.508950,"(0.0, 6.254475, 12.50895)",89.99802,89.9964,0.004844,0.008791,"(0.004844132, 0.006817694, 0.008791257)",89.99802,89.99640,"(89.99802, 89.99722, 89.9964)",0.880314,0.880314,0.880313,0.0,10081.81,542.29,542.99,"(542.29, 542.64, 542.99)",27.860648,2,Längsschnitt in mlc
2,5715081934973525403,Rohr V-K2163S V-K1693S,4816511167455310973,4779752876656844188,5204829332281547346,6.265505,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,4919359344392474301,OSM: Knoten 299394922 -> Knoten 4105649557; Lä...,595926249,0,1,0.005,0,350,345.6,Vorlauf,,5715081934973525403,5715081934973525403,False,713614.369043,5.578252e+06,False,5715081934973525403,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713614.369 5578252.145, 713614.465...",4964920487041183545,5180617780362861593,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.001977,43.50409,0.272575,0.0,0.0,0.152727,-79.74764,-79.74764,"(-79.74764, -79.74764)",0.700995,0.000957,5.699167,5.699165,5.732325,"(5.699165, 5.732325)",5.699165,5.732325,"(5.699165, 5.732325)",5.699165,5.732325,"(5.699165, 5.732325)",-287.0915,-287.0915,-287.0915,965.7026,965.7021,965.7026,965.7021,"(965.7026, 965.7021)",0.0,6.265505,"(0.0, 6.265505)",89.9956,89.9964,0.010768,0.008791,"(0.0107683, 0.008791257)",89.99561,89.99640,"(89.99561, 89.9964)",-0.880313,-0.880313,-0.880313,0.0,-10080.93,543.33,542.99,"(543.33, 542.99)",34.126153,2,Längsschnitt in mlc
3,5413647981880727734,Rohr V-K2043S V-K2163S,4816511167455310973,4779752876656844188,5204829332281547346,14.407540,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5299861566239260044,OSM: Knoten 299394921 -> Knoten 299394922; Län...,595926249,0,1,0.005,0,350,345.6,Vorlauf,,5413647981880727734,5413647981880727734,False,713616.883649,5.578266e+06,False,5413647981880727734,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.884 5578266.331, 713614.369...",4794016231137548967,4964920487041183545,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004546,43.24324,0.623029,0.0,0.0,0.152727,-79.74764,-79.74764,"(-79.74764, -79.74764, -79.74764)",0.70096,0.0022,5.630673,5.630675,5.699165,"(5.630675, 5.66492, 5.699165)",5.630675,5.699165,"(5.630675, 5.66492, 5.699165)",5.630675,5.699165,"(5.630675, 5.66492, 5.699165)",-287.0915,-287.0915,-287.0915,965.7037,965.7026,965.7037,965.7026,"(965.7037, 965.7032, 965.7026)",0.0,14.407540,"(0.0, 7.20377, 14.40754)",89.99374,89.9956,0.015315,0.010768,"(0.01531452, 0.01304141, 0.0107683)",89.99374,89.99561,"(89.99374, 89.99466, 89.99561)",-0.880312,-0.880312,-0.880313,0.0,-10080.49,544.03,543.33,"(544.03, 543.6801, 543.33)",48.533695,2,Längsschnitt in mlc
4,5134010500800575790,Rohr V-K2033S V-K2043S,4816511167455310973,4779752876656844188,5204829332281547346,13.515840,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5204837016964086891,OSM: Knoten 4105649561 -> Knoten 299394921; Lä...,408665320,0,1,0.005,0,350,345.6,Vorlauf,,5134010500800575790,5134010500800575790,False,713614.238695,5.578280e+06,False,5134010500800575790,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713614.239 5578279.586, 713616.884...",5473123125979010325,4794016231137548967,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004265,42.49493,0.574355,0.0,0.0,0.152727,-79.74764,-79.74764,"(-79.74764, -79.74764, -79.74764)",0.700913,0.002064,5.580316,5.580315,5.630675,"(5.580315, 5.605495, 5.630675)",5.580315,5.630675,"(5.580315, 5.605495, 5.630675)",5.580315,5.630675,"(5.580315, 5.605495, 5.630675)",-287.0915,-287.0915,-287.0915,965.7048,965.7037,965.7048,965.7037,"(965.7048, 965.7043, 965.7037)",0.0,13.515840,"(0.0, 6.75792, 13.51584)",89.992,89.99374,0.019579,0.015315,"(0.01957938, 0.01744695, 0.01531453)",89.99200,89.99374,"(89.992, 89.99286, 89.99374)",-0.880311,-0.880311,-0.880312,0.0,-10079.48,544.54,544.03,"(544.54, 544.285, 544.03)",62.049538,2,Längsschnitt in mlc

In [51]:
dfs[1][1].head() # Lfdnr 2 RL

,tk,Name,FkdtroRowd,Fkltgr,Fkstrasse,L,Lzu,Rau,Jlambs,Lambda0,Zein,Zaus,Zuml,Asoll,Indschall,Baujahr,Hal,Fkcont,Fk2lrohr,Beschreibung,Idreferenz,Iplanung,Kvr,LineWidthMM,DottedLine,DN,Di,KvrKlartext,HasClosedNSCHs,Tk,Pk,InVariant,Xkor,Ykor,GeometriesDiffer,bz.Fk,bz.Qsvb,bz.Irtrenn,bz.Leckstatus,bz.Leckstart,bz.Leckend,bz.Leckort,bz.Leckmenge,bz.Imptnz,bz.Zvlimptnz,bz.Kantenzv,bz.ITrennWithNSCH,geometry,fkKI,fkKK,PipeTable: Table Name,PipeTable: Name,PipeTable: Fk,PipeTable: Dn,PipeTable: Di,PipeTable: Da,PipeTable: S,PipeTable: Wsteig,PipeTable: Wtiefe,PipeTable: Kt,PipeTable: Pn,PipeTable: Ausfallzeit,PipeTable: Reparatur,PipeTable: Rehabilitation,PipeTable: Tk,PipeTable: Pk,PipeTable: InVariant,A,DTTR,DWVERL,DWVERLABS,IAKTIV,IRTRENN,JV,MVEC_start,MVEC_end,MVEC_sequence,PDAMPF,PHR,PMIN,PVEC_start,PVEC_end,PVEC_sequence,PVECMAX_INST_start,PVECMAX_INST_end,PVECMAX_INST_sequence,PVECMIN_INST_start,PVECMIN_INST_end,PVECMIN_INST_sequence,QMAV,QMI,QMK,RHOI,RHOK,RHOVEC_start,RHOVEC_end,RHOVEC_sequence,SVEC_start,SVEC_end,SVEC_sequence,TI,TK,TTRVEC_start,TTRVEC_end,TTRVEC_sequence,TVEC_start,TVEC_end,TVEC_sequence,VAV,VI,VK,VOLDA,WVL,ZVEC_start,ZVEC_end,ZVEC_sequence,l_sum,AGSN_Lfdnr,AGSN_Name
0,5025945677694931826,Rohr R-E0 R-K4163S,4816511167455310973,4779752876656844188,5204829332281547346,15.351700,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5691533564979419761,OSM: Knoten 476971238 -> Knoten 299394923; Län...,39785520,0,2,0.005,0,350,345.6,Rücklauf,,5025945677694931826,5025945677694931826,False,713621.921383,5.578219e+06,False,5025945677694931826,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713621.921 5578218.954, 713616.649...",5160850648779674898,4851678476955084637,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004935,26.63305,0.408863,0.0,0.0,0.154884,-79.74764,-79.74764,"(-79.74764, -79.74764, -79.74764)",0.197685,0.002378,3.953543,4.025455,3.953540,"(4.025455, 3.9895, 3.95354)",4.025455,3.953540,"(4.025455, 3.9895, 3.95354)",4.025455,3.953540,"(4.025455, 3.9895, 3.95354)",-287.0915,-287.0915,-287.0915,983.7845,983.7839,983.7845,983.7839,"(983.7845, 983.7842, 983.7839)",0.0,15.351700,"(0.0, 7.67585, 15.3517)",59.83105,59.83229,0.316736,0.311801,"(0.3167359, 0.3142685, 0.311801)",59.83105,59.83231,"(59.83105, 59.83167, 59.83231)",-0.864133,-0.864133,-0.864133,0.0,0.0,541.43,542.20,"(541.43, 541.815, 542.2)",15.351701,2,Längsschnitt in mlc
1,5216742060270992761,Rohr R-K4163S R-K4173S,4816511167455310973,4779752876656844188,5204829332281547346,12.508950,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5048873293262650113,OSM: Knoten 299394923 -> Knoten 4105649557; Lä...,39785520,0,2,0.005,0,350,345.6,Rücklauf,,5216742060270992761,5216742060270992761,False,713616.648712,5.578233e+06,False,5216742060270992761,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.649 5578233.372, 713616.465...",4851678476955084637,5469753985021987570,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004021,27.238,0.340719,0.0,0.0,0.154884,-79.74764,-79.74764,"(-79.74764, -79.74764, -79.74764)",0.197695,0.001937,3.885054,3.953540,3.885055,"(3.95354, 3.9193, 3.885055)",3.953540,3.885055,"(3.95354, 3.9193, 3.885055)",3.953540,3.885055,"(3.95354, 3.9193, 3.885055)",-287.0915,-287.0915,-287.0915,983.7839,983.7833,983.7839,983.7833,"(983.7839, 983.7836, 983.7833)",0.0,12.508950,"(0.0, 6.254475, 12.50895)",59.83229,59.8333,0.311801,0.307780,"(0.311801, 0.3097906, 0.30778)",59.83231,59.83331,"(59.83231, 59.83279, 59.83331)",-0.864134,-0.864133,-0.864134,0.0,0.0,542.20,542.93,"(542.2, 542.565, 542.93)",27.860648,2,Längsschnitt in mlc
2,4919359344392474301,Rohr R-K4643S R-K4173S,4816511167455310973,4779752876656844188,5204829332281547346,6.265505,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5715081934973525403,OSM: Knoten 299394922 -> Knoten 4105649557; Lä...,595926249,0,2,0.005,0,350,345.6,Rücklauf,,4919359344392474301,4919359344392474301,False,713616.369043,5.578252e+06,False,4919359344392474301,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.369 5578252.145, 713616.465...",5207603338578264169,5469753985021987570,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.002014,26.41319,0.165492,0.0,0.0,0.154884,79.74764,79.74764,"(79.74764, 79.74764)",0.197702,0.00097,3.851295,3.851295,3.885055,"(3.851295, 3.885055)",3.851295,3.885055,"(3.851295, 3.885055)",3.851295,3.885055,"(3.851295, 3.885055)",287.0915,287.0915,287.0915,983.7831,983.7833,983.7831,983.7833,"(983.7831, 983.7833)",0.0,6.265505,"(0.0, 6.265505)",59.83381,59.8333,0.305766,0.307780,"(0.305766, 0.30778)",59.83380,59.83331,"(59.8338, 59.83331)",0.864134,0.864134,0.864134,0.0,0.0,543.29,542.93,"(543.29, 542.93)",34.126153,2,Längsschnitt in mlc
3,5299861566239260044,Rohr R-K4523S R-K4643S,4816511167455310973,4779752876656844188,5204829332281547346,14.407540,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5413647981880727734,OSM: Knoten 299394921 -> Knoten 299394922; Län...,595926249,0,2,0.005,0,350,345.6,Rücklauf,,5299861566239260044,5299861566239260044,False,713618.883649,5.578266e+06,False,5299861566239260044,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713618.884 5578266.331, 713616.369...",5191457421068378074,5207603338578264169,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004631,27.02703,0.389393,0.0,0.0,0.154884,79.74764,79.74764,"(79.74764, 79.74764, 79.74764)",0.197709,0.002231,3.773449,3.773450,3.851295,"(3.77345, 3.81237, 3.851295)",3.773450,3.851295,"(3.77345, 3.81237, 3.851295)",3.773450,3.851295,"(3.77345, 3.81237, 3.851295)",287.0915,287.0915,287.0915,983.7825,983.7831,983.7825,983.7831,"(983.7825, 983.7828, 983.7831)",0.0,14.407540,"(0.0, 7.20377, 14.40754)",59.83496,59.83381,0.301135,0.305766,"(0.3011346, 0.3034503, 0.305766)",59.83496,59.83380,"(59.83496, 59.83438, 59.8338)",0.864134,0.864135,0.864134,0.0,0.0,544.12,543.29,"(544.12, 543.705, 543.29)",48.533695,2,Längsschnitt in mlc
4,5204837016964086891,Rohr R-K4513S R-K4523S,4816511167455310973,4779752876656844188,5204829332281547346,13.515840,0,0.05,1,0,0,0,0,1000,0,,0,5029128874972463118,5134010500800575790,OSM: Knoten 4105649561 -> Knoten 299394921; Lä...,408665320,0,2,0.005,0,350,345.6,Rücklauf,,5204837016964086891,5204837016964086891,False,713616.238695,5.578280e+06,False,5204837016964086891,0,0,0,0,0,0,0,0,0,0,0,"LINESTRING (713616.239 5578279.586, 713618.884...",4875054825941361274,5191457421068378074,KMR,DN 350,4927972999088213410,350,345.6,355.6,5.0,0,0,0.54,0,0,0,1300,4816511167455310973,4816511167455310973,False,0.0,0.004345,27.36961,0.369923,0.0,0.0,0.154884,79.74764,79.74764,"(79.74764, 79.74764, 79.74764)",0.19772,0.002093,3.729236,3.729235,3.773450,"(3.729235, 3.751345, 3.77345)",3.729235,3.773450,"(3.729235, 3.751345, 3.77345)",3.729235,3.773450,"(3.729235, 3.751345, 3.77345)",287.0915,287.0915,287.0915,983.782,983.7825,983.7820,983.7825,"(983.782, 983.7822, 983.7825)",0.0,13.515840,"(0.0, 6.75792, 13.51584)",59.83606,59.83496,0.296790,0.301135,"(0.2967899, 0.2989623, 0.3011346)",59.83606,59.83496,"(59.83606, 59.83551, 59.83496)",0.864135,0.864135,0.864135,0.0,0.0,544.60,544.12,"(544.6, 544.36, 544.12)",62.049538,2,Längsschnitt in mlc