# Test

## SIR 3S Toolkit

### Regular Import/Init

In [1]:
from sir3stoolkit.core import wrapper

In [2]:
wrapper

In [3]:
wrapper.Initialize_Toolkit(r"C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2")

[2026-08-12 11:59:25,531] INFO in sir3stoolkit.core.wrapper: [Initialization] Using provided SirGraf path: C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2
[2026-08-12 11:59:25,531] INFO in sir3stoolkit.core.wrapper: [Initialization] Using provided SirGraf path: C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2
[2026-08-12 11:59:25,585] INFO in sir3stoolkit.core.wrapper: [Initialization] Initializing toolkit with SirGraf path: C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2

### Additional Import/Init for Dataframes class

In [4]:
from sir3stoolkit.mantle.dataframes import SIR3S_Model_Dataframes

In [5]:
s3s = SIR3S_Model_Dataframes()

[2026-08-12 11:59:35,162] INFO in sir3stoolkit.core.wrapper: [Model Class Initialization] Initialization complete

## Additional

In [6]:
import pandas as pd
from shapely.geometry import Point
import re
import folium
from folium.plugins import HeatMap
import numpy as np
import geopandas as gpd
from shapely import wkt
import matplotlib.pyplot as plt
import contextily as cx
import logging

# Open Model

In [7]:
dbFile = r"..\Tutorial051_Assets\Toolkit_Tutorial51_Model.db3"

In [8]:
s3s.OpenModel(dbName=dbFile,
              providerType=s3s.ProviderTypes.SQLite,
              Mid="M-1-0-1",
              saveCurrentlyOpenModel=False,
              namedInstance="",
              userID="",
              password="")

[2026-08-12 11:59:46,503] INFO in sir3stoolkit.core.wrapper: Model is open for further operation

In [9]:
from PT3S.Mx import Mx

In [10]:
mx = Mx(mx1File=r"C:\Users\aUsername\3S\sir3stoolkit\docs\source\tutorials\SIR3S_Model_Mantle\Tutorial051_Assets\WDToolkit_Tutorial51_Model\B1\V0\BZ1\M-1-0-1.1.MX1",  NoH5Read=True)

In [11]:
mx.df.head()

,ALLG~~~5597593673700177669~SNAPSHOTTYPE,ALLG~~~5597593673700177669~CVERSO,ALLG~~~5597593673700177669~EXSTAT,ALLG~~~5597593673700177669~NFEHL,ALLG~~~5597593673700177669~NWARN,ALLG~~~5597593673700177669~NMELD,ALLG~~~5597593673700177669~CPUTIME,ALLG~~~5597593673700177669~USRTIME,ALLG~~~5597593673700177669~NPGREST,ALLG~~~5597593673700177669~NETZABN,ALLG~~~5597593673700177669~NFVHYUV,ALLG~~~5597593673700177669~NFVTHUV,ALLG~~~5597593673700177669~MFVHYUV,ALLG~~~5597593673700177669~MFVTHUV,ALLG~~~5597593673700177669~TVMINMAX,ALLG~~~5597593673700177669~ITERHY,ALLG~~~5597593673700177669~JWARN,ALLG~~~5597593673700177669~NETZABNEXITS,ALLG~~~5597593673700177669~LINEPACKRATE,ALLG~~~5597593673700177669~LINEPACKGES,ALLG~~~5597593673700177669~LINEPACKGEOM,ALLG~~~5597593673700177669~RHOAV,ALLG~~~5597593673700177669~TAV,ALLG~~~5597593673700177669~PAV,ALLG~~~5597593673700177669~FWVB_DPHMIN,ALLG~~~5597593673700177669~KNOT_PHMAX,ALLG~~~5597593673700177669~KNOT_PHMIN,ALLG~~~5597593673700177669~FWVB_TVLMIN,ALLG~~~5597593673700177669~NETZBEZ,ALLG~~~5597593673700177669~KNOT_PHMAX_V,ALLG~~~5597593673700177669~KNOT_PHMAX_R,ALLG~~~5597593673700177669~KNOT_PHMAX_U,ALLG~~~5597593673700177669~KNOT_PHMIN_V,ALLG~~~5597593673700177669~KNOT_PHMIN_R,ALLG~~~5597593673700177669~KNOT_PHMIN_U,ALLG~~~5597593673700177669~ITERTH,ALLG~~~5597593673700177669~INTERAKTTH,ALLG~~~5597593673700177669~INTERAKTRG,KNOT~R-E~~4945502875946918021~PH,KNOT~V-E~~5364585352767333609~PH,KNOT~V-E~~5364585352767333609~T,VENT~R-E0~R-E~5078909058477631059~QM,KNOT~R-E~~4945502875946918021~T,WBLZ~WärmeblnzGes~~5747928298316755683~WVB,WBLZ~WärmeblnzGes~~5747928298316755683~WVERL,FWVB~V-K2153S~R-K4633S~4695691920575201490~LFT,FWVB~V-K2243S~R-K4723S~4612643650175000934~DP,FWVB~V-K333S~R-K2813S~5298892186072792581~DP,FWVB~V-K1393S~R-K3873S~5641820391023802273~DP,FWVB~V-K1393S~R-K3873S~5714834959169623562~DP,FWVB~V-K593S~R-K3073S~5539308064883517142~DP,FWVB~V-K153S~R-K2633S~4851778549814053310~DP,FWVB~V-K2263S~R-K4743S~5095755403689234488~DP,FWVB~V-K2263S~R-K4743S~4754662858150981800~DP,FWVB~V-K133S~R-K2613S~4831899581981959889~DP,FWVB~V-SP01~R-SP01~5373061288922912729~DP,FWVB~V-SP01~R-SP01~5338005695177201668~DP,FWVB~V-SP01~R-SP01~5103671514823328293~DP,FWVB~V-K123S~R-K2603S~5568194212677879165~DP,FWVB~V-K1363S~R-K3843S~5534236886775923535~DP,FWVB~V-K1373S~R-K3853S~5054661805697996469~DP,FWVB~V-K1363S~R-K3843S~4677484876769683069~DP,FWVB~V-K1343S~R-K3823S~5331382729720004878~DP,FWVB~V-K1323S~R-K3803S~5320145816789148184~DP,FWVB~V-K73S~R-K2553S~4660745360789977502~DP,FWVB~V-K73S~R-K2553S~5475433067817926464~DP,FWVB~V-K63S~R-K2543S~5088507410302060583~DP,FWVB~V-K23S~R-K2503S~4799202816710088269~DP,FWVB~V-K73S~R-K2553S~5567370826017196953~DP,FWVB~V-K1313S~R-K3793S~4721603020200203929~DP,FWVB~V-K1243S~R-K3723S~5539118071732060322~DP,FWVB~V-K1283S~R-K3763S~5433812588779537970~DP,FWVB~V-K1303S~R-K3783S~4982647601065704474~DP,FWVB~V-K1303S~R-K3783S~4758534110963451621~DP,FWVB~V-K13S~R-K2493S~5157987375362402948~DP,FWVB~V-K13S~R-K2493S~5572700189436507358~DP,FWVB~V-K133S~R-K2623S~5042957248574195254~DP,FWVB~V-K123S~R-K2603S~5620374956890186419~DP,FWVB~V-K123S~R-K2603S~5642186467419772313~DP,FWVB~V-K113S~R-K2593S~4952675334963811549~DP,FWVB~V-K63S~R-K2543S~5289349232690798866~DP,FWVB~V-K23S~R-K2503S~5263894803742270480~DP,FWVB~V-K23S~R-K2503S~5258191418983486434~DP,FWVB~V-K13S~R-K2493S~5219695668506679887~DP,FWVB~V-K23S~R-K2503S~5089681968228574805~DP,FWVB~V-K23S~R-K2503S~4723552478525716099~DP,FWVB~V-K1243S~R-K3723S~4717900447084130786~DP,FWVB~V-K1243S~R-K3723S~4680566654399387170~DP,FWVB~V-K1273S~R-K3753S~4774089356071680115~DP,FWVB~V-K1303S~R-K3783S~5483836906626806693~DP,FWVB~V-K13S~R-K2493S~5723652079410431099~DP,FWVB~V-K13S~R-K2493S~5152070634362289135~DP,FWVB~V-K463S~R-K2943S~4715437119287917203~DP,FWVB~V-K2023S~R-K4503S~5429690733112787259~DP,FWVB~V-K2023S~R-K4503S~5470212073687668936~DP,FWVB~V-K2023S~R-K4503S~4690848713916516887~DP,FWVB~V-K583S~R-K3063S~5210301978863275664~DP,FWVB~V-K583S~R-K3063S~4769972484103895237~DP,FWVB~V-K583S~R-K3063S~4839284960010591311~DP,FWVB~V-K2173S~R-K4653S~5238469959575677978~DP,FWVB~V-K573S~R-K3053S~5378395521233234009~DP,FWVB~V-K2153S~R-K4633S~5272427879633450297~DP,FWVB~V-K1163S~R-K3643S~5563426535048622787~DP,FWVB~V-K583S~R-K3063S~5708564737898353551~DP,FWVB~V-K583S~R-K3063S~5646104354697048422~DP,FWVB~V-K1163S~R-K3643S~4998245026021181527~DP,FWVB~V-K2063S~R-K3063S~5030808405918905856~DP,FWVB~V-K2063S~R-K4543S~5589819464555437381~DP,FWVB~V-K933S~R-K3413S~5021149544911429814~DP,FWVB~V-K2073S~R-K4553S~5483428144944113828~DP,FWVB~V-K2073S~R-K4553S~5608524552763679614~DP,FWVB~V-K2023S~R-K4503S~5626371875066735675~DP,FWVB~V-K403S~R-K2883S~5421154557729864641~DP,FWVB~V-K2003S~R-K4483S~4808379698586732872~DP,FWVB~V-K253S~R-K2733S~4754045271859275254~DP,FWVB~V-K1643S~R-K4123S~4804522946718449543~DP,FWVB~V-K1643S~R-K4123S~5397095414062959706~DP,FWVB~V-K1653S~R-K4133S~4972542528251576003~DP,FWVB~V-K1663S~R-K4143S~4841968208579971744~DP,FWVB~V-K1663S~R-K4143S~4790880210700946505~DP,FWVB~V-K273S~R-K2753S~5134226995532837471~DP,FWVB~V-K273S~R-K2753S~5199665792777686632~DP,FWVB~V-K263S~R-K2743S~4829820734742795813~DP,FWVB~V-K1643S~R-K4123S~5473902379470916704~DP,FWVB~V-K273S~R-K2753S~5095071279723776262~DP,FWVB~V-K263S~R-K2743S~4969795535504580282~DP,FWVB~V-K263S~R-K2743S~5389503305937461852~DP,FWVB~V-K263S~R-K2743S~5491075003903254860~DP,FWVB~V-K233S~R-K2713S~5333950106019937551~DP,FWVB~V-K243S~R-K2723S~5078322764546640049~DP,FWVB~V-K573S~R-K3053S~5074136990830026951~DP,FWVB~V-K1083S~R-K3563S~5721943751421394086~DP,FWVB~V-K1083S~R-K3563S~4617599012360428982~DP,FWVB~V-K1073S~R-K3553S~5143587653110554807~DP,FWVB~V-K1073S~R-K3553S~5155974252610494227~DP,FWVB~V-K1073S~R-K3553S~5507469098629391620~DP,FWVB~V-K1083S~R-K3563S~4644294207793899393~DP,FWVB~V-K1083S~R-K3563S~4729135819215267446~DP,FWVB~V-K313S~R-K2793S~5397363169018116905~DP,FWVB~V-K323S~R-K2803S~5293083471824257348~DP,FWVB~V-K573S~R-K3053S~4692947232485098213~DP,FWVB~V-K1083S~R-K3563S~4840514655814345420~DP,FWVB~V-K1083S~R-K3563S~4984259280617000809~DP,FWVB~V-K2153S~R-K4633S~5450848705169565418~DP,FWVB~V-K1083S~R-K3563S~5013175068886361021~DP,FWVB~V-K1083S~R-K3563S~5129945735358846816~DP,FWVB~V-K1123S~R-K3603S~5641063690842961168~DP,FWVB~V-K1073S~R-K3553S~5166680757495237751~DP,FWVB~V-K1063S~R-K3543S~4614551030187170583~DP,FWVB~V-K1063S~R-K3543S~5049615340607119167~DP,FWVB~V-K1063S~R-K3543S~5182171757783007257~DP,FWVB~V-K293S~R-K2773S~4699379554487286912~DP,FWVB~V-K333S~R-K2813S~5493473140425149473~DP,FWVB~V-K333S~R-K2813S~5229547090188049969~DP,FWVB~V-K03S~R-K2483S~5078971821722268135~DP,FWVB~V-K1613S~R-K4093S~4838424991008300464~DP,FWVB~V-K1603S~R-K4083S~5119436336432835935~DP,FWVB~V-K243S~R-K2723S~5069875460823955334~DP,FWVB~V-K1623S~R-K4103S~4612562908060328263~DP,FWVB~V-K1613S~R-K4093S~4968006119183593408~DP,FWVB~V-K1603S~R-K4113S~4780867592274315225~DP,FWVB~V-K1633S~R-K4113S~4689962447077782592~DP,FWVB~V-K1633S~R-K4113S~4907629360497270624~DP,FWVB~V-K1103S~R-K3583S~5114532772926850507~DP,FWVB~V-K1143S~R-K3623S~4957429172484513667~DP,FWVB~V-K1153S~R-K3633S~5683164004528603492~DP,FWVB~V-K1153S~R-K3633S~4753737713576765068~DP,FWVB~V-K1033S~R-K3513S~5511883908108493205~DP,FWVB~V-K1033S~R-K3513S~4985463247915540404~DP,FWVB~V-K1213S~R-K3663S~5696463829656272308~DP,FWVB~V-K1223S~R-K3703S~4879060213783619417~DP,FWVB~V-K1233S~R-K3713S~5328839321384231626~DP,FWVB~V-K1233S~R-K3713S~4908302009467601605~DP,FWVB~V-K1233S~R-K3713S~5081759066536254041~DP,FWVB~V-K1223S~R-K3703S~4920414355371836818~DP,FWVB~V-K03S~R-K2483S~4953528746012203881~DP,FWVB~V-K1133S~R-K3613S~5514426350058393064~DP,FWVB~V-K2153S~R-K4633S~4695691920575201490~DP,FWVB~V-K1173S~R-K3653S~5686938269985987108~DP,FWVB~V-K1173S~R-K3653S~5608013454113942505~DP,FWVB~V-K1173S~R-K3653S~5554180086935671036~DP,FWVB~V-K1173S~R-K3653S~4715343979099977320~DP,FWVB~V-K1153S~R-K3633S~5276185429031066619~DP,FWVB~V-K1153S~R-K3633S~5752171491358190657~DP,FWVB~V-K1153S~R-K3633S~5044737621363717731~DP,FWVB~V-K1153S~R-K3633S~4959178524702114605~DP,FWVB~V-K963S~R-K3443S~5184692294783766508~DP,FWVB~V-K1023S~R-K3503S~5015574389658457843~DP,FWVB~V-K1023S~R-K3503S~5340682804823281975~DP,FWVB~V-K1183S~R-K3663S~4773718045303625562~DP,FWVB~V-K1203S~R-K3683S~4611752310942477664~DP,FWVB~V-K1213S~R-K3693S~5649394575722244706~DP,FWVB~V-K1223S~R-K3703S~5683145831265886679~DP,FWVB~V-K1223S~R-K3703S~5347934852716104645~DP,FWVB~V-K03S~R-K2483S~5338581593552364614~DP,FWVB~V-K403S~R-K2883S~4747253770471595859~DP,FWVB~V-K403S~R-K2883S~5005156965723780226~DP,FWVB~V-K413S~R-K2893S~4737813668193434747~DP,FWVB~V-K403S~R-K2883S~4824230293599010462~DP,FWVB~V-K413S~R-K2893S~4961446825744614653~DP,FWVB~V-K423S~R-K2903S~4794000986315043981~DP,FWVB~V-K433S~R-K2913S~5663966403597611254~DP,FWVB~V-K443S~R-K2923S~5285271495094652658~DP,FWVB~V-K443S~R-K2923S~5010483887057780845~DP,FWVB~V-K453S~R-K2933S~5153454494023353435~DP,FWVB~V-K463S~R-K2943S~5577210775620233409~DP,FWVB~V-K463S~R-K2943S~4884816399211992951~DP,FWVB~V-K473S~R-K2953S~5368434258234128749~DP,FWVB~V-K473S~R-K2953S~4934825369837329981~DP,FWVB~V-K473S~R-K2953S~4716889123169234975~DP,FWVB~V-K2383S~R-K4863S~4804005204522723919~DP,FWVB~V-K2383S~R-K4863S~5204002376528007016~DP,FWVB~V-K163S~R-K2643S~5118203249310421888~DP,FWVB~V-K163S~R-K2643S~4869838397682489649~DP,FWVB~V-K163S~R-K2643S~5055469814130651373~DP,FWVB~V-K163S~R-K2643S~4889571787974482626~DP,FWVB~V-K163S~R-K2643S~4615450207162449682~DP,FWVB~V-K1663S~R-K4143S~4988773153864880048~DP,FWVB~V-K163S~R-K2643S~5563311426525208573~DP,FWVB~V-K143S~R-K2623S~5330290974871142634~DP,FWVB~V-K463S~R-K2943S~4729161400809722771~DP,FWVB~V-K473S~R-K2953S~4754097142009822062~DP,FWVB~V-K2403S~R-K4883S~5401810795366193685~DP,FWVB~V-K153S~R-K2633S~5384468559580542759~DP,FWVB~V-K133S~R-K2613S~5318331789158859772~DP,FWVB~V-K1093S~R-K3573S~4738106601869918484~DP,FWVB~V-K1093S~R-K3573S~4775801701553878603~DP,FWVB~V-K1093S~R-K3573S~4732732360611106938~DP,FWVB~V-K1093S~R-K3573S~4778286022227403033~DP,FWVB~V-K2083S~R-K4563S~5435045382624363994~DP,FWVB~V-K2083S~R-K4563S~5242842916750666925~DP,FWVB~V-K2083S~R-K4563S~4912783072892831323~DP,FWVB~V-K2083S~R-K4563S~4687151605522873415~DP,FWVB~V-K2083S~R-K4563S~5634194602703056958~DP,FWVB~V-K593S~R-K3073S~5625042714189478940~DP,FWVB~V-K593S~R-K3073S~4840040765573687334~DP,FWVB~V-K603S~R-K3083S~5694344737203567106~DP,FWVB~V-K2393S~R-K4873S~4620979504570756922~DP,FWVB~V-K593S~R-K3073S~5410122665508561633~DP,FWVB~V-K603S~R-K3083S~5014468390007665690~DP,FWVB~V-K1073S~R-K3553S~5233585288374752785~DP,FWVB~V-K953S~R-K3633S~4674360527812832669~DP,FWVB~V-K953S~R-K3433S~5087702146373705981~DP,FWVB~V-K953S~R-K3433S~5142910015534822732~DP,FWVB~V-K963S~R-K3443S~5080512732384776234~DP,FWVB~V-K963S~R-K3443S~5227036118096218347~DP,FWVB~V-K973S~R-K3453S~5448365009177867429~DP,FWVB~V-K1013S~R-K3493S~4904021830209359251~DP,FWVB~V-K953S~R-K3433S~5678013267622520703~DP,FWVB~V-K953S~R-K3433S~5036661921214789266~DP,FWVB~V-K963S~R-K3443S~5533600337297302902~DP,FWVB~V-K963S~R-K3443S~4843922463467905314~DP,FWVB~V-K973S~R-K3453S~5422109685270461796~DP,FWVB~V-K973S~R-K3453S~5510201249316735879~DP,FWVB~V-K1003S~R-K3483S~5345883489919526044~DP,FWVB~V-K1013S~R-K3493S~5749366699607682518~DP,FWVB~V-K1023S~R-K3503S~5395974162027139767~DP,FWVB~V-K473S~R-K2953S~5594862625858924531~DP,FWVB~V-SP02~R-SP02~4848015442334341000~DP,FWVB~V-K473S~R-K2953S~5629665606219325209~DP,FWVB~V-K253S~R-K2733S~5033838081953255687~DP,FWVB~V-K273S~R-K2753S~4679890828975781067~DP,FWVB~V-K2383S~R-K4863S~5037872509385452159~DP,FWVB~V-K2383S~R-K4863S~5375255181374254857~DP,FWVB~V-K2383S~R-K4863S~5659192153935849444~DP,FWVB~V-K473S~R-K2953S~5416161135167168216~DP,FWVB~V-K2013S~R-K4493S~4726386820185329079~DP,FWVB~V-K2023S~R-K4503S~5048794081120001623~DP,FWVB~V-K1493S~R-K3973S~5078575524279271295~DP,FWVB~V-K1473S~R-K3953S~5328165953472204269~DP,FWVB~V-K1463S~R-K3943S~4827314536298448425~DP,FWVB~V-K1453S~R-K3933S~5053527380726940026~DP,FWVB~V-K1443S~R-K3923S~5722736529457112020~DP,FWVB~V-K1443S~R-K3923S~4833248160019911615~DP,FWVB~V-K1433S~R-K3913S~5022762526597417884~DP,FWVB~V-K1423S~R-K3903S~5172442747972094426~DP,FWVB~V-K1423S~R-K3903S~5219159297285087056~DP,FWVB~V-K1403S~R-K3883S~5290157706408162198~DP,FWVB~V-K1403S~R-K3883S~5413829902103673412~DP,FWVB~V-K1403S~R-K3883S~4724782239687086625~DP,FWVB~V-K1403S~R-K3883S~5332535673077775580~DP,FWVB~V-K2143S~R-K4623S~5690996677853628489~DP,FWVB~V-K1423S~R-K3903S~5462869912273155677~DP,FWVB~V-K1433S~R-K3913S~4912417173031909926~DP,FWVB~V-K1423S~R-K3903S~5632830894118958363~DP,FWVB~V-K1443S~R-K3923S~5129892855980697258~DP,FWVB~V-K1433S~R-K3913S~4812170061133334192~DP,FWVB~V-K1453S~R-K3933S~4650690516913118760~DP,FWVB~V-K1473S~R-K3953S~5593258920455231713~DP,FWVB~V-K1473S~R-K3953S~4773249905911243471~DP,FWVB~V-K1493S~R-K3973S~5139255343562953856~DP,FWVB~V-K1503S~R-K3983S~4945961939269554771~DP,FWVB~V-K1533S~R-K4013S~4945833664991839087~DP,FWVB~V-K1503S~R-K3983S~4805781336100450167~DP,FWVB~V-K1523S~R-K4003S~5111577951994515523~DP,FWVB~V-K943S~R-K3423S~5567312130001677534~DP,FWVB~V-K2023S~R-K4503S~5430848372257542560~DP,FWVB~V-K2063S~R-K4543S~5147813561931418786~DP,VENT~V-E~V-E0~5120684848284658605~QM,PUMP~R-E~R-E2~5374020919990423089~RHO,PUMP~R-E~R-E2~5374020919990423089~M,PUMP~R-E~R-E2~5374020919990423089~N,PUMP~R-E~R-E2~5374020919990423089~ETA,PUMP~R-E~R-E2~5374020919990423089~ETAW,PUMP~R-E~R-E2~5374020919990423089~DP,KNOT~R-E-DH~~5037146832979712094~PH,VENT~R-E3~R-E4~5652541284139882253~QM,PGRP~R-E~R-E3~4924988159454251099~RART,PGRP~R-E~R-E3~4924988159454251099~W,PGRP~R-E~R-E3~4924988159454251099~X,PUMP~V-TS-S-WU2~V-TS-S-WU2b~5661833458038115239~RHO,PUMP~V-TS-S-WU2~V-TS-S-WU2b~5661833458038115239~M,PUMP~V-TS-S-WU2~V-TS-S-WU2b~5661833458038115239~N,PUMP~V-TS-S-WU2~V-TS-S-WU2b~5661833458038115239~ETA,PUMP~V-TS-S-WU2~V-TS-S-WU2b~5661833458038115239~ETAW,PUMP~V-TS-S-WU2~V-TS-S-WU2b~5661833458038115239~DP,KNOT~R-TS-DH~~4810663080415972317~PH,FWWU~FWWU_505061~~5140753672436942021~Q,FWWU~FWWU_505061~~5140753672436942021~T2AUS,FWWU~FWWU_505061~~5140753672436942021~T2EIN,FWWU~FWWU_505061~~5140753672436942021~T1EIN,FWWU~FWWU_505061~~5140753672436942021~T1AUS,VENT~V-TS-P~V-TS-P-WU~5257205059759497594~QM,VENT~V-TS-S-WU~V-TS-S-WU2~5397401198360947165~QM,RMES~Last~~4899351962406121892~XA,RMES~Erzeugung~~5554547908379981123~XA,RDIV~WVerlProz~~5105729699655079411~XA,RMES~UWM~~5255082225302217802~XA,RFKT~TVL~~4836221118111466566~XA,RFKT~TRSP~~5737169626127702346~XA,RSLW~NetzTrennEin~~5347287125110176930~XA,SWVT~AT Tag~~5355550039103568011~W
2023-02-12 23:00:00+00:00,b'STAT',"b'SIR 3S 90-15-02-44 3S Consult, 30827 Garbsen...",0,0,1,259,0.421875,0.826000,0,0.000003,0,0,0.0,0.0,68.507812,114,30,0.0,0.0,0.0,5338.179199,975.745972,72.855896,3.684926,0.600001,4.902467,0.781000,10.0,0.000003,4.881368,4.902467,0.0,2.116193,0.781000,0.0,28,13,1,3.016982,4.881368,90.0,287.091522,59.831055,9.866673,0.216283,0.283131,1.562128,1.534682,1.500090,1.500090,1.645129,1.650819,1.567316,1.567316,1.338891,1.334246,1.334246,1.334246,1.357544,1.346191,1.331172,1.346191,1.345438,1.343815,1.379869,1.379869,1.424017,1.444013,1.379869,1.363768,1.445711,1.486872,1.468655,1.468655,1.467943,1.467943,1.472395,1.357544,1.357544,1.398005,1.424017,1.444013,1.444013,1.467943,1.444013,1.444013,1.445711,1.445711,1.483802,1.468655,1.467943,1.467943,1.652783,1.686288,1.686288,1.686288,1.730199,1.730199,1.730199,1.754024,1.682265,1.627730,1.623596,1.730199,1.730199,1.623596,1.777303,1.734113,1.753635,1.714682,1.714682,1.686288,1.519881,1.669239,1.584963,1.592160,1.592160,1.559984,1.521728,1.521728,1.637048,1.637048,1.598284,1.592160,1.637048,1.598284,1.598284,1.598284,1.566656,1.577368,1.682265,1.650043,1.650043,1.648810,1.648810,1.648810,1.650043,1.650043,1.574590,1.542218,1.682265,1.650043,1.650043,1.627730,1.650043,1.650043,1.630383,1.648810,1.641663,1.641663,1.641663,1.606455,1.534682,1.534682,1.489102,1.563378,1.545948,1.577368,1.562651,1.563378,1.440225,1.499495,1.499495,1.620642,1.641155,1.669591,1.669591,1.602790,1.602790,1.544558,1.558364,1.509137,1.509137,1.509137,1.558364,1.489102,1.640048,1.627730,1.640466,1.640466,1.640466,1.640466,1.669591,1.669591,1.669591,1.669591,1.692422,1.611863,1.611863,1.580570,1.583802,1.585436,1.558364,1.558364,1.489102,1.519881,1.519881,1.583943,1.519881,1.583943,1.592104,1.615634,1.637201,1.637201,1.653427,1.652783,1.652783,1.679202,1.679202,1.679202,1.651447,1.651447,1.583424,1.583424,1.583424,1.583424,1.583424,1.521728,1.583424,1.335192,1.652783,1.679202,1.699483,1.650819,1.338891,1.601432,1.601432,1.601432,1.601432,1.534154,1.534154,1.534154,1.534154,1.534154,1.645129,1.645129,1.614705,1.650336,1.645129,1.614705,1.648810,1.734889,1.711798,1.711798,1.692422,1.692422,1.667628,1.656252,1.711798,1.711798,1.692422,1.692422,1.667628,1.667628,1.654575,1.656252,1.611863,1.679202,1.500000,1.679202,1.584963,1.637048,1.651447,1.651447,1.651447,1.679202,1.671126,1.686288,0.678945,0.708451,0.717692,0.740269,0.772847,0.772847,0.838474,0.806022,0.806022,0.848033,0.848033,0.848033,0.848033,0.811261,0.806022,0.838474,0.806022,0.772847,0.838474,0.740269,0.708451,0.708451,0.678945,0.664446,0.600001,0.664446,0.619831,1.728623,1.686288,1.734113,287.091522,983.784485,79.747643,750.106018,0.670523,0.705814,1.902467,3.0,287.091522,b'SP ',1.5,1.500000,972.200012,8.407589,668.398865,0.628501,0.661580,0.907239,3.0,708.314880,80.0,59.880859,89.811798,60.939499,21.072384,30.267319,9.158356,10.082892,0.021451,287.091583,90.0,60.0,0.0,-9.7

### sir3stoolkit MX read (WIP, standalone, not yet wired into dataframe generation)

In [12]:
mx1_path = r"C:\Users\aUsername\3S\sir3stoolkit\docs\source\tutorials\SIR3S_Model_Mantle\Tutorial051_Assets\WDToolkit_Tutorial51_Model\B1\V0\BZ1\M-1-0-1.1.MX1"

In [13]:
s3s.GetTimeStamps()

(['2023-02-13 00:00:00.000 +01:00',
  '2023-02-13 01:00:00.000 +01:00',
  '2023-02-13 02:00:00.000 +01:00',
  '2023-02-13 03:00:00.000 +01:00',
  '2023-02-13 04:00:00.000 +01:00',
  '2023-02-13 05:00:00.000 +01:00',
  '2023-02-13 06:00:00.000 +01:00',
  '2023-02-13 07:00:00.000 +01:00',
  '2023-02-13 08:00:00.000 +01:00',
  '2023-02-13 09:00:00.000 +01:00',
  '2023-02-13 10:00:00.000 +01:00',
  '2023-02-13 11:00:00.000 +01:00',
  '2023-02-13 12:00:00.000 +01:00',
  '2023-02-13 13:00:00.000 +01:00',
  '2023-02-13 14:00:00.000 +01:00',
  '2023-02-13 15:00:00.000 +01:00',
  '2023-02-13 16:00:00.000 +01:00',
  '2023-02-13 17:00:00.000 +01:00',
  '2023-02-13 18:00:00.000 +01:00',
  '2023-02-13 19:00:00.000 +01:00',
  '2023-02-13 20:00:00.000 +01:00',
  '2023-02-13 21:00:00.000 +01:00',
  '2023-02-13 22:00:00.000 +01:00',
  '2023-02-13 23:00:00.000 +01:00',
  '2023-02-14 00:00:00.000 +01:00'],
 '2023-02-13 00:00:00.000 +01:00',
 '',
 '')

In [14]:
df_mx = s3s.read_mx_results(mx1_filepath=mx1_path
                            ,timestamps=["2023-02-13 17:00:00.000 +01:00", "2023-02-13 22:00:00.000 +01:00"])

[2026-08-12 11:59:51,894] INFO in sir3stoolkit.mantle.dataframes: [mx read] Reading MX results from: C:\Users\aUsername\3S\sir3stoolkit\docs\source\tutorials\SIR3S_Model_Mantle\Tutorial051_Assets\WDToolkit_Tutorial51_Model\B1\V0\BZ1\M-1-0-1.1.MX1
[2026-08-12 11:59:51,896] INFO in sir3stoolkit.mantle.dataframes: [mx helpers] Initializing MX read helpers ...
[2026-08-12 11:59:51,898] INFO in sir3stoolkit.mantle.dataframes: [mx helpers] Parsing MX1: C:\Users\aUsername\3S\sir3stoolkit\docs\source\tutorials\SIR3S_Model_Mantle\Tutorial051_Assets\WDToolkit_Tutorial51_Model\B1\V0\BZ1\M-1-0-1.1.MX1
[2026-08-12 11:59:51,927] INFO in sir3stoolkit.mantle.dataframes: [mx helpers] Parsed MX1 successfully. Shape: (509, 27)
[2026-08-12 11:59:51,927] INFO in sir3stoolkit.mantle.dataframes: [mx helpers] Parsing MX2: C:\Users\aUsername\3S\sir3stoolkit\docs\source\tutorials\SIR3S_Model_Mantle\Tutorial051_Assets\WDToolkit_Tutorial51_Model\B1\V0\BZ1\M-1-0-1.MX2
[2026-08-12 11:59:51,938] INFO in sir3stoolkit.mantle.dataframes: [mx helpers] Parsed MX2 successfully. Shape: (29, 7)
[2026-08-12 11:59:51,938] INFO in sir3stoolkit.mantle.dataframes: [mx helpers] Building MX record unpack format ...
[2026-08-12 11:59:51,950] INFO in sir3stoolkit.mantle.dataframes: [mx helpers] Built unpack format successfully. Record length: 210104 bytes
[2026-08-12 11:59:51,953] INFO in sir3stoolkit.mantle.dataframes: [mx helpers] Building MX unpack layout ...
[2026-08-12 11:59:52,012] INFO in sir3stoolkit.mantle.dataframes: [mx helpers] Built MX unpack layout successfully.
[2026-08-12 11:59:52,013] INFO in sir3stoolkit.mantle.dataframes: [mx helpers] Initialized. MX1 rows: 509, MX2 rows: 29, non-vector channels: 332, vector channels: 176
[2026-08-12 11:59:52,018] INFO in sir3stoolkit.mantle.dataframes: [mx read] Timestamp filter active: 2 requested timestamp(s).
[2026-08-12 11:59:52,076] INFO in sir3stoolkit.mantle.dataframes: [mx read] Done. Records scanned: 28. Records decoded: 2. Unique timestamps: 2.

In [15]:
df_mx.head()

,ALLG~~~5597593673700177669~SNAPSHOTTYPE,ALLG~~~5597593673700177669~CVERSO,ALLG~~~5597593673700177669~EXSTAT,ALLG~~~5597593673700177669~NFEHL,ALLG~~~5597593673700177669~NWARN,ALLG~~~5597593673700177669~NMELD,ALLG~~~5597593673700177669~CPUTIME,ALLG~~~5597593673700177669~USRTIME,ALLG~~~5597593673700177669~NPGREST,ALLG~~~5597593673700177669~NETZABN,ALLG~~~5597593673700177669~NFVHYUV,ALLG~~~5597593673700177669~NFVTHUV,ALLG~~~5597593673700177669~MFVHYUV,ALLG~~~5597593673700177669~MFVTHUV,ALLG~~~5597593673700177669~TVMINMAX,ALLG~~~5597593673700177669~ITERHY,ALLG~~~5597593673700177669~JWARN,ALLG~~~5597593673700177669~NETZABNEXITS,ALLG~~~5597593673700177669~LINEPACKRATE,ALLG~~~5597593673700177669~LINEPACKGES,ALLG~~~5597593673700177669~LINEPACKGEOM,ALLG~~~5597593673700177669~RHOAV,ALLG~~~5597593673700177669~TAV,ALLG~~~5597593673700177669~PAV,ALLG~~~5597593673700177669~FWVB_DPHMIN,ALLG~~~5597593673700177669~KNOT_PHMAX,ALLG~~~5597593673700177669~KNOT_PHMIN,ALLG~~~5597593673700177669~FWVB_TVLMIN,ALLG~~~5597593673700177669~NETZBEZ,ALLG~~~5597593673700177669~KNOT_PHMAX_V,ALLG~~~5597593673700177669~KNOT_PHMAX_R,ALLG~~~5597593673700177669~KNOT_PHMAX_U,ALLG~~~5597593673700177669~KNOT_PHMIN_V,ALLG~~~5597593673700177669~KNOT_PHMIN_R,ALLG~~~5597593673700177669~KNOT_PHMIN_U,ALLG~~~5597593673700177669~ITERTH,ALLG~~~5597593673700177669~INTERAKTTH,ALLG~~~5597593673700177669~INTERAKTRG,KNOT~R-E~~4945502875946918021~PH,KNOT~V-E~~5364585352767333609~PH,KNOT~V-E~~5364585352767333609~T,VENT~R-E0~R-E~5078909058477631059~QM,KNOT~R-E~~4945502875946918021~T,WBLZ~WärmeblnzGes~~5747928298316755683~WVB,WBLZ~WärmeblnzGes~~5747928298316755683~WVERL,FWVB~V-K2153S~R-K4633S~4695691920575201490~LFT,FWVB~V-K2243S~R-K4723S~4612643650175000934~DP,FWVB~V-K333S~R-K2813S~5298892186072792581~DP,FWVB~V-K1393S~R-K3873S~5641820391023802273~DP,FWVB~V-K1393S~R-K3873S~5714834959169623562~DP,FWVB~V-K593S~R-K3073S~5539308064883517142~DP,FWVB~V-K153S~R-K2633S~4851778549814053310~DP,FWVB~V-K2263S~R-K4743S~5095755403689234488~DP,FWVB~V-K2263S~R-K4743S~4754662858150981800~DP,FWVB~V-K133S~R-K2613S~4831899581981959889~DP,FWVB~V-SP01~R-SP01~5373061288922912729~DP,FWVB~V-SP01~R-SP01~5338005695177201668~DP,FWVB~V-SP01~R-SP01~5103671514823328293~DP,FWVB~V-K123S~R-K2603S~5568194212677879165~DP,FWVB~V-K1363S~R-K3843S~5534236886775923535~DP,FWVB~V-K1373S~R-K3853S~5054661805697996469~DP,FWVB~V-K1363S~R-K3843S~4677484876769683069~DP,FWVB~V-K1343S~R-K3823S~5331382729720004878~DP,FWVB~V-K1323S~R-K3803S~5320145816789148184~DP,FWVB~V-K73S~R-K2553S~4660745360789977502~DP,FWVB~V-K73S~R-K2553S~5475433067817926464~DP,FWVB~V-K63S~R-K2543S~5088507410302060583~DP,FWVB~V-K23S~R-K2503S~4799202816710088269~DP,FWVB~V-K73S~R-K2553S~5567370826017196953~DP,FWVB~V-K1313S~R-K3793S~4721603020200203929~DP,FWVB~V-K1243S~R-K3723S~5539118071732060322~DP,FWVB~V-K1283S~R-K3763S~5433812588779537970~DP,FWVB~V-K1303S~R-K3783S~4982647601065704474~DP,FWVB~V-K1303S~R-K3783S~4758534110963451621~DP,FWVB~V-K13S~R-K2493S~5157987375362402948~DP,FWVB~V-K13S~R-K2493S~5572700189436507358~DP,FWVB~V-K133S~R-K2623S~5042957248574195254~DP,FWVB~V-K123S~R-K2603S~5620374956890186419~DP,FWVB~V-K123S~R-K2603S~5642186467419772313~DP,FWVB~V-K113S~R-K2593S~4952675334963811549~DP,FWVB~V-K63S~R-K2543S~5289349232690798866~DP,FWVB~V-K23S~R-K2503S~5263894803742270480~DP,FWVB~V-K23S~R-K2503S~5258191418983486434~DP,FWVB~V-K13S~R-K2493S~5219695668506679887~DP,FWVB~V-K23S~R-K2503S~5089681968228574805~DP,FWVB~V-K23S~R-K2503S~4723552478525716099~DP,FWVB~V-K1243S~R-K3723S~4717900447084130786~DP,FWVB~V-K1243S~R-K3723S~4680566654399387170~DP,FWVB~V-K1273S~R-K3753S~4774089356071680115~DP,FWVB~V-K1303S~R-K3783S~5483836906626806693~DP,FWVB~V-K13S~R-K2493S~5723652079410431099~DP,FWVB~V-K13S~R-K2493S~5152070634362289135~DP,FWVB~V-K463S~R-K2943S~4715437119287917203~DP,FWVB~V-K2023S~R-K4503S~5429690733112787259~DP,FWVB~V-K2023S~R-K4503S~5470212073687668936~DP,FWVB~V-K2023S~R-K4503S~4690848713916516887~DP,FWVB~V-K583S~R-K3063S~5210301978863275664~DP,FWVB~V-K583S~R-K3063S~4769972484103895237~DP,FWVB~V-K583S~R-K3063S~4839284960010591311~DP,FWVB~V-K2173S~R-K4653S~5238469959575677978~DP,FWVB~V-K573S~R-K3053S~5378395521233234009~DP,FWVB~V-K2153S~R-K4633S~5272427879633450297~DP,FWVB~V-K1163S~R-K3643S~5563426535048622787~DP,FWVB~V-K583S~R-K3063S~5708564737898353551~DP,FWVB~V-K583S~R-K3063S~5646104354697048422~DP,FWVB~V-K1163S~R-K3643S~4998245026021181527~DP,FWVB~V-K2063S~R-K3063S~5030808405918905856~DP,FWVB~V-K2063S~R-K4543S~5589819464555437381~DP,FWVB~V-K933S~R-K3413S~5021149544911429814~DP,FWVB~V-K2073S~R-K4553S~5483428144944113828~DP,FWVB~V-K2073S~R-K4553S~5608524552763679614~DP,FWVB~V-K2023S~R-K4503S~5626371875066735675~DP,FWVB~V-K403S~R-K2883S~5421154557729864641~DP,FWVB~V-K2003S~R-K4483S~4808379698586732872~DP,FWVB~V-K253S~R-K2733S~4754045271859275254~DP,FWVB~V-K1643S~R-K4123S~4804522946718449543~DP,FWVB~V-K1643S~R-K4123S~5397095414062959706~DP,FWVB~V-K1653S~R-K4133S~4972542528251576003~DP,FWVB~V-K1663S~R-K4143S~4841968208579971744~DP,FWVB~V-K1663S~R-K4143S~4790880210700946505~DP,FWVB~V-K273S~R-K2753S~5134226995532837471~DP,FWVB~V-K273S~R-K2753S~5199665792777686632~DP,FWVB~V-K263S~R-K2743S~4829820734742795813~DP,FWVB~V-K1643S~R-K4123S~5473902379470916704~DP,FWVB~V-K273S~R-K2753S~5095071279723776262~DP,FWVB~V-K263S~R-K2743S~4969795535504580282~DP,FWVB~V-K263S~R-K2743S~5389503305937461852~DP,FWVB~V-K263S~R-K2743S~5491075003903254860~DP,FWVB~V-K233S~R-K2713S~5333950106019937551~DP,FWVB~V-K243S~R-K2723S~5078322764546640049~DP,FWVB~V-K573S~R-K3053S~5074136990830026951~DP,FWVB~V-K1083S~R-K3563S~5721943751421394086~DP,FWVB~V-K1083S~R-K3563S~4617599012360428982~DP,FWVB~V-K1073S~R-K3553S~5143587653110554807~DP,FWVB~V-K1073S~R-K3553S~5155974252610494227~DP,FWVB~V-K1073S~R-K3553S~5507469098629391620~DP,FWVB~V-K1083S~R-K3563S~4644294207793899393~DP,FWVB~V-K1083S~R-K3563S~4729135819215267446~DP,FWVB~V-K313S~R-K2793S~5397363169018116905~DP,FWVB~V-K323S~R-K2803S~5293083471824257348~DP,FWVB~V-K573S~R-K3053S~4692947232485098213~DP,FWVB~V-K1083S~R-K3563S~4840514655814345420~DP,FWVB~V-K1083S~R-K3563S~4984259280617000809~DP,FWVB~V-K2153S~R-K4633S~5450848705169565418~DP,FWVB~V-K1083S~R-K3563S~5013175068886361021~DP,FWVB~V-K1083S~R-K3563S~5129945735358846816~DP,FWVB~V-K1123S~R-K3603S~5641063690842961168~DP,FWVB~V-K1073S~R-K3553S~5166680757495237751~DP,FWVB~V-K1063S~R-K3543S~4614551030187170583~DP,FWVB~V-K1063S~R-K3543S~5049615340607119167~DP,FWVB~V-K1063S~R-K3543S~5182171757783007257~DP,FWVB~V-K293S~R-K2773S~4699379554487286912~DP,FWVB~V-K333S~R-K2813S~5493473140425149473~DP,FWVB~V-K333S~R-K2813S~5229547090188049969~DP,FWVB~V-K03S~R-K2483S~5078971821722268135~DP,FWVB~V-K1613S~R-K4093S~4838424991008300464~DP,FWVB~V-K1603S~R-K4083S~5119436336432835935~DP,FWVB~V-K243S~R-K2723S~5069875460823955334~DP,FWVB~V-K1623S~R-K4103S~4612562908060328263~DP,FWVB~V-K1613S~R-K4093S~4968006119183593408~DP,FWVB~V-K1603S~R-K4113S~4780867592274315225~DP,FWVB~V-K1633S~R-K4113S~4689962447077782592~DP,FWVB~V-K1633S~R-K4113S~4907629360497270624~DP,FWVB~V-K1103S~R-K3583S~5114532772926850507~DP,FWVB~V-K1143S~R-K3623S~4957429172484513667~DP,FWVB~V-K1153S~R-K3633S~5683164004528603492~DP,FWVB~V-K1153S~R-K3633S~4753737713576765068~DP,FWVB~V-K1033S~R-K3513S~5511883908108493205~DP,FWVB~V-K1033S~R-K3513S~4985463247915540404~DP,FWVB~V-K1213S~R-K3663S~5696463829656272308~DP,FWVB~V-K1223S~R-K3703S~4879060213783619417~DP,FWVB~V-K1233S~R-K3713S~5328839321384231626~DP,FWVB~V-K1233S~R-K3713S~4908302009467601605~DP,FWVB~V-K1233S~R-K3713S~5081759066536254041~DP,FWVB~V-K1223S~R-K3703S~4920414355371836818~DP,FWVB~V-K03S~R-K2483S~4953528746012203881~DP,FWVB~V-K1133S~R-K3613S~5514426350058393064~DP,FWVB~V-K2153S~R-K4633S~4695691920575201490~DP,FWVB~V-K1173S~R-K3653S~5686938269985987108~DP,FWVB~V-K1173S~R-K3653S~5608013454113942505~DP,FWVB~V-K1173S~R-K3653S~5554180086935671036~DP,FWVB~V-K1173S~R-K3653S~4715343979099977320~DP,FWVB~V-K1153S~R-K3633S~5276185429031066619~DP,FWVB~V-K1153S~R-K3633S~5752171491358190657~DP,FWVB~V-K1153S~R-K3633S~5044737621363717731~DP,FWVB~V-K1153S~R-K3633S~4959178524702114605~DP,FWVB~V-K963S~R-K3443S~5184692294783766508~DP,FWVB~V-K1023S~R-K3503S~5015574389658457843~DP,FWVB~V-K1023S~R-K3503S~5340682804823281975~DP,FWVB~V-K1183S~R-K3663S~4773718045303625562~DP,FWVB~V-K1203S~R-K3683S~4611752310942477664~DP,FWVB~V-K1213S~R-K3693S~5649394575722244706~DP,FWVB~V-K1223S~R-K3703S~5683145831265886679~DP,FWVB~V-K1223S~R-K3703S~5347934852716104645~DP,FWVB~V-K03S~R-K2483S~5338581593552364614~DP,FWVB~V-K403S~R-K2883S~4747253770471595859~DP,FWVB~V-K403S~R-K2883S~5005156965723780226~DP,FWVB~V-K413S~R-K2893S~4737813668193434747~DP,FWVB~V-K403S~R-K2883S~4824230293599010462~DP,FWVB~V-K413S~R-K2893S~4961446825744614653~DP,FWVB~V-K423S~R-K2903S~4794000986315043981~DP,FWVB~V-K433S~R-K2913S~5663966403597611254~DP,FWVB~V-K443S~R-K2923S~5285271495094652658~DP,FWVB~V-K443S~R-K2923S~5010483887057780845~DP,FWVB~V-K453S~R-K2933S~5153454494023353435~DP,FWVB~V-K463S~R-K2943S~5577210775620233409~DP,FWVB~V-K463S~R-K2943S~4884816399211992951~DP,FWVB~V-K473S~R-K2953S~5368434258234128749~DP,FWVB~V-K473S~R-K2953S~4934825369837329981~DP,FWVB~V-K473S~R-K2953S~4716889123169234975~DP,FWVB~V-K2383S~R-K4863S~4804005204522723919~DP,FWVB~V-K2383S~R-K4863S~5204002376528007016~DP,FWVB~V-K163S~R-K2643S~5118203249310421888~DP,FWVB~V-K163S~R-K2643S~4869838397682489649~DP,FWVB~V-K163S~R-K2643S~5055469814130651373~DP,FWVB~V-K163S~R-K2643S~4889571787974482626~DP,FWVB~V-K163S~R-K2643S~4615450207162449682~DP,FWVB~V-K1663S~R-K4143S~4988773153864880048~DP,FWVB~V-K163S~R-K2643S~5563311426525208573~DP,FWVB~V-K143S~R-K2623S~5330290974871142634~DP,FWVB~V-K463S~R-K2943S~4729161400809722771~DP,FWVB~V-K473S~R-K2953S~4754097142009822062~DP,FWVB~V-K2403S~R-K4883S~5401810795366193685~DP,FWVB~V-K153S~R-K2633S~5384468559580542759~DP,FWVB~V-K133S~R-K2613S~5318331789158859772~DP,FWVB~V-K1093S~R-K3573S~4738106601869918484~DP,FWVB~V-K1093S~R-K3573S~4775801701553878603~DP,FWVB~V-K1093S~R-K3573S~4732732360611106938~DP,FWVB~V-K1093S~R-K3573S~4778286022227403033~DP,FWVB~V-K2083S~R-K4563S~5435045382624363994~DP,FWVB~V-K2083S~R-K4563S~5242842916750666925~DP,FWVB~V-K2083S~R-K4563S~4912783072892831323~DP,FWVB~V-K2083S~R-K4563S~4687151605522873415~DP,FWVB~V-K2083S~R-K4563S~5634194602703056958~DP,FWVB~V-K593S~R-K3073S~5625042714189478940~DP,FWVB~V-K593S~R-K3073S~4840040765573687334~DP,FWVB~V-K603S~R-K3083S~5694344737203567106~DP,FWVB~V-K2393S~R-K4873S~4620979504570756922~DP,FWVB~V-K593S~R-K3073S~5410122665508561633~DP,FWVB~V-K603S~R-K3083S~5014468390007665690~DP,FWVB~V-K1073S~R-K3553S~5233585288374752785~DP,FWVB~V-K953S~R-K3633S~4674360527812832669~DP,FWVB~V-K953S~R-K3433S~5087702146373705981~DP,FWVB~V-K953S~R-K3433S~5142910015534822732~DP,FWVB~V-K963S~R-K3443S~5080512732384776234~DP,FWVB~V-K963S~R-K3443S~5227036118096218347~DP,FWVB~V-K973S~R-K3453S~5448365009177867429~DP,FWVB~V-K1013S~R-K3493S~4904021830209359251~DP,FWVB~V-K953S~R-K3433S~5678013267622520703~DP,FWVB~V-K953S~R-K3433S~5036661921214789266~DP,FWVB~V-K963S~R-K3443S~5533600337297302902~DP,FWVB~V-K963S~R-K3443S~4843922463467905314~DP,FWVB~V-K973S~R-K3453S~5422109685270461796~DP,FWVB~V-K973S~R-K3453S~5510201249316735879~DP,FWVB~V-K1003S~R-K3483S~5345883489919526044~DP,FWVB~V-K1013S~R-K3493S~5749366699607682518~DP,FWVB~V-K1023S~R-K3503S~5395974162027139767~DP,FWVB~V-K473S~R-K2953S~5594862625858924531~DP,FWVB~V-SP02~R-SP02~4848015442334341000~DP,FWVB~V-K473S~R-K2953S~5629665606219325209~DP,FWVB~V-K253S~R-K2733S~5033838081953255687~DP,FWVB~V-K273S~R-K2753S~4679890828975781067~DP,FWVB~V-K2383S~R-K4863S~5037872509385452159~DP,FWVB~V-K2383S~R-K4863S~5375255181374254857~DP,FWVB~V-K2383S~R-K4863S~5659192153935849444~DP,FWVB~V-K473S~R-K2953S~5416161135167168216~DP,FWVB~V-K2013S~R-K4493S~4726386820185329079~DP,FWVB~V-K2023S~R-K4503S~5048794081120001623~DP,FWVB~V-K1493S~R-K3973S~5078575524279271295~DP,FWVB~V-K1473S~R-K3953S~5328165953472204269~DP,FWVB~V-K1463S~R-K3943S~4827314536298448425~DP,FWVB~V-K1453S~R-K3933S~5053527380726940026~DP,FWVB~V-K1443S~R-K3923S~5722736529457112020~DP,FWVB~V-K1443S~R-K3923S~4833248160019911615~DP,FWVB~V-K1433S~R-K3913S~5022762526597417884~DP,FWVB~V-K1423S~R-K3903S~5172442747972094426~DP,FWVB~V-K1423S~R-K3903S~5219159297285087056~DP,FWVB~V-K1403S~R-K3883S~5290157706408162198~DP,FWVB~V-K1403S~R-K3883S~5413829902103673412~DP,FWVB~V-K1403S~R-K3883S~4724782239687086625~DP,FWVB~V-K1403S~R-K3883S~5332535673077775580~DP,FWVB~V-K2143S~R-K4623S~5690996677853628489~DP,FWVB~V-K1423S~R-K3903S~5462869912273155677~DP,FWVB~V-K1433S~R-K3913S~4912417173031909926~DP,FWVB~V-K1423S~R-K3903S~5632830894118958363~DP,FWVB~V-K1443S~R-K3923S~5129892855980697258~DP,FWVB~V-K1433S~R-K3913S~4812170061133334192~DP,FWVB~V-K1453S~R-K3933S~4650690516913118760~DP,FWVB~V-K1473S~R-K3953S~5593258920455231713~DP,FWVB~V-K1473S~R-K3953S~4773249905911243471~DP,FWVB~V-K1493S~R-K3973S~5139255343562953856~DP,FWVB~V-K1503S~R-K3983S~4945961939269554771~DP,FWVB~V-K1533S~R-K4013S~4945833664991839087~DP,FWVB~V-K1503S~R-K3983S~4805781336100450167~DP,FWVB~V-K1523S~R-K4003S~5111577951994515523~DP,FWVB~V-K943S~R-K3423S~5567312130001677534~DP,FWVB~V-K2023S~R-K4503S~5430848372257542560~DP,FWVB~V-K2063S~R-K4543S~5147813561931418786~DP,VENT~V-E~V-E0~5120684848284658605~QM,PUMP~R-E~R-E2~5374020919990423089~RHO,PUMP~R-E~R-E2~5374020919990423089~M,PUMP~R-E~R-E2~5374020919990423089~N,PUMP~R-E~R-E2~5374020919990423089~ETA,PUMP~R-E~R-E2~5374020919990423089~ETAW,PUMP~R-E~R-E2~5374020919990423089~DP,KNOT~R-E-DH~~5037146832979712094~PH,VENT~R-E3~R-E4~5652541284139882253~QM,PGRP~R-E~R-E3~4924988159454251099~RART,PGRP~R-E~R-E3~4924988159454251099~W,PGRP~R-E~R-E3~4924988159454251099~X,PUMP~V-TS-S-WU2~V-TS-S-WU2b~5661833458038115239~RHO,PUMP~V-TS-S-WU2~V-TS-S-WU2b~5661833458038115239~M,PUMP~V-TS-S-WU2~V-TS-S-WU2b~5661833458038115239~N,PUMP~V-TS-S-WU2~V-TS-S-WU2b~5661833458038115239~ETA,PUMP~V-TS-S-WU2~V-TS-S-WU2b~5661833458038115239~ETAW,PUMP~V-TS-S-WU2~V-TS-S-WU2b~5661833458038115239~DP,KNOT~R-TS-DH~~4810663080415972317~PH,FWWU~FWWU_505061~~5140753672436942021~Q,FWWU~FWWU_505061~~5140753672436942021~T2AUS,FWWU~FWWU_505061~~5140753672436942021~T2EIN,FWWU~FWWU_505061~~5140753672436942021~T1EIN,FWWU~FWWU_505061~~5140753672436942021~T1AUS,VENT~V-TS-P~V-TS-P-WU~5257205059759497594~QM,VENT~V-TS-S-WU~V-TS-S-WU2~5397401198360947165~QM,RMES~Last~~4899351962406121892~XA,RMES~Erzeugung~~5554547908379981123~XA,RDIV~WVerlProz~~5105729699655079411~XA,RMES~UWM~~5255082225302217802~XA,RFKT~TVL~~4836221118111466566~XA,RFKT~TRSP~~5737169626127702346~XA,RSLW~NetzTrennEin~~5347287125110176930~XA,SWVT~AT Tag~~5355550039103568011~W,FWES~*~*~*~DPH,FWES~*~*~*~IAKTIV,FWES~*~*~*~IHYTYP,FWES~*~*~*~ITHTYP,FWES~*~*~*~QM,FWES~*~*~*~TI,FWES~*~*~*~TK,FWES~*~*~*~W,FWES~*~*~*~WSOLL,FWWU~*~*~*~Q,FWWU~*~*~*~T1EIN,FWWU~*~*~*~T1AUS,FWWU~*~*~*~T2EIN,FWWU~*~*~*~T2AUS,FWWU~*~*~*~RE1,FWWU~*~*~*~RE2,FWWU~*~*~*~INDUV,FWWU~*~*~*~IAKTIV,KLAP~*~*~*~IAKTIV,KLAP~*~*~*~PHI,KLAP~*~*~*~PHR,KLAP~*~*~*~QM,KLAP~*~*~*~V,KLAP~*~*~*~ZETA,LFKT~*~*~*~FWVB_DPHMIN,LFKT~*~*~*~FWVB_TVLMIN,LFKT~*~*~*~NFVHYUV,LFKT~*~*~*~NFVTHUV,LFKT~*~*~*~MFVHYUV,LFKT~*~*~*~MFVTHUV,LFKT~*~*~*~TVMINMAX,PGRP~*~*~*~BK,PGRP~*~*~*~DPH,PGRP~*~*~*~ETA,PGRP~*~*~*~IAKTIV,PGRP~*~*~*~INDSTD,PGRP~*~*~*~IZSTPG,PGRP~*~*~*~NPUMPIST,PGRP~*~*~*~PE,PGRP~*~*~*~QM,PGRP~*~*~*~RART,PGRP~*~*~*~W,PGRP~*~*~*~X,PGRP_PUMP~*~*~*~IAKTIV,PUMP~*~*~*~DPH,PUMP~*~*~*~EINAUS,PUMP~*~*~*~ETA,PUMP~*~*~*~IAKTIV,PUMP~*~*~*~IND,PUMP~*~*~*~N,PUMP~*~*~*~PE,PUMP~*~*~*~QM,PUMP~*~*~*~RHO,PUMP~*~*~*~STOERUNG,PUMP~*~*~*~RCPU_W,PUMP~*~*~*~RCPU_X,PUMP~*~*~*~NPSH,PUMP~*~*~*~NPSHMIN,PUMP~*~*~*~NMINMAXDIF,PUMP~*~*~*~QN0,QVAR~*~*~*~FWVB_DPHMIN,QVAR~*~*~*~FWVB_TVLMIN,QVAR~*~*~*~NFVHYUV,QVAR~*~*~*~NFVTHUV,QVAR~*~*~*~MFVHYUV,QVAR~*~*~*~MFVTHUV,QVAR~*~*~*~TVMINMAX,RART~*~*~*~RCPL,RART~*~*~*~W,RCPL~*~*~*~KNOT,RCPL~*~*~*~W,RCPL~*~*~*~X,RCPL_ROWT~*~*~*~W,RCPL_ROWT~*~*~*~X,RDIV~*~*~*~XA,RDIV~*~*~*~XE1,RDIV~*~*~*~XE2,RFKT~*~*~*~XA,RFKT~*~*~*~XE,RLVG~*~*~*~XA,RLVG~*~*~*~XE1,RLVG~*~*~*~XE2,RMES~*~*~*~XA,RMES~*~*~*~XM,RMES~*~*~*~XU,RSLW~*~*~*~SWVT,RSLW~*~*~*~WAKT,RSLW~*~*~*~XA,RSTN~*~*~*~XE1,VENT~*~*~*~AUFZU,VENT~*~*~*~PHI,VENT~*~*~*~PHR,VENT~*~*~*~QM,VENT~*~*~*~V,VENT~*~*~*~ZETA,WBLZ~*~*~*~WES,WBLZ~*~*~*~WRAND,WBLZ~*~*~*~WSPEI,WBLZ~*~*~*~WVB,WBLZ~*~*~*~WVERL,FWES~*~*~*~V,FWVB~*~*~*~DPH,FWVB~*~*~*~IAKTIV,FWVB~*~*~*~INDUV,FWVB~*~*~*~LFH,FWVB~*~*~*~LFT,FWVB~*~*~*~M,FWVB~*~*~*~PHIRL,FWVB~*~*~*~PHIVL,FWVB~*~*~*~QM,FWVB~*~*~*~TI,FWVB~*~*~*~TK,FWVB~*~*~*~TVMIN,FWVB~*~*~*~W,FWVB~*~*~*~WSOLL,KNOT~*~*~*~DP,KNOT~*~*~*~DPH,KNOT~*~*~*~H,KNOT~*~*~*~IAKTIV,KNOT~*~*~*~LFAKTAKT,KNOT~*~*~*~P,KNOT~*~*~*~PDAMPF,KNOT~*~*~*~PH,KNOT~*~*~*~PH_EIN,KNOT~*~*~*~PH_MIN,KNOT~*~*~*~QM,KNOT~*~*~*~RHO,KNOT~*~*~*~T,KNOT~*~*~*~VOLD,KNOT~*~*~*~BCIND,KNOT~*~*~*~PHMINMAXDIF,KNOT~*~*~*~TTR,ROHR~*~*~*~A,ROHR~*~*~*~DWVERL,ROHR~*~*~*~IAKTIV,ROHR~*~*~*~IRTRENN,ROHR~*~*~*~PHR,ROHR~*~*~*~VOLDA,ROHR~*~*~*~VAV,ROHR~*~*~*~QMAV,ROHR~*~*~*~JV,ROHR~*~*~*~DWVERLABS,ROHR~*~*~*~PMIN,ROHR~*~*~*~PDAMPF,ROHR~*~*~*~TTRVEC,ROHR~*~*~*~DTTR,ROHR~*~*~*~WVL,KNOT~*~*~*~HMAX_INST,KNOT~*~*~*~HMIN_INST,KNOT~*~*~*~PMAX_INST,KNOT~*~*~*~PMIN_INST,ROHR~*~*~*~VI,ROHR~*~*~*~VK,ROHR~*~*~*~QMI,ROHR~*~*~*~QMK,ROHR~*~*~*~SVEC,ROHR~*~*~*~ZVEC,ROHR~*~*~*~PVEC,ROHR~*~*~*~MVEC,ROHR~*~*~*~TVEC,ROHR~*~*~*~RHOVEC,ROHR~*~*~*~PVECMAX_INST,ROHR~*~*~*~PVECMIN_INST,VENT~*~*~*~IAKTIV,ROHR~*~*~*~TI,ROHR~*~*~*~TK,ROHR~*~*~*~RHOI,ROHR~*~*~*~RHOK,FWVB~*~*~*~RHOI,FWVB~*~*~*~RHOK,VENT~*~*~*~RHO,VENT~*~*~*~DH,FWVB~*~*~*~DP,FWVB~*~*~*~DH,FWVB~*~*~*~MHYUV,FWVB~*~*~*~MTHUV
TIMESTAMP,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

In [16]:
df_mx.columns

Index(['ALLG~~~5597593673700177669~SNAPSHOTTYPE',
       'ALLG~~~5597593673700177669~CVERSO',
       'ALLG~~~5597593673700177669~EXSTAT', 'ALLG~~~5597593673700177669~NFEHL',
       'ALLG~~~5597593673700177669~NWARN', 'ALLG~~~5597593673700177669~NMELD',
       'ALLG~~~5597593673700177669~CPUTIME',
       'ALLG~~~5597593673700177669~USRTIME',
       'ALLG~~~5597593673700177669~NPGREST',
       'ALLG~~~5597593673700177669~NETZABN',
       ...
       'ROHR~*~*~*~RHOI', 'ROHR~*~*~*~RHOK', 'FWVB~*~*~*~RHOI',
       'FWVB~*~*~*~RHOK', 'VENT~*~*~*~RHO', 'VENT~*~*~*~DH', 'FWVB~*~*~*~DP',
       'FWVB~*~*~*~DH', 'FWVB~*~*~*~MHYUV', 'FWVB~*~*~*~MTHUV'],
      dtype='object', length=508)

Compare against the legacy PT3S.Mx read for the same file (shape and columns should line up).

In [17]:
print("legacy  mx.df shape:", mx.df.shape)
print("sir3stoolkit df_mx shape:", df_mx.shape)

legacy  mx.df shape: (25, 332)
sir3stoolkit df_mx shape: (2, 508)

In [18]:
s3s.GetPropertiesofElementType(s3s.ObjectTypes.GeneralSection)

['Name',
 'Idqm',
 'Idph',
 'Netztyp',
 'Forc',
 'Pfadol1',
 'Pk',
 'InVariant',
 'bz.Fk',
 'bz.Cdat',
 'bz.Cuhr',
 'bz.Czon',
 'bz.Iart',
 'bz.ArtTh',
 'bz.Thfakt',
 'bz.Itrenn',
 'bz.ThStat',
 'bz.ThInst',
 'bz.Jwarn',
 'bz.Lfqsv',
 'bz.Schwellqsig',
 'bz.Knuvtyp',
 'bz.ValidAggr',
 'bz.CalcNetwork',
 'bz.Idra',
 'bz.CheckRes',
 'bz.CheckMod']

In [19]:
s3s.ObjectTypes_TableNames

In [20]:
object_types = [item for item in dir(s3s.ObjectTypes_TableNames) if not (item.startswith('__') and item.endswith('__'))]
print(object_types)

['AGSN', 'ALLG', 'ANTP', 'ANTP_ROWS', 'ARRW', 'ATMO', 'AVOS', 'AVOS_ROWS', 'BEVE', 'BEWI', 'BREF', 'CIRC', 'CONT', 'CRGL', 'DPGR', 'DPGR_DPKT', 'DPKT', 'DPRG', 'DTRO', 'DTRO_ROWD', 'EBES', 'ELEMENTQUERY', 'ETAM', 'ETAM_ROWS', 'ETAR', 'ETAR_ROWS', 'ETAU', 'ETAU_ROWS', 'FKNL', 'FQPS', 'FQPS_BZ', 'FSTF', 'FWBZ', 'FWEA', 'FWES', 'FWVB', 'FWWU', 'GKMP', 'GMIX', 'GRAV', 'GTXT', 'GVWK', 'HAUS', 'HYDR', 'KLAP', 'KNOT', 'KOMK', 'KOMK_ROWS', 'KOMP', 'LAYR', 'LFKT', 'LFKT_ROWT', 'LTGR', 'MREG', 'NRCV', 'NSCH', 'OBEH', 'OVAL', 'PARI', 'PARZ', 'PGRP', 'PGRP_PUMP', 'PHI1', 'PHI1_ROWT', 'PHI2', 'PHI2_ROWS', 'PHIV', 'PHIV_ROWS', 'PHTR', 'PLYG', 'POLY', 'PREG', 'PUMD', 'PUMD_ROWT', 'PUMK', 'PUMK_ROWS', 'PUMP', 'PVAR', 'PVAR_ROWT', 'PZON', 'QVAR', 'QVAR_ROWT', 'RADD', 'RART', 'RCPL', 'RCPL_ROWT', 'RDIV', 'RECT', 'REGP', 'REGV', 'RFKT', 'RHYS', 'RINT', 'RLSR', 'RLVG', 'RMES', 'RMES_DPTS', 'RMMA', 'RMUL', 'ROHR', 'ROHR_VRTX', 'RPFL', 'RPID', 'RPT1', 'RRCT', 'RSLW', 'RSTE', 'RSTN', 'RTOT', 'RUES', 'SIVE', 'SOKO', 'SPLZ', 'SRAT', 'SRAT_ROWS', 'STOF', 'STOF_ROWS', 'STRASSE', 'STRO', 'SWVT', 'SWVT_ROWT', 'TEVT', 'TEVT_ROWT', 'TFKT', 'TFKT_ROWS', 'TRFT', 'TRFT_ROWS', 'TRVA', 'USCH', 'UTMP', 'VARA', 'VARA_ROWS', 'VENT', 'VERB', 'VKNO', 'VRCT', 'WBLZ', 'WEVT', 'WEVT_ROWT', 'WIND', 'WTTR', 'WTTR_ROWT', 'ZEP1', 'ZEP1_ROWS', 'ZEP2', 'ZEP2_ROWS']

In [21]:
len(object_types)

146

In [22]:
import sqlite3

with sqlite3.connect(f"file:C:\\Users\\aUsername\\3S\\sir3stoolkit\\docs\\source\\tutorials\\SIR3S_Model_Mantle\\Tutorial051_Assets\\Toolkit_Tutorial51_Model.db3?mode=ro", uri=True) as conn:
    rows = conn.execute("SELECT * FROM TIMD").fetchall()
conn.close()

In [ ]:
s3s.CloseModel(False)

True

: