# Tutorial 57: Bulk Result Read, Output Factors, and Time Curve Data

This example demonstrates how to read calculation results quickly with generate_element_results_dataframe(bulk=True): instead of one Toolkit API call per value, the values are read directly from the result files (.MX1/.MX2/.MXS). This pays off for every request with more than a few elements or timestamps, and makes reading very large result files possible. It also allows for the specification of an output factor file to read and therefore the reading of time curve data directly.

# Toolkit Release

In [1]:
#pip install

# Imports

## SIR 3S Toolkit

### Regular Import/Init

In [2]:
SIR3S_SIRGRAF_DIR = r"C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2" #change to local path

In [3]:
from sir3stoolkit.core import wrapper

In [4]:
wrapper

In [5]:
wrapper.Initialize_Toolkit(SIR3S_SIRGRAF_DIR)

[2026-10-14 15:02:33,209] INFO in sir3stoolkit.core.wrapper: [Initialization] Using provided SirGraf path: C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2
[2026-10-14 15:02:33,209] INFO in sir3stoolkit.core.wrapper: [Initialization] Using provided SirGraf path: C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2
[2026-10-14 15:02:33,277] INFO in sir3stoolkit.core.wrapper: [Initialization] Initializing toolkit with SirGraf path: C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2
[2026-10-14 15:02:35,326] INFO in sir3stoolkit.core.wrapper: [Initialization] Sir3S_Toolkit.dll file version 90.15.10.0 (matches this sir3stoolkit version).

### Additional Import/Init for Dataframes class

In [6]:
from sir3stoolkit.mantle.dataframes import SIR3S_Model_Dataframes

In [7]:
s3s = SIR3S_Model_Dataframes()

[2026-10-14 15:02:48,177] INFO in sir3stoolkit.core.wrapper: [Model Class Initialization] Initialization complete

# Open Model

In [8]:
s3s.OpenModel(dbName=r"Toolkit_Tutorial57_Model.db3",
              providerType=s3s.ProviderTypes.SQLite,
              Mid="M-1-0-1",
              saveCurrentlyOpenModel=False,
              namedInstance="",
              userID="",
              password="")

[2026-10-14 15:03:15,957] INFO in sir3stoolkit.core.wrapper: Model is open for further operation

# Calculate Model

In [9]:
s3s.ExecCalculation(True) # To ensure result data

[2026-10-14 15:03:28,253] INFO in sir3stoolkit.core.wrapper: Model Calculation is complete

# Bulk Read

## Basics

The regular [generate_element_results_dataframe()](https://3sconsult.github.io/sir3stoolkit/references/sir3stoolkit.mantle.html#sir3stoolkit.mantle.dataframes.SIR3S_Model_Dataframes.generate_element_results_dataframe) function utilizes the Toolkit's most basic functions like [GetResultfortimestamp()](https://3sconsult.github.io/sir3stoolkit/references/sir3stoolkit.core.html#sir3stoolkit.core.wrapper.SIR3S_Model.GetResultfortimestamp) in a Python loop to retrieve the result values for the dataframe. This can be quite slow.

In [10]:
df_results = s3s.generate_element_results_dataframe(element_type=s3s.ObjectTypes.Pipe, timestamps = [0, -1]) # takes about 90 seconds

[2026-10-14 15:03:28,274] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-10-14 15:03:28,491] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 2 timestamps: ['2023-02-13 00:00:00.000 +01:00', '2023-02-14 00:00:00.000 +01:00']
[2026-10-14 15:03:28,493] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-10-14 15:03:28,523] INFO in sir3stoolkit.mantle.dataframes: [results] No properties given → using ALL result properties for ObjectTypes.Pipe.
[2026-10-14 15:03:28,525] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-10-14 15:03:28,892] INFO in sir3stoolkit.mantle.dataframes: [results] 2 timestamp(s), 524 element(s), 82 properties resolved (0.6 s).
[2026-10-14 15:03:28,894] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values... (bulk=False)
[2026-10-14 15:03:33,652] INFO in sir3stoolkit.mantle.dataframes: [results] GetResultfortimestamp(): 20 % (17,220/85,936 values, 4.8 s)
[2026-10-14 15:03:38,142] INFO in sir3stoolkit.mantle.dataframes: [results] GetResultfortimestamp(): 40 % (34,440/85,936 values, 9.2 s)
[2026-10-14 15:03:56,942] INFO in sir3stoolkit.mantle.dataframes: [results] GetResultfortimestamp(): 60 % (51,578/85,936 values, 28.0 s)
[2026-10-14 15:04:06,529] INFO in sir3stoolkit.mantle.dataframes: [results] GetResultfortimestamp(): 80 % (68,798/85,936 values, 37.6 s)
[2026-10-14 15:04:12,311] INFO in sir3stoolkit.mantle.dataframes: [results] GetResultfortimestamp(): 100 % (85,936/85,936 values, 43.4 s)
[2026-10-14 15:04:12,342] INFO in sir3stoolkit.mantle.dataframes: [results] 85,936 value(s) retrieved via GetResultfortimestamp() (43.4 s).
[2026-10-14 15:06:14,138] INFO in sir3stoolkit.mantle.dataframes: [results] 26724 fully NaN columns dropped.
[2026-10-14 15:06:14,142] INFO in sir3stoolkit.mantle.dataframes: [results] DataFrame assembled (2.3 s).
[2026-10-14 15:06:14,395] INFO in sir3stoolkit.mantle.dataframes: [results] Names/end nodes of 524 element(s) looked up (0.2 s).
[2026-10-14 15:06:14,933] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (2, 16244) (166.7 s in total)

In [11]:
df_results.head(3)

tk                                                                    5442010239090746007  \
name                                                                   Rohr V-K03S V-K13S
end_nodes                      ('5669301360686511351', '5397948523091900401', '-1', '-1')
property                                                                                A
timestamp
2023-02-13 00:00:00.000 +01:00                                                0.0
2023-02-14 00:00:00.000 +01:00                                                0.0

tk                                                                            \
name
end_nodes
property                            DTTR     DWVERL DWVERLABS IAKTIV IRTRENN
timestamp
2023-02-13 00:00:00.000 +01:00  0.013437  35.860340  1.306369    0.0     0.0
2023-02-14 00:00:00.000 +01:00  0.012623  35.869091  1.306688    0.0     0.0

tk                                        \
name
end_nodes
property                              JV
timestamp
2023-02-13 00:00:00.000 +01:00  0.286070
2023-02-14 00:00:00.000 +01:00  0.322513

tk                                                                                \
name
end_nodes
property                                                                    MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  14.68007\t14.68007\t14.68007\t14.68007\t14.68007
2023-02-14 00:00:00.000 +01:00  15.62684\t15.62684\t15.62684\t15.62684\t15.62684

tk                                                            \
name
end_nodes
property                          PDAMPF       PHR      PMIN
timestamp
2023-02-13 00:00:00.000 +01:00  0.693796  0.010421  4.291403
2023-02-14 00:00:00.000 +01:00  0.694239  0.011749  4.315597

tk                                                                             \
name
end_nodes
property                                                                 PVEC
timestamp
2023-02-13 00:00:00.000 +01:00  4.50263\t4.44982\t4.397015\t4.34421\t4.291405
2023-02-14 00:00:00.000 +01:00  4.52815\t4.47501\t4.42187\t4.368735\t4.315595

tk                                                                             \
name
end_nodes
property                                                         PVECMAX_INST
timestamp
2023-02-13 00:00:00.000 +01:00  4.50263\t4.44982\t4.397015\t4.34421\t4.291405
2023-02-14 00:00:00.000 +01:00    5.0303\t4.97056\t4.91082\t4.85108\t4.791335

tk                                                                             \
name
end_nodes
property                                                         PVECMIN_INST
timestamp
2023-02-13 00:00:00.000 +01:00  4.50263\t4.44982\t4.397015\t4.34421\t4.291405
2023-02-14 00:00:00.000 +01:00   4.502625\t4.44982\t4.397015\t4.34421\t4.2914

tk                                                                        \
name
end_nodes
property                            QMAV       QMI       QMK        RHOI
timestamp
2023-02-13 00:00:00.000 +01:00  52.84827  52.84827  52.84827  965.860901
2023-02-14 00:00:00.000 +01:00  56.25663  56.25663  56.25663  965.851074

tk                                          \
name
end_nodes
property                              RHOK
timestamp
2023-02-13 00:00:00.000 +01:00  965.873596
2023-02-14 00:00:00.000 +01:00  965.863098

tk                                                                                \
name
end_nodes
property                                                                  RHOVEC
timestamp
2023-02-13 00:00:00.000 +01:00  965.8609\t965.8641\t965.8672\t965.8704\t965.8736
2023-02-14 00:00:00.000 +01:00  965.8511\t965.8541\t965.8571\t965.8601\t965.8631

tk                                                                         \
name
end_nodes
property                                                             SVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0\t9.107338\t18.21468\t27.32201\t36.42935
2023-02-14 00:00:00.000 +01:00  0\t9.107338\t18.21468\t27.32201\t36.42935

tk                                                    \
name
end_nodes
property                               TI         TK
timestamp
2023-02-13 00:00:00.000 +01:00  89.731827  89.710640
2023-02-14 00:00:00.000 +01:00  89.748070  89.728157

tk                                                                                 \
name
end_nodes
property                                                                   TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.3227227\t0.326082\t0.3294411\t0.3328003\t0.3...
2023-02-14 00:00:00.000 +01:00  0.303077\t0.3062327\t0.3093883\t0.312544\t0.31...

tk                                                                                \
name
end_nodes
property                                                                    TVEC
timestamp
2023-02-13 00:00:00.000 +01:00  89.73184\t89.72653\t89.72122\t89.71594\t89.71063
2023-02-14 00:00:00.000 +01:00   89.74808\t89.7431\t89.73813\t89.73315\t89.72818

tk                                                                  \
name
end_nodes
property                             VAV        VI        VK VOLDA
timestamp
2023-02-13 00:00:00.000 +01:00  0.753102  0.753107  0.753097   0.0
2023-02-14 00:00:00.000 +01:00  0.801681  0.801686  0.801676   0.0

tk                                           \
name
end_nodes
property                                WVL
timestamp
2023-02-13 00:00:00.000 +01:00  1843.650024
2023-02-14 00:00:00.000 +01:00  1962.688965

tk                                                                       \
name
end_nodes
property                                                           ZVEC
timestamp
2023-02-13 00:00:00.000 +01:00  554.04\t554.5699\t555.1\t555.63\t556.16
2023-02-14 00:00:00.000 +01:00  554.04\t554.5699\t555.1\t555.63\t556.16

tk                                                                    4917786378639043296  \
name                                                                   Rohr V-K13S V-K23S
end_nodes                      ('5397948523091900401', '5239335112004772156', '-1', '-1')
property                                                                                A
timestamp
2023-02-13 00:00:00.000 +01:00                                                0.0
2023-02-14 00:00:00.000 +01:00                                                0.0

tk                                                                            \
name
end_nodes
property                            DTTR     DWVERL DWVERLABS IAKTIV IRTRENN
timestamp
2023-02-13 00:00:00.000 +01:00  0.025371  29.877501  1.709525    0.0     0.0
2023-02-14 00:00:00.000 +01:00  0.023853  29.890051  1.710243    0.0     0.0

tk                                        \
name
end_nodes
property                              JV
timestamp
2023-02-13 00:00:00.000 +01:00  0.255595
2023-02-14 00:00:00.000 +01:00  0.287537

tk                                                                                 \
name
end_nodes
property                                                                     MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  8.24275\t8.24275\t8.24275\t8.24275\t8.24275\t8...
2023-02-14 00:00:00.000 +01:00  8.767406\t8.767406\t8.767406\t8.767406\t8.7674...

tk                                                            \
name
end_nodes
property                          PDAMPF       PHR      PMIN
timestamp
2023-02-13 00:00:00.000 +01:00  0.692872  0.014625  3.817376
2023-02-14 00:00:00.000 +01:00  0.693370  0.016452  3.839748

tk                                                                                 \
name
end_nodes
property                                                                     PVEC
timestamp
2023-02-13 00:00:00.000 +01:00  4.291405\t4.2124\t4.133395\t4.05439\t3.975385\...
2023-02-14 00:00:00.000 +01:00  4.315595\t4.23629\t4.15698\t4.077675\t3.998365...

tk                                                                                 \
name
end_nodes
property                                                             PVECMAX_INST
timestamp
2023-02-13 00:00:00.000 +01:00  4.291405\t4.2124\t4.133395\t4.05439\t3.975385\...
2023-02-14 00:00:00.000 +01:00  4.791335\t4.706015\t4.620695\t4.535375\t4.4500...

tk                                                                                 \
name
end_nodes
property                                                             PVECMIN_INST
timestamp
2023-02-13 00:00:00.000 +01:00  4.291405\t4.2124\t4.133395\t4.05439\t3.975385\...
2023-02-14 00:00:00.000 +01:00  4.2914\t4.212395\t4.133395\t4.05439\t3.975385\...

tk                                                                           \
name
end_nodes
property                             QMAV        QMI        QMK        RHOI
timestamp
2023-02-13 00:00:00.000 +01:00  29.673901  29.673901  29.673901  965.873596
2023-02-14 00:00:00.000 +01:00  31.562660  31.562660  31.562660  965.863098

tk                                         \
name
end_nodes
property                             RHOK
timestamp
2023-02-13 00:00:00.000 +01:00  965.90332
2023-02-14 00:00:00.000 +01:00  965.89093

tk                                                                                 \
name
end_nodes
property                                                                   RHOVEC
timestamp
2023-02-13 00:00:00.000 +01:00  965.8736\t965.8785\t965.8835\t965.8884\t965.89...
2023-02-14 00:00:00.000 +01:00  965.8631\t965.8677\t965.8724\t965.877\t965.881...

tk                                                                                 \
name
end_nodes
property                                                                     SVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0\t9.536302\t19.0726\t28.60891\t38.14521\t47.6...
2023-02-14 00:00:00.000 +01:00  0\t9.536302\t19.0726\t28.60891\t38.14521\t47.6...

tk                                                    \
name
end_nodes
property                               TI         TK
timestamp
2023-02-13 00:00:00.000 +01:00  89.710640  89.661278
2023-02-14 00:00:00.000 +01:00  89.728157  89.681747

tk                                                                                 \
name
end_nodes
property                                                                   TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.3361595\t0.3403881\t0.3446167\t0.3488452\t0....
2023-02-14 00:00:00.000 +01:00  0.3156996\t0.3196751\t0.3236506\t0.3276261\t0....

tk                                                                                 \
name
end_nodes
property                                                                     TVEC
timestamp
2023-02-13 00:00:00.000 +01:00  89.71063\t89.70242\t89.69418\t89.68597\t89.677...
2023-02-14 00:00:00.000 +01:00  89.72818\t89.72043\t89.71271\t89.70496\t89.697...

tk                                                                  \
name
end_nodes
property                             VAV        VI        VK VOLDA
timestamp
2023-02-13 00:00:00.000 +01:00  0.626446  0.626456  0.626436   0.0
2023-02-14 00:00:00.000 +01:00  0.666328  0.666337  0.666318   0.0

tk                                           \
name
end_nodes
property                                WVL
timestamp
2023-02-13 00:00:00.000 +01:00  1032.728027
2023-02-14 00:00:00.000 +01:00  1098.697021

tk                                                                                 \
name
end_nodes
property                                                                     ZVEC
timestamp
2023-02-13 00:00:00.000 +01:00  556.16\t556.9683\t557.7767\t558.585\t559.3933\...
2023-02-14 00:00:00.000 +01:00  556.16\t556.9683\t557.7767\t558.585\t559.3933\...

tk                                                                    4762482310382009633  \
name                                                                   Rohr V-K23S V-K33S
end_nodes                      ('5239335112004772156', '5298886695042021307', '-1', '-1')
property                                                                                A
timestamp
2023-02-13 00:00:00.000 +01:00                                                0.0
2023-02-14 00:00:00.000 +01:00                                                0.0

tk                                                                            \
name
end_nodes
property                            DTTR     DWVERL DWVERLABS IAKTIV IRTRENN
timestamp
2023-02-13 00:00:00.000 +01:00  0.017832  29.802271  1.221739    0.0     0.0
2023-02-14 00:00:00.000 +01:00  0.016756  29.825069  1.222673    0.0     0.0

tk                                        \
name
end_nodes
property                              JV
timestamp
2023-02-13 00:00:00.000 +01:00  0.265203
2023-02-14 00:00:00.000 +01:00  0.298659

tk                                                                                 \
name
end_nodes
property                                                                     MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  8.403428\t8.403428\t8.403428\t8.403428\t8.4034...
2023-02-14 00:00:00.000 +01:00  8.942982\t8.942982\t8.942982\t8.942982\t8.9429...

tk                                                            \
name
end_nodes
property                          PDAMPF       PHR      PMIN
timestamp
2023-02-13 00:00:00.000 +01:00  0.687946  0.010872  3.612304
2023-02-14 00:00:00.000 +01:00  0.688737  0.012243  3.633308

tk                                                                                 \
name
end_nodes
property                                                                     PVEC
timestamp
2023-02-13 00:00:00.000 +01:00  3.817375\t3.77636\t3.73535\t3.694335\t3.65332\...
2023-02-14 00:00:00.000 +01:00  3.83975\t3.79846\t3.75717\t3.715885\t3.674595\...

tk                                                                                 \
name
end_nodes
property                                                             PVECMAX_INST
timestamp
2023-02-13 00:00:00.000 +01:00  3.817375\t3.77636\t3.73535\t3.694335\t3.65332\...
2023-02-14 00:00:00.000 +01:00  4.27941\t4.232685\t4.185965\t4.13924\t4.09252\...

tk                                                                                 \
name
end_nodes
property                                                             PVECMIN_INST
timestamp
2023-02-13 00:00:00.000 +01:00  3.817375\t3.77636\t3.73535\t3.694335\t3.65332\...
2023-02-14 00:00:00.000 +01:00  3.817375\t3.77636\t3.735345\t3.69433\t3.65332\...

tk                                                                           \
name
end_nodes
property                             QMAV        QMI        QMK        RHOI
timestamp
2023-02-13 00:00:00.000 +01:00  30.252340  30.252340  30.252340  965.990784
2023-02-14 00:00:00.000 +01:00  32.194729  32.194729  32.194729  965.973389

tk                                          \
name
end_nodes
property                              RHOK
timestamp
2023-02-13 00:00:00.000 +01:00  966.011597
2023-02-14 00:00:00.000 +01:00  965.992920

tk                                                                                 \
name
end_nodes
property                                                                   RHOVEC
timestamp
2023-02-13 00:00:00.000 +01:00  965.9908\t965.995\t965.9991\t966.0033\t966.007...
2023-02-14 00:00:00.000 +01:00  965.9734\t965.9773\t965.9812\t965.9851\t965.98...

tk                                                                                 \
name
end_nodes
property                                                                     SVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0\t8.198964\t16.39793\t24.59689\t32.79586\t40....
2023-02-14 00:00:00.000 +01:00  0\t8.198964\t16.39793\t24.59689\t32.79586\t40....

tk                                                    \
name
end_nodes
property                               TI         TK
timestamp
2023-02-13 00:00:00.000 +01:00  89.515244  89.480629
2023-02-14 00:00:00.000 +01:00  89.544388  89.511848

tk                                                                                 \
name
end_nodes
property                                                                   TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.4288373\t0.4324038\t0.4359702\t0.4395368\t0....
2023-02-14 00:00:00.000 +01:00  0.4028289\t0.4061802\t0.4095314\t0.4128827\t0....

tk                                                                                 \
name
end_nodes
property                                                                     TVEC
timestamp
2023-02-13 00:00:00.000 +01:00  89.51523\t89.50833\t89.5014\t89.49448\t89.4875...
2023-02-14 00:00:00.000 +01:00  89.5444\t89.53787\t89.53137\t89.52487\t89.5183...

tk                                                                  \
name
end_nodes
property                             VAV        VI        VK VOLDA
timestamp
2023-02-13 00:00:00.000 +01:00  0.638583  0.638590  0.638576   0.0
2023-02-14 00:00:00.000 +01:00  0.679597  0.679604  0.679590   0.0

tk                                           \
name
end_nodes
property                                WVL
timestamp
2023-02-13 00:00:00.000 +01:00  1045.860962
2023-02-14 00:00:00.000 +01:00  1113.696045

tk                                                                              \
name
end_nodes
property                                                                  ZVEC
timestamp
2023-02-13 00:00:00.000 +01:00  561.01\t561.42\t561.83\t562.24\t562.65\t563.06
2023-02-14 00:00:00.000 +01:00  561.01\t561.42\t561.83\t562.24\t562.65\t563.06

tk                                                                    4987229536643024523  \
name                                                                   Rohr V-K33S V-K43S
end_nodes                      ('5298886695042021307', '4993257270457791438', '-1', '-1')
property                                                                                A
timestamp
2023-02-13 00:00:00.000 +01:00                                                0.0
2023-02-14 00:00:00.000 +01:00                                                0.0

tk                                                                           \
name
end_nodes
property                            DTTR    DWVERL DWVERLABS IAKTIV IRTRENN
timestamp
2023-02-13 00:00:00.000 +01:00  0.002972  29.72455  0.203110    0.0     0.0
2023-02-14 00:00:00.000 +01:00  0.002793  29.87566  0.204143    0.0     0.0

tk                                                                      \
name
end_nodes
property                              JV                MVEC    PDAMPF
timestamp
2023-02-13 00:00:00.000 +01:00  0.265205  8.403428\t8.403428  0.687417
2023-02-14 00:00:00.000 +01:00  0.298661  8.942982\t8.942982  0.688240

tk                                                                      \
name
end_nodes
property                             PHR      PMIN                PVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.001812  3.591544  3.612305\t3.591545
2023-02-14 00:00:00.000 +01:00  0.002041  3.612320    3.63331\t3.61232

tk                                                                      \
name
end_nodes
property                              PVECMAX_INST        PVECMIN_INST
timestamp
2023-02-13 00:00:00.000 +01:00  3.612305\t3.591545  3.612305\t3.591545
2023-02-14 00:00:00.000 +01:00     4.0458\t4.02028  3.612305\t3.591545

tk                                                                           \
name
end_nodes
property                             QMAV        QMI        QMK        RHOI
timestamp
2023-02-13 00:00:00.000 +01:00  30.252340  30.252340  30.252340  966.011597
2023-02-14 00:00:00.000 +01:00  32.194729  32.194729  32.194729  965.992920

tk                                                                           \
name
end_nodes
property                              RHOK              RHOVEC         SVEC
timestamp
2023-02-13 00:00:00.000 +01:00  966.015076  966.0116\t966.0151  0\t6.833079
2023-02-14 00:00:00.000 +01:00  965.996216  965.9929\t965.9962  0\t6.833079

tk                                                                          \
name
end_nodes
property                               TI         TK                TTRVEC
timestamp

Instead we can use the parameter bulk=True to read the mx result files directly. This is much faster and especially relevant for larger models.

In [12]:
df_results = s3s.generate_element_results_dataframe(element_type=s3s.ObjectTypes.Pipe, bulk=True, timestamps = [0, -1]) # takes about 1 second

[2026-10-14 15:06:17,994] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-10-14 15:06:18,126] INFO in sir3stoolkit.mantle.mx: [mx] M-1-0-1.4.MXS: 500 channels, 10 records of 210,068 bytes (0.00 GiB).
[2026-10-14 15:06:18,158] INFO in sir3stoolkit.mantle.dataframes: [bulk results] Result file: M-1-0-1.4.MX1 (output factor 4 = DTFAK_GROSS of the most recent calculation, default), 7 timestamps.
[2026-10-14 15:06:18,169] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-10-14 15:06:18,174] INFO in sir3stoolkit.mantle.dataframes: [results] Using 31 result properties from the result file.
[2026-10-14 15:06:18,193] INFO in sir3stoolkit.mantle.dataframes: [results] 2 timestamp(s), 524 element(s), 31 properties resolved (0.2 s).
[2026-10-14 15:06:18,193] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values... (bulk=True)
[2026-10-14 15:06:18,441] INFO in sir3stoolkit.mantle.dataframes: [bulk results] 31 properties read from M-1-0-1.4.MX1 (0.2 s).
[2026-10-14 15:06:18,444] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-10-14 15:06:18,446] INFO in sir3stoolkit.mantle.dataframes: [results] DataFrame assembled (0.0 s).
[2026-10-14 15:06:18,676] INFO in sir3stoolkit.mantle.dataframes: [results] Names/end nodes of 524 element(s) looked up (0.2 s).
[2026-10-14 15:06:18,841] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (2, 16244) (0.8 s in total)

The direct byte-read of the mx files is much faster. In addition only result properties that exist in the calculation results will be attempted to be read.

Still keep in mind that if you have a very large model ~ two digits of GiBs in .MXS, pandas will need to hold a dataframe of similar size in RAM if the entire file is requested. For oversized requests the function raises a MemoryError before reading anything, instead of failing during execution. You should always try to keep dimension tks X timestamps X properties to the data you actually need.

In [13]:
df_results.head(3)

tk                                                                    5442010239090746007  \
name                                                                   Rohr V-K03S V-K13S
end_nodes                      ('5669301360686511351', '5397948523091900401', '-1', '-1')
property                                                                                A
timestamp
2023-02-13 00:00:00.000 +01:00                                                0.0
2023-02-14 00:00:00.000 +01:00                                                0.0

tk                                                                            \
name
end_nodes
property                            DTTR     DWVERL DWVERLABS IAKTIV IRTRENN
timestamp
2023-02-13 00:00:00.000 +01:00  0.013437  35.860340  1.306369    0.0     0.0
2023-02-14 00:00:00.000 +01:00  0.012623  35.869095  1.306688    0.0     0.0

tk                                        \
name
end_nodes
property                              JV
timestamp
2023-02-13 00:00:00.000 +01:00  0.286070
2023-02-14 00:00:00.000 +01:00  0.322513

tk                                                                                \
name
end_nodes
property                                                                    MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  14.68007\t14.68007\t14.68007\t14.68007\t14.68007
2023-02-14 00:00:00.000 +01:00  15.62684\t15.62684\t15.62684\t15.62684\t15.62684

tk                                                            \
name
end_nodes
property                          PDAMPF       PHR      PMIN
timestamp
2023-02-13 00:00:00.000 +01:00  0.693796  0.010421  4.291403
2023-02-14 00:00:00.000 +01:00  0.694239  0.011749  4.315597

tk                                                                             \
name
end_nodes
property                                                                 PVEC
timestamp
2023-02-13 00:00:00.000 +01:00  4.50263\t4.44982\t4.397015\t4.34421\t4.291405
2023-02-14 00:00:00.000 +01:00  4.52815\t4.47501\t4.42187\t4.368735\t4.315595

tk                                                                             \
name
end_nodes
property                                                         PVECMAX_INST
timestamp
2023-02-13 00:00:00.000 +01:00  4.50263\t4.44982\t4.397015\t4.34421\t4.291405
2023-02-14 00:00:00.000 +01:00    5.0303\t4.97056\t4.91082\t4.85108\t4.791335

tk                                                                             \
name
end_nodes
property                                                         PVECMIN_INST
timestamp
2023-02-13 00:00:00.000 +01:00  4.50263\t4.44982\t4.397015\t4.34421\t4.291405
2023-02-14 00:00:00.000 +01:00   4.502625\t4.44982\t4.397015\t4.34421\t4.2914

tk                                                                           \
name
end_nodes
property                             QMAV        QMI        QMK        RHOI
timestamp
2023-02-13 00:00:00.000 +01:00  52.848267  52.848267  52.848267  965.860901
2023-02-14 00:00:00.000 +01:00  56.256630  56.256630  56.256630  965.851135

tk                                          \
name
end_nodes
property                              RHOK
timestamp
2023-02-13 00:00:00.000 +01:00  965.873596
2023-02-14 00:00:00.000 +01:00  965.863098

tk                                                                                \
name
end_nodes
property                                                                  RHOVEC
timestamp
2023-02-13 00:00:00.000 +01:00  965.8609\t965.8641\t965.8672\t965.8704\t965.8736
2023-02-14 00:00:00.000 +01:00  965.8511\t965.8541\t965.8571\t965.8601\t965.8631

tk                                                                         \
name
end_nodes
property                                                             SVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0\t9.107338\t18.21468\t27.32201\t36.42935
2023-02-14 00:00:00.000 +01:00  0\t9.107338\t18.21468\t27.32201\t36.42935

tk                                                    \
name
end_nodes
property                               TI         TK
timestamp
2023-02-13 00:00:00.000 +01:00  89.731827  89.710640
2023-02-14 00:00:00.000 +01:00  89.748070  89.728165

tk                                                                                 \
name
end_nodes
property                                                                   TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.3227227\t0.326082\t0.3294411\t0.3328003\t0.3...
2023-02-14 00:00:00.000 +01:00  0.303077\t0.3062327\t0.3093883\t0.312544\t0.31...

tk                                                                                \
name
end_nodes
property                                                                    TVEC
timestamp
2023-02-13 00:00:00.000 +01:00  89.73184\t89.72653\t89.72122\t89.71594\t89.71063
2023-02-14 00:00:00.000 +01:00   89.74808\t89.7431\t89.73813\t89.73315\t89.72818

tk                                                                  \
name
end_nodes
property                             VAV        VI        VK VOLDA
timestamp
2023-02-13 00:00:00.000 +01:00  0.753102  0.753107  0.753097   0.0
2023-02-14 00:00:00.000 +01:00  0.801681  0.801686  0.801676   0.0

tk                                           \
name
end_nodes
property                                WVL
timestamp
2023-02-13 00:00:00.000 +01:00  1843.650269
2023-02-14 00:00:00.000 +01:00  1962.688965

tk                                                                       \
name
end_nodes
property                                                           ZVEC
timestamp
2023-02-13 00:00:00.000 +01:00  554.04\t554.5699\t555.1\t555.63\t556.16
2023-02-14 00:00:00.000 +01:00  554.04\t554.5699\t555.1\t555.63\t556.16

tk                                                                    4917786378639043296  \
name                                                                   Rohr V-K13S V-K23S
end_nodes                      ('5397948523091900401', '5239335112004772156', '-1', '-1')
property                                                                                A
timestamp
2023-02-13 00:00:00.000 +01:00                                                0.0
2023-02-14 00:00:00.000 +01:00                                                0.0

tk                                                                            \
name
end_nodes
property                            DTTR     DWVERL DWVERLABS IAKTIV IRTRENN
timestamp
2023-02-13 00:00:00.000 +01:00  0.025371  29.877504  1.709525    0.0     0.0
2023-02-14 00:00:00.000 +01:00  0.023853  29.890053  1.710243    0.0     0.0

tk                                        \
name
end_nodes
property                              JV
timestamp
2023-02-13 00:00:00.000 +01:00  0.255595
2023-02-14 00:00:00.000 +01:00  0.287537

tk                                                                                 \
name
end_nodes
property                                                                     MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  8.24275\t8.24275\t8.24275\t8.24275\t8.24275\t8...
2023-02-14 00:00:00.000 +01:00  8.767406\t8.767406\t8.767406\t8.767406\t8.7674...

tk                                                            \
name
end_nodes
property                          PDAMPF       PHR      PMIN
timestamp
2023-02-13 00:00:00.000 +01:00  0.692872  0.014625  3.817376
2023-02-14 00:00:00.000 +01:00  0.693370  0.016452  3.839748

tk                                                                                 \
name
end_nodes
property                                                                     PVEC
timestamp
2023-02-13 00:00:00.000 +01:00  4.291405\t4.2124\t4.133395\t4.05439\t3.975385\...
2023-02-14 00:00:00.000 +01:00  4.315595\t4.23629\t4.15698\t4.077675\t3.998365...

tk                                                                                 \
name
end_nodes
property                                                             PVECMAX_INST
timestamp
2023-02-13 00:00:00.000 +01:00  4.291405\t4.2124\t4.133395\t4.05439\t3.975385\...
2023-02-14 00:00:00.000 +01:00  4.791335\t4.706015\t4.620695\t4.535375\t4.4500...

tk                                                                                 \
name
end_nodes
property                                                             PVECMIN_INST
timestamp
2023-02-13 00:00:00.000 +01:00  4.291405\t4.2124\t4.133395\t4.05439\t3.975385\...
2023-02-14 00:00:00.000 +01:00  4.2914\t4.212395\t4.133395\t4.05439\t3.975385\...

tk                                                                           \
name
end_nodes
property                             QMAV        QMI        QMK        RHOI
timestamp
2023-02-13 00:00:00.000 +01:00  29.673901  29.673901  29.673901  965.873596
2023-02-14 00:00:00.000 +01:00  31.562658  31.562658  31.562658  965.863098

tk                                          \
name
end_nodes
property                              RHOK
timestamp
2023-02-13 00:00:00.000 +01:00  965.903259
2023-02-14 00:00:00.000 +01:00  965.890930

tk                                                                                 \
name
end_nodes
property                                                                   RHOVEC
timestamp
2023-02-13 00:00:00.000 +01:00  965.8736\t965.8785\t965.8835\t965.8884\t965.89...
2023-02-14 00:00:00.000 +01:00  965.8631\t965.8677\t965.8724\t965.877\t965.881...

tk                                                                                 \
name
end_nodes
property                                                                     SVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0\t9.536302\t19.0726\t28.60891\t38.14521\t47.6...
2023-02-14 00:00:00.000 +01:00  0\t9.536302\t19.0726\t28.60891\t38.14521\t47.6...

tk                                                    \
name
end_nodes
property                               TI         TK
timestamp
2023-02-13 00:00:00.000 +01:00  89.710640  89.661278
2023-02-14 00:00:00.000 +01:00  89.728165  89.681747

tk                                                                                 \
name
end_nodes
property                                                                   TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.3361595\t0.3403881\t0.3446167\t0.3488452\t0....
2023-02-14 00:00:00.000 +01:00  0.3156996\t0.3196751\t0.3236506\t0.3276261\t0....

tk                                                                                 \
name
end_nodes
property                                                                     TVEC
timestamp
2023-02-13 00:00:00.000 +01:00  89.71063\t89.70242\t89.69418\t89.68597\t89.677...
2023-02-14 00:00:00.000 +01:00  89.72818\t89.72043\t89.71271\t89.70496\t89.697...

tk                                                                  \
name
end_nodes
property                             VAV        VI        VK VOLDA
timestamp
2023-02-13 00:00:00.000 +01:00  0.626446  0.626456  0.626437   0.0
2023-02-14 00:00:00.000 +01:00  0.666328  0.666337  0.666318   0.0

tk                                           \
name
end_nodes
property                                WVL
timestamp
2023-02-13 00:00:00.000 +01:00  1032.728394
2023-02-14 00:00:00.000 +01:00  1098.696533

tk                                                                                 \
name
end_nodes
property                                                                     ZVEC
timestamp
2023-02-13 00:00:00.000 +01:00  556.16\t556.9683\t557.7767\t558.585\t559.3933\...
2023-02-14 00:00:00.000 +01:00  556.16\t556.9683\t557.7767\t558.585\t559.3933\...

tk                                                                    4762482310382009633  \
name                                                                   Rohr V-K23S V-K33S
end_nodes                      ('5239335112004772156', '5298886695042021307', '-1', '-1')
property                                                                                A
timestamp
2023-02-13 00:00:00.000 +01:00                                                0.0
2023-02-14 00:00:00.000 +01:00                                                0.0

tk                                                                            \
name
end_nodes
property                            DTTR     DWVERL DWVERLABS IAKTIV IRTRENN
timestamp
2023-02-13 00:00:00.000 +01:00  0.017832  29.802269  1.221739    0.0     0.0
2023-02-14 00:00:00.000 +01:00  0.016756  29.825066  1.222673    0.0     0.0

tk                                        \
name
end_nodes
property                              JV
timestamp
2023-02-13 00:00:00.000 +01:00  0.265203
2023-02-14 00:00:00.000 +01:00  0.298659

tk                                                                                 \
name
end_nodes
property                                                                     MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  8.403428\t8.403428\t8.403428\t8.403428\t8.4034...
2023-02-14 00:00:00.000 +01:00  8.942982\t8.942982\t8.942982\t8.942982\t8.9429...

tk                                                            \
name
end_nodes
property                          PDAMPF       PHR      PMIN
timestamp
2023-02-13 00:00:00.000 +01:00  0.687946  0.010872  3.612304
2023-02-14 00:00:00.000 +01:00  0.688737  0.012243  3.633308

tk                                                                                 \
name
end_nodes
property                                                                     PVEC
timestamp
2023-02-13 00:00:00.000 +01:00  3.817375\t3.77636\t3.73535\t3.694335\t3.65332\...
2023-02-14 00:00:00.000 +01:00  3.83975\t3.79846\t3.75717\t3.715885\t3.674595\...

tk                                                                                 \
name
end_nodes
property                                                             PVECMAX_INST
timestamp
2023-02-13 00:00:00.000 +01:00  3.817375\t3.77636\t3.73535\t3.694335\t3.65332\...
2023-02-14 00:00:00.000 +01:00  4.27941\t4.232685\t4.185965\t4.13924\t4.09252\...

tk                                                                                 \
name
end_nodes
property                                                             PVECMIN_INST
timestamp
2023-02-13 00:00:00.000 +01:00  3.817375\t3.77636\t3.73535\t3.694335\t3.65332\...
2023-02-14 00:00:00.000 +01:00  3.817375\t3.77636\t3.735345\t3.69433\t3.65332\...

tk                                                                           \
name
end_nodes
property                             QMAV        QMI        QMK        RHOI
timestamp
2023-02-13 00:00:00.000 +01:00  30.252340  30.252340  30.252340  965.990845
2023-02-14 00:00:00.000 +01:00  32.194733  32.194733  32.194733  965.973389

tk                                          \
name
end_nodes
property                              RHOK
timestamp
2023-02-13 00:00:00.000 +01:00  966.011597
2023-02-14 00:00:00.000 +01:00  965.992920

tk                                                                                 \
name
end_nodes
property                                                                   RHOVEC
timestamp
2023-02-13 00:00:00.000 +01:00  965.9908\t965.995\t965.9991\t966.0033\t966.007...
2023-02-14 00:00:00.000 +01:00  965.9734\t965.9773\t965.9812\t965.9851\t965.98...

tk                                                                                 \
name
end_nodes
property                                                                     SVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0\t8.198964\t16.39793\t24.59689\t32.79586\t40....
2023-02-14 00:00:00.000 +01:00  0\t8.198964\t16.39793\t24.59689\t32.79586\t40....

tk                                                    \
name
end_nodes
property                               TI         TK
timestamp
2023-02-13 00:00:00.000 +01:00  89.515236  89.480629
2023-02-14 00:00:00.000 +01:00  89.544388  89.511848

tk                                                                                 \
name
end_nodes
property                                                                   TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.4288373\t0.4324038\t0.4359702\t0.4395368\t0....
2023-02-14 00:00:00.000 +01:00  0.4028289\t0.4061802\t0.4095314\t0.4128827\t0....

tk                                                                                 \
name
end_nodes
property                                                                     TVEC
timestamp
2023-02-13 00:00:00.000 +01:00  89.51523\t89.50833\t89.5014\t89.49448\t89.4875...
2023-02-14 00:00:00.000 +01:00  89.5444\t89.53787\t89.53137\t89.52487\t89.5183...

tk                                                                  \
name
end_nodes
property                             VAV        VI        VK VOLDA
timestamp
2023-02-13 00:00:00.000 +01:00  0.638583  0.638590  0.638576   0.0
2023-02-14 00:00:00.000 +01:00  0.679597  0.679604  0.679590   0.0

tk                                           \
name
end_nodes
property                                WVL
timestamp
2023-02-13 00:00:00.000 +01:00  1045.860596
2023-02-14 00:00:00.000 +01:00  1113.695923

tk                                                                              \
name
end_nodes
property                                                                  ZVEC
timestamp
2023-02-13 00:00:00.000 +01:00  561.01\t561.42\t561.83\t562.24\t562.65\t563.06
2023-02-14 00:00:00.000 +01:00  561.01\t561.42\t561.83\t562.24\t562.65\t563.06

tk                                                                    4987229536643024523  \
name                                                                   Rohr V-K33S V-K43S
end_nodes                      ('5298886695042021307', '4993257270457791438', '-1', '-1')
property                                                                                A
timestamp
2023-02-13 00:00:00.000 +01:00                                                0.0
2023-02-14 00:00:00.000 +01:00                                                0.0

tk                                                                            \
name
end_nodes
property                            DTTR     DWVERL DWVERLABS IAKTIV IRTRENN
timestamp
2023-02-13 00:00:00.000 +01:00  0.002972  29.724550  0.203110    0.0     0.0
2023-02-14 00:00:00.000 +01:00  0.002793  29.875664  0.204143    0.0     0.0

tk                                                                      \
name
end_nodes
property                              JV                MVEC    PDAMPF
timestamp
2023-02-13 00:00:00.000 +01:00  0.265205  8.403428\t8.403428  0.687417
2023-02-14 00:00:00.000 +01:00  0.298661  8.942982\t8.942982  0.688239

tk                                                                      \
name
end_nodes
property                             PHR      PMIN                PVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.001812  3.591544  3.612305\t3.591545
2023-02-14 00:00:00.000 +01:00  0.002041  3.612320    3.63331\t3.61232

tk                                                                      \
name
end_nodes
property                              PVECMAX_INST        PVECMIN_INST
timestamp
2023-02-13 00:00:00.000 +01:00  3.612305\t3.591545  3.612305\t3.591545
2023-02-14 00:00:00.000 +01:00     4.0458\t4.02028  3.612305\t3.591545

tk                                                                           \
name
end_nodes
property                             QMAV        QMI        QMK        RHOI
timestamp
2023-02-13 00:00:00.000 +01:00  30.252340  30.252340  30.252340  966.011597
2023-02-14 00:00:00.000 +01:00  32.194733  32.194733  32.194733  965.992920

tk                                                                           \
name
end_nodes
property                              RHOK              RHOVEC         SVEC
timestamp
2023-02-13 00:00:00.000 +01:00  966.015076  966.0116\t966.0151  0\t6.833079
2023-02-14 00:00:00.000 +01:00  965.996155  965.9929\t965.9962  0\t6.833079

tk                                                                          \
name
end_nodes
property                               TI         TK                TTRVEC

## Interior Points Formatting

Interior points make up a large share of the result data and of the read time, so you should only request them if they are actually required.

### str

By default interior point result properties with bulk=True are formatted as tab-separated strings to be compatible with the format from the bulk=False read.

In [14]:
tk_of_interest = "5442010239090746007"

In [15]:
timestamp_of_interest = "2023-02-13 00:00:00.000 +01:00"

In [16]:
vec = df_results.xs((tk_of_interest, "PVEC"), axis=1, level=["tk", "property"]).loc[timestamp_of_interest]

In [17]:
vec.iloc[0]

'4.50263\t4.44982\t4.397015\t4.34421\t4.291405'

#### merge with model data

In [18]:
df_model_data = s3s.generate_element_model_data_dataframe(element_type=s3s.ObjectTypes.Pipe, properties=["Di"])

[2026-10-14 15:06:21,001] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-10-14 15:06:21,019] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-10-14 15:06:21,026] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 1 model_data properties.
[2026-10-14 15:06:21,053] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Di']...
[2026-10-14 15:06:21,222] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (524, 2)

In [19]:
df_results = s3s.add_interior_points_to_start_end_sequence(df_results)

In [20]:
df_results, timestamp_to_tuple_index = s3s.convert_rows_to_single_tuple_row(df_results)

[2026-10-14 15:06:41,292] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...

[2026-10-14 15:06:44,884] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Done. Shape: (1, 25676)

In [21]:
df = s3s.merge_model_data_and_results(df_model_data, df_results)

In [22]:
df.head()

,tk,Di,A,DTTR,DWVERL,DWVERLABS,IAKTIV,IRTRENN,JV,MVEC_end,MVEC_sequence,MVEC_start,PDAMPF,PHR,PMIN,PVECMAX_INST_end,PVECMAX_INST_sequence,PVECMAX_INST_start,PVECMIN_INST_end,PVECMIN_INST_sequence,PVECMIN_INST_start,PVEC_end,PVEC_sequence,PVEC_start,QMAV,QMI,QMK,RHOI,RHOK,RHOVEC_end,RHOVEC_sequence,RHOVEC_start,SVEC_end,SVEC_sequence,SVEC_start,TI,TK,TTRVEC_end,TTRVEC_sequence,TTRVEC_start,TVEC_end,TVEC_sequence,TVEC_start,VAV,VI,VK,VOLDA,WVL,ZVEC_end,ZVEC_sequence,ZVEC_start
0,4614463970292122863,994.0,"(0.0, 0.0)","(7.780674, 7.780674)","(0.0, 0.0)","(0.0, 0.0)","(1.0, 1.0)","(0.0, 0.0)","(1.1317442e-23, 1.1317442e-23)","(-1.455192e-10, 1.455192e-10)","((-1.455192e-10, -1.455192e-10), (1.455192e-10...","(-1.455192e-10, 1.455192e-10)","(0.0123, 0.0123)","(8.805733e-26, 8.805733e-26)","(1.6150573, 1.6150573)","(1.68863, 1.688645)","((1.615055, 1.68863), (1.615075, 1.688645))","(1.615055, 1.615075)","(1.68863, 1.68863)","((1.615055, 1.68863), (1.615055, 1.68863))","(1.615055, 1.615055)","(1.68863, 1.68863)","((1.615055, 1.68863), (1.615055, 1.68863))","(1.615055, 1.615055)","(-5.2386895e-10, 5.2386895e-10)","(-5.2386895e-10, 5.2386895e-10)","(-5.2386895e-10, 5.2386895e-10)","(1000.3, 1000.3)","(1000.3, 1000.3)","(1000.3, 1000.3)","((1000.3, 1000.3), (1000.3, 1000.3))","(1000.3, 1000.3)","(7.780674, 7.780674)","((0.0, 7.780674), (0.0, 7.780674))","(0.0, 0.0)","(9.999994, 9.999994)","(9.999994, 9.999994)","(128434800.0, 258.1758)","((128434800.0, 128434800.0), (250.3951, 258.17...","(128434800.0, 250.3951)","(10.0, 10.0)","((10.0, 10.0), (10.0, 10.0))","(10.0, 10.0)","(-1.8746803e-13, 1.8746803e-13)","(-1.8746803e-13, 1.8746803e-13)","(-1.8746803e-13, 1.8746803e-13)","(0.0, 0.0)","(0.0, 0.0)","(544.34, 544.34)","((545.09, 544.34), (545.09, 544.34))","(545.09, 545.09)"
1,4615723899944629797,994.0,"(0.0, 0.0)","(64.28724, 64.28724)","(0.0, 0.0)","(0.0, 0.0)","(1.0, 1.0)","(0.0, 0.0)","(4.7816196e-24, 4.756155e-23)","(-9.458745e-11, 2.983143e-10)","((-9.458745e-11, -9.458745e-11, -9.458745e-11,...","(-9.458745e-11, 2.983143e-10)","(0.0123, 0.0123)","(3.073971e-25, 3.0576008e-24)","(3.3046803, 3.319371)","(3.590145, 3.89263)","((3.30468, 3.34546, 3.38624, 3.42702, 3.4678, ...","(3.30468, 3.607165)","(3.590145, 3.59014)","((3.30468, 3.34546, 3.38624, 3.42702, 3.4678, ...","(3.30468, 3.30468)","(3.590145, 3.604835)","((3.30468, 3.34546, 3.38624, 3.42702, 3.4678, ...","(3.30468, 3.31937)","(-3.405148e-10, 1.0739314e-09)","(-3.405148e-10, 1.0739314e-09)","(-3.405148e-10, 1.0739314e-09)","(1000.3, 1000.3)","(1000.3, 1000.3)","(1000.3, 1000.3)","((1000.3, 1000.3, 1000.3, 1000.3, 1000.3, 1000...","(1000.3, 1000.3)","(64.28724, 64.28724)","((0.0, 9.183891, 18.36778, 27.55167, 36.73557,...","(0.0, 0.0)","(9.999994, 9.999994)","(9.999994, 9.999994)","(43.0797, 267.8637)","((107.3669, 98.18304, 88.99916, 79.81527, 70.6...","(107.3669, 203.5764)","(10.0, 10.0)","((10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10...","(10.0, 10.0)","(-1.2185423e-13, 3.8430947e-13)","(-1.2185423e-13, 3.8430947e-13)","(-1.2185423e-13, 3.8430947e-13)","(0.0, 0.0)","(0.0, 0.0)","(562.93, 562.93)","((565.84, 565.4243, 565.0086, 564.5929, 564.17...","(565.84, 565.84)"
2,4621030304810285220,107.1,"(0.0, 0.0)","(0.0022914498, 0.0021534697)","(16.2622, 16.187708)","(0.06434689, 0.06405214)","(0.0, 0.0)","(0.0, 0.0)","(0.21113664, 0.23715848)","(-4.251046, -4.523407)","((-4.251046, -4.251046), (-4.523407, -4.523407))","(-4.251046, -4.523407)","(0.19802281, 0.19809355)","(0.0008354334, 0.00093839766)","(2.198662, 2.232901)","(2.19866, 2.91134)","((2.21037, 2.19866), (2.92093, 2.91134))","(2.21037, 2.92093)","(2.19866, 2.19866)","((2.21037, 2.19866), (2.21037, 2.19866))","(2.21037, 2.21037)","(2.19866, 2.2329)","((2.21037, 2.19866), (2.244505, 2.2329))","(2.21037, 2.244505)","(-15.303764, -16.284264)","(-15.303764, -16.284264)","(-15.303764, -16.284264)","(983.7663, 983.7623)","(983.7645, 983.7606)","(983.7645, 983.7606)","((983.7663, 983.7645), (983.7623, 983.7606))","(983.7663, 983.7623)","(3.956838, 3.956838)","((0.0, 3.956838), (0.0, 3.956838))","(0.0, 0.0)","(59.867393, 59.875362)","(59.871002, 59.878754)","(0.05315936, 0.04995842)","((0.05545081, 0.05315936), (0.05211188, 0.0499...","(0.05545081, 0.05211188)","(59.871, 59.87875)","((59.8674, 59.871), (59.87537, 59.87875))","(59.8674, 59.87537)","(-0.47966212, -0.51039565)","(-0.47966167, -0.5103952)","(-0.47966254, -0.5103961)","(0.0, 0.0)","(0.0, 0.0)","(563.14, 563.14)","((563.01, 563.14), (563.01, 563.14))","(563.01, 563.01)"
3,4621904482639719098,211.1,"(0.0, 0.0)","(0.008394263, 0.007881174)","(39.596752, 39.556736)","(0.8544683, 0.85360473)","(0.0, 0.0)","(0.0, 0.0)","(0.18498307, 0.20875517)","(-24.13726, -25.70857)","((-24.13726, -24.13726, -24.13726, -24.13726),...","(-24.13726, -25.70857)","(0.6983759, 0.6985426)","(0.003991796, 0.00450478)","(4.137745, 4.1745057)","(4.214665, 4.988325)","((4.137745, 4.163385, 4.189025, 4.214665), (4....","(4.137745, 4.90065)","(4.214665, 4.214665)","((4.137745, 4.163385, 4.189025, 4.214665), (4....","(4.137745, 4.137745)","(4.214665, 4.25194)","((4.137745, 4.163385, 4.189025, 4.214665), (4....","(4.137745, 4.174505)","(-86.89412, -92.550835)","(-86.89412, -92.550835)","(-86.89412, -92.550835)","(965.7649, 965.7609)","(965.7599, 965.7562)","(965.7599, 965.7562)","((965.7649, 965.7632, 965.7615, 965.7599), (96...","(965.7649, 965.7609)","(21.57925, 21.57925)","((0.0, 7.193083, 14.38617, 21.57925), (0.0, 7....","(0.0, 0.0)","(89.891815, 89.89842)","(89.90023, 89.90632)","(0.2075832, 0.1948991)","((0.2159775, 0.2131794, 0.2103813, 0.2075832),...","(0.2159775, 0.2027803)","(89.90024, 89.90634)","((89.89182, 89.89462, 89.89743, 89.90024), (89...","(89.89182, 89.89844)","(-0.71408725, -0.76057655)","(-0.7140854, -0.7605747)","(-0.7140891, -0.7605784)","(0.0, 0.0)","(-3045.4753, -3243.0388)","(558.05, 558.05)","((558.82, 558.5634, 558.3066, 558.05), (558.82...","(558.82, 558.82)"
4,4623301797443553869,994.0,"(0.0, 0.0)","(47.21349, 47.21349)","(0.0, 0.0)","(0.0, 0.0)","(1.0, 1.0)","(1.0, 1.0)","(7.183063e-24, 1.7695746e-24)","(-1.164153e-10, -5.729817e-11)","((-1.164153e-10, -1.164153e-10, -1.164153e-10,...","(-1.164153e-10, -5.729817e-11)","(0.10575, 0.10575)","(3.3913747e-25, 8.3547784e-26)","(2.303985, 2.3258429)","(2.32851, 2.77933)","((2.303985, 2.30889, 2.313795, 2.3187, 2.32360...","(2.303985, 2.75501)","(2.32851, 2.32851)","((2.303985, 2.30889, 2.313795, 2.3187, 2.32360...","(2.303985, 2.303985)","(2.32851, 2.350165)","((2.303985, 2.30889, 2.313795, 2.3187, 2.32360...","(2.303985, 2.325845)","(-4.1909515e-10, -2.062734e-10)","(-4.1909515e-10, -2.062734e-10)","(-4.1909515e-10, -2.062734e-10)","(1000.3, 1000.3)","(983.7, 983.7)","(983.7, 983.7)","((1000.3, 996.98, 993.66, 990.34, 987.02, 983....","(1000.3, 1000.3)","(47.21349, 47.21349)","((0.0, 9.442698, 18.8854, 28.32809, 37.77079, ...","(0.0, 0.0)","(9.999994, 9.999994)","(59.999992, 59.999992)","(3.814697e-06, 3.814697e-06)","((47.21349, 37.77079, 28.32809, 18.8854, 9.442...","(47.21349, 47.21349)","(60.0, 60.0)","((10.0, 20.0, 30.0, 40.0, 50.0, 60.0), (10.0, ...","(10.0, 10.0)","(-1.4997442e-13, -7.443836e-14)","(-1.4997442e-13, -7.381554e-14)","(-1.5250525e-13, -7.506118e-14)","(0.0, 0.0)","(0.0, 0.0)","(560.76, 560.76)","((561.01, 560.96, 560.91, 560.86, 560.81, 560....","(561.01, 561.01)"

### multiindex

But for even faster result retrieval use vec_format = "multiindex". Every interior point has its own sub column. This scales for larger models and can have quite a large time saving effect.

Unless you still rely on some older toolkit code using the str formatting to merge the results with model data, multiindex formatting is superior.

In [23]:
df_results = s3s.generate_element_results_dataframe(element_type=s3s.ObjectTypes.Pipe, bulk=True, timestamps = [0, -1], vec_format = "multiindex")

[2026-10-14 15:06:45,625] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-10-14 15:06:45,643] INFO in sir3stoolkit.mantle.dataframes: [bulk results] Result file: M-1-0-1.4.MX1 (output factor 4 = DTFAK_GROSS of the most recent calculation, default), 7 timestamps.
[2026-10-14 15:06:45,660] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-10-14 15:06:45,665] INFO in sir3stoolkit.mantle.dataframes: [results] Using 31 result properties from the result file.
[2026-10-14 15:06:45,684] INFO in sir3stoolkit.mantle.dataframes: [results] 2 timestamp(s), 524 element(s), 31 properties resolved (0.1 s).
[2026-10-14 15:06:45,684] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values... (bulk=True)
[2026-10-14 15:06:45,744] INFO in sir3stoolkit.mantle.dataframes: [bulk results] 31 properties read from M-1-0-1.4.MX1 (0.1 s).
[2026-10-14 15:06:45,744] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-10-14 15:06:45,747] INFO in sir3stoolkit.mantle.dataframes: [results] DataFrame assembled (0.0 s).
[2026-10-14 15:06:46,010] INFO in sir3stoolkit.mantle.dataframes: [results] Names/end nodes of 524 element(s) looked up (0.2 s).
[2026-10-14 15:06:46,630] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (2, 34190) (1.0 s in total)

In [24]:
df_results.head()

tk                                                                    5442010239090746007  \
name                                                                   Rohr V-K03S V-K13S
end_nodes                      ('5669301360686511351', '5397948523091900401', '-1', '-1')
property                                                                                A
interior points                                                                        -1
timestamp
2023-02-13 00:00:00.000 +01:00                                                0.0
2023-02-14 00:00:00.000 +01:00                                                0.0

tk                                                                            \
name
end_nodes
property                            DTTR     DWVERL DWVERLABS IAKTIV IRTRENN
interior points                       -1         -1        -1     -1      -1
timestamp
2023-02-13 00:00:00.000 +01:00  0.013437  35.860340  1.306369    0.0     0.0
2023-02-14 00:00:00.000 +01:00  0.012623  35.869095  1.306688    0.0     0.0

tk                                                                         \
name
end_nodes
property                              JV       MVEC
interior points                       -1          0          1          2
timestamp
2023-02-13 00:00:00.000 +01:00  0.286070  14.680074  14.680074  14.680074
2023-02-14 00:00:00.000 +01:00  0.322513  15.626842  15.626842  15.626842

tk                                                                        \
name
end_nodes
property                                                PDAMPF       PHR
interior points                         3          4        -1        -1
timestamp
2023-02-13 00:00:00.000 +01:00  14.680074  14.680074  0.693796  0.010421
2023-02-14 00:00:00.000 +01:00  15.626842  15.626842  0.694239  0.011749

tk                                                                    \
name
end_nodes
property                            PMIN     PVEC
interior points                       -1        0        1         2
timestamp
2023-02-13 00:00:00.000 +01:00  4.291403  4.50263  4.44982  4.397015
2023-02-14 00:00:00.000 +01:00  4.315597  4.52815  4.47501  4.421870

tk                                                                        \
name
end_nodes
property                                           PVECMAX_INST
interior points                        3         4            0        1
timestamp
2023-02-13 00:00:00.000 +01:00  4.344210  4.291405      4.50263  4.44982
2023-02-14 00:00:00.000 +01:00  4.368735  4.315595      5.03030  4.97056

tk                                                                        \
name
end_nodes
property                                                    PVECMIN_INST
interior points                        2        3         4            0
timestamp
2023-02-13 00:00:00.000 +01:00  4.397015  4.34421  4.291405     4.502630
2023-02-14 00:00:00.000 +01:00  4.910820  4.85108  4.791335     4.502625

tk                                                                    \
name
end_nodes
property
interior points                       1         2        3         4
timestamp
2023-02-13 00:00:00.000 +01:00  4.44982  4.397015  4.34421  4.291405
2023-02-14 00:00:00.000 +01:00  4.44982  4.397015  4.34421  4.291400

tk                                                                           \
name
end_nodes
property                             QMAV        QMI        QMK        RHOI
interior points                        -1         -1         -1          -1
timestamp
2023-02-13 00:00:00.000 +01:00  52.848267  52.848267  52.848267  965.860901
2023-02-14 00:00:00.000 +01:00  56.256630  56.256630  56.256630  965.851135

tk                                                                  \
name
end_nodes
property                              RHOK      RHOVEC
interior points                         -1           0           1
timestamp
2023-02-13 00:00:00.000 +01:00  965.873596  965.860901  965.864075
2023-02-14 00:00:00.000 +01:00  965.863098  965.851135  965.854126

tk                                                                       \
name
end_nodes
property                                                           SVEC
interior points                          2           3           4    0
timestamp
2023-02-13 00:00:00.000 +01:00  965.867249  965.870422  965.873596  0.0
2023-02-14 00:00:00.000 +01:00  965.857117  965.860107  965.863098  0.0

tk                                                                         \
name
end_nodes
property
interior points                        1          2          3          4
timestamp
2023-02-13 00:00:00.000 +01:00  9.107338  18.214676  27.322014  36.429352
2023-02-14 00:00:00.000 +01:00  9.107338  18.214676  27.322014  36.429352

tk                                                                        \
name
end_nodes
property                               TI         TK    TTRVEC
interior points                        -1         -1         0         1
timestamp
2023-02-13 00:00:00.000 +01:00  89.731827  89.710640  0.322723  0.326082
2023-02-14 00:00:00.000 +01:00  89.748070  89.728165  0.303077  0.306233

tk                                                                      \
name
end_nodes
property                                                          TVEC
interior points                        2         3        4          0
timestamp
2023-02-13 00:00:00.000 +01:00  0.329441  0.332800  0.33616  89.731842
2023-02-14 00:00:00.000 +01:00  0.309388  0.312544  0.31570  89.748077

tk                                                                          \
name
end_nodes
property
interior points                         1          2          3          4
timestamp
2023-02-13 00:00:00.000 +01:00  89.726532  89.721222  89.715942  89.710632
2023-02-14 00:00:00.000 +01:00  89.743103  89.738129  89.733154  89.728180

tk                                                                  \
name
end_nodes
property                             VAV        VI        VK VOLDA
interior points                       -1        -1        -1    -1
timestamp
2023-02-13 00:00:00.000 +01:00  0.753102  0.753107  0.753097   0.0
2023-02-14 00:00:00.000 +01:00  0.801681  0.801686  0.801676   0.0

tk                                                                   \
name
end_nodes
property                                WVL        ZVEC
interior points                          -1           0           1
timestamp
2023-02-13 00:00:00.000 +01:00  1843.650269  554.039978  554.569946
2023-02-14 00:00:00.000 +01:00  1962.688965  554.039978  554.569946

tk                                                                  \
name
end_nodes
property
interior points                          2           3           4
timestamp
2023-02-13 00:00:00.000 +01:00  555.099976  555.630005  556.159973
2023-02-14 00:00:00.000 +01:00  555.099976  555.630005  556.159973

tk                                                                    4917786378639043296  \
name                                                                   Rohr V-K13S V-K23S
end_nodes                      ('5397948523091900401', '5239335112004772156', '-1', '-1')
property                                                                                A
interior points                                                                        -1
timestamp
2023-02-13 00:00:00.000 +01:00                                                0.0
2023-02-14 00:00:00.000 +01:00                                                0.0

tk                                                                            \
name
end_nodes
property                            DTTR     DWVERL DWVERLABS IAKTIV IRTRENN
interior points                       -1         -1        -1     -1      -1
timestamp
2023-02-13 00:00:00.000 +01:00  0.025371  29.877504  1.709525    0.0     0.0
2023-02-14 00:00:00.000 +01:00  0.023853  29.890053  1.710243    0.0     0.0

tk                                                                      \
name
end_nodes
property                              JV      MVEC
interior points                       -1         0         1         2
timestamp
2023-02-13 00:00:00.000 +01:00  0.255595  8.242750  8.242750  8.242750
2023-02-14 00:00:00.000 +01:00  0.287537  8.767406  8.767406  8.767406

tk                                                                      \
name
end_nodes
property
interior points                        3         4         5         6
timestamp
2023-02-13 00:00:00.000 +01:00  8.242750  8.242750  8.242750  8.242750
2023-02-14 00:00:00.000 +01:00  8.767406  8.767406  8.767406  8.767406

tk                                                                      \
name
end_nodes
property                          PDAMPF       PHR      PMIN      PVEC
interior points                       -1        -1        -1         0
timestamp
2023-02-13 00:00:00.000 +01:00  0.692872  0.014625  3.817376  4.291405
2023-02-14 00:00:00.000 +01:00  0.693370  0.016452  3.839748  4.315595

tk                                                                     \
name
end_nodes
property
interior points                       1         2         3         4
timestamp
2023-02-13 00:00:00.000 +01:00  4.21240  4.133395  4.054390  3.975385
2023-02-14 00:00:00.000 +01:00  4.23629  4.156980  4.077675  3.998365

tk                                                                         \
name
end_nodes
property                                           PVECMAX_INST
interior points                        5         6            0         1
timestamp
2023-02-13 00:00:00.000 +01:00  3.896380  3.817375     4.291405  4.212400
2023-02-14 00:00:00.000 +01:00  3.919055  3.839750     4.791335  4.706015

tk                                                                     \
name
end_nodes
property
interior points                        2         3         4        5
timestamp
2023-02-13 00:00:00.000 +01:00  4.133395  4.054390  3.975385  3.89638
2023-02-14 00:00:00.000 +01:00  4.620695  4.535375  4.450050  4.36473

tk                                                                         \
name
end_nodes
property                                 PVECMIN_INST
interior points                        6            0         1         2
timestamp
2023-02-13 00:00:00.000 +01:00  3.817375     4.291405  4.212400  4.133395
2023-02-14 00:00:00.000 +01:00  4.279410     4.291400  4.212395  4.133395

tk                                                                    \
name
end_nodes
property
interior points                       3         4        5         6
timestamp
2023-02-13 00:00:00.000 +01:00  4.05439  3.975385  3.89638  3.817375
2023-02-14 00:00:00.000 +01:00  4.05439  3.975385  3.89638  3.817375

tk                                                                           \
name
end_nodes
property                             QMAV        QMI        QMK        RHOI
interior points                        -1         -1         -1          -1
timestamp
2023-02-13 00:00:00.000 +01:00  29.673901  29.673901  29.673901  965.873596
2023-02-14 00:00:00.000 +01:00  31.562658  31.562658  31.562658  965.863098

tk                                                                  \
name
end_nodes
property                              RHOK      RHOVEC
interior points                         -1           0           1
timestamp
2023-02-13 00:00:00.000 +01:00  965.903259  965.873596  965.878540
2023-02-14 00:00:00.000 +01:00  965.890930  965.863098  965.867737

tk                                                                  \
name
end_nodes
property
interior points                          2           3           4
timestamp
2023-02-13 00:00:00.000 +01:00  965.883484  965.888428  965.893372
2023-02-14 00:00:00.000 +01:00  965.872375  965.877014  965.881653

tk                                                                     \
name
end_nodes
property                                               SVEC
interior points                          5           6    0         1
timestamp
2023-02-13 00:00:00.000 +01:00  965.898315  965.903259  0.0  9.536302
2023-02-14 00:00:00.000 +01:00  965.886292  965.890930  0.0  9.536302

tk                                                                          \
name
end_nodes
property
interior points                         2          3          4          5
timestamp
2023-02-13 00:00:00.000 +01:00  19.072603  28.608906  38.145206  47.681507
2023-02-14 00:00:00.000 +01:00  19.072603  28.608906  38.145206  47.681507

tk                                                                        \
name
end_nodes
property                                          TI         TK   TTRVEC
interior points                         6         -1         -1        0
timestamp
2023-02-13 00:00:00.000 +01:00  57.217812  89.710640  89.661278  0.33616
2023-02-14 00:00:00.000 +01:00  57.217812  89.728165  89.681747  0.31570

tk                                                                      \
name
end_nodes
property
interior points                        1         2         3         4
timestamp
2023-02-13 00:00:00.000 +01:00  0.340388  0.344617  0.348845  0.353074
2023-02-14 00:00:00.000 +01:00  0.319675  0.323651  0.327626  0.331602

tk                                                                        \
name
end_nodes
property                                                 TVEC
interior points                        5         6          0          1
timestamp
2023-02-13 00:00:00.000 +01:00  0.357302  0.361531  89.710632  89.702423
2023-02-14 00:00:00.000 +01:00  0.335577  0.339553  89.728180  89.720428

tk                                                                          \
name
end_nodes
property
interior points                         2          3          4          5
timestamp
2023-02-13 00:00:00.000 +01:00  89.694183  89.685974  89.677734  89.669495
2023-02-14 00:00:00.000 +01:00  89.712708  89.704956  89.697235  89.689484

tk                                                                             \
name
end_nodes
property                                        VAV        VI        VK VOLDA
interior points                         6        -1        -1        -1    -1
timestamp
2023-02-13 00:00:00.000 +01:00  89.661285  0.626446  0.626456  0.626437   0.0
2023-02-14 00:00:00.000 +01:00  89.681763  0.666328  0.666337  0.666318   0.0

tk                                                                   \
name
end_nodes
property                                WVL        ZVEC
interior points                          -1           0           1
timestamp
2023-02-13 00:00:00.000 +01:00  1032.728394  556.159973  556.968323
2023-02-14 00:00:00.000 +01:00  1098.696533  556.159973  556.968323

tk                                                                             \
name
end_nodes
property
interior points                          2           3           4          5
timestamp
2023-02-13 00:00:00.000 +01:00  557.776672  558.584961  559.393311  560.20166
2023-02-14 00:00:00.000 +01:00  557.776672  558.584961  559.393311  560.20166

tk                                         \
name
end_nodes
property
interior points                         6
timestamp
2023-02-13 00:00:00.000 +01:00  561.01001
2023-02-14 00:00:00.000 +01:00  561.01001

tk                                                                    4762482310382009633  \
name                                                                   Rohr V-K23S V-K33S
end_nodes                      ('5239335112004772156', '5298886695042021307', '-1', '-1')
property                                                                                A
interior points                                                                        -1
timestamp
2023-02-13 00:00:00.000 +01:00                                                0.0
2023-02-14 00:00:00.000 +01:00                                                0.0

tk                                                                            \
name
end_nodes
property                            DTTR     DWVERL DWVERLABS IAKTIV IRTRENN
interior points                       -1         -1        -1     -1      -1
timestamp
2023-02-13 00:00:00.000 +01:00  0.017832  29.802269  1.221739    0.0     0.0
2023-02-14 00:00:00.000 +01:00  0.016756  29.825066  1.222673    0.0     0.0

tk                                                                      \
name
end_nodes
property                              JV      MVEC
interior points                       -1         0         1         2
timestamp
2023-02-13 00:00:00.000 +01:00  0.265203  8.403428  8.403428  8.403428
2023-02-14 00:00:00.000 +01:00  0.298659  8.942982  8.942982  8.942982

tk                                                                      \
name
end_nodes
property                                                        PDAMPF
interior points                        3         4         5        -1
timestamp
2023-02-13 00:00:00.000 +01:00  8.403428  8.403428  8.403428  0.687946
2023-02-14 00:00:00.000 +01:00  8.942982  8.942982  8.942982  0.688737

tk                                                                     \
name
end_nodes
property                             PHR      PMIN      PVEC
interior points                       -1        -1         0        1
timestamp
2023-02-13 00:00:00.000 +01:00  0.010872  3.612304  3.817375  3.77636
2023-02-14 00:00:00.000 +01:00  0.012243  3.633308  3.839750  3.79846

tk                                                                     \
name
end_nodes
property
interior points                       2         3         4         5
timestamp
2023-02-13 00:00:00.000 +01:00  3.73535  3.694335  3.653320  3.612305
2023-02-14 00:00:00.000 +01:00  3.75717  3.715885  3.674595  3.633310

tk                                                                         \
name
end_nodes
property                       PVECMAX_INST
interior points                           0         1         2         3
timestamp
2023-02-13 00:00:00.000 +01:00     3.817375  3.776360  3.735350  3.694335
2023-02-14 00:00:00.000 +01:00     4.279410  4.232685  4.185965  4.139240

tk                                                                       \
name
end_nodes
property                                          PVECMIN_INST
interior points                       4         5            0        1
timestamp
2023-02-13 00:00:00.000 +01:00  3.65332  3.612305     3.817375  3.77636
2023-02-14 00:00:00.000 +01:00  4.09252  4.045800     3.817375  3.77636

tk                                                                     \
name
end_nodes
property
interior points                        2         3        4         5
timestamp
2023-02-13 00:00:00.000 +01:00  3.735350  3.694335  3.65332  3.612305
2023-02-14 00:00:00.000 +01:00  3.735345  3.694330  3.65332  3.612305

tk                                                                           \
name
end_nodes
property                             QMAV        QMI        QMK        RHOI
interior points                        -1         -1         -1          -1
timestamp
2023-02-13 00:00:00.000 +01:00  30.252340  30.252340  30.252340  965.990845
2023-02-14 00:00:00.000 +01:00  32.194733  32.194733  32.194733  965.973389

tk                                                                  \
name
end_nodes
property                              RHOK      RHOVEC
interior points                         -1           0           1
timestamp
2023-02-13 00:00:00.000 +01:00  966.011597  965.990845  965.994995
2023-02-14 00:00:00.000 +01:00  965.992920  965.973389  965.977295

tk                                                                  \
name
end_nodes
property
interior points                          2           3           4
timestamp
2023-02-13 00:00:00.000 +01:00  965.999146  966.003296  966.007446
2023-02-14 00:00:00.000 +01:00  965.981201  965.985107  965.989014

tk                                                                    \
name
end_nodes
property                                   SVEC

Note that the access to the interior points therefore also changes.

In [25]:
vec = df_results.xs((tk_of_interest, "PVEC"), axis=1, level=["tk", "property"]).loc[timestamp_of_interest].to_list()

In [26]:
type(vec)

list

In [27]:
vec

[4.50262975692749,
 4.449820041656494,
 4.39701509475708,
 4.344209671020508,
 4.291404724121094]

The data access can also be facilitated if you drop index levels "name" and "end_nodes".

In [28]:
df_results.columns = df_results.columns.droplevel(["name", "end_nodes"])

Using other methods of removing the levels might take long time and memory.

In [29]:
df_results.head()

tk                             5442010239090746007                       \
property                                         A      DTTR     DWVERL
interior points                                 -1        -1         -1
timestamp
2023-02-13 00:00:00.000 +01:00                 0.0  0.013437  35.860340
2023-02-14 00:00:00.000 +01:00                 0.0  0.012623  35.869095

tk                                                                            \
property                       DWVERLABS IAKTIV IRTRENN        JV       MVEC
interior points                       -1     -1      -1        -1          0
timestamp
2023-02-13 00:00:00.000 +01:00  1.306369    0.0     0.0  0.286070  14.680074
2023-02-14 00:00:00.000 +01:00  1.306688    0.0     0.0  0.322513  15.626842

tk                                                                          \
property
interior points                         1          2          3          4
timestamp
2023-02-13 00:00:00.000 +01:00  14.680074  14.680074  14.680074  14.680074
2023-02-14 00:00:00.000 +01:00  15.626842  15.626842  15.626842  15.626842

tk                                                                     \
property                          PDAMPF       PHR      PMIN     PVEC
interior points                       -1        -1        -1        0
timestamp
2023-02-13 00:00:00.000 +01:00  0.693796  0.010421  4.291403  4.50263
2023-02-14 00:00:00.000 +01:00  0.694239  0.011749  4.315597  4.52815

tk                                                                     \
property
interior points                       1         2         3         4
timestamp
2023-02-13 00:00:00.000 +01:00  4.44982  4.397015  4.344210  4.291405
2023-02-14 00:00:00.000 +01:00  4.47501  4.421870  4.368735  4.315595

tk                                                                       \
property                       PVECMAX_INST
interior points                           0        1         2        3
timestamp
2023-02-13 00:00:00.000 +01:00      4.50263  4.44982  4.397015  4.34421
2023-02-14 00:00:00.000 +01:00      5.03030  4.97056  4.910820  4.85108

tk                                                                        \
property                                 PVECMIN_INST
interior points                        4            0        1         2
timestamp
2023-02-13 00:00:00.000 +01:00  4.291405     4.502630  4.44982  4.397015
2023-02-14 00:00:00.000 +01:00  4.791335     4.502625  4.44982  4.397015

tk                                                                       \
property                                                QMAV        QMI
interior points                       3         4         -1         -1
timestamp
2023-02-13 00:00:00.000 +01:00  4.34421  4.291405  52.848267  52.848267
2023-02-14 00:00:00.000 +01:00  4.34421  4.291400  56.256630  56.256630

tk                                                                             \
property                              QMK        RHOI        RHOK      RHOVEC
interior points                        -1          -1          -1           0
timestamp
2023-02-13 00:00:00.000 +01:00  52.848267  965.860901  965.873596  965.860901
2023-02-14 00:00:00.000 +01:00  56.256630  965.851135  965.863098  965.851135

tk                                                                  \
property
interior points                          1           2           3
timestamp
2023-02-13 00:00:00.000 +01:00  965.864075  965.867249  965.870422
2023-02-14 00:00:00.000 +01:00  965.854126  965.857117  965.860107

tk                                                                    \
property                                   SVEC
interior points                          4    0         1          2
timestamp
2023-02-13 00:00:00.000 +01:00  965.873596  0.0  9.107338  18.214676
2023-02-14 00:00:00.000 +01:00  965.863098  0.0  9.107338  18.214676

tk                                                                          \
property                                                     TI         TK
interior points                         3          4         -1         -1
timestamp
2023-02-13 00:00:00.000 +01:00  27.322014  36.429352  89.731827  89.710640
2023-02-14 00:00:00.000 +01:00  27.322014  36.429352  89.748070  89.728165

tk                                                                      \
property                          TTRVEC
interior points                        0         1         2         3
timestamp
2023-02-13 00:00:00.000 +01:00  0.322723  0.326082  0.329441  0.332800
2023-02-14 00:00:00.000 +01:00  0.303077  0.306233  0.309388  0.312544

tk                                                                        \
property                                      TVEC
interior points                       4          0          1          2
timestamp
2023-02-13 00:00:00.000 +01:00  0.33616  89.731842  89.726532  89.721222
2023-02-14 00:00:00.000 +01:00  0.31570  89.748077  89.743103  89.738129

tk                                                                        \
property                                                   VAV        VI
interior points                         3          4        -1        -1
timestamp
2023-02-13 00:00:00.000 +01:00  89.715942  89.710632  0.753102  0.753107
2023-02-14 00:00:00.000 +01:00  89.733154  89.728180  0.801681  0.801686

tk                                                                       \
property                              VK VOLDA          WVL        ZVEC
interior points                       -1    -1           -1           0
timestamp
2023-02-13 00:00:00.000 +01:00  0.753097   0.0  1843.650269  554.039978
2023-02-14 00:00:00.000 +01:00  0.801676   0.0  1962.688965  554.039978

tk                                                                  \
property
interior points                          1           2           3
timestamp
2023-02-13 00:00:00.000 +01:00  554.569946  555.099976  555.630005
2023-02-14 00:00:00.000 +01:00  554.569946  555.099976  555.630005

tk                                         4917786378639043296            \
property                                                     A      DTTR
interior points                          4                  -1        -1
timestamp
2023-02-13 00:00:00.000 +01:00  556.159973                 0.0  0.025371
2023-02-14 00:00:00.000 +01:00  556.159973                 0.0  0.023853

tk                                                                            \
property                           DWVERL DWVERLABS IAKTIV IRTRENN        JV
interior points                        -1        -1     -1      -1        -1
timestamp
2023-02-13 00:00:00.000 +01:00  29.877504  1.709525    0.0     0.0  0.255595
2023-02-14 00:00:00.000 +01:00  29.890053  1.710243    0.0     0.0  0.287537

tk                                                                      \
property                            MVEC
interior points                        0         1         2         3
timestamp
2023-02-13 00:00:00.000 +01:00  8.242750  8.242750  8.242750  8.242750
2023-02-14 00:00:00.000 +01:00  8.767406  8.767406  8.767406  8.767406

tk                                                                      \
property                                                        PDAMPF
interior points                        4         5         6        -1
timestamp
2023-02-13 00:00:00.000 +01:00  8.242750  8.242750  8.242750  0.692872
2023-02-14 00:00:00.000 +01:00  8.767406  8.767406  8.767406  0.693370

tk                                                                     \
property                             PHR      PMIN      PVEC
interior points                       -1        -1         0        1
timestamp
2023-02-13 00:00:00.000 +01:00  0.014625  3.817376  4.291405  4.21240
2023-02-14 00:00:00.000 +01:00  0.016452  3.839748  4.315595  4.23629

tk                                                                      \
property
interior points                        2         3         4         5
timestamp
2023-02-13 00:00:00.000 +01:00  4.133395  4.054390  3.975385  3.896380
2023-02-14 00:00:00.000 +01:00  4.156980  4.077675  3.998365  3.919055

tk                                                                         \
property                                 PVECMAX_INST
interior points                        6            0         1         2
timestamp
2023-02-13 00:00:00.000 +01:00  3.817375     4.291405  4.212400  4.133395
2023-02-14 00:00:00.000 +01:00  3.839750     4.791335  4.706015  4.620695

tk                                                                     \
property
interior points                        3         4        5         6
timestamp
2023-02-13 00:00:00.000 +01:00  4.054390  3.975385  3.89638  3.817375
2023-02-14 00:00:00.000 +01:00  4.535375  4.450050  4.36473  4.279410

tk                                                                        \
property                       PVECMIN_INST
interior points                           0         1         2        3
timestamp
2023-02-13 00:00:00.000 +01:00     4.291405  4.212400  4.133395  4.05439
2023-02-14 00:00:00.000 +01:00     4.291400  4.212395  4.133395  4.05439

tk                                                                      \
property                                                          QMAV
interior points                        4        5         6         -1
timestamp
2023-02-13 00:00:00.000 +01:00  3.975385  3.89638  3.817375  29.673901
2023-02-14 00:00:00.000 +01:00  3.975385  3.89638  3.817375  31.562658

tk                                                                            \
property                              QMI        QMK        RHOI        RHOK
interior points                        -1         -1          -1          -1
timestamp
2023-02-13 00:00:00.000 +01:00  29.673901  29.673901  965.873596  965.903259
2023-02-14 00:00:00.000 +01:00  31.562658  31.562658  965.863098  965.890930

tk                                                                  \
property                            RHOVEC
interior points                          0           1           2
timestamp
2023-02-13 00:00:00.000 +01:00  965.873596  965.878540  965.883484
2023-02-14 00:00:00.000 +01:00  965.863098  965.867737  965.872375

tk                                                                  \
property
interior points                          3           4           5
timestamp
2023-02-13 00:00:00.000 +01:00  965.888428  965.893372  965.898315
2023-02-14 00:00:00.000 +01:00  965.877014  965.881653  965.886292

tk                                                                    \
property                                   SVEC
interior points                          6    0         1          2
timestamp
2023-02-13 00:00:00.000 +01:00  965.903259  0.0  9.536302  19.072603
2023-02-14 00:00:00.000 +01:00  965.890930  0.0  9.536302  19.072603

tk                                                                          \
property
interior points                         3          4          5          6
timestamp
2023-02-13 00:00:00.000 +01:00  28.608906  38.145206  47.681507  57.217812
2023-02-14 00:00:00.000 +01:00  28.608906  38.145206  47.681507  57.217812

tk                                                                       \
property                               TI         TK   TTRVEC
interior points                        -1         -1        0         1
timestamp
2023-02-13 00:00:00.000 +01:00  89.710640  89.661278  0.33616  0.340388
2023-02-14 00:00:00.000 +01:00  89.728165  89.681747  0.31570  0.319675

tk                                                                      \
property
interior points                        2         3         4         5
timestamp
2023-02-13 00:00:00.000 +01:00  0.344617  0.348845  0.353074  0.357302
2023-02-14 00:00:00.000 +01:00  0.323651  0.327626  0.331602  0.335577

tk                                                                         \
property                                       TVEC
interior points                        6          0          1          2
timestamp
2023-02-13 00:00:00.000 +01:00  0.361531  89.710632  89.702423  89.694183
2023-02-14 00:00:00.000 +01:00  0.339553  89.728180  89.720428  89.712708

tk                                                                          \
property
interior points                         3          4          5          6
timestamp
2023-02-13 00:00:00.000 +01:00  89.685974  89.677734  89.669495  89.661285
2023-02-14 00:00:00.000 +01:00  89.704956  89.697235  89.689484  89.681763

tk                                                                  \
property                             VAV        VI        VK VOLDA
interior points                       -1        -1        -1    -1
timestamp
2023-02-13 00:00:00.000 +01:00  0.626446  0.626456  0.626437   0.0
2023-02-14 00:00:00.000 +01:00  0.666328  0.666337  0.666318   0.0

tk                                                                   \
property                                WVL        ZVEC
interior points                          -1           0           1
timestamp
2023-02-13 00:00:00.000 +01:00  1032.728394  556.159973  556.968323
2023-02-14 00:00:00.000 +01:00  1098.696533  556.159973  556.968323

tk                                                                             \
property
interior points                          2           3           4          5
timestamp
2023-02-13 00:00:00.000 +01:00  557.776672  558.584961  559.393311  560.20166
2023-02-14 00:00:00.000 +01:00  557.776672  558.584961  559.393311  560.20166

tk                                        4762482310382009633            \
property                                                    A      DTTR
interior points                         6                  -1        -1
timestamp
2023-02-13 00:00:00.000 +01:00  561.01001                 0.0  0.017832
2023-02-14 00:00:00.000 +01:00  561.01001                 0.0  0.016756

tk                                                                            \
property                           DWVERL DWVERLABS IAKTIV IRTRENN        JV
interior points                        -1        -1     -1      -1        -1
timestamp
2023-02-13 00:00:00.000 +01:00  29.802269  1.221739    0.0     0.0  0.265203
2023-02-14 00:00:00.000 +01:00  29.825066  1.222673    0.0     0.0  0.298659

tk                                                                      \
property                            MVEC
interior points                        0         1         2         3
timestamp
2023-02-13 00:00:00.000 +01:00  8.403428  8.403428  8.403428  8.403428
2023-02-14 00:00:00.000 +01:00  8.942982  8.942982  8.942982  8.942982

tk                                                                      \
property                                              PDAMPF       PHR
interior points                        4         5        -1        -1
timestamp
2023-02-13 00:00:00.000 +01:00  8.403428  8.403428  0.687946  0.010872
2023-02-14 00:00:00.000 +01:00  8.942982  8.942982  0.688737  0.012243

tk                                                                    \
property                            PMIN      PVEC
interior points                       -1         0        1        2
timestamp
2023-02-13 00:00:00.000 +01:00  3.612304  3.817375  3.77636  3.73535
2023-02-14 00:00:00.000 +01:00  3.633308  3.839750  3.79846  3.75717

tk                                                                         \
property                                                     PVECMAX_INST
interior points                        3         4         5            0
timestamp
2023-02-13 00:00:00.000 +01:00  3.694335  3.653320  3.612305     3.817375
2023-02-14 00:00:00.000 +01:00  3.715885  3.674595  3.633310     4.279410

tk                                                                     \
property
interior points                        1         2         3        4
timestamp
2023-02-13 00:00:00.000 +01:00  3.776360  3.735350  3.694335  3.65332
2023-02-14 00:00:00.000 +01:00  4.232685  4.185965  4.139240  4.09252

tk                                                                        \
property                                 PVECMIN_INST
interior points                        5            0        1         2
timestamp
2023-02-13 00:00:00.000 +01:00  3.612305     3.817375  3.77636  3.735350
2023-02-14 00:00:00.000 +01:00  4.045800     3.817375  3.77636  3.735345

tk                                                                      \
property                                                          QMAV
interior points                        3        4         5         -1
timestamp
2023-02-13 00:00:00.000 +01:00  3.694335  3.65332  3.612305  30.252340
2023-02-14 00:00:00.000 +01:00  3.694330  3.65332  3.612305  32.194733

tk                                                                            \
property                              QMI        QMK        RHOI        RHOK
interior points                        -1         -1          -1          -1
timestamp
2023-02-13 00:00:00.000 +01:00  30.252340  30.252340  965.990845  966.011597
2023-02-14 00:00:00.000 +01:00  32.194733  32.194733  965.973389  965.992920

tk                                                                  \
property                            RHOVEC
interior points                          0           1           2
timestamp
2023-02-13 00:00:00.000 +01:00  965.990845  965.994995  965.999146
2023-02-14 00:00:00.000 +01:00  965.973389  965.977295  965.981201

tk                                                                       \
property                                                           SVEC
interior points                          3           4           5    0
timestamp
2023-02-13 00:00:00.000 +01:00  966.003296  966.007446  966.011597  0.0
2023-02-14 00:00:00.000 +01:00  965.985107  965.989014  965.992920  0.0

tk                                                                         \
property
interior points                        1          2          3          4
timestamp
2023-02-13 00:00:00.000 +01:00  8.198964  16.397928  24.596893  32.795856
2023-02-14 00:00:00.000 +01:00  8.198964  16.397928  24.596893  32.795856

tk                                                                        \
property                                         TI         TK    TTRVEC
interior points                        5         -1         -1         0
timestamp
2023-02-13 00:00:00.000 +01:00  40.99482  89.515236  89.480629  0.428837
2023-02-14 00:00:00.000 +01:00  40.99482  89.544388  89.511848  0.402829

tk                                                                      \
property
interior points                        1         2         3         4
timestamp
2023-02-13 00:00:00.000 +01:00  0.432404  0.435970  0.439537  0.443103
2023-02-14 00:00:00.000 +01:00  0.406180  0.409531  0.412883  0.416234

tk                                                                         \
property                                       TVEC
interior points                        5          0          1          2
timestamp
2023-02-13 00:00:00.000 +01:00  0.446670  89.515228  89.508331  89.501404
2023-02-14 00:00:00.000 +01:00  0.419585  89.544403  89.537872  89.531372

tk                                                                         \
property                                                              VAV
interior points                         3          4          5        -1
timestamp
2023-02-13 00:00:00.000 +01:00  89.494476  89.487549  89.480621  0.638583
2023-02-14 00:00:00.000 +01:00  89.524872  89.518372  89.511841  0.679597

tk                                                                     \
property                              VI        VK VOLDA          WVL
interior points                       -1        -1    -1           -1
timestamp
2023-02-13 00:00:00.000 +01:00  0.638590  0.638576   0.0  1045.860596

In [30]:
vec = df_results.loc[timestamp_of_interest, (tk_of_interest, "PVEC")].to_list()

In [31]:
vec

[4.50262975692749,
 4.449820041656494,
 4.39701509475708,
 4.344209671020508,
 4.291404724121094]

#### merge with model data

In [32]:
df = s3s.merge_model_data_and_results(df_model_data, df_results)

In [33]:
df.head()

,tk,Di,A,DTTR,DWVERL,DWVERLABS,IAKTIV,IRTRENN,JV,MVEC_end,MVEC_sequence,MVEC_start,PDAMPF,PHR,PMIN,PVECMAX_INST_end,PVECMAX_INST_sequence,PVECMAX_INST_start,PVECMIN_INST_end,PVECMIN_INST_sequence,PVECMIN_INST_start,PVEC_end,PVEC_sequence,PVEC_start,QMAV,QMI,QMK,RHOI,RHOK,RHOVEC_end,RHOVEC_sequence,RHOVEC_start,SVEC_end,SVEC_sequence,SVEC_start,TI,TK,TTRVEC_end,TTRVEC_sequence,TTRVEC_start,TVEC_end,TVEC_sequence,TVEC_start,VAV,VI,VK,VOLDA,WVL,ZVEC_end,ZVEC_sequence,ZVEC_start
0,4614463970292122863,994.0,"(0.0, 0.0)","(7.780674, 7.780674)","(0.0, 0.0)","(0.0, 0.0)","(1.0, 1.0)","(0.0, 0.0)","(1.1317442e-23, 1.1317442e-23)","(-1.4551915e-10, 1.4551915e-10)","((-1.4551915e-10, -1.4551915e-10), (1.4551915e...","(-1.4551915e-10, 1.4551915e-10)","(0.0123, 0.0123)","(8.805733e-26, 8.805733e-26)","(1.6150573, 1.6150573)","(1.68863, 1.688645)","((1.615055, 1.68863), (1.615075, 1.688645))","(1.615055, 1.615075)","(1.68863, 1.68863)","((1.615055, 1.68863), (1.615055, 1.68863))","(1.615055, 1.615055)","(1.68863, 1.68863)","((1.615055, 1.68863), (1.615055, 1.68863))","(1.615055, 1.615055)","(-5.2386895e-10, 5.2386895e-10)","(-5.2386895e-10, 5.2386895e-10)","(-5.2386895e-10, 5.2386895e-10)","(1000.3, 1000.3)","(1000.3, 1000.3)","(1000.3, 1000.3)","((1000.3, 1000.3), (1000.3, 1000.3))","(1000.3, 1000.3)","(7.780674, 7.780674)","((0.0, 7.780674), (0.0, 7.780674))","(0.0, 0.0)","(9.999994, 9.999994)","(9.999994, 9.999994)","(128434776.0, 258.17575)","((128434780.0, 128434776.0), (250.39507, 258.1...","(128434780.0, 250.39507)","(10.0, 10.0)","((10.0, 10.0), (10.0, 10.0))","(10.0, 10.0)","(-1.8746803e-13, 1.8746803e-13)","(-1.8746803e-13, 1.8746803e-13)","(-1.8746803e-13, 1.8746803e-13)","(0.0, 0.0)","(0.0, 0.0)","(544.34, 544.34)","((545.09, 544.34), (545.09, 544.34))","(545.09, 545.09)"
1,4615723899944629797,994.0,"(0.0, 0.0)","(64.28724, 64.28724)","(0.0, 0.0)","(0.0, 0.0)","(1.0, 1.0)","(0.0, 0.0)","(4.7816196e-24, 4.756155e-23)","(-9.458745e-11, 2.9831426e-10)","((-9.458745e-11, -9.458745e-11, -9.458745e-11,...","(-9.458745e-11, 2.9831426e-10)","(0.0123, 0.0123)","(3.073971e-25, 3.0576008e-24)","(3.3046803, 3.319371)","(3.5901449, 3.8926299)","((3.3046799, 3.34546, 3.38624, 3.4270198, 3.46...","(3.3046799, 3.6071649)","(3.5901449, 3.5901399)","((3.3046799, 3.34546, 3.38624, 3.4270198, 3.46...","(3.3046799, 3.3046799)","(3.5901449, 3.6048348)","((3.3046799, 3.34546, 3.38624, 3.4270198, 3.46...","(3.3046799, 3.31937)","(-3.405148e-10, 1.0739314e-09)","(-3.405148e-10, 1.0739314e-09)","(-3.405148e-10, 1.0739314e-09)","(1000.3, 1000.3)","(1000.3, 1000.3)","(1000.3, 1000.3)","((1000.3, 1000.3, 1000.3, 1000.3, 1000.3, 1000...","(1000.3, 1000.3)","(64.28724, 64.28724)","((0.0, 9.183891, 18.367783, 27.551674, 36.7355...","(0.0, 0.0)","(9.999994, 9.999994)","(9.999994, 9.999994)","(43.0797, 267.86368)","((107.366936, 98.183044, 88.99916, 79.81527, 7...","(107.366936, 203.57645)","(10.0, 10.0)","((10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10...","(10.0, 10.0)","(-1.2185423e-13, 3.8430947e-13)","(-1.2185423e-13, 3.8430947e-13)","(-1.2185423e-13, 3.8430947e-13)","(0.0, 0.0)","(0.0, 0.0)","(562.93, 562.93)","((565.84, 565.4243, 565.0086, 564.5929, 564.17...","(565.84, 565.84)"
2,4621030304810285220,107.1,"(0.0, 0.0)","(0.0022914498, 0.0021534697)","(16.2622, 16.187708)","(0.06434689, 0.06405214)","(0.0, 0.0)","(0.0, 0.0)","(0.21113664, 0.23715848)","(-4.2510457, -4.5234065)","((-4.2510457, -4.2510457), (-4.5234065, -4.523...","(-4.2510457, -4.5234065)","(0.19802281, 0.19809355)","(0.0008354334, 0.00093839766)","(2.198662, 2.232901)","(2.19866, 2.91134)","((2.2103698, 2.19866), (2.92093, 2.91134))","(2.2103698, 2.92093)","(2.19866, 2.19866)","((2.2103698, 2.19866), (2.2103698, 2.19866))","(2.2103698, 2.2103698)","(2.19866, 2.2329)","((2.2103698, 2.19866), (2.244505, 2.2329))","(2.2103698, 2.244505)","(-15.303764, -16.284264)","(-15.303764, -16.284264)","(-15.303764, -16.284264)","(983.7663, 983.7623)","(983.7645, 983.7606)","(983.7645, 983.7606)","((983.7663, 983.7645), (983.7623, 983.7606))","(983.7663, 983.7623)","(3.956838, 3.956838)","((0.0, 3.956838), (0.0, 3.956838))","(0.0, 0.0)","(59.867393, 59.875362)","(59.871002, 59.878754)","(0.053159364, 0.049958415)","((0.055450812, 0.053159364), (0.052111883, 0.0...","(0.055450812, 0.052111883)","(59.871002, 59.878754)","((59.8674, 59.871002), (59.875366, 59.878754))","(59.8674, 59.875366)","(-0.47966212, -0.51039565)","(-0.47966167, -0.5103952)","(-0.47966254, -0.5103961)","(0.0, 0.0)","(0.0, 0.0)","(563.14, 563.14)","((563.01, 563.14), (563.01, 563.14))","(563.01, 563.01)"
3,4621904482639719098,211.1,"(0.0, 0.0)","(0.008394263, 0.007881174)","(39.596752, 39.556736)","(0.8544683, 0.85360473)","(0.0, 0.0)","(0.0, 0.0)","(0.18498307, 0.20875517)","(-24.137257, -25.708567)","((-24.137257, -24.137257, -24.137257, -24.1372...","(-24.137257, -25.708567)","(0.6983759, 0.6985426)","(0.003991796, 0.00450478)","(4.137745, 4.1745057)","(4.214665, 4.9883246)","((4.137745, 4.163385, 4.189025, 4.214665), (4....","(4.137745, 4.90065)","(4.214665, 4.214665)","((4.137745, 4.163385, 4.189025, 4.214665), (4....","(4.137745, 4.137745)","(4.214665, 4.25194)","((4.137745, 4.163385, 4.189025, 4.214665), (4....","(4.137745, 4.1745048)","(-86.89412, -92.550835)","(-86.89412, -92.550835)","(-86.89412, -92.550835)","(965.7649, 965.7609)","(965.7599, 965.7562)","(965.7599, 965.7562)","((965.7649, 965.76324, 965.76154, 965.7599), (...","(965.7649, 965.7609)","(21.57925, 21.57925)","((0.0, 7.1930833, 14.386167, 21.57925), (0.0, ...","(0.0, 0.0)","(89.891815, 89.89842)","(89.90023, 89.90632)","(0.20758325, 0.19489911)","((0.2159775, 0.21317942, 0.21038133, 0.2075832...","(0.2159775, 0.20278029)","(89.90024, 89.90634)","((89.891815, 89.89462, 89.89743, 89.90024), (8...","(89.891815, 89.89844)","(-0.71408725, -0.76057655)","(-0.7140854, -0.7605747)","(-0.7140891, -0.7605784)","(0.0, 0.0)","(-3045.4753, -3243.0388)","(558.05, 558.05)","((558.82, 558.56335, 558.30664, 558.05), (558....","(558.82, 558.82)"
4,4623301797443553869,994.0,"(0.0, 0.0)","(47.21349, 47.21349)","(0.0, 0.0)","(0.0, 0.0)","(1.0, 1.0)","(1.0, 1.0)","(7.183063e-24, 1.7695746e-24)","(-1.1641532e-10, -5.7298166e-11)","((-1.1641532e-10, -1.1641532e-10, -1.1641532e-...","(-1.1641532e-10, -5.7298166e-11)","(0.10575, 0.10575)","(3.3913747e-25, 8.3547784e-26)","(2.303985, 2.3258429)","(2.32851, 2.77933)","((2.3039849, 2.3088899, 2.3137949, 2.3186998, ...","(2.3039849, 2.75501)","(2.32851, 2.32851)","((2.3039849, 2.3088899, 2.3137949, 2.3186998, ...","(2.3039849, 2.3039849)","(2.32851, 2.350165)","((2.3039849, 2.3088899, 2.3137949, 2.3186998, ...","(2.3039849, 2.325845)","(-4.1909515e-10, -2.062734e-10)","(-4.1909515e-10, -2.062734e-10)","(-4.1909515e-10, -2.062734e-10)","(1000.3, 1000.3)","(983.7, 983.7)","(983.7, 983.7)","((1000.3, 996.98, 993.66, 990.34, 987.02, 983....","(1000.3, 1000.3)","(47.213486, 47.213486)","((0.0, 9.442698, 18.885395, 28.328093, 37.7707...","(0.0, 0.0)","(9.999994, 9.999994)","(59.999992, 59.999992)","(3.8146973e-06, 3.8146973e-06)","((47.21349, 37.77079, 28.328094, 18.885397, 9....","(47.21349, 47.21349)","(60.0, 60.0)","((10.0, 20.0, 30.0, 40.0, 50.0, 60.0), (10.0, ...","(10.0, 10.0)","(-1.4997442e-13, -7.443836e-14)","(-1.4997442e-13, -7.381554e-14)","(-1.5250525e-13, -7.506118e-14)","(0.0, 0.0)","(0.0, 0.0)","(560.76, 560.76)","((561.01, 560.96, 560.91003, 560.86, 560.81, 5...","(561.01, 561.01)"

## Output Factors

In SIR 3S calculation settings the output factors large and small are determined. Unless they are identical two result files with output factor as postfix are created.

### Large

We can use the function [get_result_file_properties()](https://3sconsult.github.io/sir3stoolkit/references/sir3stoolkit.mantle.html#sir3stoolkit.mantle.dataframes.SIR3S_Model_Dataframes.get_result_file_properties) to check what properties are stored for a certain output factor.

In [34]:
s3s.get_result_file_properties(output_factor=4).head()

[2026-10-14 15:06:53,351] INFO in sir3stoolkit.mantle.dataframes: [results] M-1-0-1.4.MX1 (output factor 4 = DTFAK_GROSS of the most recent calculation, output_factor parameter): 179 result properties of 22 element type(s), 7 timestamps.

,element_type,objtype,property,unit,description,stored_for,result_file,n_timestamps
0,DistrictHeatingFeeder,FWES,DPH,[bar],Reibungsdruckverlust/-druckverlusthöhe,all elements,M-1-0-1.4.MX1,7
1,DistrictHeatingFeeder,FWES,IAKTIV,[],Netztrennstatus,all elements,M-1-0-1.4.MX1,7
2,DistrictHeatingFeeder,FWES,IHYTYP,[],Hydraulische Fahrweise,all elements,M-1-0-1.4.MX1,7
3,DistrictHeatingFeeder,FWES,ITHTYP,[],Thermische Fahrweise,all elements,M-1-0-1.4.MX1,7
4,DistrictHeatingFeeder,FWES,QM,[t/h],Durchfluss,all elements,M-1-0-1.4.MX1,7

By default generate_element_results_dataframe(bulk=True) reads the largest output factor file, or a file without an output factor if it existed.

In [35]:
df_results = s3s.generate_element_results_dataframe(element_type=s3s.ObjectTypes.Pipe, properties=["PVEC", "DTTR"], bulk=True, vec_format = "multiindex")

[2026-10-14 15:06:53,401] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-10-14 15:06:53,414] INFO in sir3stoolkit.mantle.dataframes: [bulk results] Result file: M-1-0-1.4.MX1 (output factor 4 = DTFAK_GROSS of the most recent calculation, default), 7 timestamps.
[2026-10-14 15:06:53,424] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-10-14 15:06:53,424] INFO in sir3stoolkit.mantle.dataframes: [results] Using 2 result properties from the result file.
[2026-10-14 15:06:53,447] INFO in sir3stoolkit.mantle.dataframes: [results] 7 timestamp(s), 524 element(s), 2 properties resolved (0.0 s).
[2026-10-14 15:06:53,450] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values... (bulk=True)
[2026-10-14 15:06:53,466] INFO in sir3stoolkit.mantle.dataframes: [bulk results] 2 properties read from M-1-0-1.4.MX1 (0.0 s).
[2026-10-14 15:06:53,467] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-10-14 15:06:53,470] INFO in sir3stoolkit.mantle.dataframes: [results] DataFrame assembled (0.0 s).
[2026-10-14 15:06:53,666] INFO in sir3stoolkit.mantle.dataframes: [results] Names/end nodes of 524 element(s) looked up (0.2 s).
[2026-10-14 15:06:53,705] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (7, 3042) (0.3 s in total)

In [36]:
df_results.index

Index(['2023-02-13 00:00:00.000 +01:00', '2023-02-13 04:00:00.000 +01:00',
       '2023-02-13 08:00:00.000 +01:00', '2023-02-13 12:00:00.000 +01:00',
       '2023-02-13 16:00:00.000 +01:00', '2023-02-13 20:00:00.000 +01:00',
       '2023-02-14 00:00:00.000 +01:00'],
      dtype='object', name='timestamp')

### Small

Result properties in the file for the small output factor are determined by the time curves set in SIR 3S.

In [37]:
s3s.get_result_file_properties(output_factor=2)

[2026-10-14 15:06:53,861] INFO in sir3stoolkit.mantle.mx: [mx] M-1-0-1.2.MXS: 48 channels, 16 records of 296 bytes (0.00 GiB).
[2026-10-14 15:06:53,896] INFO in sir3stoolkit.mantle.dataframes: [results] M-1-0-1.2.MX1 (output factor 2 = DTFAK_KLEIN of the most recent calculation, output_factor parameter): 6 result properties of 5 element type(s), 13 timestamps.

,element_type,objtype,property,unit,description,stored_for,result_file,n_timestamps
0,Divider,RDIV,XA,[signal],Signalwert am Ausgang,single elements,M-1-0-1.2.MX1,13
1,FunctionGenerator,RFKT,XA,[signal],Signalwert am Ausgang,single elements,M-1-0-1.2.MX1,13
2,Transmitter,RMES,XA,[signal],Signalwert am Ausgang,single elements,M-1-0-1.2.MX1,13
3,MeasuredVariableTable,SWVT,W,[unitX],Tabellensollwert generisch,single elements,M-1-0-1.2.MX1,13
4,WBLZ_ThermalBalance,WBLZ,WVB,[MW],Verbrauchsleistung Istwert,single elements,M-1-0-1.2.MX1,13
5,WBLZ_ThermalBalance,WBLZ,WVERL,[MW],Verlustleistung Rohrnetz,single elements,M-1-0-1.2.MX1,13

Then we can force the read of the output factor file using the param output_factor.

In [38]:
df_results = s3s.generate_element_results_dataframe(element_type=s3s.ObjectTypes.WBLZ_ThermalBalance, bulk=True, vec_format = "multiindex", output_factor=2, properties=["WVB", "WVERL"])

[2026-10-14 15:06:53,956] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.WBLZ_ThermalBalance
[2026-10-14 15:06:53,971] INFO in sir3stoolkit.mantle.dataframes: [bulk results] Result file: M-1-0-1.2.MX1 (output factor 2 = DTFAK_KLEIN of the most recent calculation, output_factor parameter), 13 timestamps.
[2026-10-14 15:06:53,983] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 1 element(s) of element type ObjectTypes.WBLZ_ThermalBalance.
[2026-10-14 15:06:53,990] INFO in sir3stoolkit.mantle.dataframes: [results] Using 2 result properties from the result file.
[2026-10-14 15:06:54,019] INFO in sir3stoolkit.mantle.dataframes: [results] 13 timestamp(s), 1 element(s), 2 properties resolved (0.1 s).
[2026-10-14 15:06:54,022] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values... (bulk=True)
[2026-10-14 15:06:54,034] INFO in sir3stoolkit.mantle.dataframes: [bulk results] 2 properties read from M-1-0-1.2.MX1 (0.0 s).
[2026-10-14 15:06:54,039] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-10-14 15:06:54,041] INFO in sir3stoolkit.mantle.dataframes: [results] DataFrame assembled (0.0 s).
[2026-10-14 15:06:54,044] INFO in sir3stoolkit.mantle.dataframes: [results] Names/end nodes of 1 element(s) looked up (0.0 s).
[2026-10-14 15:06:54,054] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (13, 2) (0.1 s in total)

In [39]:
df_results.head()

tk                                      5747928298316755683
name                                           WärmeblnzGes
end_nodes                      No end nodes on element type
property                                                WVB     WVERL
interior points                                          -1        -1
timestamp
2023-02-13 00:00:00.000 +01:00                     9.866673  0.216283
2023-02-13 02:00:00.000 +01:00                    10.146021  0.216307
2023-02-13 04:00:00.000 +01:00                    11.968699  0.216427
2023-02-13 06:00:00.000 +01:00                    19.523130  0.216701
2023-02-13 08:00:00.000 +01:00                    18.400509  0.216666

In [40]:
df_results.index

Index(['2023-02-13 00:00:00.000 +01:00', '2023-02-13 02:00:00.000 +01:00',
       '2023-02-13 04:00:00.000 +01:00', '2023-02-13 06:00:00.000 +01:00',
       '2023-02-13 08:00:00.000 +01:00', '2023-02-13 10:00:00.000 +01:00',
       '2023-02-13 12:00:00.000 +01:00', '2023-02-13 14:00:00.000 +01:00',
       '2023-02-13 16:00:00.000 +01:00', '2023-02-13 18:00:00.000 +01:00',
       '2023-02-13 20:00:00.000 +01:00', '2023-02-13 22:00:00.000 +01:00',
       '2023-02-14 00:00:00.000 +01:00'],
      dtype='object', name='timestamp')

## Limitations

If a single pipe is invalid (e.g. its length is 0 or negative), it can make an interior-point property unreadable for all pipes with bulk=True: the property is left out with a warning. bulk=False still returns it via the API.