# Tutorial 51: Manual Creation of Element Dataframes

This Example demonstrates the capabilities of the class Dataframes_SIR3S_Model that extends SIR3S_Model be abilities to work directley with pandas dataframes. It is shown how to create dataframes containing information about elements such as Nodes, Pipes, etc. existing in a SIR 3S Model. The methods presented are manual, user-defined and detailed. For creating more general dataframes with less input necessary, see Tutorial 52.

# Toolkit Release

In [1]:
#pip install

# Imports

## SIR 3S Toolkit

### Regular Import/Init

In [2]:
SIR3S_SIRGRAF_DIR = r"C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2" #change to local path

In [3]:
from sir3stoolkit.core import wrapper

In [4]:
wrapper

In [5]:
wrapper.Initialize_Toolkit(SIR3S_SIRGRAF_DIR)

[2026-06-08 10:25:10,820] INFO in sir3stoolkit.core.wrapper: [Initialization] Using provided SirGraf path: C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2
[2026-06-08 10:25:10,820] INFO in sir3stoolkit.core.wrapper: [Initialization] Using provided SirGraf path: C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2
[2026-06-08 10:25:10,882] INFO in sir3stoolkit.core.wrapper: [Initialization] Initializing toolkit with SirGraf path: C:\3S\SIR 3S\SirGraf-90-15-00-24_Quebec-Upd2

### Additional Import/Init for Dataframes class

In [6]:
from sir3stoolkit.mantle.dataframes import SIR3S_Model_Dataframes

In [7]:
s3s = SIR3S_Model_Dataframes()

[2026-06-08 10:25:23,888] INFO in sir3stoolkit.core.wrapper: [Model Class Initialization] Initialization complete

## Additional

In [8]:
import pandas as pd
from shapely.geometry import Point
import re
import folium
from folium.plugins import HeatMap
import numpy as np
import geopandas as gpd
from shapely import wkt
import matplotlib.pyplot as plt
import contextily as cx

# Open Model

In [9]:
s3s.OpenModel(dbName=r"Toolkit_Tutorial51_Model.db3",
              providerType=s3s.ProviderTypes.SQLite,
              Mid="M-1-0-1",
              saveCurrentlyOpenModel=False,
              namedInstance="",
              userID="",
              password="")

[2026-06-08 10:25:39,238] INFO in sir3stoolkit.core.wrapper: Model is open for further operation

# Calculate Model

In [10]:
#s3s.ExecCalculation(True) # To ensure result data

# Manual Dataframe creation

## model_data - Nodes

We can use the [generate_element_model_data_dataframe()](https://3sconsult.github.io/sir3stoolkit/references/sir3stoolkit.mantle.html#sir3stoolkit.mantle.dataframes.Dataframes_SIR3S_Model.generate_element_model_data_dataframe) method to obtain a dataframe for all instances of a specifc component type (Nodes, Pipes, etc.) with user defined model_data properties (all non-result data related to a component) to be added. For this example we will use nodes.

In this case we are interested in Nodes, let's check what model_data properties are available for this element.

In [11]:
s3s.GetPropertiesofElementType(s3s.ObjectTypes.Node)

['Name',
 'Ktyp',
 'Zkor',
 'QmEin',
 'Lfakt',
 'Fkpzon',
 'Fkfstf',
 'Fkutmp',
 'Fkfqps',
 'Fkcont',
 'Fk2lknot',
 'Beschreibung',
 'Idreferenz',
 'Iplanung',
 'Kvr',
 'Qakt',
 'Xkor',
 'Ykor',
 'NodeNamePosition',
 'ShowNodeName',
 'KvrKlartext',
 'NumberOfVERB',
 'HasBlockConnection',
 'Tk',
 'Pk',
 'InVariant',
 'GeometriesDiffer',
 'SymbolFactor',
 'bz.Drakonz',
 'bz.Fk',
 'bz.Fkpvar',
 'bz.Fkqvar',
 'bz.Fklfkt',
 'bz.PhEin',
 'bz.Tm',
 'bz.Te',
 'bz.PhMin']

In the below subcases differnt choices of parameters for creating the model_data dataframe manually are shown. Note that not all possible combination of paramters are shown here.

### Subcase 1: Minimal

Let's say for now we only want a dataframe with all node tks without any related data.

In [12]:
(s3s.generate_element_model_data_dataframe(element_type=s3s.ObjectTypes.Node
                                        ,properties=[]
                                        )).head(3)

[2026-06-08 10:25:39,309] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Node
[2026-06-08 10:25:39,317] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 517 element(s) of element type ObjectTypes.Node.
[2026-06-08 10:25:39,348] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 0 model_data properties.
[2026-06-08 10:25:39,350] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving ...
[2026-06-08 10:25:39,356] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (517, 1)

                    tk
0  5669301360686511351
1  5397948523091900401
2  5239335112004772156

### Subcase 2: Specific Properties

Let's say we now want the minimal dataframe extended with supply/return info (kvr) and height (Zkor) of the nodes.

In [13]:
(s3s.generate_element_model_data_dataframe(element_type=s3s.ObjectTypes.Node
                                        ,properties=["Kvr", "Zkor"]
                                        )).head(3)

[2026-06-08 10:25:39,398] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Node
[2026-06-08 10:25:39,403] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 517 element(s) of element type ObjectTypes.Node.
[2026-06-08 10:25:39,409] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 2 model_data properties.
[2026-06-08 10:25:39,411] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Kvr', 'Zkor']...
[2026-06-08 10:25:39,517] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (517, 3)

                    tk  Kvr    Zkor
0  5669301360686511351    1  554.04
1  5397948523091900401    1  556.16
2  5239335112004772156    1  561.01

### Subcase 3: Maximal

Let's say now we want basically all available model_data (non-result data) related to nodes.

If geometry=True, the 2D Point geometry will be added for Nodes and it will be attempted to transform the DataFrame into a GeoDataFrame using the SRID (eg. EPSG: 25832) defined in the model. If no SRID is defined, the DataFrame will remain as a DataFrame, but the geometry column with be added nonetheless.

In [14]:
(s3s.generate_element_model_data_dataframe(element_type=s3s.ObjectTypes.Node
                                        ,properties=None # Instead of an empty or filled list, we pass None to indicate we want all available properties
                                        ,geometry=True # geometry data has to be explicitly requested
                                        )).head(3)

[2026-06-08 10:25:39,555] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Node
[2026-06-08 10:25:39,561] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 517 element(s) of element type ObjectTypes.Node.
[2026-06-08 10:25:39,562] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] No properties given → using ALL model_data properties for ObjectTypes.Node.
[2026-06-08 10:25:39,562] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 37 model_data properties.
[2026-06-08 10:25:39,562] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['Name', 'Ktyp', 'Zkor', 'QmEin', 'Lfakt', 'Fkpzon', 'Fkfstf', 'Fkutmp', 'Fkfqps', 'Fkcont', 'Fk2lknot', 'Beschreibung', 'Idreferenz', 'Iplanung', 'Kvr', 'Qakt', 'Xkor', 'Ykor', 'NodeNamePosition', 'ShowNodeName', 'KvrKlartext', 'NumberOfVERB', 'HasBlockConnection', 'Tk', 'Pk', 'InVariant', 'GeometriesDiffer', 'SymbolFactor', 'bz.Drakonz', 'bz.Fk', 'bz.Fkpvar', 'bz.Fkqvar', 'bz.Fklfkt', 'bz.PhEin', 'bz.Tm', 'bz.Te', 'bz.PhMin'], geometry...
[2026-06-08 10:25:42,146] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 10:25:42,146] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (517, 39)

,tk,Name,Ktyp,Zkor,QmEin,Lfakt,Fkpzon,Fkfstf,Fkutmp,Fkfqps,Fkcont,Fk2lknot,Beschreibung,Idreferenz,Iplanung,Kvr,Qakt,Xkor,Ykor,NodeNamePosition,ShowNodeName,KvrKlartext,NumberOfVERB,HasBlockConnection,Tk,Pk,InVariant,GeometriesDiffer,SymbolFactor,bz.Drakonz,bz.Fk,bz.Fkpvar,bz.Fkqvar,bz.Fklfkt,bz.PhEin,bz.Tm,bz.Te,bz.PhMin,geometry
0,5669301360686511351,V-K03S,QKON,554.04,0,1,5520728169779652386,4798673252636751115,5591325053703727727,-1,5029128874972463118,5761544923588724980,Abzw. Am Sonnenbühl,3S3768E2953006F125B34916F6A1681667,1,1,0,713620.267807,5.578828e+06,1,False,Vorlauf,0,False,5669301360686511351,5669301360686511351,False,False,0.2,0,5669301360686511351,-1,-1,-1,0,0,0,0,POINT (713620.268 5578828.419)
1,5397948523091900401,V-K13S,QKON,556.16,0,1,5520728169779652386,4798673252636751115,5591325053703727727,-1,5029128874972463118,4749864932928780363,Anfangsknoten generiert von SirDB,3SC30ED954AA2F1D59B1F92FFEBCCB7B5B,1,1,0,713602.294600,5.578860e+06,1,False,Vorlauf,0,False,5397948523091900401,5397948523091900401,False,False,0.2,0,5397948523091900401,-1,-1,-1,0,0,0,0,POINT (713602.295 5578860.106)
2,5239335112004772156,V-K23S,QKON,561.01,0,1,5520728169779652386,4798673252636751115,5591325053703727727,-1,5029128874972463118,4899862460906451371,Anfangsknoten generiert von SirDB,3SC30ED954AA2F1D59B1F92FFEBCCB7B5B,1,1,0,713574.061627,5.578910e+06,1,False,Vorlauf,0,False,5239335112004772156,5239335112004772156,False,False,0.2,0,5239335112004772156,-1,-1,-1,0,0,0,0,POINT (713574.062 5578909.873)

### Subcase 4: Filtering + Element Type Col

Let's say we only want nodes inside a specific container and we also want to have an element type col adding "Node" to each row (useful when joining with other dataframes later).

In [15]:
for container_id in (s3s.GetTksofElementType(s3s.ObjectTypes.ObjectContainerSymbol)):
    print(f"{container_id}: {s3s.GetValue(container_id, 'Name')[0]}")

5029128874972463118: M-1-0-1
5027846505677995694: Erzeugung
5172832702839270493: TS
5152808213068069018: Laststeuerung
5467315850619588583: Sekundärwerte
5320319133990336755: Netztrennung

In [16]:
all_tks = s3s.GetTksofElementType(s3s.ObjectTypes.Node)

In [17]:
good_tks = []

In [ ]:
for tk in all_tks:
    if s3s.GetValue(tk, "FkCont")[0] == "5029128874972463118": # Main container
        if s3s.GetValue(tk, "Kvr")[0] == "1": # Supply/Vorlauf
            good_tks.append(tk)

In [19]:
(s3s.generate_element_model_data_dataframe(element_type=s3s.ObjectTypes.Node
                                        ,properties=[]
                                        ,tks=good_tks
                                        ,geometry=True
                                        ,element_type_col=True
                                        )).head(3)

[2026-06-08 10:25:42,312] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Node
[2026-06-08 10:25:42,318] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 517 element(s) of element type ObjectTypes.Node.
[2026-06-08 10:25:42,321] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 0 model_data properties.
[2026-06-08 10:25:42,323] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving geometry...
[2026-06-08 10:25:42,378] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 10:25:42,388] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (517, 3)

                    tk                        geometry element type
0  5669301360686511351  POINT (713620.268 5578828.419)         Node
1  5397948523091900401  POINT (713602.295 5578860.106)         Node
2  5239335112004772156  POINT (713574.062 5578909.873)         Node

## Result Data - Pipes

We can use the [generate_element_model_data_dataframe()](https://3sconsult.github.io/sir3stoolkit/references/sir3stoolkit.mantle.html#sir3stoolkit.mantle.dataframes.Dataframes_SIR3S_Model.generate_element_results_dataframe) method to obtain a dataframe for all instances of a specifc component type (Nodes, Pipes, etc.) with user defined result values for certain timestamps to be added. For this example we will use pipes.

Let's check what result properties are available for Pipes.

In [20]:
s3s.GetResultProperties_from_elementType(elementType=s3s.ObjectTypes.Pipe
                                         ,onlySelectedVectors=False 
                                         )

['A',
 'ACALC',
 'CPI',
 'CPK',
 'DH',
 'DP',
 'DRAGRED',
 'DRAKONZ',
 'DSI',
 'DSK',
 'DTTR',
 'DWVERL',
 'DWVERLABS',
 'ETAAV',
 'FS',
 'HR',
 'HVEC',
 'IAKTIV',
 'IRTRENN',
 'JV',
 'JV2',
 'LAMBDA',
 'LECKEINAUS',
 'LECKMENGE',
 'LECKORT',
 'LINEPACK',
 'LINEPACKGEOM',
 'LINEPACKRATE',
 'MAINELEMENT',
 'MAV',
 'MI',
 'MK',
 'MKOND',
 'MMAX_INST',
 'MMIN_INST',
 'MVEC',
 'MVECMAX_INST',
 'MVECMIN_INST',
 'PAV',
 'PDAMPF',
 'PHR',
 'PHVEC',
 'PMAX',
 'PMIN',
 'PR',
 'PVEC',
 'PVECMAX_INST',
 'PVECMIN_INST',
 'QI2',
 'QK2',
 'QMAV',
 'QMI',
 'QMK',
 'QMMAX_INST',
 'QMMIN_INST',
 'QMVEC',
 'QSVB',
 'RHOAV',
 'RHOI',
 'RHOK',
 'RHOVEC',
 'SVEC',
 'TAV',
 'TI',
 'TK',
 'TTRVEC',
 'TVEC',
 'TVECMAX_INST',
 'TVECMIN_INST',
 'VAV',
 'VI',
 'VK',
 'VMAX_INST',
 'VMIN_INST',
 'VOLDA',
 'WALTERI',
 'WALTERK',
 'WVL',
 'ZAUS',
 'ZEIN',
 'ZHKNR',
 'ZVEC']

Let's also check what simulation timestamps are available in the model.

In [21]:
s3s.GetTimeStamps()[0] # list of simulation timestamps

['2023-02-13 00:00:00.000 +01:00',
 '2023-02-13 01:00:00.000 +01:00',
 '2023-02-13 02:00:00.000 +01:00',
 '2023-02-13 03:00:00.000 +01:00',
 '2023-02-13 04:00:00.000 +01:00',
 '2023-02-13 05:00:00.000 +01:00',
 '2023-02-13 06:00:00.000 +01:00',
 '2023-02-13 07:00:00.000 +01:00',
 '2023-02-13 08:00:00.000 +01:00',
 '2023-02-13 09:00:00.000 +01:00',
 '2023-02-13 10:00:00.000 +01:00',
 '2023-02-13 11:00:00.000 +01:00',
 '2023-02-13 12:00:00.000 +01:00',
 '2023-02-13 13:00:00.000 +01:00',
 '2023-02-13 14:00:00.000 +01:00',
 '2023-02-13 15:00:00.000 +01:00',
 '2023-02-13 16:00:00.000 +01:00',
 '2023-02-13 17:00:00.000 +01:00',
 '2023-02-13 18:00:00.000 +01:00',
 '2023-02-13 19:00:00.000 +01:00',
 '2023-02-13 20:00:00.000 +01:00',
 '2023-02-13 21:00:00.000 +01:00',
 '2023-02-13 22:00:00.000 +01:00',
 '2023-02-13 23:00:00.000 +01:00',
 '2023-02-14 00:00:00.000 +01:00']

In [22]:
s3s.GetTimeStamps()[1] # Static

'2023-02-13 00:00:00.000 +01:00'

In the below subcases differnt choices of parameters for creating the result dataframe manually are shown. Note that not all possible combination of paramters are shown here.

### Subcase 1: Static + All Result Values

In [23]:
(s3s.generate_element_results_dataframe(element_type=s3s.ObjectTypes.Pipe
                                        ,properties=None # None => All available properties
                                        ,timestamps=[s3s.GetTimeStamps()[1]] # static
                                        )).head(3)

[2026-06-08 10:25:42,894] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-06-08 10:25:43,055] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Only static timestamp 2023-02-13 00:00:00.000 +01:00 is used
[2026-06-08 10:25:43,056] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 10:25:43,063] INFO in sir3stoolkit.mantle.dataframes: [results] No properties given → using ALL result properties for ObjectTypes.Pipe.
[2026-06-08 10:25:43,065] INFO in sir3stoolkit.mantle.dataframes: [results] Using 82 result properties.
[2026-06-08 10:25:43,311] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 10:25:52,189] INFO in sir3stoolkit.mantle.dataframes: [results] 26724 fully NaN columns dropped.
[2026-06-08 10:25:54,722] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (1, 16244)

tk                                                                    5442010239090746007  \
name                                                                   Rohr V-K03S V-K13S
end_nodes                      ('5669301360686511351', '5397948523091900401', '-1', '-1')
property                                                                                A
timestamp
2023-02-13 00:00:00.000 +01:00                                                0.0

tk                                                                           \
name
end_nodes
property                            DTTR    DWVERL DWVERLABS IAKTIV IRTRENN
timestamp
2023-02-13 00:00:00.000 +01:00  0.013437  35.86034  1.306369    0.0     0.0

tk                                       \
name
end_nodes
property                             JV
timestamp
2023-02-13 00:00:00.000 +01:00  0.28607

tk                                                                                \
name
end_nodes
property                                                                    MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  14.68007\t14.68007\t14.68007\t14.68007\t14.68007

tk                                                            \
name
end_nodes
property                          PDAMPF       PHR      PMIN
timestamp
2023-02-13 00:00:00.000 +01:00  0.693796  0.010421  4.291257

tk                                                                               \
name
end_nodes
property                                                                   PVEC
timestamp
2023-02-13 00:00:00.000 +01:00  4.502485\t4.449675\t4.39687\t4.344065\t4.291255

tk                                                                               \
name
end_nodes
property                                                           PVECMAX_INST
timestamp
2023-02-13 00:00:00.000 +01:00  4.502485\t4.449675\t4.39687\t4.344065\t4.291255

tk                                                                               \
name
end_nodes
property                                                           PVECMIN_INST
timestamp
2023-02-13 00:00:00.000 +01:00  4.502485\t4.449675\t4.39687\t4.344065\t4.291255

tk                                                                      \
name
end_nodes
property                            QMAV       QMI       QMK      RHOI
timestamp
2023-02-13 00:00:00.000 +01:00  52.84827  52.84827  52.84827  965.8609

tk                                        \
name
end_nodes
property                            RHOK
timestamp
2023-02-13 00:00:00.000 +01:00  965.8736

tk                                                                                \
name
end_nodes
property                                                                  RHOVEC
timestamp
2023-02-13 00:00:00.000 +01:00  965.8609\t965.8641\t965.8672\t965.8704\t965.8736

tk                                                                         \
name
end_nodes
property                                                             SVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0\t9.107338\t18.21468\t27.32201\t36.42935

tk                                                  \
name
end_nodes
property                              TI        TK
timestamp
2023-02-13 00:00:00.000 +01:00  89.73183  89.71064

tk                                                                                 \
name
end_nodes
property                                                                   TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.3227228\t0.326082\t0.3294412\t0.3328004\t0.3...

tk                                                                                \
name
end_nodes
property                                                                    TVEC
timestamp
2023-02-13 00:00:00.000 +01:00  89.73184\t89.72653\t89.72122\t89.71594\t89.71063

tk                                                                           \
name
end_nodes
property                             VAV        VI        VK VOLDA      WVL
timestamp
2023-02-13 00:00:00.000 +01:00  0.753102  0.753107  0.753097   0.0  1843.65

tk                                                                       \
name
end_nodes
property                                                           ZVEC
timestamp
2023-02-13 00:00:00.000 +01:00  554.04\t554.5699\t555.1\t555.63\t556.16

tk                                                                    4917786378639043296  \
name                                                                   Rohr V-K13S V-K23S
end_nodes                      ('5397948523091900401', '5239335112004772156', '-1', '-1')
property                                                                                A
timestamp
2023-02-13 00:00:00.000 +01:00                                                0.0

tk                                                                           \
name
end_nodes
property                            DTTR    DWVERL DWVERLABS IAKTIV IRTRENN
timestamp
2023-02-13 00:00:00.000 +01:00  0.025371  29.87751  1.709525    0.0     0.0

tk                                        \
name
end_nodes
property                              JV
timestamp
2023-02-13 00:00:00.000 +01:00  0.255595

tk                                                                                 \
name
end_nodes
property                                                                     MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  8.24275\t8.24275\t8.24275\t8.24275\t8.24275\t8...

tk                                                            \
name
end_nodes
property                          PDAMPF       PHR      PMIN
timestamp
2023-02-13 00:00:00.000 +01:00  0.692872  0.014625  3.817231

tk                                                                                 \
name
end_nodes
property                                                                     PVEC
timestamp
2023-02-13 00:00:00.000 +01:00  4.291255\t4.212255\t4.13325\t4.054245\t3.97524...

tk                                                                                 \
name
end_nodes
property                                                             PVECMAX_INST
timestamp
2023-02-13 00:00:00.000 +01:00  4.291255\t4.212255\t4.13325\t4.054245\t3.97524...

tk                                                                                 \
name
end_nodes
property                                                             PVECMIN_INST
timestamp
2023-02-13 00:00:00.000 +01:00  4.291255\t4.212255\t4.13325\t4.054245\t3.97524...

tk                                                                             \
name
end_nodes
property                           QMAV      QMI      QMK      RHOI      RHOK
timestamp
2023-02-13 00:00:00.000 +01:00  29.6739  29.6739  29.6739  965.8736  965.9033

tk                                                                                 \
name
end_nodes
property                                                                   RHOVEC
timestamp
2023-02-13 00:00:00.000 +01:00  965.8736\t965.8785\t965.8835\t965.8884\t965.89...

tk                                                                                 \
name
end_nodes
property                                                                     SVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0\t9.536302\t19.0726\t28.60891\t38.14521\t47.6...

tk                                                  \
name
end_nodes
property                              TI        TK
timestamp
2023-02-13 00:00:00.000 +01:00  89.71064  89.66128

tk                                                                                 \
name
end_nodes
property                                                                   TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.3361596\t0.3403881\t0.3446167\t0.3488453\t0....

tk                                                                                 \
name
end_nodes
property                                                                     TVEC
timestamp
2023-02-13 00:00:00.000 +01:00  89.71063\t89.70242\t89.69418\t89.68597\t89.677...

tk                                                                            \
name
end_nodes
property                             VAV        VI        VK VOLDA       WVL
timestamp
2023-02-13 00:00:00.000 +01:00  0.626446  0.626456  0.626436   0.0  1032.729

tk                                                                                 \
name
end_nodes
property                                                                     ZVEC
timestamp
2023-02-13 00:00:00.000 +01:00  556.16\t556.9683\t557.7767\t558.585\t559.3933\...

tk                                                                    4762482310382009633  \
name                                                                   Rohr V-K23S V-K33S
end_nodes                      ('5239335112004772156', '5298886695042021307', '-1', '-1')
property                                                                                A
timestamp
2023-02-13 00:00:00.000 +01:00                                                0.0

tk                                                                           \
name
end_nodes
property                            DTTR    DWVERL DWVERLABS IAKTIV IRTRENN
timestamp
2023-02-13 00:00:00.000 +01:00  0.017832  29.80227  1.221739    0.0     0.0

tk                                        \
name
end_nodes
property                              JV
timestamp
2023-02-13 00:00:00.000 +01:00  0.265203

tk                                                                                 \
name
end_nodes
property                                                                     MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  8.403428\t8.403428\t8.403428\t8.403428\t8.4034...

tk                                                            \
name
end_nodes
property                          PDAMPF       PHR      PMIN
timestamp
2023-02-13 00:00:00.000 +01:00  0.687946  0.010872  3.612159

tk                                                                                 \
name
end_nodes
property                                                                     PVEC
timestamp
2023-02-13 00:00:00.000 +01:00  3.81723\t3.776215\t3.7352\t3.69419\t3.653175\t...

tk                                                                                 \
name
end_nodes
property                                                             PVECMAX_INST
timestamp
2023-02-13 00:00:00.000 +01:00  3.81723\t3.776215\t3.7352\t3.69419\t3.653175\t...

tk                                                                                 \
name
end_nodes
property                                                             PVECMIN_INST
timestamp
2023-02-13 00:00:00.000 +01:00  3.81723\t3.776215\t3.7352\t3.69419\t3.653175\t...

tk                                                                      \
name
end_nodes
property                            QMAV       QMI       QMK      RHOI
timestamp
2023-02-13 00:00:00.000 +01:00  30.25234  30.25234  30.25234  965.9908

tk                                        \
name
end_nodes
property                            RHOK
timestamp
2023-02-13 00:00:00.000 +01:00  966.0116

tk                                                                                 \
name
end_nodes
property                                                                   RHOVEC
timestamp
2023-02-13 00:00:00.000 +01:00  965.9908\t965.995\t965.9991\t966.0033\t966.007...

tk                                                                                 \
name
end_nodes
property                                                                     SVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0\t8.198964\t16.39793\t24.59689\t32.79586\t40....

tk                                                  \
name
end_nodes
property                              TI        TK
timestamp
2023-02-13 00:00:00.000 +01:00  89.51524  89.48063

tk                                                                                 \
name
end_nodes
property                                                                   TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.4288374\t0.4324038\t0.4359703\t0.4395368\t0....

tk                                                                                 \
name
end_nodes
property                                                                     TVEC
timestamp
2023-02-13 00:00:00.000 +01:00  89.51523\t89.50833\t89.5014\t89.49448\t89.4875...

tk                                                                           \
name
end_nodes
property                             VAV       VI        VK VOLDA       WVL
timestamp
2023-02-13 00:00:00.000 +01:00  0.638583  0.63859  0.638576   0.0  1045.861

tk                                                                              \
name
end_nodes
property                                                                  ZVEC
timestamp
2023-02-13 00:00:00.000 +01:00  561.01\t561.42\t561.83\t562.24\t562.65\t563.06

tk                                                                    4987229536643024523  \
name                                                                   Rohr V-K33S V-K43S
end_nodes                      ('5298886695042021307', '4993257270457791438', '-1', '-1')
property                                                                                A
timestamp
2023-02-13 00:00:00.000 +01:00                                                0.0

tk                                                                           \
name
end_nodes
property                            DTTR    DWVERL DWVERLABS IAKTIV IRTRENN
timestamp
2023-02-13 00:00:00.000 +01:00  0.002972  29.72455   0.20311    0.0     0.0

tk                                                                      \
name
end_nodes
property                              JV                MVEC    PDAMPF
timestamp
2023-02-13 00:00:00.000 +01:00  0.265205  8.403428\t8.403428  0.687417

tk                                                                   \
name
end_nodes
property                             PHR      PMIN             PVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.001812  3.591399  3.61216\t3.5914

tk                                                                          \
name
end_nodes
property                           PVECMAX_INST     PVECMIN_INST      QMAV
timestamp
2023-02-13 00:00:00.000 +01:00  3.61216\t3.5914  3.61216\t3.5914  30.25234

tk                                                                      \
name
end_nodes
property                             QMI       QMK      RHOI      RHOK
timestamp
2023-02-13 00:00:00.000 +01:00  30.25234  30.25234  966.0116  966.0151

tk                                                                         \
name
end_nodes
property                                    RHOVEC         SVEC        TI
timestamp
2023-02-13 00:00:00.000 +01:00  966.0116\t966.0151  0\t6.833079  89.48063

tk                                                              \
name
end_nodes
property                              TK                TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  89.47486  0.4466697\t0.4496421

tk                                                                      \
name
end_nodes
property                                      TVEC       VAV        VI
timestamp
2023-02-13 00:00:00.000 +01:00  89.48062\t89.47485  0.638575  0.638576

tk                                                                        \
name
end_nodes
property                              VK VOLDA       WVL            ZVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.638574   0.0  1043.873  563.06\t563.26

tk                                                                    5722206630503885118  \
name                                                                   Rohr V-K43S V-K53S
end_nodes                      ('4993257270457791438', '5317865645994989592', '-1', '-1')
property                                                                                A
timestamp
2023-02-13 00:00:00.000 +01:00                                                0.0

tk                                                                           \
name
end_nodes
property                            DTTR    DWVERL DWVERLABS IAKTIV IRTRENN
timestamp
2023-02-13 00:00:00.000 +01:00  0.003259  29.84431  0.223626    0.0     0.0

tk                                                                      \
name
end_nodes
property                              JV                MVEC    PDAMPF
timestamp
2023-02-13 00:00:00.000 +01:00  0.265206  8.403428\t8.403428  0.687258

tk                                                                    \
name
end_nodes
property                             PHR      PMIN              PVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.001987  3.574257  3.5914\t3.574255

tk                                                                            \
name
end_nodes
property                            PVECMAX_INST      PVECMIN_INST      QMAV
timestamp
2023-02-13 00:00:00.000 +01:00  3.5914\t3.574255  3.5914\t3.574255  30.25234

tk                                                                      \
name
end_nodes
property                             QMI       QMK      RHOI      RHOK
timestamp
2023-02-13 00:00:00.000 +01:00  30.25234  30.25234  966.0151  966.0189

tk                                                                         \
name
end_nodes
property                                    RHOVEC         SVEC        TI
timestamp
2023-02-13 00:00:00.000 +01:00  966.0151\t966.0189  0\t7.493101  89.47486

tk                                                              \
name
end_nodes
property                              TK                TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  89.46854  0.4496421\t0.4529015

tk                                                                      \
name
end_nodes
property                                      TVEC       VAV        VI
timestamp
2023-02-13 00:00:00.000 +01:00  89.47485\t89.46854  0.638573  0.638574

tk                                                                        \
name
end_nodes
property                              VK VOLDA       WVL            ZVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.638571   0.0  1043.542  563.26\t563.42

tk                                                                    5089459212485379804  \
name                                                                   Rohr V-K53S V-K63S
end_nodes                      ('5317865645994989592', '5085491372308261877', '-1', '-1')
property                                                                                A
timestamp
2023-02-13 00:00:00.000 +01:00                                                0.0

tk                                                                          \
name
end_nodes
property                           DTTR    DWVERL DWVERLABS IAKTIV IRTRENN
timestamp
2023-02-13 00:00:00.000 +01:00  0.00362  29.83195  0.248246    0.0     0.0

tk                                                                      \
name
end_nodes
property                              JV                MVEC    PDAMPF
timestamp
2023-02-13 00:00:00.000 +01:00  0.265207  8.403428\t8.403428  0.687084

tk                                                                     \
name
end_nodes
property                             PHR      PMIN               PVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.002207  3.556889  3.574255\t3.55689

tk                                                                    \
name
end_nodes
property                             PVECMAX_INST       PVECMIN_INST
timestamp
2023-02-13 00:00:00.000 +01:00  3.574255\t3.55689  3.574255\t3.55689

tk                                                                      \
name
end_nodes
property                            QMAV       QMI       QMK      RHOI
timestamp
2023-02-13 00:00:00.000 +01:00  30.25234  30.25234  30.25234  966.0189

tk                                                                         \
name
end_nodes

Note that a multi index on the columns is created, holding the most important model_data.
- Level 0: tk (device ID)
- Level 1: name (device name)
- Level 2: end_nodes (tuple of connected node IDs as string)
- Level 3: property (result name)

As can be seen a lot of 99999.0 placeholder values are inserted, because we attempt to access many result values that SIR Calc can calculate but are not requested for this model. Therefore using all available result properties(properties=None), is generally not recommended.

### Subcase 2: All Timestamps + Specific Values

In [24]:
df_pipes_2 = s3s.generate_element_results_dataframe(element_type=s3s.ObjectTypes.Pipe
                                                    ,properties=["DTTR", "PHR"] # Specify result properties of interest
                                                    ,timestamps=None # None => All available simulation timestamps
                                                    )

[2026-06-08 10:25:55,572] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-06-08 10:25:55,574] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] No timestamps were given. Checking available simulation timestamps (SIR3S_Model.GetTimeStamps()[0]).
[2026-06-08 10:25:55,674] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] 25 simulation timestamp(s) are available.
[2026-06-08 10:25:55,772] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 25 timestamps: ['2023-02-13 00:00:00.000 +01:00', '2023-02-13 01:00:00.000 +01:00', '2023-02-13 02:00:00.000 +01:00', '2023-02-13 03:00:00.000 +01:00', '2023-02-13 04:00:00.000 +01:00', '2023-02-13 05:00:00.000 +01:00', '2023-02-13 06:00:00.000 +01:00', '2023-02-13 07:00:00.000 +01:00', '2023-02-13 08:00:00.000 +01:00', '2023-02-13 09:00:00.000 +01:00', '2023-02-13 10:00:00.000 +01:00', '2023-02-13 11:00:00.000 +01:00', '2023-02-13 12:00:00.000 +01:00', '2023-02-13 13:00:00.000 +01:00', '2023-02-13 14:00:00.000 +01:00', '2023-02-13 15:00:00.000 +01:00', '2023-02-13 16:00:00.000 +01:00', '2023-02-13 17:00:00.000 +01:00', '2023-02-13 18:00:00.000 +01:00', '2023-02-13 19:00:00.000 +01:00', '2023-02-13 20:00:00.000 +01:00', '2023-02-13 21:00:00.000 +01:00', '2023-02-13 22:00:00.000 +01:00', '2023-02-13 23:00:00.000 +01:00', '2023-02-14 00:00:00.000 +01:00']
[2026-06-08 10:25:55,776] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 10:25:55,780] INFO in sir3stoolkit.mantle.dataframes: [results] Using 2 result properties.
[2026-06-08 10:25:55,806] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 10:26:00,564] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 10:26:00,767] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (25, 1048)

In [25]:
df_pipes_2.head(3)

tk                                                                    5442010239090746007  \
name                                                                   Rohr V-K03S V-K13S
end_nodes                      ('5669301360686511351', '5397948523091900401', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.013437
2023-02-13 01:00:00.000 +01:00                                           0.013280
2023-02-13 02:00:00.000 +01:00                                           0.013070

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.010421
2023-02-13 01:00:00.000 +01:00  0.010659
2023-02-13 02:00:00.000 +01:00  0.010989

tk                                                                    4917786378639043296  \
name                                                                   Rohr V-K13S V-K23S
end_nodes                      ('5397948523091900401', '5239335112004772156', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.025371
2023-02-13 01:00:00.000 +01:00                                           0.025077
2023-02-13 02:00:00.000 +01:00                                           0.024686

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.014625
2023-02-13 01:00:00.000 +01:00  0.014954
2023-02-13 02:00:00.000 +01:00  0.015408

tk                                                                    4762482310382009633  \
name                                                                   Rohr V-K23S V-K33S
end_nodes                      ('5239335112004772156', '5298886695042021307', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.017832
2023-02-13 01:00:00.000 +01:00                                           0.017624
2023-02-13 02:00:00.000 +01:00                                           0.017347

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.010872
2023-02-13 01:00:00.000 +01:00  0.011119
2023-02-13 02:00:00.000 +01:00  0.011460

tk                                                                    4987229536643024523  \
name                                                                   Rohr V-K33S V-K43S
end_nodes                      ('5298886695042021307', '4993257270457791438', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.002972
2023-02-13 01:00:00.000 +01:00                                           0.002938
2023-02-13 02:00:00.000 +01:00                                           0.002891

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.001812
2023-02-13 01:00:00.000 +01:00  0.001853
2023-02-13 02:00:00.000 +01:00  0.001910

tk                                                                    5722206630503885118  \
name                                                                   Rohr V-K43S V-K53S
end_nodes                      ('4993257270457791438', '5317865645994989592', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.003259
2023-02-13 01:00:00.000 +01:00                                           0.003221
2023-02-13 02:00:00.000 +01:00                                           0.003171

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.001987
2023-02-13 01:00:00.000 +01:00  0.002032
2023-02-13 02:00:00.000 +01:00  0.002095

tk                                                                    5089459212485379804  \
name                                                                   Rohr V-K53S V-K63S
end_nodes                      ('5317865645994989592', '5085491372308261877', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.003620
2023-02-13 01:00:00.000 +01:00                                           0.003577
2023-02-13 02:00:00.000 +01:00                                           0.003521

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.002207
2023-02-13 01:00:00.000 +01:00  0.002257
2023-02-13 02:00:00.000 +01:00  0.002326

tk                                                                    5526871502288882655  \
name                                                                   Rohr V-K63S V-K73S
end_nodes                      ('5085491372308261877', '4989694427717344427', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.039475
2023-02-13 01:00:00.000 +01:00                                           0.039013
2023-02-13 02:00:00.000 +01:00                                           0.038400

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.018532
2023-02-13 01:00:00.000 +01:00  0.018951
2023-02-13 02:00:00.000 +01:00  0.019531

tk                                                                    4809089329099085219  \
name                                                                   Rohr V-K73S V-K83S
end_nodes                      ('4989694427717344427', '5097833100706648505', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.001627
2023-02-13 01:00:00.000 +01:00                                           0.001608
2023-02-13 02:00:00.000 +01:00                                           0.001583

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.002248
2023-02-13 01:00:00.000 +01:00  0.002300
2023-02-13 02:00:00.000 +01:00  0.002370

tk                                                                    5170001087020228683  \
name                                                                   Rohr V-K83S V-K93S
end_nodes                      ('5097833100706648505', '5748593725990350490', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.002951
2023-02-13 01:00:00.000 +01:00                                           0.002916
2023-02-13 02:00:00.000 +01:00                                           0.002871

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.001065
2023-02-13 01:00:00.000 +01:00  0.001089
2023-02-13 02:00:00.000 +01:00  0.001122

tk                                                                    5625716875961234775  \
name                                                                  Rohr V-K93S V-K103S
end_nodes                      ('5748593725990350490', '5498236250497948633', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.002250
2023-02-13 01:00:00.000 +01:00                                           0.002224
2023-02-13 02:00:00.000 +01:00                                           0.002189

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.000812
2023-02-13 01:00:00.000 +01:00  0.000831
2023-02-13 02:00:00.000 +01:00  0.000856

tk                                                                    5501916898830363065  \
name                                                                 Rohr V-K103S V-K113S
end_nodes                      ('5498236250497948633', '4764732356959599958', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.012035
2023-02-13 01:00:00.000 +01:00                                           0.011894
2023-02-13 02:00:00.000 +01:00                                           0.011707

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.004345
2023-02-13 01:00:00.000 +01:00  0.004442
2023-02-13 02:00:00.000 +01:00  0.004578

tk                                                                    5192970129555982907  \
name                                                                 Rohr V-K113S V-K123S
end_nodes                      ('4764732356959599958', '5648425495460137243', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.015949
2023-02-13 01:00:00.000 +01:00                                           0.015762
2023-02-13 02:00:00.000 +01:00                                           0.015515

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.004761
2023-02-13 01:00:00.000 +01:00  0.004868
2023-02-13 02:00:00.000 +01:00  0.005016

tk                                                                    5027225217797463802  \
name                                                                 Rohr V-K123S V-K133S
end_nodes                      ('5648425495460137243', '5603354735453128217', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.014919
2023-02-13 01:00:00.000 +01:00                                           0.014744
2023-02-13 02:00:00.000 +01:00                                           0.014513

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.009291
2023-02-13 01:00:00.000 +01:00  0.009501
2023-02-13 02:00:00.000 +01:00  0.009790

tk                                                                    5107343838750080243  \
name                                                                 Rohr V-K133S V-K143S
end_nodes                      ('5603354735453128217', '5554918259063780747', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.057364
2023-02-13 01:00:00.000 +01:00                                           0.056693
2023-02-13 02:00:00.000 +01:00                                           0.055810

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.003588
2023-02-13 01:00:00.000 +01:00  0.003666
2023-02-13 02:00:00.000 +01:00  0.003773

tk                                                                    4840056338230495043  \
name                                                                 Rohr V-K153S V-K163S
end_nodes                      ('4992867596416688120', '4921884425075838112', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.057824
2023-02-13 01:00:00.000 +01:00                                           0.057147
2023-02-13 02:00:00.000 +01:00                                           0.056244

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.032887
2023-02-13 01:00:00.000 +01:00  0.033629
2023-02-13 02:00:00.000 +01:00  0.034659

tk                                                                    5700872284015490704  \
name                                                                 Rohr V-K163S V-K143S
end_nodes                      ('4921884425075838112', '5554918259063780747', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           165.7806
2023-02-13 01:00:00.000 +01:00                                           165.7806
2023-02-13 02:00:00.000 +01:00                                           165.7806

tk                                   \
name
end_nodes
property                        PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.0
2023-02-13 01:00:00.000 +01:00  0.0
2023-02-13 02:00:00.000 +01:00  0.0

tk                                                                    5290590848336792638  \
name                                                                 Rohr V-K143S V-K173S
end_nodes                      ('5554918259063780747', '4858392140572707635', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           3.842942
2023-02-13 01:00:00.000 +01:00                                           3.842942
2023-02-13 02:00:00.000 +01:00                                           3.842942

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  4.289871e-25
2023-02-13 01:00:00.000 +01:00  2.553306e-25
2023-02-13 02:00:00.000 +01:00  5.837172e-25

tk                                                                    4781821593135991761  \
name                                                                 Rohr V-K173S V-K183S
end_nodes                      ('4858392140572707635', '5167668521501299921', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           64.19534
2023-02-13 01:00:00.000 +01:00                                           64.19534
2023-02-13 02:00:00.000 +01:00                                           64.19534

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  1.348729e-24
2023-02-13 01:00:00.000 +01:00  1.373590e-24
2023-02-13 02:00:00.000 +01:00  3.433976e-25

tk                                                                    4770083637349644299  \
name                                                                 Rohr V-K183S V-K193S
end_nodes                      ('5167668521501299921', '5362725334032147732', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           51.01035
2023-02-13 01:00:00.000 +01:00                                           51.01035
2023-02-13 02:00:00.000 +01:00                                           51.01035

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  1.908720e-25
2023-02-13 01:00:00.000 +01:00  5.278974e-25
2023-02-13 02:00:00.000 +01:00  5.278974e-25

tk                                                                    5140383994159421977  \
name                                                                 Rohr V-K193S V-K203S
end_nodes                      ('5362725334032147732', '5129584372458662150', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                            83.9612
2023-02-13 01:00:00.000 +01:00                                            83.9612
2023-02-13 02:00:00.000 +01:00                                            83.9612

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  1.368325e-24
2023-02-13 01:00:00.000 +01:00  3.420814e-25
2023-02-13 02:00:00.000 +01:00  1.368325e-24

tk                                                                    4615723899944629797  \
name                                                                 Rohr V-K203S V-K213S
end_nodes                      ('5129584372458662150', '5332825919690090061', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           64.28724
2023-02-13 01:00:00.000 +01:00                                           64.28724
2023-02-13 02:00:00.000 +01:00                                           64.28724

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  3.057601e-24
2023-02-13 01:00:00.000 +01:00  0.000000e+00
2023-02-13 02:00:00.000 +01:00  3.565079e-25

tk                                                                    5485743457841402038  \
name                                                                 Rohr V-K213S V-K223S
end_nodes                      ('5332825919690090061', '5210475429427900126', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                            43.0797
2023-02-13 01:00:00.000 +01:00                                            43.0797
2023-02-13 02:00:00.000 +01:00                                            43.0797

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  1.248133e-24
2023-02-13 01:00:00.000 +01:00  3.120333e-25
2023-02-13 02:00:00.000 +01:00  3.120333e-25

tk                                                                    5061682782623660813  \
name                                                                 Rohr V-K233S V-K243S
end_nodes                      ('5434645737310584056', '4704578559698354879', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.092052
2023-02-13 01:00:00.000 +01:00                                           0.090975
2023-02-13 02:00:00.000 +01:00                                           0.089553

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.003742
2023-02-13 01:00:00.000 +01:00  0.003823
2023-02-13 02:00:00.000 +01:00  0.003934

tk                                                                    4868922965129592512  \
name                                                                 Rohr V-K243S V-K253S

We can access individual values as follows.

In [26]:
df_pipes_2.loc[
    "2023-02-13 00:00:00.000 +01:00",
    ("5442010239090746007", slice(None), slice(None), "DTTR")
].item()

0.01343678

### Subcase 3: Specific Timestamps + Specific Values

We can specify the list of timestamps to include either as a list of str timestamps ...

In [27]:
(s3s.generate_element_results_dataframe(element_type=s3s.ObjectTypes.Pipe
                                        ,properties=["DTTR", "PHR"]
                                        ,timestamps=['2023-02-13 00:00:00.000 +01:00', '2023-02-13 05:00:00.000 +01:00', '2023-02-13 23:00:00.000 +01:00'] 
                                        )).head(3)

[2026-06-08 10:26:02,161] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe

[2026-06-08 10:26:02,377] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 3 timestamps: ['2023-02-13 00:00:00.000 +01:00', '2023-02-13 05:00:00.000 +01:00', '2023-02-13 23:00:00.000 +01:00']
[2026-06-08 10:26:02,381] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 10:26:02,384] INFO in sir3stoolkit.mantle.dataframes: [results] Using 2 result properties.
[2026-06-08 10:26:02,408] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 10:26:03,188] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 10:26:03,410] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (3, 1048)

tk                                                                    5442010239090746007  \
name                                                                   Rohr V-K03S V-K13S
end_nodes                      ('5669301360686511351', '5397948523091900401', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.013437
2023-02-13 05:00:00.000 +01:00                                           0.008582
2023-02-13 23:00:00.000 +01:00                                           0.012622

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.010421
2023-02-13 05:00:00.000 +01:00  0.024731
2023-02-13 23:00:00.000 +01:00  0.011750

tk                                                                    4917786378639043296  \
name                                                                   Rohr V-K13S V-K23S
end_nodes                      ('5397948523091900401', '5239335112004772156', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.025371
2023-02-13 05:00:00.000 +01:00                                           0.016282
2023-02-13 23:00:00.000 +01:00                                           0.023852

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.014625
2023-02-13 05:00:00.000 +01:00  0.034240
2023-02-13 23:00:00.000 +01:00  0.016454

tk                                                                    4762482310382009633  \
name                                                                   Rohr V-K23S V-K33S
end_nodes                      ('5239335112004772156', '5298886695042021307', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.017832
2023-02-13 05:00:00.000 +01:00                                           0.011407
2023-02-13 23:00:00.000 +01:00                                           0.016755

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.010872
2023-02-13 05:00:00.000 +01:00  0.025619
2023-02-13 23:00:00.000 +01:00  0.012245

tk                                                                    4987229536643024523  \
name                                                                   Rohr V-K33S V-K43S
end_nodes                      ('5298886695042021307', '4993257270457791438', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.002972
2023-02-13 05:00:00.000 +01:00                                           0.001901
2023-02-13 23:00:00.000 +01:00                                           0.002793

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.001812
2023-02-13 05:00:00.000 +01:00  0.004270
2023-02-13 23:00:00.000 +01:00  0.002041

tk                                                                    5722206630503885118  \
name                                                                   Rohr V-K43S V-K53S
end_nodes                      ('4993257270457791438', '5317865645994989592', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.003259
2023-02-13 05:00:00.000 +01:00                                           0.002085
2023-02-13 23:00:00.000 +01:00                                           0.003063

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.001987
2023-02-13 05:00:00.000 +01:00  0.004683
2023-02-13 23:00:00.000 +01:00  0.002238

tk                                                                    5089459212485379804  \
name                                                                   Rohr V-K53S V-K63S
end_nodes                      ('5317865645994989592', '5085491372308261877', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.003620
2023-02-13 05:00:00.000 +01:00                                           0.002316
2023-02-13 23:00:00.000 +01:00                                           0.003401

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.002207
2023-02-13 05:00:00.000 +01:00  0.005200
2023-02-13 23:00:00.000 +01:00  0.002486

tk                                                                    5526871502288882655  \
name                                                                   Rohr V-K63S V-K73S
end_nodes                      ('5085491372308261877', '4989694427717344427', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.039475
2023-02-13 05:00:00.000 +01:00                                           0.025259
2023-02-13 23:00:00.000 +01:00                                           0.037092

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.018532
2023-02-13 05:00:00.000 +01:00  0.043554
2023-02-13 23:00:00.000 +01:00  0.020864

tk                                                                    4809089329099085219  \
name                                                                   Rohr V-K73S V-K83S
end_nodes                      ('4989694427717344427', '5097833100706648505', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.001627
2023-02-13 05:00:00.000 +01:00                                           0.001041
2023-02-13 23:00:00.000 +01:00                                           0.001529

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.002248
2023-02-13 05:00:00.000 +01:00  0.005313
2023-02-13 23:00:00.000 +01:00  0.002533

tk                                                                    5170001087020228683  \
name                                                                   Rohr V-K83S V-K93S
end_nodes                      ('5097833100706648505', '5748593725990350490', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.002951
2023-02-13 05:00:00.000 +01:00                                           0.001889
2023-02-13 23:00:00.000 +01:00                                           0.002773

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.001065
2023-02-13 05:00:00.000 +01:00  0.002490
2023-02-13 23:00:00.000 +01:00  0.001198

tk                                                                    5625716875961234775  \
name                                                                  Rohr V-K93S V-K103S
end_nodes                      ('5748593725990350490', '5498236250497948633', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.002250
2023-02-13 05:00:00.000 +01:00                                           0.001441
2023-02-13 23:00:00.000 +01:00                                           0.002115

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.000812
2023-02-13 05:00:00.000 +01:00  0.001899
2023-02-13 23:00:00.000 +01:00  0.000914

tk                                                                    5501916898830363065  \
name                                                                 Rohr V-K103S V-K113S
end_nodes                      ('5498236250497948633', '4764732356959599958', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.012035
2023-02-13 05:00:00.000 +01:00                                           0.007704
2023-02-13 23:00:00.000 +01:00                                           0.011309

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.004345
2023-02-13 05:00:00.000 +01:00  0.010155
2023-02-13 23:00:00.000 +01:00  0.004887

tk                                                                    5192970129555982907  \
name                                                                 Rohr V-K113S V-K123S
end_nodes                      ('4764732356959599958', '5648425495460137243', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.015949
2023-02-13 05:00:00.000 +01:00                                           0.010211
2023-02-13 23:00:00.000 +01:00                                           0.014987

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.004761
2023-02-13 05:00:00.000 +01:00  0.011107
2023-02-13 23:00:00.000 +01:00  0.005354

tk                                                                    5027225217797463802  \
name                                                                 Rohr V-K123S V-K133S
end_nodes                      ('5648425495460137243', '5603354735453128217', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.014919
2023-02-13 05:00:00.000 +01:00                                           0.009560
2023-02-13 23:00:00.000 +01:00                                           0.014021

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.009291
2023-02-13 05:00:00.000 +01:00  0.021705
2023-02-13 23:00:00.000 +01:00  0.010451

tk                                                                    5107343838750080243  \
name                                                                 Rohr V-K133S V-K143S
end_nodes                      ('5603354735453128217', '5554918259063780747', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.057364
2023-02-13 05:00:00.000 +01:00                                           0.036867
2023-02-13 23:00:00.000 +01:00                                           0.053937

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.003588
2023-02-13 05:00:00.000 +01:00  0.008108
2023-02-13 23:00:00.000 +01:00  0.004017

tk                                                                    4840056338230495043  \
name                                                                 Rohr V-K153S V-K163S
end_nodes                      ('4992867596416688120', '4921884425075838112', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.057824
2023-02-13 05:00:00.000 +01:00                                           0.036898
2023-02-13 23:00:00.000 +01:00                                           0.054310

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.032887
2023-02-13 05:00:00.000 +01:00  0.077411
2023-02-13 23:00:00.000 +01:00  0.037035

tk                                                                    5700872284015490704  \
name                                                                 Rohr V-K163S V-K143S
end_nodes                      ('4921884425075838112', '5554918259063780747', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           165.7806
2023-02-13 05:00:00.000 +01:00                                           165.7806
2023-02-13 23:00:00.000 +01:00                                           165.7806

tk                                   \
name
end_nodes
property                        PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.0
2023-02-13 05:00:00.000 +01:00  0.0
2023-02-13 23:00:00.000 +01:00  0.0

tk                                                                    5290590848336792638  \
name                                                                 Rohr V-K143S V-K173S
end_nodes                      ('5554918259063780747', '4858392140572707635', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           3.842942
2023-02-13 05:00:00.000 +01:00                                           3.842942
2023-02-13 23:00:00.000 +01:00                                           3.842942

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  4.289871e-25
2023-02-13 05:00:00.000 +01:00  5.327804e-27
2023-02-13 23:00:00.000 +01:00  2.590683e-25

tk                                                                    4781821593135991761  \
name                                                                 Rohr V-K173S V-K183S
end_nodes                      ('4858392140572707635', '5167668521501299921', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           64.19534
2023-02-13 05:00:00.000 +01:00                                           64.19534
2023-02-13 23:00:00.000 +01:00                                           64.19534

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  1.348729e-24
2023-02-13 05:00:00.000 +01:00  3.433976e-25
2023-02-13 23:00:00.000 +01:00  1.348729e-24

tk                                                                    4770083637349644299  \
name                                                                 Rohr V-K183S V-K193S
end_nodes                      ('5167668521501299921', '5362725334032147732', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           51.01035
2023-02-13 05:00:00.000 +01:00                                           51.01035
2023-02-13 23:00:00.000 +01:00                                           51.01035

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  1.908720e-25
2023-02-13 05:00:00.000 +01:00  5.278974e-25
2023-02-13 23:00:00.000 +01:00  1.032748e-24

tk                                                                    5140383994159421977  \
name                                                                 Rohr V-K193S V-K203S
end_nodes                      ('5362725334032147732', '5129584372458662150', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                            83.9612
2023-02-13 05:00:00.000 +01:00                                            83.9612
2023-02-13 23:00:00.000 +01:00                                            83.9612

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  1.368325e-24
2023-02-13 05:00:00.000 +01:00  3.078732e-24
2023-02-13 23:00:00.000 +01:00  1.368325e-24

tk                                                                    4615723899944629797  \
name                                                                 Rohr V-K203S V-K213S
end_nodes                      ('5129584372458662150', '5332825919690090061', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           64.28724
2023-02-13 05:00:00.000 +01:00                                           64.28724
2023-02-13 23:00:00.000 +01:00                                           64.28724

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  3.057601e-24
2023-02-13 05:00:00.000 +01:00  0.000000e+00
2023-02-13 23:00:00.000 +01:00  1.325991e-24

tk                                                                    5485743457841402038  \
name                                                                 Rohr V-K213S V-K223S
end_nodes                      ('5332825919690090061', '5210475429427900126', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                            43.0797
2023-02-13 05:00:00.000 +01:00                                            43.0797
2023-02-13 23:00:00.000 +01:00                                            43.0797

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  1.248133e-24
2023-02-13 05:00:00.000 +01:00  3.120333e-25
2023-02-13 23:00:00.000 +01:00  3.120333e-25

tk                                                                    5061682782623660813  \
name                                                                 Rohr V-K233S V-K243S
end_nodes                      ('5434645737310584056', '4704578559698354879', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.092052
2023-02-13 05:00:00.000 +01:00                                           0.059074
2023-02-13 23:00:00.000 +01:00                                           0.086533

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.003742
2023-02-13 05:00:00.000 +01:00  0.008446
2023-02-13 23:00:00.000 +01:00  0.004189

tk                                                                    4868922965129592512  \
name                                                                 Rohr V-K243S V-K253S

... or as a list of int indices.

In [28]:
simulation_timestamps=s3s.GetTimeStamps()[0]

In [29]:
for idx, timestamp in enumerate(simulation_timestamps):
    print(idx, timestamp)

0 2023-02-13 00:00:00.000 +01:00
1 2023-02-13 01:00:00.000 +01:00
2 2023-02-13 02:00:00.000 +01:00
3 2023-02-13 03:00:00.000 +01:00
4 2023-02-13 04:00:00.000 +01:00
5 2023-02-13 05:00:00.000 +01:00
6 2023-02-13 06:00:00.000 +01:00
7 2023-02-13 07:00:00.000 +01:00
8 2023-02-13 08:00:00.000 +01:00
9 2023-02-13 09:00:00.000 +01:00
10 2023-02-13 10:00:00.000 +01:00
11 2023-02-13 11:00:00.000 +01:00
12 2023-02-13 12:00:00.000 +01:00
13 2023-02-13 13:00:00.000 +01:00
14 2023-02-13 14:00:00.000 +01:00
15 2023-02-13 15:00:00.000 +01:00
16 2023-02-13 16:00:00.000 +01:00
17 2023-02-13 17:00:00.000 +01:00
18 2023-02-13 18:00:00.000 +01:00
19 2023-02-13 19:00:00.000 +01:00
20 2023-02-13 20:00:00.000 +01:00
21 2023-02-13 21:00:00.000 +01:00
22 2023-02-13 22:00:00.000 +01:00
23 2023-02-13 23:00:00.000 +01:00
24 2023-02-14 00:00:00.000 +01:00

In [30]:
(s3s.generate_element_results_dataframe(element_type=s3s.ObjectTypes.Pipe
                                        ,properties=["DTTR", "PHR"]
                                        ,timestamps=[0, 5, -2] 
                                        )).head(3)

[2026-06-08 10:26:04,713] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-06-08 10:26:04,846] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 3 timestamps: ['2023-02-13 00:00:00.000 +01:00', '2023-02-13 05:00:00.000 +01:00', '2023-02-13 23:00:00.000 +01:00']
[2026-06-08 10:26:04,849] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 10:26:04,851] INFO in sir3stoolkit.mantle.dataframes: [results] Using 2 result properties.
[2026-06-08 10:26:04,895] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 10:26:05,527] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 10:26:05,722] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (3, 1048)

tk                                                                    5442010239090746007  \
name                                                                   Rohr V-K03S V-K13S
end_nodes                      ('5669301360686511351', '5397948523091900401', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.013437
2023-02-13 05:00:00.000 +01:00                                           0.008582
2023-02-13 23:00:00.000 +01:00                                           0.012622

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.010421
2023-02-13 05:00:00.000 +01:00  0.024731
2023-02-13 23:00:00.000 +01:00  0.011750

tk                                                                    4917786378639043296  \
name                                                                   Rohr V-K13S V-K23S
end_nodes                      ('5397948523091900401', '5239335112004772156', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.025371
2023-02-13 05:00:00.000 +01:00                                           0.016282
2023-02-13 23:00:00.000 +01:00                                           0.023852

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.014625
2023-02-13 05:00:00.000 +01:00  0.034240
2023-02-13 23:00:00.000 +01:00  0.016454

tk                                                                    4762482310382009633  \
name                                                                   Rohr V-K23S V-K33S
end_nodes                      ('5239335112004772156', '5298886695042021307', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.017832
2023-02-13 05:00:00.000 +01:00                                           0.011407
2023-02-13 23:00:00.000 +01:00                                           0.016755

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.010872
2023-02-13 05:00:00.000 +01:00  0.025619
2023-02-13 23:00:00.000 +01:00  0.012245

tk                                                                    4987229536643024523  \
name                                                                   Rohr V-K33S V-K43S
end_nodes                      ('5298886695042021307', '4993257270457791438', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.002972
2023-02-13 05:00:00.000 +01:00                                           0.001901
2023-02-13 23:00:00.000 +01:00                                           0.002793

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.001812
2023-02-13 05:00:00.000 +01:00  0.004270
2023-02-13 23:00:00.000 +01:00  0.002041

tk                                                                    5722206630503885118  \
name                                                                   Rohr V-K43S V-K53S
end_nodes                      ('4993257270457791438', '5317865645994989592', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.003259
2023-02-13 05:00:00.000 +01:00                                           0.002085
2023-02-13 23:00:00.000 +01:00                                           0.003063

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.001987
2023-02-13 05:00:00.000 +01:00  0.004683
2023-02-13 23:00:00.000 +01:00  0.002238

tk                                                                    5089459212485379804  \
name                                                                   Rohr V-K53S V-K63S
end_nodes                      ('5317865645994989592', '5085491372308261877', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.003620
2023-02-13 05:00:00.000 +01:00                                           0.002316
2023-02-13 23:00:00.000 +01:00                                           0.003401

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.002207
2023-02-13 05:00:00.000 +01:00  0.005200
2023-02-13 23:00:00.000 +01:00  0.002486

tk                                                                    5526871502288882655  \
name                                                                   Rohr V-K63S V-K73S
end_nodes                      ('5085491372308261877', '4989694427717344427', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.039475
2023-02-13 05:00:00.000 +01:00                                           0.025259
2023-02-13 23:00:00.000 +01:00                                           0.037092

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.018532
2023-02-13 05:00:00.000 +01:00  0.043554
2023-02-13 23:00:00.000 +01:00  0.020864

tk                                                                    4809089329099085219  \
name                                                                   Rohr V-K73S V-K83S
end_nodes                      ('4989694427717344427', '5097833100706648505', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.001627
2023-02-13 05:00:00.000 +01:00                                           0.001041
2023-02-13 23:00:00.000 +01:00                                           0.001529

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.002248
2023-02-13 05:00:00.000 +01:00  0.005313
2023-02-13 23:00:00.000 +01:00  0.002533

tk                                                                    5170001087020228683  \
name                                                                   Rohr V-K83S V-K93S
end_nodes                      ('5097833100706648505', '5748593725990350490', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.002951
2023-02-13 05:00:00.000 +01:00                                           0.001889
2023-02-13 23:00:00.000 +01:00                                           0.002773

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.001065
2023-02-13 05:00:00.000 +01:00  0.002490
2023-02-13 23:00:00.000 +01:00  0.001198

tk                                                                    5625716875961234775  \
name                                                                  Rohr V-K93S V-K103S
end_nodes                      ('5748593725990350490', '5498236250497948633', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.002250
2023-02-13 05:00:00.000 +01:00                                           0.001441
2023-02-13 23:00:00.000 +01:00                                           0.002115

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.000812
2023-02-13 05:00:00.000 +01:00  0.001899
2023-02-13 23:00:00.000 +01:00  0.000914

tk                                                                    5501916898830363065  \
name                                                                 Rohr V-K103S V-K113S
end_nodes                      ('5498236250497948633', '4764732356959599958', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.012035
2023-02-13 05:00:00.000 +01:00                                           0.007704
2023-02-13 23:00:00.000 +01:00                                           0.011309

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.004345
2023-02-13 05:00:00.000 +01:00  0.010155
2023-02-13 23:00:00.000 +01:00  0.004887

tk                                                                    5192970129555982907  \
name                                                                 Rohr V-K113S V-K123S
end_nodes                      ('4764732356959599958', '5648425495460137243', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.015949
2023-02-13 05:00:00.000 +01:00                                           0.010211
2023-02-13 23:00:00.000 +01:00                                           0.014987

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.004761
2023-02-13 05:00:00.000 +01:00  0.011107
2023-02-13 23:00:00.000 +01:00  0.005354

tk                                                                    5027225217797463802  \
name                                                                 Rohr V-K123S V-K133S
end_nodes                      ('5648425495460137243', '5603354735453128217', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.014919
2023-02-13 05:00:00.000 +01:00                                           0.009560
2023-02-13 23:00:00.000 +01:00                                           0.014021

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.009291
2023-02-13 05:00:00.000 +01:00  0.021705
2023-02-13 23:00:00.000 +01:00  0.010451

tk                                                                    5107343838750080243  \
name                                                                 Rohr V-K133S V-K143S
end_nodes                      ('5603354735453128217', '5554918259063780747', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.057364
2023-02-13 05:00:00.000 +01:00                                           0.036867
2023-02-13 23:00:00.000 +01:00                                           0.053937

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.003588
2023-02-13 05:00:00.000 +01:00  0.008108
2023-02-13 23:00:00.000 +01:00  0.004017

tk                                                                    4840056338230495043  \
name                                                                 Rohr V-K153S V-K163S
end_nodes                      ('4992867596416688120', '4921884425075838112', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.057824
2023-02-13 05:00:00.000 +01:00                                           0.036898
2023-02-13 23:00:00.000 +01:00                                           0.054310

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.032887
2023-02-13 05:00:00.000 +01:00  0.077411
2023-02-13 23:00:00.000 +01:00  0.037035

tk                                                                    5700872284015490704  \
name                                                                 Rohr V-K163S V-K143S
end_nodes                      ('4921884425075838112', '5554918259063780747', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           165.7806
2023-02-13 05:00:00.000 +01:00                                           165.7806
2023-02-13 23:00:00.000 +01:00                                           165.7806

tk                                   \
name
end_nodes
property                        PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.0
2023-02-13 05:00:00.000 +01:00  0.0
2023-02-13 23:00:00.000 +01:00  0.0

tk                                                                    5290590848336792638  \
name                                                                 Rohr V-K143S V-K173S
end_nodes                      ('5554918259063780747', '4858392140572707635', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           3.842942
2023-02-13 05:00:00.000 +01:00                                           3.842942
2023-02-13 23:00:00.000 +01:00                                           3.842942

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  4.289871e-25
2023-02-13 05:00:00.000 +01:00  5.327804e-27
2023-02-13 23:00:00.000 +01:00  2.590683e-25

tk                                                                    4781821593135991761  \
name                                                                 Rohr V-K173S V-K183S
end_nodes                      ('4858392140572707635', '5167668521501299921', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           64.19534
2023-02-13 05:00:00.000 +01:00                                           64.19534
2023-02-13 23:00:00.000 +01:00                                           64.19534

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  1.348729e-24
2023-02-13 05:00:00.000 +01:00  3.433976e-25
2023-02-13 23:00:00.000 +01:00  1.348729e-24

tk                                                                    4770083637349644299  \
name                                                                 Rohr V-K183S V-K193S
end_nodes                      ('5167668521501299921', '5362725334032147732', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           51.01035
2023-02-13 05:00:00.000 +01:00                                           51.01035
2023-02-13 23:00:00.000 +01:00                                           51.01035

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  1.908720e-25
2023-02-13 05:00:00.000 +01:00  5.278974e-25
2023-02-13 23:00:00.000 +01:00  1.032748e-24

tk                                                                    5140383994159421977  \
name                                                                 Rohr V-K193S V-K203S
end_nodes                      ('5362725334032147732', '5129584372458662150', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                            83.9612
2023-02-13 05:00:00.000 +01:00                                            83.9612
2023-02-13 23:00:00.000 +01:00                                            83.9612

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  1.368325e-24
2023-02-13 05:00:00.000 +01:00  3.078732e-24
2023-02-13 23:00:00.000 +01:00  1.368325e-24

tk                                                                    4615723899944629797  \
name                                                                 Rohr V-K203S V-K213S
end_nodes                      ('5129584372458662150', '5332825919690090061', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           64.28724
2023-02-13 05:00:00.000 +01:00                                           64.28724
2023-02-13 23:00:00.000 +01:00                                           64.28724

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  3.057601e-24
2023-02-13 05:00:00.000 +01:00  0.000000e+00
2023-02-13 23:00:00.000 +01:00  1.325991e-24

tk                                                                    5485743457841402038  \
name                                                                 Rohr V-K213S V-K223S
end_nodes                      ('5332825919690090061', '5210475429427900126', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                            43.0797
2023-02-13 05:00:00.000 +01:00                                            43.0797
2023-02-13 23:00:00.000 +01:00                                            43.0797

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  1.248133e-24
2023-02-13 05:00:00.000 +01:00  3.120333e-25
2023-02-13 23:00:00.000 +01:00  3.120333e-25

tk                                                                    5061682782623660813  \
name                                                                 Rohr V-K233S V-K243S
end_nodes                      ('5434645737310584056', '4704578559698354879', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.092052
2023-02-13 05:00:00.000 +01:00                                           0.059074
2023-02-13 23:00:00.000 +01:00                                           0.086533

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.003742
2023-02-13 05:00:00.000 +01:00  0.008446
2023-02-13 23:00:00.000 +01:00  0.004189

tk                                                                    4868922965129592512  \
name                                                                 Rohr V-K243S V-K253S

### Subcase 4: Specific Timestamps + Specific Values + Filtering

If we want to filter for more than just the container, we have to filter tks outside the function and then pass them. Works same way as for model_data.

In [31]:
all_tks = s3s.GetTksofElementType(s3s.ObjectTypes.Pipe)

In [32]:
len(all_tks)

524

In [33]:
good_tks = []

In [34]:
for tk in all_tks:
    if s3s.GetValue(tk, "FkCont")[0] == "5029128874972463118":
        if s3s.GetValue(tk, "bz.Irtrenn")[0] == "0": # Rohr nicht getrennt
            good_tks.append(tk)

In [35]:
len(good_tks)

480

In [36]:
(s3s.generate_element_results_dataframe(element_type=s3s.ObjectTypes.Pipe
                                        ,tks=good_tks # here we specify that not all available tks should be used
                                        ,properties=["DTTR", "PHR"]
                                        ,timestamps=[0, 5, -2] 
                                        )).head(3)

[2026-06-08 10:26:07,091] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-06-08 10:26:07,242] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 3 timestamps: ['2023-02-13 00:00:00.000 +01:00', '2023-02-13 05:00:00.000 +01:00', '2023-02-13 23:00:00.000 +01:00']
[2026-06-08 10:26:07,245] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 10:26:07,251] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] 480 tks remain after filtering for given tks.
[2026-06-08 10:26:07,256] INFO in sir3stoolkit.mantle.dataframes: [results] Using 2 result properties.
[2026-06-08 10:26:07,282] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 10:26:07,939] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 10:26:08,134] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (3, 960)

tk                                                                    5442010239090746007  \
name                                                                   Rohr V-K03S V-K13S
end_nodes                      ('5669301360686511351', '5397948523091900401', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.013437
2023-02-13 05:00:00.000 +01:00                                           0.008582
2023-02-13 23:00:00.000 +01:00                                           0.012622

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.010421
2023-02-13 05:00:00.000 +01:00  0.024731
2023-02-13 23:00:00.000 +01:00  0.011750

tk                                                                    4917786378639043296  \
name                                                                   Rohr V-K13S V-K23S
end_nodes                      ('5397948523091900401', '5239335112004772156', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.025371
2023-02-13 05:00:00.000 +01:00                                           0.016282
2023-02-13 23:00:00.000 +01:00                                           0.023852

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.014625
2023-02-13 05:00:00.000 +01:00  0.034240
2023-02-13 23:00:00.000 +01:00  0.016454

tk                                                                    4762482310382009633  \
name                                                                   Rohr V-K23S V-K33S
end_nodes                      ('5239335112004772156', '5298886695042021307', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.017832
2023-02-13 05:00:00.000 +01:00                                           0.011407
2023-02-13 23:00:00.000 +01:00                                           0.016755

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.010872
2023-02-13 05:00:00.000 +01:00  0.025619
2023-02-13 23:00:00.000 +01:00  0.012245

tk                                                                    4987229536643024523  \
name                                                                   Rohr V-K33S V-K43S
end_nodes                      ('5298886695042021307', '4993257270457791438', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.002972
2023-02-13 05:00:00.000 +01:00                                           0.001901
2023-02-13 23:00:00.000 +01:00                                           0.002793

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.001812
2023-02-13 05:00:00.000 +01:00  0.004270
2023-02-13 23:00:00.000 +01:00  0.002041

tk                                                                    5722206630503885118  \
name                                                                   Rohr V-K43S V-K53S
end_nodes                      ('4993257270457791438', '5317865645994989592', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.003259
2023-02-13 05:00:00.000 +01:00                                           0.002085
2023-02-13 23:00:00.000 +01:00                                           0.003063

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.001987
2023-02-13 05:00:00.000 +01:00  0.004683
2023-02-13 23:00:00.000 +01:00  0.002238

tk                                                                    5089459212485379804  \
name                                                                   Rohr V-K53S V-K63S
end_nodes                      ('5317865645994989592', '5085491372308261877', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.003620
2023-02-13 05:00:00.000 +01:00                                           0.002316
2023-02-13 23:00:00.000 +01:00                                           0.003401

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.002207
2023-02-13 05:00:00.000 +01:00  0.005200
2023-02-13 23:00:00.000 +01:00  0.002486

tk                                                                    5526871502288882655  \
name                                                                   Rohr V-K63S V-K73S
end_nodes                      ('5085491372308261877', '4989694427717344427', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.039475
2023-02-13 05:00:00.000 +01:00                                           0.025259
2023-02-13 23:00:00.000 +01:00                                           0.037092

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.018532
2023-02-13 05:00:00.000 +01:00  0.043554
2023-02-13 23:00:00.000 +01:00  0.020864

tk                                                                    4809089329099085219  \
name                                                                   Rohr V-K73S V-K83S
end_nodes                      ('4989694427717344427', '5097833100706648505', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.001627
2023-02-13 05:00:00.000 +01:00                                           0.001041
2023-02-13 23:00:00.000 +01:00                                           0.001529

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.002248
2023-02-13 05:00:00.000 +01:00  0.005313
2023-02-13 23:00:00.000 +01:00  0.002533

tk                                                                    5170001087020228683  \
name                                                                   Rohr V-K83S V-K93S
end_nodes                      ('5097833100706648505', '5748593725990350490', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.002951
2023-02-13 05:00:00.000 +01:00                                           0.001889
2023-02-13 23:00:00.000 +01:00                                           0.002773

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.001065
2023-02-13 05:00:00.000 +01:00  0.002490
2023-02-13 23:00:00.000 +01:00  0.001198

tk                                                                    5625716875961234775  \
name                                                                  Rohr V-K93S V-K103S
end_nodes                      ('5748593725990350490', '5498236250497948633', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.002250
2023-02-13 05:00:00.000 +01:00                                           0.001441
2023-02-13 23:00:00.000 +01:00                                           0.002115

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.000812
2023-02-13 05:00:00.000 +01:00  0.001899
2023-02-13 23:00:00.000 +01:00  0.000914

tk                                                                    5501916898830363065  \
name                                                                 Rohr V-K103S V-K113S
end_nodes                      ('5498236250497948633', '4764732356959599958', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.012035
2023-02-13 05:00:00.000 +01:00                                           0.007704
2023-02-13 23:00:00.000 +01:00                                           0.011309

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.004345
2023-02-13 05:00:00.000 +01:00  0.010155
2023-02-13 23:00:00.000 +01:00  0.004887

tk                                                                    5192970129555982907  \
name                                                                 Rohr V-K113S V-K123S
end_nodes                      ('4764732356959599958', '5648425495460137243', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.015949
2023-02-13 05:00:00.000 +01:00                                           0.010211
2023-02-13 23:00:00.000 +01:00                                           0.014987

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.004761
2023-02-13 05:00:00.000 +01:00  0.011107
2023-02-13 23:00:00.000 +01:00  0.005354

tk                                                                    5027225217797463802  \
name                                                                 Rohr V-K123S V-K133S
end_nodes                      ('5648425495460137243', '5603354735453128217', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.014919
2023-02-13 05:00:00.000 +01:00                                           0.009560
2023-02-13 23:00:00.000 +01:00                                           0.014021

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.009291
2023-02-13 05:00:00.000 +01:00  0.021705
2023-02-13 23:00:00.000 +01:00  0.010451

tk                                                                    5107343838750080243  \
name                                                                 Rohr V-K133S V-K143S
end_nodes                      ('5603354735453128217', '5554918259063780747', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.057364
2023-02-13 05:00:00.000 +01:00                                           0.036867
2023-02-13 23:00:00.000 +01:00                                           0.053937

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.003588
2023-02-13 05:00:00.000 +01:00  0.008108
2023-02-13 23:00:00.000 +01:00  0.004017

tk                                                                    4840056338230495043  \
name                                                                 Rohr V-K153S V-K163S
end_nodes                      ('4992867596416688120', '4921884425075838112', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.057824
2023-02-13 05:00:00.000 +01:00                                           0.036898
2023-02-13 23:00:00.000 +01:00                                           0.054310

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.032887
2023-02-13 05:00:00.000 +01:00  0.077411
2023-02-13 23:00:00.000 +01:00  0.037035

tk                                                                    4781821593135991761  \
name                                                                 Rohr V-K173S V-K183S
end_nodes                      ('4858392140572707635', '5167668521501299921', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           64.19534
2023-02-13 05:00:00.000 +01:00                                           64.19534
2023-02-13 23:00:00.000 +01:00                                           64.19534

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  1.348729e-24
2023-02-13 05:00:00.000 +01:00  3.433976e-25
2023-02-13 23:00:00.000 +01:00  1.348729e-24

tk                                                                    4770083637349644299  \
name                                                                 Rohr V-K183S V-K193S
end_nodes                      ('5167668521501299921', '5362725334032147732', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           51.01035
2023-02-13 05:00:00.000 +01:00                                           51.01035
2023-02-13 23:00:00.000 +01:00                                           51.01035

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  1.908720e-25
2023-02-13 05:00:00.000 +01:00  5.278974e-25
2023-02-13 23:00:00.000 +01:00  1.032748e-24

tk                                                                    5140383994159421977  \
name                                                                 Rohr V-K193S V-K203S
end_nodes                      ('5362725334032147732', '5129584372458662150', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                            83.9612
2023-02-13 05:00:00.000 +01:00                                            83.9612
2023-02-13 23:00:00.000 +01:00                                            83.9612

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  1.368325e-24
2023-02-13 05:00:00.000 +01:00  3.078732e-24
2023-02-13 23:00:00.000 +01:00  1.368325e-24

tk                                                                    4615723899944629797  \
name                                                                 Rohr V-K203S V-K213S
end_nodes                      ('5129584372458662150', '5332825919690090061', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           64.28724
2023-02-13 05:00:00.000 +01:00                                           64.28724
2023-02-13 23:00:00.000 +01:00                                           64.28724

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  3.057601e-24
2023-02-13 05:00:00.000 +01:00  0.000000e+00
2023-02-13 23:00:00.000 +01:00  1.325991e-24

tk                                                                    5485743457841402038  \
name                                                                 Rohr V-K213S V-K223S
end_nodes                      ('5332825919690090061', '5210475429427900126', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                            43.0797
2023-02-13 05:00:00.000 +01:00                                            43.0797
2023-02-13 23:00:00.000 +01:00                                            43.0797

tk                                            \
name
end_nodes
property                                 PHR
timestamp
2023-02-13 00:00:00.000 +01:00  1.248133e-24
2023-02-13 05:00:00.000 +01:00  3.120333e-25
2023-02-13 23:00:00.000 +01:00  3.120333e-25

tk                                                                    5061682782623660813  \
name                                                                 Rohr V-K233S V-K243S
end_nodes                      ('5434645737310584056', '4704578559698354879', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.092052
2023-02-13 05:00:00.000 +01:00                                           0.059074
2023-02-13 23:00:00.000 +01:00                                           0.086533

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.003742
2023-02-13 05:00:00.000 +01:00  0.008446
2023-02-13 23:00:00.000 +01:00  0.004189

tk                                                                    4868922965129592512  \
name                                                                 Rohr V-K243S V-K253S
end_nodes                      ('4704578559698354879', '5387381929229094663', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.007840
2023-02-13 05:00:00.000 +01:00                                           0.005003
2023-02-13 23:00:00.000 +01:00                                           0.007363

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.002576
2023-02-13 05:00:00.000 +01:00  0.006018
2023-02-13 23:00:00.000 +01:00  0.002898

tk                                                                    5253822763469470014  \
name                                                                 Rohr V-K253S V-K263S
end_nodes                      ('5387381929229094663', '5013768275797703467', '-1', '-1')
property                                                                             DTTR
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.017054
2023-02-13 05:00:00.000 +01:00                                           0.010888
2023-02-13 23:00:00.000 +01:00                                           0.016019

tk                                        \
name
end_nodes
property                             PHR
timestamp
2023-02-13 00:00:00.000 +01:00  0.006804
2023-02-13 05:00:00.000 +01:00  0.016003
2023-02-13 23:00:00.000 +01:00  0.007661

tk                                                                    5468996363795343031  \
name                                                                 Rohr V-K263S V-K273S

### Subcase 5: Specific Vectorized results + Specific Timestamps

For pipes we have interior point result values. These are usually found as vectors with the postfix VEC.

In [37]:
available_result_props=s3s.GetResultProperties_from_elementType(s3s.ObjectTypes.Pipe,False)

In [38]:
available_result_props

['A',
 'ACALC',
 'CPI',
 'CPK',
 'DH',
 'DP',
 'DRAGRED',
 'DRAKONZ',
 'DSI',
 'DSK',
 'DTTR',
 'DWVERL',
 'DWVERLABS',
 'ETAAV',
 'FS',
 'HR',
 'HVEC',
 'IAKTIV',
 'IRTRENN',
 'JV',
 'JV2',
 'LAMBDA',
 'LECKEINAUS',
 'LECKMENGE',
 'LECKORT',
 'LINEPACK',
 'LINEPACKGEOM',
 'LINEPACKRATE',
 'MAINELEMENT',
 'MAV',
 'MI',
 'MK',
 'MKOND',
 'MMAX_INST',
 'MMIN_INST',
 'MVEC',
 'MVECMAX_INST',
 'MVECMIN_INST',
 'PAV',
 'PDAMPF',
 'PHR',
 'PHVEC',
 'PMAX',
 'PMIN',
 'PR',
 'PVEC',
 'PVECMAX_INST',
 'PVECMIN_INST',
 'QI2',
 'QK2',
 'QMAV',
 'QMI',
 'QMK',
 'QMMAX_INST',
 'QMMIN_INST',
 'QMVEC',
 'QSVB',
 'RHOAV',
 'RHOI',
 'RHOK',
 'RHOVEC',
 'SVEC',
 'TAV',
 'TI',
 'TK',
 'TTRVEC',
 'TVEC',
 'TVECMAX_INST',
 'TVECMIN_INST',
 'VAV',
 'VI',
 'VK',
 'VMAX_INST',
 'VMIN_INST',
 'VOLDA',
 'WALTERI',
 'WALTERK',
 'WVL',
 'ZAUS',
 'ZEIN',
 'ZHKNR',
 'ZVEC']

In [39]:
available_result_vector_props=[available_result_props for available_result_props in available_result_props if "VEC" in available_result_props]

In [40]:
available_result_vector_props

['HVEC',
 'MVEC',
 'MVECMAX_INST',
 'MVECMIN_INST',
 'PHVEC',
 'PVEC',
 'PVECMAX_INST',
 'PVECMIN_INST',
 'QMVEC',
 'RHOVEC',
 'SVEC',
 'TTRVEC',
 'TVEC',
 'TVECMAX_INST',
 'TVECMIN_INST',
 'ZVEC']

In [41]:
df_pipes = s3s.generate_element_results_dataframe(element_type=s3s.ObjectTypes.Pipe
                                        ,properties=["TTRVEC", "MVEC", "DTTR"]
                                        ,timestamps=[0, 5, -2] 
                                        )

[2026-06-08 10:26:09,351] INFO in sir3stoolkit.mantle.dataframes: [results] Generating results dataframe for element type: ObjectTypes.Pipe
[2026-06-08 10:26:09,528] INFO in sir3stoolkit.mantle.dataframes: [Resolving Timestamps] Using 3 timestamps: ['2023-02-13 00:00:00.000 +01:00', '2023-02-13 05:00:00.000 +01:00', '2023-02-13 23:00:00.000 +01:00']
[2026-06-08 10:26:09,528] INFO in sir3stoolkit.mantle.dataframes: [Resolving tks] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 10:26:09,546] INFO in sir3stoolkit.mantle.dataframes: [results] Using 3 result properties.
[2026-06-08 10:26:09,605] INFO in sir3stoolkit.mantle.dataframes: [results] Retrieving result values...
[2026-06-08 10:26:10,673] INFO in sir3stoolkit.mantle.dataframes: [results] 0 fully NaN columns dropped.
[2026-06-08 10:26:11,075] INFO in sir3stoolkit.mantle.dataframes: [results] Done. Shape: (3, 1572)

In [42]:
df_pipes.head(3)

tk                                                                    5442010239090746007  \
name                                                                   Rohr V-K03S V-K13S
end_nodes                      ('5669301360686511351', '5397948523091900401', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.3227228\t0.326082\t0.3294412\t0.3328004\t0.3...
2023-02-13 05:00:00.000 +01:00  0.2057882\t0.2079337\t0.2100792\t0.2122246\t0....
2023-02-13 23:00:00.000 +01:00  0.3030591\t0.3062146\t0.3093701\t0.3125256\t0....

tk                                                                                \
name
end_nodes
property                                                                    MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  14.68007\t14.68007\t14.68007\t14.68007\t14.68007
2023-02-13 05:00:00.000 +01:00  22.98332\t22.98332\t22.98332\t22.98332\t22.98332
2023-02-13 23:00:00.000 +01:00  15.62753\t15.62753\t15.62753\t15.62753\t15.62753

tk                                        \
name
end_nodes
property                            DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  0.013437
2023-02-13 05:00:00.000 +01:00  0.008582
2023-02-13 23:00:00.000 +01:00  0.012622

tk                                                                    4917786378639043296  \
name                                                                   Rohr V-K13S V-K23S
end_nodes                      ('5397948523091900401', '5239335112004772156', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.3361596\t0.3403881\t0.3446167\t0.3488453\t0....
2023-02-13 05:00:00.000 +01:00  0.2143701\t0.2170838\t0.2197974\t0.2225111\t0....
2023-02-13 23:00:00.000 +01:00  0.3156811\t0.3196564\t0.3236316\t0.3276069\t0....

tk                                                                                 \
name
end_nodes
property                                                                     MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  8.24275\t8.24275\t8.24275\t8.24275\t8.24275\t8...
2023-02-13 05:00:00.000 +01:00  12.84338\t12.84338\t12.84338\t12.84338\t12.843...
2023-02-13 23:00:00.000 +01:00  8.767911\t8.767911\t8.767911\t8.767911\t8.7679...

tk                                        \
name
end_nodes
property                            DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  0.025371
2023-02-13 05:00:00.000 +01:00  0.016282
2023-02-13 23:00:00.000 +01:00  0.023852

tk                                                                    4762482310382009633  \
name                                                                   Rohr V-K23S V-K33S
end_nodes                      ('5239335112004772156', '5298886695042021307', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.4288374\t0.4324038\t0.4359703\t0.4395368\t0....
2023-02-13 05:00:00.000 +01:00  0.273829\t0.2761104\t0.2783919\t0.2806734\t0.2...
2023-02-13 23:00:00.000 +01:00  0.4028447\t0.4061958\t0.4095468\t0.4128978\t0....

tk                                                                                 \
name
end_nodes
property                                                                     MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  8.403428\t8.403428\t8.403428\t8.403428\t8.4034...
2023-02-13 05:00:00.000 +01:00  13.13508\t13.13508\t13.13508\t13.13508\t13.135...
2023-02-13 23:00:00.000 +01:00  8.943539\t8.943539\t8.943539\t8.943539\t8.9435...

tk                                        \
name
end_nodes
property                            DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  0.017832
2023-02-13 05:00:00.000 +01:00  0.011407
2023-02-13 23:00:00.000 +01:00  0.016755

tk                                                                    4987229536643024523  \
name                                                                   Rohr V-K33S V-K43S
end_nodes                      ('5298886695042021307', '4993257270457791438', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00                               0.4466697\t0.4496421
2023-02-13 05:00:00.000 +01:00                               0.2852363\t0.2871377
2023-02-13 23:00:00.000 +01:00                               0.4195999\t0.4223926

tk                                                            \
name
end_nodes
property                                      MVEC      DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  8.403428\t8.403428  0.002972
2023-02-13 05:00:00.000 +01:00  13.13508\t13.13508  0.001901
2023-02-13 23:00:00.000 +01:00  8.943539\t8.943539  0.002793

tk                                                                    5722206630503885118  \
name                                                                   Rohr V-K43S V-K53S
end_nodes                      ('4993257270457791438', '5317865645994989592', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00                               0.4496421\t0.4529015
2023-02-13 05:00:00.000 +01:00                               0.2871377\t0.2892228
2023-02-13 23:00:00.000 +01:00                               0.4223926\t0.4254552

tk                                                            \
name
end_nodes
property                                      MVEC      DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  8.403428\t8.403428  0.003259
2023-02-13 05:00:00.000 +01:00  13.13508\t13.13508  0.002085
2023-02-13 23:00:00.000 +01:00  8.943539\t8.943539  0.003063

tk                                                                    5089459212485379804  \
name                                                                   Rohr V-K53S V-K63S
end_nodes                      ('5317865645994989592', '5085491372308261877', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00                               0.4529015\t0.4565214
2023-02-13 05:00:00.000 +01:00                               0.2892228\t0.2915384
2023-02-13 23:00:00.000 +01:00                               0.4254552\t0.4288564

tk                                                            \
name
end_nodes
property                                      MVEC      DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  8.403428\t8.403428  0.003620
2023-02-13 05:00:00.000 +01:00  13.13508\t13.13508  0.002316
2023-02-13 23:00:00.000 +01:00  8.943539\t8.943539  0.003401

tk                                                                    5526871502288882655  \
name                                                                   Rohr V-K63S V-K73S
end_nodes                      ('5085491372308261877', '4989694427717344427', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.4565214\t0.4609075\t0.4652937\t0.4696799\t0....
2023-02-13 05:00:00.000 +01:00  0.2915384\t0.2943449\t0.2971514\t0.299958\t0.3...
2023-02-13 23:00:00.000 +01:00  0.4288564\t0.4329778\t0.4370991\t0.4412205\t0....

tk                                                                                 \
name
end_nodes
property                                                                     MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  7.680472\t7.680472\t7.680472\t7.680472\t7.6804...
2023-02-13 05:00:00.000 +01:00  12.0017\t12.0017\t12.0017\t12.0017\t12.0017\t1...
2023-02-13 23:00:00.000 +01:00  8.173762\t8.173762\t8.173762\t8.173762\t8.1737...

tk                                        \
name
end_nodes
property                            DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  0.039475
2023-02-13 05:00:00.000 +01:00  0.025259
2023-02-13 23:00:00.000 +01:00  0.037092

tk                                                                    4809089329099085219  \
name                                                                   Rohr V-K73S V-K83S
end_nodes                      ('4989694427717344427', '5097833100706648505', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00                               0.4959968\t0.4976238
2023-02-13 05:00:00.000 +01:00                               0.3167973\t0.3178388
2023-02-13 23:00:00.000 +01:00                               0.4659487\t0.4674776

tk                                                            \
name
end_nodes
property                                      MVEC      DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  6.748159\t6.748159  0.001627
2023-02-13 05:00:00.000 +01:00  10.54151\t10.54151  0.001041
2023-02-13 23:00:00.000 +01:00    7.18122\t7.18122  0.001529

tk                                                                    5170001087020228683  \
name                                                                   Rohr V-K83S V-K93S
end_nodes                      ('5097833100706648505', '5748593725990350490', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00                               0.4976238\t0.5005747
2023-02-13 05:00:00.000 +01:00                               0.3178388\t0.3197278
2023-02-13 23:00:00.000 +01:00                               0.4674776\t0.4702505

tk                                                            \
name
end_nodes
property                                      MVEC      DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  4.251046\t4.251046  0.002951
2023-02-13 05:00:00.000 +01:00  6.639488\t6.639488  0.001889
2023-02-13 23:00:00.000 +01:00  4.523731\t4.523731  0.002773

tk                                                                    5625716875961234775  \
name                                                                  Rohr V-K93S V-K103S
end_nodes                      ('5748593725990350490', '5498236250497948633', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00                                0.5005747\t0.502825
2023-02-13 05:00:00.000 +01:00                               0.3197278\t0.3211684
2023-02-13 23:00:00.000 +01:00                               0.4702505\t0.4723651

tk                                                            \
name
end_nodes
property                                      MVEC      DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  4.251046\t4.251046  0.002250
2023-02-13 05:00:00.000 +01:00  6.639488\t6.639488  0.001441
2023-02-13 23:00:00.000 +01:00  4.523731\t4.523731  0.002115

tk                                                                    5501916898830363065  \
name                                                                 Rohr V-K103S V-K113S
end_nodes                      ('5498236250497948633', '4764732356959599958', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00          0.502825\t0.5068366\t0.5108482\t0.5148597
2023-02-13 05:00:00.000 +01:00         0.3211684\t0.3237365\t0.3263046\t0.3288727
2023-02-13 23:00:00.000 +01:00         0.4723651\t0.4761348\t0.4799044\t0.4836741

tk                                                                      \
name
end_nodes
property                                                          MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  4.251046\t4.251046\t4.251046\t4.251046
2023-02-13 05:00:00.000 +01:00  6.639488\t6.639488\t6.639488\t6.639488
2023-02-13 23:00:00.000 +01:00  4.523731\t4.523731\t4.523731\t4.523731

tk                                        \
name
end_nodes
property                            DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  0.012035
2023-02-13 05:00:00.000 +01:00  0.007704
2023-02-13 23:00:00.000 +01:00  0.011309

tk                                                                    5192970129555982907  \
name                                                                 Rohr V-K113S V-K123S
end_nodes                      ('4764732356959599958', '5648425495460137243', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00          0.5148597\t0.520176\t0.5254923\t0.5308086
2023-02-13 05:00:00.000 +01:00         0.3288727\t0.3322766\t0.3356804\t0.3390842
2023-02-13 23:00:00.000 +01:00         0.4836741\t0.4886699\t0.4936657\t0.4986615

tk                                                                      \
name
end_nodes
property                                                          MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  3.980511\t3.980511\t3.980511\t3.980511
2023-02-13 05:00:00.000 +01:00      6.21603\t6.21603\t6.21603\t6.21603
2023-02-13 23:00:00.000 +01:00  4.235746\t4.235746\t4.235746\t4.235746

tk                                        \
name
end_nodes
property                            DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  0.015949
2023-02-13 05:00:00.000 +01:00  0.010211
2023-02-13 23:00:00.000 +01:00  0.014987

tk                                                                    5027225217797463802  \
name                                                                 Rohr V-K123S V-K133S
end_nodes                      ('5648425495460137243', '5603354735453128217', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00         0.5308086\t0.5357814\t0.5407543\t0.5457272
2023-02-13 05:00:00.000 +01:00          0.3390842\t0.3422708\t0.3454574\t0.348644
2023-02-13 23:00:00.000 +01:00          0.4986615\t0.5033352\t0.508009\t0.5126826

tk                                                                      \
name
end_nodes
property                                                          MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  2.725789\t2.725789\t2.725789\t2.725789
2023-02-13 05:00:00.000 +01:00  4.253057\t4.253057\t4.253057\t4.253057
2023-02-13 23:00:00.000 +01:00  2.900195\t2.900195\t2.900195\t2.900195

tk                                        \
name
end_nodes
property                            DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  0.014919
2023-02-13 05:00:00.000 +01:00  0.009560
2023-02-13 23:00:00.000 +01:00  0.014021

tk                                                                    5107343838750080243  \
name                                                                 Rohr V-K133S V-K143S
end_nodes                      ('5603354735453128217', '5554918259063780747', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.5457272\t0.5572001\t0.568673\t0.5801458\t0.5...
2023-02-13 05:00:00.000 +01:00  0.348644\t0.3560175\t0.363391\t0.3707645\t0.37...
2023-02-13 23:00:00.000 +01:00  0.5126826\t0.52347\t0.5342574\t0.5450448\t0.55...

tk                                                                                 \
name
end_nodes
property                                                                     MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.4454001\t0.4454001\t0.4454001\t0.4454001\t0....
2023-02-13 05:00:00.000 +01:00  0.6928714\t0.6928714\t0.6928714\t0.6928714\t0....
2023-02-13 23:00:00.000 +01:00  0.4736846\t0.4736846\t0.4736846\t0.4736846\t0....

tk                                        \
name
end_nodes
property                            DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  0.057364
2023-02-13 05:00:00.000 +01:00  0.036867
2023-02-13 23:00:00.000 +01:00  0.053937

tk                                                                    4840056338230495043  \
name                                                                 Rohr V-K153S V-K163S
end_nodes                      ('4992867596416688120', '4921884425075838112', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0.3351198\t0.3403764\t0.3456331\t0.3508899\t0....
2023-02-13 05:00:00.000 +01:00  0.2133179\t0.2166723\t0.2200267\t0.223381\t0.2...
2023-02-13 23:00:00.000 +01:00  0.3146621\t0.3195994\t0.3245367\t0.329474\t0.3...

tk                                                                                 \
name
end_nodes
property                                                                     MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  2.641599\t2.641599\t2.641599\t2.641599\t2.6415...
2023-02-13 05:00:00.000 +01:00  4.13939\t4.13939\t4.13939\t4.13939\t4.13939\t4...
2023-02-13 23:00:00.000 +01:00  2.81246\t2.81246\t2.81246\t2.81246\t2.81246\t2...

tk                                        \
name
end_nodes
property                            DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  0.057824
2023-02-13 05:00:00.000 +01:00  0.036898
2023-02-13 23:00:00.000 +01:00  0.054310

tk                                                                    5700872284015490704  \
name                                                                 Rohr V-K163S V-K143S
end_nodes                      ('4921884425075838112', '5554918259063780747', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  166.2786\t166.2786\t166.2786\t166.2786\t166.27...
2023-02-13 05:00:00.000 +01:00  166.0984\t166.0984\t166.0984\t166.0984\t166.09...
2023-02-13 23:00:00.000 +01:00  166.2484\t166.2484\t166.2484\t166.2484\t166.24...

tk                                                                                 \
name
end_nodes
property                                                                     MVEC
timestamp
2023-02-13 00:00:00.000 +01:00  0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0...
2023-02-13 05:00:00.000 +01:00  0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0...
2023-02-13 23:00:00.000 +01:00  0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0...

tk                                        \
name
end_nodes
property                            DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  165.7806
2023-02-13 05:00:00.000 +01:00  165.7806
2023-02-13 23:00:00.000 +01:00  165.7806

tk                                                                    5290590848336792638  \
name                                                                 Rohr V-K143S V-K173S
end_nodes                      ('5554918259063780747', '4858392140572707635', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00                                 310.3768\t306.5338
2023-02-13 05:00:00.000 +01:00                                 175.4052\t171.5623
2023-02-13 23:00:00.000 +01:00                                0.5666201\t4.409562

tk                                                                      \
name
end_nodes
property                                                MVEC      DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  -4.570211E-10\t-4.570211E-10  3.842942
2023-02-13 05:00:00.000 +01:00    -5.09317E-11\t-5.09317E-11  3.842942
2023-02-13 23:00:00.000 +01:00    3.551577E-10\t3.551577E-10  3.842942

tk                                                                    4781821593135991761  \
name                                                                 Rohr V-K173S V-K183S
end_nodes                      ('4858392140572707635', '5167668521501299921', '-1', '-1')
property                                                                           TTRVEC
timestamp
2023-02-13 00:00:00.000 +01:00  306.5338\t297.3631\t288.1923\t279.0215\t269.85...

As can be seen, the vectorized result values are written as strings with "/" seperators. For better access we can extend these values to a multiindex using [add_interior_points_as_multiindex()](https://3sconsult.github.io/sir3stoolkit/references/sir3stoolkit.mantle.html#sir3stoolkit.mantle.dataframes.SIR3S_Model_Dataframes.add_interior_points_as_multiindex).

In [43]:
df_pipes_interior_points = s3s.add_interior_points_to_start_end_sequence(df_pipes)

In [44]:
df_pipes_interior_points.head(3)

tk                                                                    5442010239090746007  \
name                                                                   Rohr V-K03S V-K13S
end_nodes                      ('5669301360686511351', '5397948523091900401', '-1', '-1')
property                                                                     TTRVEC_start
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.322723
2023-02-13 05:00:00.000 +01:00                                           0.205788
2023-02-13 23:00:00.000 +01:00                                           0.303059

tk                                         \
name
end_nodes
property                       TTRVEC_end
timestamp
2023-02-13 00:00:00.000 +01:00   0.336160
2023-02-13 05:00:00.000 +01:00   0.214370
2023-02-13 23:00:00.000 +01:00   0.315681

tk                                                                                 \
name
end_nodes
property                                                          TTRVEC_sequence
timestamp
2023-02-13 00:00:00.000 +01:00  (0.3227228, 0.326082, 0.3294412, 0.3328004, 0....
2023-02-13 05:00:00.000 +01:00  (0.2057882, 0.2079337, 0.2100792, 0.2122246, 0...
2023-02-13 23:00:00.000 +01:00  (0.3030591, 0.3062146, 0.3093701, 0.3125256, 0...

tk                                                   \
name
end_nodes
property                       MVEC_start  MVEC_end
timestamp
2023-02-13 00:00:00.000 +01:00   14.68007  14.68007
2023-02-13 05:00:00.000 +01:00   22.98332  22.98332
2023-02-13 23:00:00.000 +01:00   15.62753  15.62753

tk                                                                                 \
name
end_nodes
property                                                            MVEC_sequence
timestamp
2023-02-13 00:00:00.000 +01:00  (14.68007, 14.68007, 14.68007, 14.68007, 14.68...
2023-02-13 05:00:00.000 +01:00  (22.98332, 22.98332, 22.98332, 22.98332, 22.98...
2023-02-13 23:00:00.000 +01:00  (15.62753, 15.62753, 15.62753, 15.62753, 15.62...

tk                                        \
name
end_nodes
property                            DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  0.013437
2023-02-13 05:00:00.000 +01:00  0.008582
2023-02-13 23:00:00.000 +01:00  0.012622

tk                                                                    4917786378639043296  \
name                                                                   Rohr V-K13S V-K23S
end_nodes                      ('5397948523091900401', '5239335112004772156', '-1', '-1')
property                                                                     TTRVEC_start
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.336160
2023-02-13 05:00:00.000 +01:00                                           0.214370
2023-02-13 23:00:00.000 +01:00                                           0.315681

tk                                         \
name
end_nodes
property                       TTRVEC_end
timestamp
2023-02-13 00:00:00.000 +01:00   0.361531
2023-02-13 05:00:00.000 +01:00   0.230652
2023-02-13 23:00:00.000 +01:00   0.339533

tk                                                                                 \
name
end_nodes
property                                                          TTRVEC_sequence
timestamp
2023-02-13 00:00:00.000 +01:00  (0.3361596, 0.3403881, 0.3446167, 0.3488453, 0...
2023-02-13 05:00:00.000 +01:00  (0.2143701, 0.2170838, 0.2197974, 0.2225111, 0...
2023-02-13 23:00:00.000 +01:00  (0.3156811, 0.3196564, 0.3236316, 0.3276069, 0...

tk                                                    \
name
end_nodes
property                       MVEC_start   MVEC_end
timestamp
2023-02-13 00:00:00.000 +01:00   8.242750   8.242750
2023-02-13 05:00:00.000 +01:00  12.843380  12.843380
2023-02-13 23:00:00.000 +01:00   8.767911   8.767911

tk                                                                                 \
name
end_nodes
property                                                            MVEC_sequence
timestamp
2023-02-13 00:00:00.000 +01:00  (8.24275, 8.24275, 8.24275, 8.24275, 8.24275, ...
2023-02-13 05:00:00.000 +01:00  (12.84338, 12.84338, 12.84338, 12.84338, 12.84...
2023-02-13 23:00:00.000 +01:00  (8.767911, 8.767911, 8.767911, 8.767911, 8.767...

tk                                        \
name
end_nodes
property                            DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  0.025371
2023-02-13 05:00:00.000 +01:00  0.016282
2023-02-13 23:00:00.000 +01:00  0.023852

tk                                                                    4762482310382009633  \
name                                                                   Rohr V-K23S V-K33S
end_nodes                      ('5239335112004772156', '5298886695042021307', '-1', '-1')
property                                                                     TTRVEC_start
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.428837
2023-02-13 05:00:00.000 +01:00                                           0.273829
2023-02-13 23:00:00.000 +01:00                                           0.402845

tk                                         \
name
end_nodes
property                       TTRVEC_end
timestamp
2023-02-13 00:00:00.000 +01:00   0.446670
2023-02-13 05:00:00.000 +01:00   0.285236
2023-02-13 23:00:00.000 +01:00   0.419600

tk                                                                                 \
name
end_nodes
property                                                          TTRVEC_sequence
timestamp
2023-02-13 00:00:00.000 +01:00  (0.4288374, 0.4324038, 0.4359703, 0.4395368, 0...
2023-02-13 05:00:00.000 +01:00  (0.273829, 0.2761104, 0.2783919, 0.2806734, 0....
2023-02-13 23:00:00.000 +01:00  (0.4028447, 0.4061958, 0.4095468, 0.4128978, 0...

tk                                                    \
name
end_nodes
property                       MVEC_start   MVEC_end
timestamp
2023-02-13 00:00:00.000 +01:00   8.403428   8.403428
2023-02-13 05:00:00.000 +01:00  13.135080  13.135080
2023-02-13 23:00:00.000 +01:00   8.943539   8.943539

tk                                                                                 \
name
end_nodes
property                                                            MVEC_sequence
timestamp
2023-02-13 00:00:00.000 +01:00  (8.403428, 8.403428, 8.403428, 8.403428, 8.403...
2023-02-13 05:00:00.000 +01:00  (13.13508, 13.13508, 13.13508, 13.13508, 13.13...
2023-02-13 23:00:00.000 +01:00  (8.943539, 8.943539, 8.943539, 8.943539, 8.943...

tk                                        \
name
end_nodes
property                            DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  0.017832
2023-02-13 05:00:00.000 +01:00  0.011407
2023-02-13 23:00:00.000 +01:00  0.016755

tk                                                                    4987229536643024523  \
name                                                                   Rohr V-K33S V-K43S
end_nodes                      ('5298886695042021307', '4993257270457791438', '-1', '-1')
property                                                                     TTRVEC_start
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.446670
2023-02-13 05:00:00.000 +01:00                                           0.285236
2023-02-13 23:00:00.000 +01:00                                           0.419600

tk                                                                            \
name
end_nodes
property                       TTRVEC_end         TTRVEC_sequence MVEC_start
timestamp
2023-02-13 00:00:00.000 +01:00   0.449642  (0.4466697, 0.4496421)   8.403428
2023-02-13 05:00:00.000 +01:00   0.287138  (0.2852363, 0.2871377)  13.135080
2023-02-13 23:00:00.000 +01:00   0.422393  (0.4195999, 0.4223926)   8.943539

tk                                                                         \
name
end_nodes
property                         MVEC_end         MVEC_sequence      DTTR
timestamp
2023-02-13 00:00:00.000 +01:00   8.403428  (8.403428, 8.403428)  0.002972
2023-02-13 05:00:00.000 +01:00  13.135080  (13.13508, 13.13508)  0.001901
2023-02-13 23:00:00.000 +01:00   8.943539  (8.943539, 8.943539)  0.002793

tk                                                                    5722206630503885118  \
name                                                                   Rohr V-K43S V-K53S
end_nodes                      ('4993257270457791438', '5317865645994989592', '-1', '-1')
property                                                                     TTRVEC_start
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.449642
2023-02-13 05:00:00.000 +01:00                                           0.287138
2023-02-13 23:00:00.000 +01:00                                           0.422393

tk                                                                            \
name
end_nodes
property                       TTRVEC_end         TTRVEC_sequence MVEC_start
timestamp
2023-02-13 00:00:00.000 +01:00   0.452902  (0.4496421, 0.4529015)   8.403428
2023-02-13 05:00:00.000 +01:00   0.289223  (0.2871377, 0.2892228)  13.135080
2023-02-13 23:00:00.000 +01:00   0.425455  (0.4223926, 0.4254552)   8.943539

tk                                                                         \
name
end_nodes
property                         MVEC_end         MVEC_sequence      DTTR
timestamp
2023-02-13 00:00:00.000 +01:00   8.403428  (8.403428, 8.403428)  0.003259
2023-02-13 05:00:00.000 +01:00  13.135080  (13.13508, 13.13508)  0.002085
2023-02-13 23:00:00.000 +01:00   8.943539  (8.943539, 8.943539)  0.003063

tk                                                                    5089459212485379804  \
name                                                                   Rohr V-K53S V-K63S
end_nodes                      ('5317865645994989592', '5085491372308261877', '-1', '-1')
property                                                                     TTRVEC_start
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.452902
2023-02-13 05:00:00.000 +01:00                                           0.289223
2023-02-13 23:00:00.000 +01:00                                           0.425455

tk                                                                            \
name
end_nodes
property                       TTRVEC_end         TTRVEC_sequence MVEC_start
timestamp
2023-02-13 00:00:00.000 +01:00   0.456521  (0.4529015, 0.4565214)   8.403428
2023-02-13 05:00:00.000 +01:00   0.291538  (0.2892228, 0.2915384)  13.135080
2023-02-13 23:00:00.000 +01:00   0.428856  (0.4254552, 0.4288564)   8.943539

tk                                                                         \
name
end_nodes
property                         MVEC_end         MVEC_sequence      DTTR
timestamp
2023-02-13 00:00:00.000 +01:00   8.403428  (8.403428, 8.403428)  0.003620
2023-02-13 05:00:00.000 +01:00  13.135080  (13.13508, 13.13508)  0.002316
2023-02-13 23:00:00.000 +01:00   8.943539  (8.943539, 8.943539)  0.003401

tk                                                                    5526871502288882655  \
name                                                                   Rohr V-K63S V-K73S
end_nodes                      ('5085491372308261877', '4989694427717344427', '-1', '-1')
property                                                                     TTRVEC_start
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.456521
2023-02-13 05:00:00.000 +01:00                                           0.291538
2023-02-13 23:00:00.000 +01:00                                           0.428856

tk                                         \
name
end_nodes
property                       TTRVEC_end
timestamp
2023-02-13 00:00:00.000 +01:00   0.495997
2023-02-13 05:00:00.000 +01:00   0.316797
2023-02-13 23:00:00.000 +01:00   0.465949

tk                                                                                 \
name
end_nodes
property                                                          TTRVEC_sequence
timestamp
2023-02-13 00:00:00.000 +01:00  (0.4565214, 0.4609075, 0.4652937, 0.4696799, 0...
2023-02-13 05:00:00.000 +01:00  (0.2915384, 0.2943449, 0.2971514, 0.299958, 0....
2023-02-13 23:00:00.000 +01:00  (0.4288564, 0.4329778, 0.4370991, 0.4412205, 0...

tk                                                    \
name
end_nodes
property                       MVEC_start   MVEC_end
timestamp
2023-02-13 00:00:00.000 +01:00   7.680472   7.680472
2023-02-13 05:00:00.000 +01:00  12.001700  12.001700
2023-02-13 23:00:00.000 +01:00   8.173762   8.173762

tk                                                                                 \
name
end_nodes
property                                                            MVEC_sequence
timestamp
2023-02-13 00:00:00.000 +01:00  (7.680472, 7.680472, 7.680472, 7.680472, 7.680...
2023-02-13 05:00:00.000 +01:00  (12.0017, 12.0017, 12.0017, 12.0017, 12.0017, ...
2023-02-13 23:00:00.000 +01:00  (8.173762, 8.173762, 8.173762, 8.173762, 8.173...

tk                                        \
name
end_nodes
property                            DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  0.039475
2023-02-13 05:00:00.000 +01:00  0.025259
2023-02-13 23:00:00.000 +01:00  0.037092

tk                                                                    4809089329099085219  \
name                                                                   Rohr V-K73S V-K83S
end_nodes                      ('4989694427717344427', '5097833100706648505', '-1', '-1')
property                                                                     TTRVEC_start
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.495997
2023-02-13 05:00:00.000 +01:00                                           0.316797
2023-02-13 23:00:00.000 +01:00                                           0.465949

tk                                                                            \
name
end_nodes
property                       TTRVEC_end         TTRVEC_sequence MVEC_start
timestamp
2023-02-13 00:00:00.000 +01:00   0.497624  (0.4959968, 0.4976238)   6.748159
2023-02-13 05:00:00.000 +01:00   0.317839  (0.3167973, 0.3178388)  10.541510
2023-02-13 23:00:00.000 +01:00   0.467478  (0.4659487, 0.4674776)   7.181220

tk                                                                         \
name
end_nodes
property                         MVEC_end         MVEC_sequence      DTTR
timestamp
2023-02-13 00:00:00.000 +01:00   6.748159  (6.748159, 6.748159)  0.001627
2023-02-13 05:00:00.000 +01:00  10.541510  (10.54151, 10.54151)  0.001041
2023-02-13 23:00:00.000 +01:00   7.181220    (7.18122, 7.18122)  0.001529

tk                                                                    5170001087020228683  \
name                                                                   Rohr V-K83S V-K93S
end_nodes                      ('5097833100706648505', '5748593725990350490', '-1', '-1')
property                                                                     TTRVEC_start
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.497624
2023-02-13 05:00:00.000 +01:00                                           0.317839
2023-02-13 23:00:00.000 +01:00                                           0.467478

tk                                                                            \
name
end_nodes
property                       TTRVEC_end         TTRVEC_sequence MVEC_start
timestamp
2023-02-13 00:00:00.000 +01:00   0.500575  (0.4976238, 0.5005747)   4.251046
2023-02-13 05:00:00.000 +01:00   0.319728  (0.3178388, 0.3197278)   6.639488
2023-02-13 23:00:00.000 +01:00   0.470251  (0.4674776, 0.4702505)   4.523731

tk                                                                        \
name
end_nodes
property                        MVEC_end         MVEC_sequence      DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  4.251046  (4.251046, 4.251046)  0.002951
2023-02-13 05:00:00.000 +01:00  6.639488  (6.639488, 6.639488)  0.001889
2023-02-13 23:00:00.000 +01:00  4.523731  (4.523731, 4.523731)  0.002773

tk                                                                    5625716875961234775  \
name                                                                  Rohr V-K93S V-K103S
end_nodes                      ('5748593725990350490', '5498236250497948633', '-1', '-1')
property                                                                     TTRVEC_start
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.500575
2023-02-13 05:00:00.000 +01:00                                           0.319728
2023-02-13 23:00:00.000 +01:00                                           0.470251

tk                                                                            \
name
end_nodes
property                       TTRVEC_end         TTRVEC_sequence MVEC_start
timestamp
2023-02-13 00:00:00.000 +01:00   0.502825   (0.5005747, 0.502825)   4.251046
2023-02-13 05:00:00.000 +01:00   0.321168  (0.3197278, 0.3211684)   6.639488
2023-02-13 23:00:00.000 +01:00   0.472365  (0.4702505, 0.4723651)   4.523731

tk                                                                        \
name
end_nodes
property                        MVEC_end         MVEC_sequence      DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  4.251046  (4.251046, 4.251046)  0.002250
2023-02-13 05:00:00.000 +01:00  6.639488  (6.639488, 6.639488)  0.001441
2023-02-13 23:00:00.000 +01:00  4.523731  (4.523731, 4.523731)  0.002115

tk                                                                    5501916898830363065  \
name                                                                 Rohr V-K103S V-K113S
end_nodes                      ('5498236250497948633', '4764732356959599958', '-1', '-1')
property                                                                     TTRVEC_start
timestamp
2023-02-13 00:00:00.000 +01:00                                           0.502825
2023-02-13 05:00:00.000 +01:00                                           0.321168
2023-02-13 23:00:00.000 +01:00                                           0.472365

tk                                         \
name
end_nodes
property                       TTRVEC_end
timestamp
2023-02-13 00:00:00.000 +01:00   0.514860
2023-02-13 05:00:00.000 +01:00   0.328873
2023-02-13 23:00:00.000 +01:00   0.483674

tk                                                                            \
name
end_nodes
property                                                     TTRVEC_sequence
timestamp
2023-02-13 00:00:00.000 +01:00   (0.502825, 0.5068366, 0.5108482, 0.5148597)
2023-02-13 05:00:00.000 +01:00  (0.3211684, 0.3237365, 0.3263046, 0.3288727)
2023-02-13 23:00:00.000 +01:00  (0.4723651, 0.4761348, 0.4799044, 0.4836741)

tk                                                   \
name
end_nodes
property                       MVEC_start  MVEC_end
timestamp
2023-02-13 00:00:00.000 +01:00   4.251046  4.251046
2023-02-13 05:00:00.000 +01:00   6.639488  6.639488
2023-02-13 23:00:00.000 +01:00   4.523731  4.523731

tk                                                                        \
name
end_nodes
property                                                   MVEC_sequence
timestamp
2023-02-13 00:00:00.000 +01:00  (4.251046, 4.251046, 4.251046, 4.251046)
2023-02-13 05:00:00.000 +01:00  (6.639488, 6.639488, 6.639488, 6.639488)
2023-02-13 23:00:00.000 +01:00  (4.523731, 4.523731, 4.523731, 4.523731)

tk                                        \
name
end_nodes
property                            DTTR
timestamp
2023-02-13 00:00:00.000 +01:00  0.012035
2023-02-13 05:00:00.000 +01:00  0.007704
2023-02-13 23:00:00.000 +01:00  0.011309

tk                                                                    5192970129555982907  \

We can access individual values as follows.

In [45]:
df_pipes_interior_points.loc[
    "2023-02-13 00:00:00.000 +01:00",
    ("5442010239090746007", slice(None), slice(None), "MVEC_sequence")
].item()

(14.68007, 14.68007, 14.68007, 14.68007, 14.68007)

We can also collapse the three time rows into one tuple.

In [46]:
df_pipes_simplified, timestamp_to_tuple_index = s3s.convert_rows_to_single_tuple_row(df_pipes_interior_points)

[2026-06-08 10:26:20,813] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Collapsing dataframe rows into tuple row...
[2026-06-08 10:26:21,781] INFO in sir3stoolkit.mantle.dataframes: [rows_to_tuple_row] Done. Shape: (1, 3668)

In [47]:
df_pipes_simplified

tk                                               5442010239090746007  \
name                                              Rohr V-K03S V-K13S
end_nodes ('5669301360686511351', '5397948523091900401', '-1', '-1')
property                                                TTRVEC_start
0                          (0.3227228, 0.2057882, 0.3030591)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.3361596, 0.2143701, 0.3156811)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.3227228, 0.326082, 0.3294412, 0.3328004, 0...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (14.68007, 22.98332, 15.62753)  (14.68007, 22.98332, 15.62753)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((14.68007, 14.68007, 14.68007, 14.68007, 14.6...

tk                                                \
name
end_nodes
property                                    DTTR
0          (0.01343678, 0.008581901, 0.01262201)

tk                                               4917786378639043296  \
name                                              Rohr V-K13S V-K23S
end_nodes ('5397948523091900401', '5239335112004772156', '-1', '-1')
property                                                TTRVEC_start
0                          (0.3361596, 0.2143701, 0.3156811)

tk                                           \
name
end_nodes
property                         TTRVEC_end
0          (0.361531, 0.2306521, 0.3395326)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.3361596, 0.3403881, 0.3446167, 0.3488453, ...

tk                                                                       \
name
end_nodes
property                      MVEC_start                       MVEC_end
0          (8.24275, 12.84338, 8.767911)  (8.24275, 12.84338, 8.767911)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((8.24275, 8.24275, 8.24275, 8.24275, 8.24275,...

tk                                               \
name
end_nodes
property                                   DTTR
0          (0.02537143, 0.01628198, 0.02385151)

tk                                               4762482310382009633  \
name                                              Rohr V-K23S V-K33S
end_nodes ('5239335112004772156', '5298886695042021307', '-1', '-1')
property                                                TTRVEC_start
0                           (0.4288374, 0.273829, 0.4028447)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.4466697, 0.2852363, 0.4195999)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.4288374, 0.4324038, 0.4359703, 0.4395368, ...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (8.403428, 13.13508, 8.943539)  (8.403428, 13.13508, 8.943539)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((8.403428, 8.403428, 8.403428, 8.403428, 8.40...

tk                                               \
name
end_nodes
property                                   DTTR
0          (0.01783237, 0.01140733, 0.01675515)

tk                                               4987229536643024523  \
name                                              Rohr V-K33S V-K43S
end_nodes ('5298886695042021307', '4993257270457791438', '-1', '-1')
property                                                TTRVEC_start
0                          (0.4466697, 0.2852363, 0.4195999)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.4496421, 0.2871377, 0.4223926)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.4466697, 0.4496421), (0.2852363, 0.2871377...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (8.403428, 13.13508, 8.943539)  (8.403428, 13.13508, 8.943539)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((8.403428, 8.403428), (13.13508, 13.13508), (...

tk                                                  \
name
end_nodes
property                                      DTTR
0          (0.002972364, 0.001901407, 0.002792806)

tk                                               5722206630503885118  \
name                                              Rohr V-K43S V-K53S
end_nodes ('4993257270457791438', '5317865645994989592', '-1', '-1')
property                                                TTRVEC_start
0                          (0.4496421, 0.2871377, 0.4223926)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.4529015, 0.2892228, 0.4254552)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.4496421, 0.4529015), (0.2871377, 0.2892228...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (8.403428, 13.13508, 8.943539)  (8.403428, 13.13508, 8.943539)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((8.403428, 8.403428), (13.13508, 13.13508), (...

tk                                                  \
name
end_nodes
property                                      DTTR
0          (0.003259483, 0.002085073, 0.003062581)

tk                                               5089459212485379804  \
name                                              Rohr V-K53S V-K63S
end_nodes ('5317865645994989592', '5085491372308261877', '-1', '-1')
property                                                TTRVEC_start
0                          (0.4529015, 0.2892228, 0.4254552)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.4565214, 0.2915384, 0.4288564)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.4529015, 0.4565214), (0.2892228, 0.2915384...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (8.403428, 13.13508, 8.943539)  (8.403428, 13.13508, 8.943539)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((8.403428, 8.403428), (13.13508, 13.13508), (...

tk                                                  \
name
end_nodes
property                                      DTTR
0          (0.003619839, 0.002315587, 0.003401167)

tk                                               5526871502288882655  \
name                                              Rohr V-K63S V-K73S
end_nodes ('5085491372308261877', '4989694427717344427', '-1', '-1')
property                                                TTRVEC_start
0                          (0.4565214, 0.2915384, 0.4288564)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.4959968, 0.3167973, 0.4659487)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.4565214, 0.4609075, 0.4652937, 0.4696799, ...

tk                                                                       \
name
end_nodes
property                      MVEC_start                       MVEC_end
0          (7.680472, 12.0017, 8.173762)  (7.680472, 12.0017, 8.173762)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((7.680472, 7.680472, 7.680472, 7.680472, 7.68...

tk                                               \
name
end_nodes
property                                   DTTR
0          (0.03947543, 0.02525898, 0.03709229)

tk                                               4809089329099085219  \
name                                              Rohr V-K73S V-K83S
end_nodes ('4989694427717344427', '5097833100706648505', '-1', '-1')
property                                                TTRVEC_start
0                          (0.4959968, 0.3167973, 0.4659487)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.4976238, 0.3178388, 0.4674776)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.4959968, 0.4976238), (0.3167973, 0.3178388...

tk                                                                       \
name
end_nodes
property                      MVEC_start                       MVEC_end
0          (6.748159, 10.54151, 7.18122)  (6.748159, 10.54151, 7.18122)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((6.748159, 6.748159), (10.54151, 10.54151), (...

tk                                                  \
name
end_nodes
property                                      DTTR
0          (0.001627007, 0.001041386, 0.001528857)

tk                                               5170001087020228683  \
name                                              Rohr V-K83S V-K93S
end_nodes ('5097833100706648505', '5748593725990350490', '-1', '-1')
property                                                TTRVEC_start
0                          (0.4976238, 0.3178388, 0.4674776)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.5005747, 0.3197278, 0.4702505)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.4976238, 0.5005747), (0.3178388, 0.3197278...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (4.251046, 6.639488, 4.523731)  (4.251046, 6.639488, 4.523731)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((4.251046, 4.251046), (6.639488, 6.639488), (...

tk                                                 \
name
end_nodes
property                                     DTTR
0          (0.00295089, 0.001889094, 0.002772951)

tk                                               5625716875961234775  \
name                                             Rohr V-K93S V-K103S
end_nodes ('5748593725990350490', '5498236250497948633', '-1', '-1')
property                                                TTRVEC_start
0                          (0.5005747, 0.3197278, 0.4702505)

tk                                           \
name
end_nodes
property                         TTRVEC_end
0          (0.502825, 0.3211684, 0.4723651)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.5005747, 0.502825), (0.3197278, 0.3211684)...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (4.251046, 6.639488, 4.523731)  (4.251046, 6.639488, 4.523731)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((4.251046, 4.251046), (6.639488, 6.639488), (...

tk                                                \
name
end_nodes
property                                    DTTR
0          (0.00225025, 0.001440558, 0.00211456)

tk                                               5501916898830363065  \
name                                            Rohr V-K103S V-K113S
end_nodes ('5498236250497948633', '4764732356959599958', '-1', '-1')
property                                                TTRVEC_start
0                           (0.502825, 0.3211684, 0.4723651)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.5148597, 0.3288727, 0.4836741)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.502825, 0.5068366, 0.5108482, 0.5148597), ...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (4.251046, 6.639488, 4.523731)  (4.251046, 6.639488, 4.523731)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((4.251046, 4.251046, 4.251046, 4.251046), (6....

tk                                                \
name
end_nodes
property                                    DTTR
0          (0.01203477, 0.007704346, 0.01130906)

tk                                               5192970129555982907  \
name                                            Rohr V-K113S V-K123S
end_nodes ('4764732356959599958', '5648425495460137243', '-1', '-1')
property                                                TTRVEC_start
0                          (0.5148597, 0.3288727, 0.4836741)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.5308086, 0.3390842, 0.4986615)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.5148597, 0.520176, 0.5254923, 0.5308086), ...

tk                                                                       \
name
end_nodes
property                      MVEC_start                       MVEC_end
0          (3.980511, 6.21603, 4.235746)  (3.980511, 6.21603, 4.235746)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((3.980511, 3.980511, 3.980511, 3.980511), (6....

tk                                               \
name
end_nodes
property                                   DTTR
0          (0.01594882, 0.01021145, 0.01498741)

tk                                               5027225217797463802  \
name                                            Rohr V-K123S V-K133S
end_nodes ('5648425495460137243', '5603354735453128217', '-1', '-1')
property                                                TTRVEC_start
0                          (0.5308086, 0.3390842, 0.4986615)

tk                                           \
name
end_nodes
property                         TTRVEC_end
0          (0.5457272, 0.348644, 0.5126826)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.5308086, 0.5357814, 0.5407543, 0.5457272),...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (2.725789, 4.253057, 2.900195)  (2.725789, 4.253057, 2.900195)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((2.725789, 2.725789, 2.725789, 2.725789), (4....

tk                                                \
name
end_nodes
property                                    DTTR
0          (0.01491862, 0.009559788, 0.01402111)

tk                                               5107343838750080243  \
name                                            Rohr V-K133S V-K143S
end_nodes ('5603354735453128217', '5554918259063780747', '-1', '-1')
property                                                TTRVEC_start
0                           (0.5457272, 0.348644, 0.5126826)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.6030915, 0.3855114, 0.5666197)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.5457272, 0.5572001, 0.568673, 0.5801458, 0...

tk                                            \
name
end_nodes
property                          MVEC_start
0          (0.4454001, 0.6928714, 0.4736846)

tk                                            \
name
end_nodes
property                            MVEC_end
0          (0.4454001, 0.6928714, 0.4736846)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((0.4454001, 0.4454001, 0.4454001, 0.4454001, ...

tk                                               \
name
end_nodes
property                                   DTTR
0          (0.05736437, 0.03686747, 0.05393704)

tk                                               4840056338230495043  \
name                                            Rohr V-K153S V-K163S
end_nodes ('4992867596416688120', '4921884425075838112', '-1', '-1')
property                                                TTRVEC_start
0                          (0.3351198, 0.2133179, 0.3146621)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.3929434, 0.2502159, 0.3689722)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.3351198, 0.3403764, 0.3456331, 0.3508899, ...

tk                                                                     \
name
end_nodes
property                     MVEC_start                      MVEC_end
0          (2.641599, 4.13939, 2.81246)  (2.641599, 4.13939, 2.81246)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((2.641599, 2.641599, 2.641599, 2.641599, 2.64...

tk                                               \
name
end_nodes
property                                   DTTR
0          (0.05782364, 0.03689794, 0.05431006)

tk                                               5700872284015490704  \
name                                            Rohr V-K163S V-K143S
end_nodes ('4921884425075838112', '5554918259063780747', '-1', '-1')
property                                                TTRVEC_start
0                             (166.2786, 166.0984, 166.2484)


For every result value we now have a tuple with each entry corresponding to one simulation timestamp.

In [48]:
df_pipes_simplified.loc[
    0,
    ("5442010239090746007", slice(None), slice(None), "DTTR")
].item()

(0.01343678, 0.008581901, 0.01262201)

We can access individual values via the dict, that was returned.

In [49]:
df_pipes_simplified.loc[
    0,
    ("5442010239090746007", slice(None), slice(None), "DTTR")
].item()[timestamp_to_tuple_index['2023-02-13 00:00:00.000 +01:00']]

0.01343678

For vectorized result properties (pipe interior points) we will receive a tuple of tuples. With the time tuple as the higher level one.

In [50]:
df_pipes_simplified.loc[
    0,
    ("5442010239090746007", slice(None), slice(None), "MVEC_sequence")
].item()

((14.68007, 14.68007, 14.68007, 14.68007, 14.68007),
 (22.98332, 22.98332, 22.98332, 22.98332, 22.98332),
 (15.62753, 15.62753, 15.62753, 15.62753, 15.62753))

In [51]:
df_pipes_simplified.loc[
    0,
    ("5442010239090746007", slice(None), slice(None), "MVEC_sequence")
].item()[timestamp_to_tuple_index['2023-02-13 00:00:00.000 +01:00']]

(14.68007, 14.68007, 14.68007, 14.68007, 14.68007)

## Merge model_data and Result Dataframes (for one timestamp)

### Create Dataframes - For pipes

#### model_data

In [52]:
df_pipes_model_data = s3s.generate_element_model_data_dataframe(element_type=s3s.ObjectTypes.Pipe
                                                            ,properties=["L", "DN"]
                                                            ,geometry=True
                                                            )

[2026-06-08 10:26:23,584] INFO in sir3stoolkit.mantle.dataframes: [model_data] Generating model_data dataframe for element type: ObjectTypes.Pipe
[2026-06-08 10:26:23,590] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieved 524 element(s) of element type ObjectTypes.Pipe.
[2026-06-08 10:26:23,593] INFO in sir3stoolkit.mantle.dataframes: [Resolving model_data Properties] Using 2 model_data properties.
[2026-06-08 10:26:23,593] INFO in sir3stoolkit.mantle.dataframes: [model_data] Retrieving model_data properties ['L', 'DN'], geometry...
[2026-06-08 10:26:23,846] INFO in sir3stoolkit.mantle.dataframes: [model_data] Transforming DataFrame to GeoDataFrame successful with EPSG: 25832
[2026-06-08 10:26:23,846] INFO in sir3stoolkit.mantle.dataframes: [model_data] Done. Shape: (524, 4)

In [53]:
df_pipes_model_data.head(3)

,tk,L,DN,geometry
0,5442010239090746007,36.42935,150,"LINESTRING (713620.268 5578828.419, 713602.295..."
1,4917786378639043296,57.21781,125,"LINESTRING (713602.295 5578860.106, 713574.062..."
2,4762482310382009633,40.99482,125,"LINESTRING (713574.062 5578909.873, 713553.84 ..."

#### Results

In [54]:
df_pipes_simplified.head(3)

tk                                               5442010239090746007  \
name                                              Rohr V-K03S V-K13S
end_nodes ('5669301360686511351', '5397948523091900401', '-1', '-1')
property                                                TTRVEC_start
0                          (0.3227228, 0.2057882, 0.3030591)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.3361596, 0.2143701, 0.3156811)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.3227228, 0.326082, 0.3294412, 0.3328004, 0...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (14.68007, 22.98332, 15.62753)  (14.68007, 22.98332, 15.62753)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((14.68007, 14.68007, 14.68007, 14.68007, 14.6...

tk                                                \
name
end_nodes
property                                    DTTR
0          (0.01343678, 0.008581901, 0.01262201)

tk                                               4917786378639043296  \
name                                              Rohr V-K13S V-K23S
end_nodes ('5397948523091900401', '5239335112004772156', '-1', '-1')
property                                                TTRVEC_start
0                          (0.3361596, 0.2143701, 0.3156811)

tk                                           \
name
end_nodes
property                         TTRVEC_end
0          (0.361531, 0.2306521, 0.3395326)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.3361596, 0.3403881, 0.3446167, 0.3488453, ...

tk                                                                       \
name
end_nodes
property                      MVEC_start                       MVEC_end
0          (8.24275, 12.84338, 8.767911)  (8.24275, 12.84338, 8.767911)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((8.24275, 8.24275, 8.24275, 8.24275, 8.24275,...

tk                                               \
name
end_nodes
property                                   DTTR
0          (0.02537143, 0.01628198, 0.02385151)

tk                                               4762482310382009633  \
name                                              Rohr V-K23S V-K33S
end_nodes ('5239335112004772156', '5298886695042021307', '-1', '-1')
property                                                TTRVEC_start
0                           (0.4288374, 0.273829, 0.4028447)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.4466697, 0.2852363, 0.4195999)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.4288374, 0.4324038, 0.4359703, 0.4395368, ...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (8.403428, 13.13508, 8.943539)  (8.403428, 13.13508, 8.943539)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((8.403428, 8.403428, 8.403428, 8.403428, 8.40...

tk                                               \
name
end_nodes
property                                   DTTR
0          (0.01783237, 0.01140733, 0.01675515)

tk                                               4987229536643024523  \
name                                              Rohr V-K33S V-K43S
end_nodes ('5298886695042021307', '4993257270457791438', '-1', '-1')
property                                                TTRVEC_start
0                          (0.4466697, 0.2852363, 0.4195999)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.4496421, 0.2871377, 0.4223926)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.4466697, 0.4496421), (0.2852363, 0.2871377...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (8.403428, 13.13508, 8.943539)  (8.403428, 13.13508, 8.943539)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((8.403428, 8.403428), (13.13508, 13.13508), (...

tk                                                  \
name
end_nodes
property                                      DTTR
0          (0.002972364, 0.001901407, 0.002792806)

tk                                               5722206630503885118  \
name                                              Rohr V-K43S V-K53S
end_nodes ('4993257270457791438', '5317865645994989592', '-1', '-1')
property                                                TTRVEC_start
0                          (0.4496421, 0.2871377, 0.4223926)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.4529015, 0.2892228, 0.4254552)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.4496421, 0.4529015), (0.2871377, 0.2892228...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (8.403428, 13.13508, 8.943539)  (8.403428, 13.13508, 8.943539)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((8.403428, 8.403428), (13.13508, 13.13508), (...

tk                                                  \
name
end_nodes
property                                      DTTR
0          (0.003259483, 0.002085073, 0.003062581)

tk                                               5089459212485379804  \
name                                              Rohr V-K53S V-K63S
end_nodes ('5317865645994989592', '5085491372308261877', '-1', '-1')
property                                                TTRVEC_start
0                          (0.4529015, 0.2892228, 0.4254552)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.4565214, 0.2915384, 0.4288564)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.4529015, 0.4565214), (0.2892228, 0.2915384...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (8.403428, 13.13508, 8.943539)  (8.403428, 13.13508, 8.943539)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((8.403428, 8.403428), (13.13508, 13.13508), (...

tk                                                  \
name
end_nodes
property                                      DTTR
0          (0.003619839, 0.002315587, 0.003401167)

tk                                               5526871502288882655  \
name                                              Rohr V-K63S V-K73S
end_nodes ('5085491372308261877', '4989694427717344427', '-1', '-1')
property                                                TTRVEC_start
0                          (0.4565214, 0.2915384, 0.4288564)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.4959968, 0.3167973, 0.4659487)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.4565214, 0.4609075, 0.4652937, 0.4696799, ...

tk                                                                       \
name
end_nodes
property                      MVEC_start                       MVEC_end
0          (7.680472, 12.0017, 8.173762)  (7.680472, 12.0017, 8.173762)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((7.680472, 7.680472, 7.680472, 7.680472, 7.68...

tk                                               \
name
end_nodes
property                                   DTTR
0          (0.03947543, 0.02525898, 0.03709229)

tk                                               4809089329099085219  \
name                                              Rohr V-K73S V-K83S
end_nodes ('4989694427717344427', '5097833100706648505', '-1', '-1')
property                                                TTRVEC_start
0                          (0.4959968, 0.3167973, 0.4659487)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.4976238, 0.3178388, 0.4674776)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.4959968, 0.4976238), (0.3167973, 0.3178388...

tk                                                                       \
name
end_nodes
property                      MVEC_start                       MVEC_end
0          (6.748159, 10.54151, 7.18122)  (6.748159, 10.54151, 7.18122)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((6.748159, 6.748159), (10.54151, 10.54151), (...

tk                                                  \
name
end_nodes
property                                      DTTR
0          (0.001627007, 0.001041386, 0.001528857)

tk                                               5170001087020228683  \
name                                              Rohr V-K83S V-K93S
end_nodes ('5097833100706648505', '5748593725990350490', '-1', '-1')
property                                                TTRVEC_start
0                          (0.4976238, 0.3178388, 0.4674776)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.5005747, 0.3197278, 0.4702505)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.4976238, 0.5005747), (0.3178388, 0.3197278...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (4.251046, 6.639488, 4.523731)  (4.251046, 6.639488, 4.523731)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((4.251046, 4.251046), (6.639488, 6.639488), (...

tk                                                 \
name
end_nodes
property                                     DTTR
0          (0.00295089, 0.001889094, 0.002772951)

tk                                               5625716875961234775  \
name                                             Rohr V-K93S V-K103S
end_nodes ('5748593725990350490', '5498236250497948633', '-1', '-1')
property                                                TTRVEC_start
0                          (0.5005747, 0.3197278, 0.4702505)

tk                                           \
name
end_nodes
property                         TTRVEC_end
0          (0.502825, 0.3211684, 0.4723651)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.5005747, 0.502825), (0.3197278, 0.3211684)...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (4.251046, 6.639488, 4.523731)  (4.251046, 6.639488, 4.523731)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((4.251046, 4.251046), (6.639488, 6.639488), (...

tk                                                \
name
end_nodes
property                                    DTTR
0          (0.00225025, 0.001440558, 0.00211456)

tk                                               5501916898830363065  \
name                                            Rohr V-K103S V-K113S
end_nodes ('5498236250497948633', '4764732356959599958', '-1', '-1')
property                                                TTRVEC_start
0                           (0.502825, 0.3211684, 0.4723651)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.5148597, 0.3288727, 0.4836741)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.502825, 0.5068366, 0.5108482, 0.5148597), ...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (4.251046, 6.639488, 4.523731)  (4.251046, 6.639488, 4.523731)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((4.251046, 4.251046, 4.251046, 4.251046), (6....

tk                                                \
name
end_nodes
property                                    DTTR
0          (0.01203477, 0.007704346, 0.01130906)

tk                                               5192970129555982907  \
name                                            Rohr V-K113S V-K123S
end_nodes ('4764732356959599958', '5648425495460137243', '-1', '-1')
property                                                TTRVEC_start
0                          (0.5148597, 0.3288727, 0.4836741)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.5308086, 0.3390842, 0.4986615)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.5148597, 0.520176, 0.5254923, 0.5308086), ...

tk                                                                       \
name
end_nodes
property                      MVEC_start                       MVEC_end
0          (3.980511, 6.21603, 4.235746)  (3.980511, 6.21603, 4.235746)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((3.980511, 3.980511, 3.980511, 3.980511), (6....

tk                                               \
name
end_nodes
property                                   DTTR
0          (0.01594882, 0.01021145, 0.01498741)

tk                                               5027225217797463802  \
name                                            Rohr V-K123S V-K133S
end_nodes ('5648425495460137243', '5603354735453128217', '-1', '-1')
property                                                TTRVEC_start
0                          (0.5308086, 0.3390842, 0.4986615)

tk                                           \
name
end_nodes
property                         TTRVEC_end
0          (0.5457272, 0.348644, 0.5126826)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.5308086, 0.5357814, 0.5407543, 0.5457272),...

tk                                                                         \
name
end_nodes
property                       MVEC_start                        MVEC_end
0          (2.725789, 4.253057, 2.900195)  (2.725789, 4.253057, 2.900195)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((2.725789, 2.725789, 2.725789, 2.725789), (4....

tk                                                \
name
end_nodes
property                                    DTTR
0          (0.01491862, 0.009559788, 0.01402111)

tk                                               5107343838750080243  \
name                                            Rohr V-K133S V-K143S
end_nodes ('5603354735453128217', '5554918259063780747', '-1', '-1')
property                                                TTRVEC_start
0                           (0.5457272, 0.348644, 0.5126826)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.6030915, 0.3855114, 0.5666197)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.5457272, 0.5572001, 0.568673, 0.5801458, 0...

tk                                            \
name
end_nodes
property                          MVEC_start
0          (0.4454001, 0.6928714, 0.4736846)

tk                                            \
name
end_nodes
property                            MVEC_end
0          (0.4454001, 0.6928714, 0.4736846)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((0.4454001, 0.4454001, 0.4454001, 0.4454001, ...

tk                                               \
name
end_nodes
property                                   DTTR
0          (0.05736437, 0.03686747, 0.05393704)

tk                                               4840056338230495043  \
name                                            Rohr V-K153S V-K163S
end_nodes ('4992867596416688120', '4921884425075838112', '-1', '-1')
property                                                TTRVEC_start
0                          (0.3351198, 0.2133179, 0.3146621)

tk                                            \
name
end_nodes
property                          TTRVEC_end
0          (0.3929434, 0.2502159, 0.3689722)

tk                                                            \
name
end_nodes
property                                     TTRVEC_sequence
0          ((0.3351198, 0.3403764, 0.3456331, 0.3508899, ...

tk                                                                     \
name
end_nodes
property                     MVEC_start                      MVEC_end
0          (2.641599, 4.13939, 2.81246)  (2.641599, 4.13939, 2.81246)

tk                                                            \
name
end_nodes
property                                       MVEC_sequence
0          ((2.641599, 2.641599, 2.641599, 2.641599, 2.64...

tk                                               \
name
end_nodes
property                                   DTTR
0          (0.05782364, 0.03689794, 0.05431006)

tk                                               5700872284015490704  \
name                                            Rohr V-K163S V-K143S
end_nodes ('4921884425075838112', '5554918259063780747', '-1', '-1')
property                                                TTRVEC_start
0                             (166.2786, 166.0984, 166.2484)


### Merge

In [55]:
df_pipes_simplified.columns = df_pipes_simplified.columns.droplevel([1, 2])
df_pipes_simplified = df_pipes_simplified.T.unstack(level=0).T
df_pipes_simplified = df_pipes_simplified.droplevel(0, axis=0)
df_pipes = df_pipes_model_data.merge(on="tk",
                    how="outer",
                    right=df_pipes_simplified)

In [56]:
df_pipes.head(3)

,tk,L,DN,geometry,DTTR,MVEC_end,MVEC_sequence,MVEC_start,TTRVEC_end,TTRVEC_sequence,TTRVEC_start
0,4614463970292122863,7.780674,999,"LINESTRING (714262.483 5578857.42, 714269.543 ...","(7.780674, 7.780674, 7.780674)","(2.837623e-10, 1.142325e-09, 1.455192e-10)","((2.837623e-10, 2.837623e-10), (1.142325e-09, ...","(2.837623e-10, 1.142325e-09, 1.455192e-10)","(249.9251, 7.780674, 72269530.0)","((242.1444, 249.9251), (0.0, 7.780674), (72269...","(242.1444, 0.0, 72269520.0)"
1,4615723899944629797,64.287240,999,"LINESTRING (713738.297 5579219.902, 713793.23 ...","(64.28724, 64.28724, 64.28724)","(-2.983143e-10, 0.0, -1.964509e-10)","((-2.983143e-10, -2.983143e-10, -2.983143e-10,...","(-2.983143e-10, 0.0, -1.964509e-10)","(43.0797, 139.5106, 43.0797)","((107.3669, 98.18304, 88.99916, 79.81527, 70.6...","(107.3669, 139.5106, 107.3669)"
2,4621030304810285220,3.956838,100,"LINESTRING (713650.613 5578990.488, 713649.498...","(0.00229145, 0.001467105, 0.002153316)","(-4.251046, -6.639488, -4.523731)","((-4.251046, -4.251046), (-6.639488, -6.639488...","(-4.251046, -6.639488, -4.523731)","(0.05315937, 0.0340941, 0.04989032)","((0.05545082, 0.05315937), (0.0355612, 0.03409...","(0.05545082, 0.0355612, 0.05204364)"

To get this dataframe without having to perform all intermediate steps, use [generate_element_dataframe()](https://3sconsult.github.io/sir3stoolkit/references/sir3stoolkit.mantle.html#sir3stoolkit.mantle.dataframes.SIR3S_Model_Dataframes.generate_element_dataframe), described in Tutorial 52.